### ISSUE TITLE
AltStore crashes when trying to install Kodi 19.4

### ISSUE THREAD

**Issue by r3dlobst3r** [rileytestut/AltStore#1000]
I have created a test AltStore source where I have been testing different Kodi versions with AltStore. TLDR, none of the 19+ Kodi versions work. I have the full crash log out of xcode, hopefully it is helpful.

I have uploaded the full crash log here: 
[kodi_log.txt](https://github.com/rileytestut/AltStore/files/8645111/kodi_log.txt)
and here:
https://paste.kodi.tv/eberezoyus

**Comment by michael1900** [comment]
Framework signing problem. Altstore dev probably never will fix this.

**Comment by shanegillio** [comment]
this issue has been noted, so am going to close this issue as a duplicate. will provide update later when we have more info for you
