### ISSUE TITLE
Sideloaded apps via AltServer not visible in AltStore `My Apps`

### ISSUE THREAD

**Issue by bachig26** [rileytestut/AltStore#1002]
I recently tried the `Sideload .ipa` via **`AltServer` (Windows)**, the App installed as expected but the Apps installed via AltServer doesn't show in the **AltStore `My Apps`**.
From the current state, this will be an issue for refreshing the app after the 7 day period.

The App show properly under **Device Management `Developer App`**.

**Comment by AymenKcm1** [comment]
That's a normal behavior, if you want them to show in AltStore app for future resigning you need to copy the IPA files to the device and install them with AltStore, use any files manager app and transfer via iTunes (or 3uTools) or wirelessly if the app offers this feature, personally I use [Phone Drive](https://apps.apple.com/us/app/phone-drive-file-storage-sync/id431033044) or [MaxVault](https://apps.apple.com/us/app/maxvault-photo-video-vault/id645754521) (previously PocketFiles).
