### ISSUE TITLE
Altserver 1.5 won't work anymore

### ISSUE THREAD

**Issue by BatteryDie** [rileytestut/AltStore#1003]
Before the update, there is zero problem with installing and refreshing.

When my iPhone tried refresh but it failed. I manually reinstall altstore via altserver but it becomes broken with high cpu (see figure 1) after I entered Apple ID. I waited for 1 hours. Seem it is doing nothing. It never pop up notifications and error dialog.

![image](https://user-images.githubusercontent.com/13942195/167280543-9368476f-8b39-4d03-abf6-fd9857449da2.png)Figure 1

I downgraded it to 1.4. It's working fine. There is something wrong with 1.5.

My setup is Windows 10 and iPhone 11 with iOS 15.4.1

**Comment by szl0834** [comment]
I got the same problem, and downgrade to 1.4 fix it

**Comment by evilskaap** [comment]
Is there an official link for 1.4 somewhere? I don't have the original zip anymore...

**Comment by szl0834** [comment]
> Is there an official link for 1.4 somewhere? I don't have the original zip anymore...

I don't find it, I was used the one in my archive disk.

**Comment by WilliamWickerson** [comment]
> Is there an official link for 1.4 somewhere? I don't have the original zip anymore...

I was able to downgrade using an old version on choco - https://community.chocolatey.org/packages/altserver.install

**Comment by TempAccountNull** [comment]
I made this bug issue a year ago and since I wasn't around to elaborate on it after the update it was closed.
https://github.com/rileytestut/AltStore/issues/130

**Comment by maertens-ca** [comment]
Just wanted to add on that I'm having the same issue on:
Windows 11 Pro (10.0.22000 Build 22000)
IOS 14.2.1
iPhone 12 Mini

**Comment by BatteryDie** [comment]
> I made this bug issue a year ago and since I wasn't around to elaborate on it after the update it was closed. #130
I looked your issue. Very interesting debugging. You mentioned the device is unplugged from the host. I went ahead to reinstalled with AltServer 1.5 and I tested install/refresh ipa on my iPhone via wired and wireless both. They have same issue. I think there are some different ways to cause high cpu usage with AltServer 1.5 but it's very weird.

I forgot to tell you that my Windows 10 is running 24/7 VM on my headless KVM server. They do not have sleep and hibernate by default.

**Comment by jyu041** [comment]
> > Is there an official link for 1.4 somewhere? I don't have the original zip anymore...
> 
> I was able to downgrade using an old version on choco - https://community.chocolatey.org/packages/altserver.install

I had the same issue lol, downgrading at that link worked immediately (windows 10, iphone 13 pm, ios 15.5

**Comment by RahulDAnand** [comment]
for anyone who is having issues downloading the older version from the above URL
simply click on the download button from the left bottom and rename the nupkg to zip and extract the msi file from achieve.

regards,

**Comment by BomberFish** [comment]
> Is there an official link for 1.4 somewhere? I don't have the original zip anymore...

Try [this](https://web.archive.org/web/20220331081450/https://cdn.altstore.io/file/altstore/altserver.zip)
