### ISSUE TITLE
mail plug in is not supported for mail 16.0

### ISSUE THREAD

**Issue by Anywhereyouare** [rileytestut/AltStore#1008]
what do I do?? please help me

**Comment by mailinglists35** [comment]
update altserver. I had the same error message on monterey and after update worked

**Comment by Anywhereyouare** [comment]
yes it worked thanks so much!!

**Comment by Haroon-Sharif** [comment]
I tired updating the AltServer app but it still didn;'t work. Any advise?

**Comment by tatooye** [comment]
same issues after update 1.5 altserver

**Comment by leonpano2006** [comment]
same here

**Comment by Xmoncoco** [comment]
really I don't know why the latest fix is on the patreon because the plugin was fix but only for the patreon supporter

**Comment by joshuah345** [comment]
1. Ensure AltServer.app is in /Applications
2. Check for updates to AltServer

If there's no updates available or the issue still isn't resolved, try the steps below.

1. Quit Mail
2. Open a Finder window and press Command+Shift+G
3. Go to this path: ~/Library/Application Support/Mail/Plug-ins
4. Rename “Bundles” in the opened folder to “Bundles-DISABLED”
5. Open Mail and Enable AltPlugin.mailbundle once again.

@Haroon-Sharif @Xmoncoco  @tatooye @leonpano2006

**Comment by davidnoelopez** [comment]
> 1. Ensure AltServer.app is in /Applications
> 
>     2. Check for updates to AltServer
> 
> 
> If there's no updates available or the issue still isn't resolved, try the steps below.
> 
>     1. Quit Mail
> 
>     2. Open a Finder window and press Command+Shift+G
> 
>     3. Go to this path: `~/Library/Application Support/Mail/Plug-ins`
> 
>     4. Rename “Bundles” in the opened folder to “Bundles-DISABLED”
> 
>     5. Open Mail and Enable AltPlugin.mailbundle once again.
> 
> 
> @Haroon-Sharif @Xmoncoco @tatooye @leonpano2006

Thanks! that worked for mail 16.0 in macos 12.4

**Comment by CypherVault** [comment]
> 1. Ensure AltServer.app is in /Applications
> 2. Check for updates to AltServer
> 
> If there's no updates available or the issue still isn't resolved, try the steps below.
> 
> 1. Quit Mail
> 2. Open a Finder window and press Command+Shift+G
> 3. Go to this path: `~/Library/Application Support/Mail/Plug-ins`
> 4. Rename “Bundles” in the opened folder to “Bundles-DISABLED”
> 5. Open Mail and Enable AltPlugin.mailbundle once again.
> 
> @Haroon-Sharif @Xmoncoco @tatooye @leonpano2006

this worked mail 16.0 macOS 12.6 THANK YOU SO MUCH

**Comment by HandingTo1** [comment]
> 1. Ensure AltServer.app is in /Applications
> 2. Check for updates to AltServer
> 
> If there's no updates available or the issue still isn't resolved, try the steps below.
> 
> 1. Quit Mail
> 2. Open a Finder window and press Command+Shift+G
> 3. Go to this path: `~/Library/Application Support/Mail/Plug-ins`
> 4. Rename “Bundles” in the opened folder to “Bundles-DISABLED”
> 5. Open Mail and Enable AltPlugin.mailbundle once again.
> 
> @Haroon-Sharif @Xmoncoco @tatooye @leonpano2006

Thank you, MacOS 12.6.1, Mail 16.0 has successfully run according to this method👍

**Comment by Starry-Tacos** [comment]
My mac is currently running on MacOS 12.5.1 (Monterey) and I don't have `Mail` in `Application Support`.

**Comment by aow207** [comment]
@Starry-Tacos Go to Finder and type "cmd + shift  + g" then you should be able to paste the path in.

**Comment by faizanafz** [comment]
> 1. Ensure AltServer.app is in /Applications
> 2. Check for updates to AltServer
> 
> If there's no updates available or the issue still isn't resolved, try the steps below.
> 
> 1. Quit Mail
> 2. Open a Finder window and press Command+Shift+G
> 3. Go to this path: `~/Library/Application Support/Mail/Plug-ins`
> 4. Rename “Bundles” in the opened folder to “Bundles-DISABLED”
> 5. Open Mail and Enable AltPlugin.mailbundle once again.
> 
> @Haroon-Sharif @Xmoncoco @tatooye @leonpano2006

This worked for me as well. 
macOS Version 12.6.3 (21G419)
Mail 16.0
Altserver 1.6

**Comment by jefro108** [comment]
It was working for me on Ventura before I transferred from an old Intel Mac (that I had upgraded using OpenCore-Patcher) but, on an M1 Pro MacBook Pro, it comes up with this error while the above instructions have no effect. 
macOS 13.3 (22E252)
Mail Version 16.0 (3731.500.231)
AltServer Version 1.6 (72)

Any other solution?

**Comment by MaximeLuk** [comment]
There is no bundles icon in the plug-ins folder
![Screenshot 2023-08-13 at 9 27 51 PM](https://github.com/altstoreio/AltStore/assets/124394124/b34aefc8-51c2-439b-8c33-3149069350a6)

**Comment by laik** [comment]
thanks ,efficient in macOs 13.5.1
