### ISSUE TITLE
Website version out of date

### ISSUE THREAD

**Issue by Jarred-Sumner** [rileytestut/AltStore#101]
The website version is `1.1.2` but in Releases, it shows `1.2.0` is available.

It'd be great if releases included precompiled `.app` files.

I'm trying to update because the mail plugin is failing to install on my Mac (10.15.3).

Edit: I didn't realize that, in order to install the mail plugin, I had to go in here and check this box:
![image](https://user-images.githubusercontent.com/709451/74404995-dfbdea80-4de0-11ea-89cd-ddd5b29af3fa.png)
I suggest updating the instructions to include this step.

**Comment by noah978** [comment]
These instructions are now included in the FAQ. Closing this issue.
