### ISSUE TITLE
Still impossible to sign Kodi

### ISSUE THREAD

**Issue by michael1900** [rileytestut/AltStore#1015]
HI! When this will be solved? It's almost 1 year now.

**Comment by michael1900** [comment]
No one? :(

**Comment by michael1900** [comment]
@rileytestut

**Comment by michael1900** [comment]
no one single reply.. only those who pay on patreon can have an answer?

**Comment by shanegillio** [comment]
hi, sorry for no replies on these messages as we are working to improve our outreach. I have the Kodi bug listed as a priority, so only going to close this as a duplicate, but know that it will be looked at.
