### ISSUE TITLE
iOS 16.0 Developer Disk Image not added to the CDN yet

### ISSUE THREAD

**Issue by willfaust** [rileytestut/AltStore#1022]
The [JSON](https://cdn.altstore.io/file/altstore/altserver/developerdisks.json) on the AltStore CDN with URLs to Developer Disk Images is not yet up to date with an entry for iOS 16.0. This prevents AltJIT from functioning on devices running the iOS 16 Developer Beta.

The two URLs listed below should be added to the CDN:

16.0 disk URL:
https://raw.githubusercontent.com/pdso/DeveloperDiskImage/master/16.0/DeveloperDiskImage.dmg

16.0 signature URL:
https://raw.githubusercontent.com/pdso/DeveloperDiskImage/master/16.0/DeveloperDiskImage.dmg.signature

**Comment by Hycade** [comment]
This is also preventing all newly installed apps from launching, each of them will crash immediately upon launch.

**Comment by coreycusick** [comment]
This was fixed, it is there as of this morning

**Comment by Kenan-Blasius** [comment]
Same problem with iOS 16.4 here are the two necessary links:

16.4 disk URL:
https://raw.githubusercontent.com/pdso/DeveloperDiskImage/master/16.4/DeveloperDiskImage.dmg

16.4 signature URL:
https://raw.githubusercontent.com/pdso/DeveloperDiskImage/master/16.4/DeveloperDiskImage.dmg.signature
