### ISSUE TITLE
Altstore randomly doesn’t be available on iOS 16 beta1

### ISSUE THREAD

**Issue by justyuya** [rileytestut/AltStore#1025]

**Comment by JJTech0130** [comment]
Could you provide some more information? I'm on the beta, and I don't have any issues with it.

**Comment by justyuya** [comment]
When I tried to install UyouPlus, the installation continued endlessly and then became unusable

**Comment by justyuya** [comment]
Then Altserver crashes when trying to reinstall Altstore.

**Comment by justyuya** [comment]
This tweet 

https://twitter.com/arichornyt/status/1536838133102399488?s=21&t=3wew3QNdhx-IdtDYbRB4mA

**Comment by lrs95** [comment]
alike...
