### ISSUE TITLE
MessagesExtension.appex/Info.plist: No such file or Directory

### ISSUE THREAD

**Issue by martinoturrina** [rileytestut/AltStore#1038]
While installing uYou Plus IPA I’m always getting this “ MessagesExtension.appex/Info.plist: No such file or directory”

This happens with various IPAs

ios16 iphone 11 pro

![80AE3060-5015-49E3-AA08-7C042EA3899E](https://user-images.githubusercontent.com/13062849/180770571-2be95675-728d-47c0-8b0d-f6ddff37142a.png)

**Comment by martinoturrina** [comment]
Probably happening due to the specidic IPA

**Comment by lakshayb** [comment]
How did you get it fixed i am having the same issue

**Comment by martinoturrina** [comment]
@lakshayb I think it was related to the specific IPA I was trying to install (uYou+) 
Which was the IPA in your case?

**Comment by lakshayb** [comment]
I was tried multiple IPAs of uYouplus from github and appdb but still the same result. Did you find any other ipa working for you?

**Comment by martinoturrina** [comment]
Not yet but uYouPlus seems the one having this problem since it's also mentioned in their FAQ

**Comment by parthnayak7448** [comment]
Hello 

I am facing same problem currently with latest of cercubePlus and uYouPlus in ios 16 

can you guys tell me exact steps how you guys resolve the issue?

**Comment by novitae** [comment]
same for uYouPlus_17.36.3_21.1_F2

**Comment by martinoturrina** [comment]
For me the solution was:

- delete altstore and all sideloaded apps
- delete youtube official app
- reboot
- install altstore
- authorize dev profile
- install uYouPlus

Maybe first try without deleting altstore, I thin in my case the fixing action was to delete yt and reboot

**Comment by tinng81** [comment]
I don't have a problem with installing uYouPlus but cannot backing up; without extensions and no other Youtube apps were already installed. Anyone able to backup uYouPlus? Backing up other apps were fine.

uYouPlus `v17.39.5-2.1`
AltStore `v1.5.1`
