### ISSUE TITLE
AltStore misspelled my name

### ISSUE THREAD

**Issue by StormyGalaxy** [rileytestut/AltStore#1039]
In my apple account i have my name spelled as Gehrig, but in the app they have my name spelled as Gehig. Why did this happen, and is there a way to fix this?
![CE459AC1-E887-42EC-813B-806F5D7A467A](https://user-images.githubusercontent.com/67121041/181358450-a2cd6a35-ce80-4e49-98a1-860d7e11ef21.jpeg)
![86ACB4D3-86C2-4EC2-A9AA-634AD33D6B18](https://user-images.githubusercontent.com/67121041/181358455-3a868cd0-f10b-4bb0-ab63-868e62651ae2.jpeg)

**Comment by mth141** [comment]
> In my apple account i have my name spelled as Gehrig, but in the app they have my name spelled as Gehig. Why did this happen, and is there a way to fix this?
> ![CE459AC1-E887-42EC-813B-806F5D7A467A](https://user-images.githubusercontent.com/67121041/181358450-a2cd6a35-ce80-4e49-98a1-860d7e11ef21.jpeg)
> ![86ACB4D3-86C2-4EC2-A9AA-634AD33D6B18](https://user-images.githubusercontent.com/67121041/181358455-3a868cd0-f10b-4bb0-ab63-868e62651ae2.jpeg)

**Comment by lonkelle** [comment]
This is something only AppleCare can fix actually. They require verification of your license - well, they needed it for me anyway when I had the same thing happen to me.
