### ISSUE TITLE
iPA installation failed with "Your session has expired. Please log in. (1100)" error

### ISSUE THREAD

**Issue by telegramcore** [rileytestut/AltStore#104]
Hi, I have this error when I try to install any IPA that is not alt store, I'm on win 7 64 bit and yes I have iTunes and iCloud.

What does it mean and how to fix? Thanks.

![](https://i.imgur.com/JmJeliq.jpg)

**Comment by noah978** [comment]
Windows 7 is not officially supported and we also don't take AltServer Patcher issues here. However, the issue should be fixed by updating to the latest version of AltServer.
