### ISSUE TITLE
AltStore not refreshing app in background

### ISSUE THREAD

**Issue by adamturbo** [rileytestut/AltStore#105]
I’m running iPhone 11 Pro, iOS 13.2.3 and using latest version of MacOS Catalina, AltStore 1.2b4 and AltServer 1.2b2. Every time I enter the debug menu and select ‘View Refresh Attempts’ it says ‘No Refresh Attempts.’ I have download the app for a week, left my MacBook on with the power on and lid closed. And have my phone plugged in the power most of the time when I’m at home.

**Comment by nighto** [comment]
I think the lid would need to be open, and the computer woke up and in use.

**Comment by webvictim** [comment]
Does manually refreshing inside the app work?

You also need Background App Refresh enabled for AltStore. The more you open AltStore, the more often iOS tries to refresh it in the background.

**Comment by adamturbo** [comment]
It all seems to be working well since the update for unc0ver
