### ISSUE TITLE
Where source adding button?

### ISSUE THREAD

**Issue by ra1n08** [rileytestut/AltStore#1052]
Hi, im using ios 14.7.1 and altstore 1.5.1

so i want add some source :)
I opened source window, i see buitin source
But i can’t find + button, now im disconnected altstore out altserver

tks
Srr for my english
![93ABF93B-4E3D-41B8-B927-32794085934E](https://user-images.githubusercontent.com/89585797/188422208-3025fa4b-e959-4558-954b-a9e7f1f6c358.png)

**Comment by AlexSpaces** [comment]
Are you jailbroken?

**Comment by ra1n08** [comment]
No, im not jailbreak, so what wrong?

**Comment by bigfloppa234** [comment]
You need a beta version of AltStore to add custom sources

**Comment by ra1n08** [comment]
> You need a beta version of AltStore to add custom sources

can run?
