### ISSUE TITLE
AltServer crashes when trying to install AltStore to phone

### ISSUE THREAD

**Issue by vladaad** [rileytestut/AltStore#106]
Tried with 2 apple IDs, running Windows 10 1909. Installing to iPhone 8, iOS 13.3, jailbroken. Crashes after entering apple id. Happens also when intentionally entering bad password

**Comment by vladaad** [comment]
Still is an issue with AltServer 1.2.1

**Comment by Beninjam101** [comment]
Same problem here on MacOS Catalina with the same device and iOS version

**Comment by noah978** [comment]
Updating to the [latest version of AltServer](https://altstore.io/altserver/beta) should fix the problem. I'll consider this issue closed.
