### ISSUE TITLE
MacOs Support High Sierra 10.13.6

### ISSUE THREAD

**Issue by tomsmile0** [rileytestut/AltStore#107]
Can someone help me run MacOs High Sierra 10.13.6?

**Comment by BartmanEH** [comment]
duplicate of [https://github.com/rileytestut/AltStore/issues/88#issue-549952273](https://github.com/rileytestut/AltStore/issues/88#issue-549952273)

**Comment by noah978** [comment]
Closing since this is a duplicate of #88.
