### ISSUE TITLE
icon missing windows11

### ISSUE THREAD

**Issue by Xiantyl** [rileytestut/AltStore#1072]
The Altserver icon no longer shows in windows 11 taskbar , unable to install altstore on device. I reinstalled and rebooted three times. Four others have this issue on reddit as well.

**Comment by chriszhang1** [comment]
same issue

**Comment by Xiantyl** [comment]
Are you on windows 11?

**Comment by chriszhang1** [comment]
yes 22H2

**Comment by okejadi** [comment]
can we launch command to install altserver to the ios with cmd line?
