### ISSUE TITLE
Windows 11 (Insider Preview) New Taskbar Update Broke Altstore in the Tray Menu 

### ISSUE THREAD

**Issue by Multisquid2k3** [rileytestut/AltStore#1075]
Windows 11 Insider Preview added a new taskbar update which broke Altstore. (I can't access it anymore in the tray menu, it's hidden)
I tried reinstalling but nothing changes.
![JsWDTF3Abc](https://user-images.githubusercontent.com/102807444/197626737-31c69651-cd41-4697-8246-a05d69cbf20e.gif)
.

**Comment by stressatoo** [comment]
can repro, same

**Comment by tbb98** [comment]
Same issue, thanks MS 😎👍

**Comment by tbb98** [comment]
#1072

**Comment by Star-tears** [comment]
me too，please quickly fix this bug！

**Comment by Neo1102** [comment]
Windows 11 Pro  Ver: 10.0.22623 N/A Build: 22623 , same.

**Comment by Wonerby** [comment]
You can use [this](https://github.com/valinet/ExplorerPatcher) to solve the problem temporarily

**Comment by shanegillio** [comment]
hi all! we have many reports on this issue and are working on a fix to be available shortly. I'm going to close this as a duplicate, but thank you for reporting
