### ISSUE TITLE
Issue with altserver not visible in taskbar area

### ISSUE THREAD

**Issue by rutvik788845** [rileytestut/AltStore#1080]
Since update Windows 11 Pro Insider Preview
Version	22H2
Installed on	‎10/‎31/‎2022
OS build	25231.1000
Experience	Windows Feature Experience Pack 1000.25231.1000.0

i am facing a weird error which is causing altstore to not to show up on taskbar menu 
i tried reinstalling, opening with administrator, updating windows still its not working !
please provide a solution. 
Thank you !

![image](https://user-images.githubusercontent.com/25553036/198912250-30a00d45-cf6f-423d-95da-40831d8acdea.png)

**Comment by Lord0SY** [comment]
u need to uninstall the update uploaded in the beginings of october i cant find the series number of the update anymore

**Comment by abbaccadd0** [comment]
> u need to uninstall the update uploaded in the beginings of october i cant find the series number of the update anymore

He joined the Windows Insider and now he's in the Dev Channel, so there's no choice to uninstall the October update

https://github.com/rileytestut/AltStore/issues/1072 is the same issue, just wait developers to fix it

**Comment by oomek** [comment]
Same here, AltServer missing in the system tray, but the process is running.
Unfortunately refreshing also stopped working. Any chance for a fix?

**Comment by Marcus5408** [comment]
![image](https://user-images.githubusercontent.com/46655509/202616651-f9450ae1-034e-4e0f-849e-9901a55cbe0e.png)
On the Dev channel as well, Windows 11 Pro Insider Preview 22H2 build 25236.1000 and AltServer does not show up in taskbar

**Comment by nyancatda** [comment]
Windows Feature Experience Pack 1000.22637.1000.0 encountered the same problem

**Comment by oomek** [comment]
Are we getting a fix for that any time soon?

**Comment by craftgeil** [comment]
Same problem, is it beeing worked on?

![Screenshot (2)](https://user-images.githubusercontent.com/80261988/205453618-75fb268b-3b83-41ae-b3ed-b5c0706cc0c1.png)

**Comment by oomek** [comment]
@rileytestut

**Comment by Wonerby** [comment]
You can use [this](https://github.com/valinet/ExplorerPatcher) to solve the problem temporarily

**Comment by craftgeil** [comment]
Explorer Patcher does not revert my Taskbar to the old one. It kinda buggs around and when clicking the taskbar, the taskbar crashes and restarts itself, till I uninstall Explorer Patcher. Could it be that newer versions of Windows stop working with Explorer Patcher?

**Comment by Marcus5408** [comment]
> You can use [this](https://github.com/valinet/ExplorerPatcher) to solve the problem temporarily

ExplorerPatcher causes Windows to stop rendering my Desktop and makes my taskbar turn into a tiny sliver that can't be resized.

**Comment by nyancatda** [comment]
ExplorerPatcher is useless, it crashes in this Windows preview

**Comment by chriszhang1** [comment]
any replies from developers?

**Comment by oomek** [comment]
...

**Comment by lonkelle** [comment]
@chriszhang1 I'm trying very hard to get @shanegillio or @rileytestut on this. I have been away from this project for awhile but this is app-breaking and needs to be addressed ASAP.

**Comment by chriszhang1** [comment]
@lonkelle Thank you so much!

**Comment by nyancatda** [comment]
> @chriszhang1 I'm trying very hard to get @shanegillio or @rileytestut on this. I have been away from this project for awhile but this is app-breaking and needs to be addressed ASAP.

Thank you

**Comment by lonkelle** [comment]
> Still no update on this I presume? Kinda odd how this hasn't been resolved yet. It's been nearly 3 months now.

I find it hard to believe myself that it's been this long. But there's radio silence from Riley and Shane - so the community, with Joe from Provenance and myself heading the project, has decided to forego waiting for Riley / Shane and we've built SideStore + an AltServer replacement to be released January 18th (soon). Will update this ticket on release date.

PS. SideStore doesn't require any server to refresh or install on-device IPAs, literally being on any WiFi network will allow SideStore to function as we built in a module I call "SideServer mobile" into the app itself to run the commands without needing any external computer. It's a pretty cool project we can't wait to share with you guys.

But just to show y'all, I really did try to get Riley and Shane to fix this issue:

![Screenshot 2023-01-05 at 4 06 49 AM](https://user-images.githubusercontent.com/5572600/210742566-376ef89b-ec2c-4d56-86f4-0b1f01a9d01d.jpg)

**Comment by nyancatda** [comment]
Is this bug still possible to be fixed, AltStore still doesn't work properly in the latest beta version of Windows

**Comment by Marcus5408** [comment]
> Is this bug still possible to be fixed, AltStore still doesn't work properly in the latest beta version of Windows

Apparently they're working on it

**Comment by shanegillio** [comment]
the latest AltServer release is available now on the Github with a fix and a regular release will come soon. Going to close this out now, but please reopen if the issue persists

**Comment by oomek** [comment]
I don't see it. Can I have a direct link please?

**Comment by nyancatda** [comment]
This problem has not been solved in the 1.5.2b version of AltServer, and the taskbar still cannot see the icon

**Comment by nyancatda** [comment]
Windows version 22623.1095

**Comment by nyancatda** [comment]
![image](https://user-images.githubusercontent.com/63787593/213511089-151bcf76-eb1a-41e3-848d-82681a171372.png)
![image](https://user-images.githubusercontent.com/63787593/213511162-2c4a131e-eb1f-4350-b10b-f4ff3b063c08.png)

**Comment by nyancatda** [comment]
@shanegillio

**Comment by Scoty43** [comment]
I have the same issue on latest Windows 11 22623.1095. I dont see a Icon and can not open. i have uninstall and install again but not help.
