### ISSUE TITLE
Can't install IPAs - Build error?

### ISSUE THREAD

**Issue by Peiprjs** [rileytestut/AltStore#1082]
I've tried reinstalling Altstore several times. I've tried cable, WiFi.
Fails to load info.plist. See image
![IMG_6C6F84E767D8-1](https://user-images.githubusercontent.com/72313029/199597195-b4a04825-eb92-4017-8b16-4acb17bb047e.jpeg)

**Comment by lonkelle** [comment]
Does this happen for every IPA or just a specific one?
