### ISSUE TITLE
the flutter_secure_storage key conflict

### ISSUE THREAD

**Issue by jiangxiaoqiang** [rileytestut/AltStore#1089]
When I using altstore 1.5.1 to install apps in the iPhone(15.6.1), I found the flutter_secure_storage key conflict across apps, for example the app1's refresh token was share with other apps, it it possible to avoid this problem?

**Comment by lonkelle** [comment]
I've seen a conflict when installing more than one AltStore's on a device, is this perhaps what you ran into?

**Comment by jiangxiaoqiang** [comment]
> I've seen a conflict when installing more than one AltStore's on a device, is this perhaps what you ran into?

I only installed one altstore, I have changed the cached key name for different apps, this problem solved.
