### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by aclem339** [rileytestut/AltStore#109]
I'm using Win10, iphone 8 13.3
Error : This Action could not be completed. Try Again. (-22421)
What i did before install Altserver: 
1) installed Itunes from the apple' site
2) ^ Same thing with icloud
3) installed Altserver (Windows)
4) Re-start Windows
5) Iphone connected from usb Cable.
6) Itunes Sync wifi Enabled
7) Install Altstore -> Got this error.

**Comment by noah978** [comment]
Moving this issue to #175.
