### ISSUE TITLE
How can I distribute my apps to that store? How-To available?

### ISSUE THREAD

**Issue by theRealBitcoinClub** [rileytestut/AltStore#11]
If I wanted to distribute to that store, would I be able to do that without paying the $99 for the developer Apple ID??

Is there any How-To available on how to distribute to that store?

**Comment by Danbana** [comment]
Yes, Riley we would love any info about this.

AltStore seems not quite ready to add other apps, but perhaps we could have a sideloading apps directory in the mean time. or some information about how to distribute apps for sideloading. 

thanks

**Comment by khertan** [comment]
I would love also to distribute my open source apps.

**Comment by brvier** [comment]
I would love also to distribute my open source apps

**Comment by noah978** [comment]
This feature is currently in the AltStore Patreon Beta. If you'd like a how-to guide on how to create your own AltStore Source, you can find that [here.](https://noah978.github.io/AltStore-Docs/Sources)

Closing this issue since it has been properly addressed.
