### ISSUE TITLE
Add VCMI in trusted sources

### ISSUE THREAD

**Issue by Nordsoft91** [rileytestut/AltStore#1101]
Hi team, tried to reach you via email, but didn't get any response. 

I’m representing VCMI team ([vcmi.eu](http://vcmi.eu/)) and we are making Heroes of Might & Magic III open-source engine.
The project has quite long history from 2008 and now finally ported our engine to iOS.
On GitHub: https://github.com/vcmi/vcmi

We made new release today, so want to ask for adding our application into AltStore (basically into trusted sources) as primary distribution platform for iOS users.

Record to be added into trusted sources.json should look like this
```
{
      "identifier": «com.vcmi.VCMI",
      "sourceURL": "https://raw.githubusercontent.com/vcmi/vcmi-updates/master/altstore/altstore.json"
}
```
What else is necessary for that? Should I also create PR with «news» update into apps.json?

Thank you in advance!

**Comment by shanegillio** [comment]
Hi there! Sorry we missed your email, and I will certainly take a look at this source. We have a JSON format I can give you as well to make sure you use the correct formatting we need for any trusted sources

**Comment by Nordsoft91** [comment]
@shanegillio , thanks, I've updated json. Should work for now

**Comment by Nordsoft91** [comment]
@shanegillio , when it will appear at store?

**Comment by shanegillio** [comment]
I will try out the source and do some testing to give feedback. I'm not sure if this will become a trusted source, but those on the beta version will be able to enter in the source link themselves. So if everything is working, you can let users know that a source for the app is available

**Comment by noah978** [comment]
> @shanegillio , when it will appear at store?

Aside from the trusted source, I would also advise displaying the AltStore repo on your public installation instructions. You’ll find the URI install link can be helpful for this: https://noah978.gitbook.io/altstore-docs/url-schemes

Additionally, the open source docs if you haven’t seen them yet are quite helpful at explaining how the json works: https://noah978.gitbook.io/altstore-docs/sources

**Comment by Nordsoft91** [comment]
> Is this essentially a way to mod this old game that people still play?

No, it's not a mod, but engine which allows basically to play old game on any platform. Also it's actively supported so we are going to have another incremental release quite soon

**Comment by Nordsoft91** [comment]
> Aside from the trusted source, I would also advise displaying the AltStore repo on your public installation instructions.

It's already there: https://wiki.vcmi.eu/Installation_on_iOS

**Comment by Nordsoft91** [comment]
json updated according to latest requirements [https://github.com/vcmi/vcmi-updates/blob/master/altstore/altstore.json]

**Comment by shanegillio** [comment]
It's telling me this isn't a valid JSON, so maybe something got messed up? 

Also I think what @noah978  is saying is to include the JSON link on the install page so people can copy/paste it easily

**Comment by noah978** [comment]
It’s not valid because there is an extraneous comma after the “size” attribute:

```json
"size": 25570455,
```

**Comment by Nordsoft91** [comment]
usually json supports commas at last elements because it helps to avoid mistakes while expanding objects.
Anyway, fixed now

**Comment by noah978** [comment]
@Nordsoft91 Actually I just noticed a flaw in your AltSource, the latest version you have is listed second in the “versions” array, AltStore doesn’t actually check to see which versions in the list are the latest, for auto-updating purposes, it simply assumes that the version at index 0 (the top) is the latest version

**Comment by Nordsoft91** [comment]
@noah978 , understood, fixed

**Comment by Nordsoft91** [comment]
Should I reopen this?

**Comment by shanegillio** [comment]
let me test out the source and app, and I can DM you later on what we're thinking
