### ISSUE TITLE
Support for Linux in the future?

### ISSUE THREAD

**Issue by ghost** [rileytestut/AltStore#111]
In the future can this be ran on Linux Ubuntu Arch etc?

**Comment by realmayus** [comment]
Did you try using Wine?

**Comment by Austcool-Walker** [comment]
> Did you try using Wine?

no but I'll try and get back with you.

**Comment by Austcool-Walker** [comment]
@realmayus I tried it isn't working because of I could required programs that I couldn't get in wine... A native build against libimobiledevice would be best I think.

**Comment by BananaManCJ** [comment]
I highly doubt we'll ever get a native AltServer for Linux since the Apple Mobile Device driver doesn't exist for Linux

**Comment by noah978** [comment]
Duplicate of #6. Closing this issue.
