### ISSUE TITLE
the procedure entry point IsWow64Process2 could not be located in the dynamic link library obs.dll

### ISSUE THREAD

**Issue by prince00p** [rileytestut/AltStore#1110]
![Capture](https://user-images.githubusercontent.com/122534745/212325440-b3b85ccc-2a43-43fa-894f-2f07699c1d22.PNG)
facing this error when i try to open obs latest virsion in windoes 10 pro. i install all the microsoft visual c ++ but its not working

**Comment by shanegillio** [comment]
are you saying this is related to altstore somehow?

**Comment by prince00p** [comment]
No I am facing this problem after installing new version of obs

**Comment by shanegillio** [comment]
ok, I will have to close this then and recommend you post to https://github.com/obsproject/obs-studio
