### ISSUE TITLE
Server Tray Icon Is Not Appearing - Windows11

### ISSUE THREAD

**Issue by nimsandu** [rileytestut/AltStore#1116]
### **issue description**: 
After Recent windows11 updates (22h2), after launching altserver tray Icon does not appear as it used to be. but application is running properly in the background.

### **Issue Screenshots**
![Issue](https://user-images.githubusercontent.com/57834844/214482704-eee4e5a8-e94d-4c29-87e9-1bbc3db909b6.png)

### **Specs and Other Necessary Info** 
_Windows_ 

> Edition	Windows 11 Pro
>Version	22H2
>Installed on	‎9/‎25/‎2022
>OS build	22621.755
>Experience	Windows Feature Experience Pack 1000.22636.1000.0

_Taskbar Overflow Icons Page_
![Screenshot_20230125_102611](https://user-images.githubusercontent.com/57834844/214483452-e0c9f82f-94cd-4b29-aabf-ec766dbd8b90.png)
![Screenshot_20230125_102633](https://user-images.githubusercontent.com/57834844/214483454-d2ef4fe2-cd04-4235-9bb7-8bfae9d61d24.png)

_Experimented the issue by_
>Restarting The machine.
>Ending Altserver Task and rerunning. 
>completely uninstalling and re installing latest setup.
>repairing application using latest setup. 

**note1: Even though icon doesn't appear, refreshing apps on iPhone is possible. this issue only effects when installing altstore using altserver**

**note2: This issue doesn't present on windows11 22h1 and windows 10 latest versions.**

**Comment by TotallyNotPooh** [comment]
Me too. Hope this got fixed soon as possible.

**Comment by shanegillio** [comment]
Hi there! have you tried this public beta release that we made to fix this - https://github.com/rileytestut/AltServer-Windows/releases/tag/1.5.2b

make sure to first uninstall any AltServer files for the previous version to make sure this works correctly

**Comment by Kholtien** [comment]
This doesn't seem to work. I just uninstalled Altserver, restarted my pc, then installed this beta. Still no access to altserver

**Comment by nimsandu** [comment]
> Hi there! have you tried this public beta release that we made to fix this - https://github.com/rileytestut/AltServer-Windows/releases/tag/1.5.2b
> 
> 
> 
> make sure to first uninstall any AltServer files for the previous version to make sure this works correctly

Probably we haven't. I really appreciate you for reporting this. Ill install this public beta asap and let you know whether it's fixed

**Comment by nimsandu** [comment]
@shanegillio you got me! everything works fine in this prerelease.
@TotallyNotPooh you should try it too. it will fix the issue. 
![Untitled](https://user-images.githubusercontent.com/57834844/215642366-a69dd19e-91f6-4de5-97bd-704993619277.png)
@shanegillio thanks for your help.
Closing the issue as completed

**Comment by TotallyNotPooh** [comment]
@nimsandu yeah its works! tks

**Comment by nimsandu** [comment]
@TotallyNotPooh Nice
All the credit goes to @shanegillio

**Comment by shanegillio** [comment]
HOORAY :)

**Comment by Lightup1** [comment]
> It is happening now in my windows 22621.1992. The server tray icon is not appearing. I've tried both the latest version of AltStore from the website or the version I found in this issue.

I try to use the compatible mode win8 to start the server, then everything works fine.

**Comment by LeXuanKhanh** [comment]
> > It is happening now in my windows 22621.1992. The server tray icon is not appearing. I've tried both the latest version of AltStore from the website or the version I found in this issue.
> 
> I try to use the compatible mode win8 to start the server, then everything works fine.

this work in window 11 22H2 22621.2428
