### ISSUE TITLE
No AltStore in "Open in"

### ISSUE THREAD

**Issue by Duxter7** [rileytestut/AltStore#117]
Installed Filza File Manager and i suppose after that I longer see AltStore in "Open in". Rebooted. And now i can't install jailbreak. Tried reinstalling AltStore - no result. Just wanted to update unc0ver)

**Comment by santscho** [comment]
sideloading .ipa files is only possible with AltStore Beta. For this, you need to pay 3$. I did and it says, I can download the Beta now. But when I try, I am getting the message, that connection to the server is not possible. :-(

**Comment by noah978** [comment]
Filza is causing an issue with AltStore in this case. It shouldn't be an issue on the latest versions of AltStore and Filza, if it persists, please leave a comment below. Closing this issue.
