### ISSUE TITLE
Will there someday be a way to refresh App IDs without needing Mail to be running in the background?

### ISSUE THREAD

**Issue by Evertt** [rileytestut/AltStore#118]
Because I _never_ use Mail, which basically means that the App ID refreshing is a manual process. I can't let it work automatically in the background and that makes using AltStore waaaay less appealing.

**Comment by nighto** [comment]
I also don't use Mail, what I do is to open it once, add an account that
doesn't receive any messages, remove notifications and minimize it so it is
out of my way. So whenever I reboot it's just opening and minimizing it,
really painless.


Em sex., 21 de fev. de 2020 às 18:37, Evert van Brussel <
notifications@github.com> escreveu:

**Comment by Evertt** [comment]
Yeah but then it takes up space in my app-switcher. Like it sounds stupid, but that does kinda bother me.

**Comment by jcampbell05** [comment]
I presume this is to get the certificates ?

**Comment by aaron-trout** [comment]
Kinda off topic here but it would be good to have an FAQ entry to explain the purpose of the Mail plugin. Is this on the Phone or Mac side? Cheers!

**Comment by noah978** [comment]
I have answered this question on #152 if you are interested.
