### ISSUE TITLE
Paid developer accounts

### ISSUE THREAD

**Issue by jcampbell05** [rileytestut/AltStore#120]
Will there be support for those who do have paid accounts ?

**Comment by winedog** [comment]
It doesn't work with a paid developer account? I have tried to run it using my developer appleid and I get a -22411 error, but if I use my regular personal appleid it works fine?

**Comment by Kidohu** [comment]
Use Cydia Impactor. You will become no xcode error with an Dev Account at Cydia Impactor.

**Comment by noah978** [comment]
There is paid developer account support but there is a bug related to it that prevents it from working properly, transferring this to #199.
