### ISSUE TITLE
AltStore Email and Password Won't Work

### ISSUE THREAD

**Issue by helpmanthatsme** [rileytestut/AltStore#123]
I did everything correctly because I have AltStore downloaded and it is running on my computer and I synced it. But when I go to put my email and password on AltStore on my phone it logs me in. I go to download an app, it says: "Your Apple ID or password was entered incorrectly (20101)." I look at my email and it is changed to my old email that I use to use and I don't know how to fix it. Plz help if you can 

![IMG_3290](https://user-images.githubusercontent.com/61524771/75399136-b6a95980-58b8-11ea-8442-16bd906d1e56.PNG)
![IMG_E3291](https://user-images.githubusercontent.com/61524771/75399143-ba3ce080-58b8-11ea-8ce4-5dc0a0f91116.png)

**Comment by luixiuno** [comment]
I got the same issue

**Comment by luixiuno** [comment]
I try to install delta, and uncover but, the give me Apple ID incorrect error code: -20101

**Comment by luixiuno** [comment]
Try by installing appcake or jailbreak

**Comment by luixiuno** [comment]
if you are tryna install delta then go to checker.in and jailbreak

once you jailbroke and install Cydia then add this repo: http://getdelta.co/

or: deltarepo.github.io

**Comment by luixiuno** [comment]
Enjoy :)

**Comment by dontbanmeplz** [comment]
ok I know how to fix this
1. connect your computer to your phone hotspot
2. retry

**Comment by luixiuno** [comment]
install ReProvision Or Unc0ver from iosgods and Provision it with ReProvision just log in with dev account (paid or free) then it signs them, even if your membership is expired, and once it's done, 

if you used checkra1n then restart, if your app is unc0ver then open it AND GOD IT WORKS!

You're welcome, you can also import ipas to reprovision and it installs them and signs them for 6 days so resign them all when 2 days left or if you wait 2 days more they won't open.


I recommend the tweak called: appsync unified made by linus yang on the repo: https://cydia.akemi.ai/

**Comment by noah978** [comment]
This issue should be fixed in the latest updates to AltStore/AltServer. Make sure to try using a USB cable and restarting your device(s). Closing this issue.
