### ISSUE TITLE
This Action could not be completed. Try Again. (-22411)

### ISSUE THREAD

**Issue by 4x8** [rileytestut/AltStore#124]
Using Windows 10
installed Itunes from the Apple site
installed Icloud from the Apple site
restarted my pc 
iphone connected and wifi synced 
installed & re-installed Altstore

Tried doing it with a Mac Book
got the same error

**Comment by Spidy123222** [comment]
How did you solve this problem exactly sense it’s closed. I’m having the same problem with getting error -22411. I’m wondering if it’s me using a iCloud email but I would think that wouldn’t matter.

I’ve tried things like reinstalling iTunes and iCloud
Reinstalled altstore 5 times and tried changing password and a new appleID.

**Comment by 4x8** [comment]
Hello,
yes I just made a new iTunes account and it worked.
