### ISSUE TITLE
Windows beta altstore/altserver not working - NO OTHER OPTIONS for iphone 5 32 bit - please help

### ISSUE THREAD

**Issue by AnakinSkywalkerVader** [rileytestut/AltStore#128]
i've tried several times to make this all work on my iphone 5 32 bit ios 10.3.4 but have been met with every prob listed in the faq & more. I've uninstalled & reinstalled & restarted windows a few times but nothing works & altstore never does install at all on iphone 5 no matter how long ya wait or what else ya try. i have both itunes & icloud installed directly from apple but that didnt seem to make any diff either especially now when even the Apple itunes site says to download itunes from microsoft LOL never thought id c the day that would happen haha. 

Anyways another thought i had is that I have ubuntu installed on my Win10Pro64bit pc using WSL - is there maybe a way to make that work kinda like they did with usbra1n/checkra1n?? I'm physically disabled so i have no money (iphone 5 was an xmas gift to me years ago when it came out & 5s was given after apple dropped support) so i definitely cant afford any monthly service or a big 1 time fee otherwise i wouldnt be hunting down every link i can find trying to re-jailbreak my iphone 5 32 bit ios 10.3.4 with the h3lix-rc6 jailbreak which without a ton of tweaks from cydia wont barely even run its so slow. PLEASE HELP - posted on reddit about it but either no1 knows or no1 cares - betting the 2nd since its a 32 bit device :^(

**Comment by noah978** [comment]
AltStore is only compatible with devices iOS 12.2 and up. Unfortunately, this is not going to change so we cannot help you here.

**Comment by AnakinSkywalkerVader** [comment]
Sorry but you are incorrect but only partially - Alt Store will not run/function on less than ios 12.2 so that part you are correct however it does still work to install custom ipa's on older ios devices like iOS 10.3.4 on my original iPhone 5 32 bit. I know it works bcuz I've jailbroke that same phone many many times by installing h3lixRc6 using Altstore custom ipa install option then just repeatedly resign it every 7 days like always or just use ReProvision to resign without a computer even 😀😀 So yes it can be done - I 4got I posted this months ago 😀
