### ISSUE TITLE
Alt Server Mac Os Crash After Sign In

### ISSUE THREAD

**Issue by RUGMJ** [rileytestut/AltStore#1291]
After updating to the most recent version (1.7) after signing in alt server crashes without an error. Is it possible to downgrade my version?

**Comment by shanegillio** [comment]
So the crash is happening when you try to install once you enter your AppleID info?

**Comment by andresmtzc** [comment]
iPhone 14 pro max iOS 16.2
Macbook Air M1 BigSur
Altserver 1.7

Correct, Altstore is crashing when I try to install after entering AppleID info

**Comment by andresmtzc** [comment]
Found the solution!
Had to go to 
https://developer.apple.com/account
Login with my ID, and select "don't upgrade" to 2-factor authentication
Now up and running with Altstore again
