### ISSUE TITLE
altstore says verification error while installation

### ISSUE THREAD

**Issue by netzherpes** [rileytestut/AltStore#13]
Just heard about your cool project. 
I installed iTunes from apple
![fail_AltStore](https://user-images.githubusercontent.com/55878774/65764007-e6471080-e124-11e9-8f74-1f9a5bdd615b.png)
, 
installed altstore, 
created a specific password, 
altstore started to install, 
but failed with the following message:
failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd/staging/temp.blabla/extracted/AltStore.app

My mistake or something deeper. I googled, but did not find a solution. 
Iphone 6S, iOS13.1

thanks

**Comment by droidbizz** [comment]
I join to the same issue can't install

**Comment by loofkid** [comment]
Same issue but on iOS 13.2 Developer Beta 2.

**Comment by sonothingatall** [comment]
Same issue. iOS 13.2 Public beta 2
It popped up a windowed error with the same message but with a error code:
**0xe8008001 (An unknown error has occurred.)**
![image](https://user-images.githubusercontent.com/32032824/66696621-2bac3600-ed00-11e9-9cb1-0370b1f9aa65.png)

**Comment by HexaC** [comment]
Same problem on iOS 13.2 iPhone X

**Comment by noah978** [comment]
If you issue wasn't fixed by updating to the latest iOS, try making sure that both iOS and your PC have their time and date properly set and synced. I'll consider this one closed then.
