### ISSUE TITLE
[Critical Bug] Hibernation Memory Leaks cause high cpu usage

### ISSUE THREAD

**Issue by TempAccountNull** [rileytestut/AltStore#130]
A Hibernation memory leak, causes alt server to use excessive amounts of resources after a device is unplugged from the host computer. I have tried to contact you multiple times with no avail.

Some information:
Executable in question: AltServer.exe
AltServer version
![AltServerV](https://user-images.githubusercontent.com/11286901/76444897-a1412e80-6392-11ea-8c41-7c54b3faee3f.PNG)

### The Steps
0. Open Power and sleep settings and set the following Window settings
0.1 Click screen dropdown and set 'When plugged in, turn off after' to 15 min

### To replicate the bug

*** First way ***
1. Open AltServer on Host PC
2. Plug a iPhone in and send an ipa To device from Host PC (wireless sync)
3. Wait to windows hibernates to lock-screen
4. Let monitor turn off
5. Log back into task manager, continuously having 60+ CPU Usage

*** Second way ***
1. Make sure AltStore has been sent to the iPhone
2. Connect iPhone to Windows PC (with cable)
3. In AltStore APP -> Refresh Any application even itself
4. Unplug the phone
5. wait

Images of this happening [used the following programs]
- Process explorer
- Process hacker
- Procmon
- Resource monitor

![EScEdlgWAAARxJl](https://user-images.githubusercontent.com/11286901/76444519-17916100-6392-11ea-89ee-49f3566fe2d9.png)
![EScEdlRWoAIcD4a](https://user-images.githubusercontent.com/11286901/76444521-1829f780-6392-11ea-9cef-326e98d96cf7.png)
![EScEdleWAAI89XP](https://user-images.githubusercontent.com/11286901/76444522-18c28e00-6392-11ea-9318-3fc3da7ceb6d.png)
![EScEdllWsAAHBOe](https://user-images.githubusercontent.com/11286901/76444523-18c28e00-6392-11ea-9c9b-312a1e0875b8.png)

**Comment by noah978** [comment]
Thanks for the excessive debugging! This issue should be fixed in that latest versions of AltServer. If you test it once more and find that there's somehow still an issue, please leave a comment below.

I'll consider this issue closed then.

**Comment by MalexTP** [comment]
still happens

**Comment by skim2257** [comment]
bump @noah978 
Still an issue.

**Comment by TempAccountNull** [comment]
I can definitely get it some times.
