### ISSUE TITLE
Failed to verify code signature

### ISSUE THREAD

**Issue by Lmodu** [rileytestut/AltStore#137]
![51795ADA-090A-47EC-89B8-B90A063E3C69](https://user-images.githubusercontent.com/62182723/76706888-30c84380-66eb-11ea-85d5-04a8c7dc75ae.jpeg)
When i try to install an ipa via altserver , or when i try to install the alt server i get this proplem . 0xe8008018 (the identity used to sign the executable is no longer valid)  Any solution ?

**Comment by noah978** [comment]
@Lmodu Please make sure that your iOS Time + Date and Windows Time + Date are correct and in sync. This should fix your issue.

**Comment by noah978** [comment]
Moving to #94.
