### ISSUE TITLE
Swift Compiler Error | Cannot convert value of type 'ALTEntitlement' to expected argument type 'String'

### ISSUE THREAD

**Issue by burritosoftware** [rileytestut/AltStore#14]
Hey. Trying to build AltStore, when I get the error mentioned in the title, from ResignAppOperation.swift

Here is the line of code:

```swift
let requiredFeatures = app.entitlements.compactMap { (entitlement, value) -> (ALTFeature, Any)? in
            guard let feature = ALTFeature(entitlement) else { return nil }	// this is the error
            return (feature, value)
        }
```

**Comment by burritosoftware** [comment]
I am also on Xcode 11.0, so if I need to be on 11.1 GM seed lmk.

**Comment by eni9889** [comment]
This fixed it for me but I'm not great at Swift @burritosoftware 

```
let requiredFeatures = app.entitlements.compactMap { (entitlement, value) -> (ALTFeature, Any)? in
            let feature = ALTFeature(entitlement.rawValue)
            return (feature, value)
        }
```

**Comment by burritosoftware** [comment]
Will try when I get back home and fix some VMware issues I'm having

**Comment by eni9889** [comment]
@burritosoftware  it turns out you need to use Xcode 10.3 to build the project. Xcode 11 has issues.

**Comment by burritosoftware** [comment]
Alright, will try

**Comment by dlevi309** [comment]
@eni9889 oh thanks for the tip, I hadn't even thought of downloading xcode 10.3 and have been having issues building all week, appreciate that

**Comment by dlevi309** [comment]
@eni9889 you were right, she built perfectly but I wasn't able to get around the installation on my iPhone 11 Pro running 13.1.1 because of supported firmware versions 10.3 allows, any fixes you have in mind for this? very much appreciated

**Comment by dlevi309** [comment]
@eni9889 @burritosoftware got it -- if anyone see's this with that earlier issue download Xcode 10.3 as Enea specified, then download these files (or whatever iOS support files are needed) from this github repository ( https://github.com/Yatko/iOS-device-support-files )
and paste them into your local directory of the 10.3 Xcode app:

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport

should run then

**Comment by burritosoftware** [comment]
Newest AltStore supports Xcode 11 compiling.
