### ISSUE TITLE
Not compatible with iOS 8.4.1?

### ISSUE THREAD

**Issue by alend88** [rileytestut/AltStore#140]
I'm using windows to try and install Altstore on an iPad 2 and iPhone 4s - both on 8.4.1 . Installation fails on both with same error message - "An unknown error occurred" or 1.3b2, or "Could not connect to AltServer" on the download link direct from the Alstore homepage.

Have confirmed device are authorized in iTunes, have iCloud installed, etc...
Has anyone successfully installed AltStore on  iOS 8.4.1?

**Comment by supremethememe** [comment]
I don’t think so, I would greatly suggest thinking about upgrading to an iDevice that can support iOS 12 or greater.

**Comment by noah978** [comment]
AltStore is iOS 12.2+ only. Closing this issue.

**Comment by PF94** [comment]
great now i wasted 6+ hours of my life trying to jailbreak my goddamn ipad mini 1st gen on 8.4.1, it's now a paperweight.
