### ISSUE TITLE
apps wont refresh

### ISSUE THREAD

**Issue by mongomang** [rileytestut/AltStore#141]
Hey man!

I've been using delta for a week now on my iphone and I'm in love with it. I was playing pokemon leaf green and made it pretty far. It was working earlier today, but after dinner when I went to open it, it wouldnt open and neither would alt store. I did some searching around on reddit and found a way to get altstore back, but now my apps wont refresh. When I go to refresh them it just spins forever. I have itunes, icloud and alt store running on my PC, but no luck. I didnt install the newest IOS either. I'm at a loss and I'm hoping you can help me out. 

Cheers!
Connor

**Comment by dontbanmeplz** [comment]
#123

**Comment by noah978** [comment]
This is a fairly straightforward issue, you need to make sure that your Windows firewall is either off or you have created an exception for AltServer in there. Restarting your computer and iPhone can also help. I'll consider this issue closed.
