### ISSUE TITLE
No download after purchase

### ISSUE THREAD

**Issue by tomasandrle** [rileytestut/AltStore#1425]
I didn't get a working download link after purchasing the subscription to the iOS "PAL" app in the EU. All I got was billed. Not good.

Where do I get my download link?

**Comment by Grac333k** [comment]
I have same issue

**Comment by erkage** [comment]
Hey there,

I got redirected to the download page but when I clicked on it got an error that I can't install the app. I'm on iOS 17.4.1, situated in the EU and my region settings is also in the EU.
Also when I navigate from the download page to elsewhere and then go back to try downloading it again the Download button does nothing.

Also when I logged into Stripe and the Altstore logo's link is the following:
`https://api.altstore.io/install?session={CHECKOUT_SESSION_ID}&email={CUSTOMER_EMAIL}`
I assume this could be used to reach the download page but the values are missing.

**Comment by jasomtubratu** [comment]
Same issue here!

**Comment by Grac333k** [comment]
Found solution. Go to page where you bought altstore and enter your mail under apple pay button. then click download, go to the ios settings and allow on the top. i had to switch to my eu account on app store also

**Comment by jasomtubratu** [comment]
I had to spam that Download button to start working.

**Comment by erkage** [comment]
Perfect solution @Grac333k, thanks!

**Comment by tentomasne** [comment]
Worked, thank you @Grac333k

**Comment by tomasandrle** [comment]
@Grac333k I entered the email address in the purchase form, without filling in any payment details. It said I had an account there and redirected me to another page with a "Download" button and "Manage account" link.

The download button doesn't work. It says "Safari cannot open the page because the address is invalid".

The link worked however, opened a Stripe page where I was able to cancel the plan. Thanks!

**Comment by MadMacMad** [comment]
same here... NOT WORKING!
did everything... allow in settings etc...  reboot ...
payed and nothing....
SCAM
don't pay ... you never will get it back... do not support this bullshit

Safari kann die Seite nicht öffnen, da die Adresse ungültig ist. !!!
Safari cannot open the page because the address is invalid !!!

iOS 17.4.1

**Comment by tentomasne** [comment]
For me it worked, it was complicated but worked

**Comment by tomasandrle** [comment]
After updating and restarting my phone, I was able to install Altstore.

 - re-download worked after entering email into purchase form to access account (thanks again @Grac333k)
 - latest iOS was required
 - had to allow 3rd party store in Settings
 - got no reply from any of the emails found on altstore website (some even bounced)
