### ISSUE TITLE
Can't reinstall Altserver PAL

### ISSUE THREAD

**Issue by GreyBoyTinker** [rileytestut/AltStore#1436]
Hey guys

I gladly paid the yearly subscription to download the PAL version of Altstore but had to uninstall it since I wasn't able to sideload my apps on it. Now I'm trying to re-install it hoping this fixes the problem but the link I used to download the app more. Do I have to pay each time I want to download? 

Thanks in advance for the help!

**Comment by Ein-Tim** [comment]
@GreyBoyTinker You can simply re-enter your mail address when the stripe page opens (after clicking the download button on the website) & will be prompted to a new download link.

**Comment by GreyBoyTinker** [comment]
> @GreyBoyTinker You can simply re-enter your mail address when the stripe page opens (after clicking the download button on the website) & will be prompted to a new download link.

Hey! Thanks for the answer! Looks like it's working again! I'll tkae the chance to ask if it's possible to sideload from the new PAL App. I haven't been able to...

**Comment by Ein-Tim** [comment]
@GreyBoyTinker No, that's not possible. For sideloading you have to use the non PAL version of AltStore. 
Sadly the texts in the PAL app are not really clear about that.
