### ISSUE TITLE
Not compatible with Global HTTP Proxy

### ISSUE THREAD

**Issue by GreyAsteroid** [rileytestut/AltStore#144]
If an iOS device is supervised and set to use a Global HTTP Proxy via profile then the device will not be able to find the AltServer. 

I personally use a proxy like this to block ads for all apps installed on my phone. This likely also keeps some work/school devices from being compatible with AltStore.

**Comment by Titanius** [comment]
How can I configure the proxy for the WinHTTP Services?
There is a simple way to do that, by issuing the following command on a command prompt with elevated privileges:

Windows + R
cmd

netsh winhttp set proxy : "<Exclusion list, separated by ";">"

As an example, this command will configure the address proxy.contoso.com in port 8080, with the exclusion of "localhost" and "contoso.com" domain:

netsh winhttp set proxy proxy.contoso.com:8080 "localhost;*.contoso.com"

You can also import the settings from the Internet Settings Control Panel (Browser), but bear in mind the WinHTTP Services do not support the use of Scripts (like PAC or DAT files). For such behavior you can use following command:

netsh winhttp import proxy source=ie

The last part would be to check and ensure your proxy settings got properly applied to the WinHTTP Services. You can achieve that by issuing the following command:

netsh winhttp show proxy

If you have everything properly set up and want to get back to direct connection, you'll need to issue the following command:

netsh winhttp reset proxy
