### ISSUE TITLE
I don’t want to install altstore widget since it consumes another app id for me. Is there any way I can just install altstore and remove the widget ?

### ISSUE THREAD

**Issue by raed203** [rileytestut/AltStore#1468]
I don’t want to install altstore widget since it consumes another app id for me. Is there any way I can just install altstore and remove the widget ? 

_Originally posted by @ashutoshbitcot in https://github.com/altstoreio/AltStore/issues/1154_

**Comment by Workable1766** [comment]
Did tou find a solution?
