### ISSUE TITLE
Ipad Pro M4 cannot run JIT

### ISSUE THREAD

**Issue by Awsomegameplay123** [rileytestut/AltStore#1469]
I'm assuming their is some type of architecture update that prevents jit from being ran on ipad pro M4 at the moment? Has anyone been able to run JIT yet?

**Comment by kaygdotorg** [comment]
Yes, I just did with SideJITServer for utm.app.

Okay, nevermind. Even though I had JIT enabled for utm, I am not able to run VMs.

**Comment by Awsomegameplay123** [comment]
FIXED - I don't know how I fixed it but I did some research, ran some commands and completely fixed the issue

**Comment by dbacks2196** [comment]
@Awsomegameplay123 no way! How did you fix it?? I have the same problem!

**Comment by Awsomegameplay123** [comment]
> @Awsomegameplay123 no way! How did you fix it?? I have the same problem!

Honestly, I'm not sure I just searched up issues and ran a bunch of random stuff and it just fixed itself.

**Comment by dbacks2196** [comment]
@Awsomegameplay123 hahah awesome happy it worked! Hopefully I'll be able to figure it out eventually 😬
