### ISSUE TITLE
Altserver crashes upon attempting to uninstall app

### ISSUE THREAD

**Issue by rmart1n-dev** [rileytestut/AltStore#1472]
Upon trying to uninstall a currently active app, it gets to about 75-80% (just after going to the app and backing up data,) then states that it lost connection to AltServer. This has happened across multiple server devices, AltServer versions, and iOS updates.

Tested with:
**IPHONE:** iPhone 11 running iOS 17.5.1
**COMPUTER:** 2019 Macbook Air (Intel) running MacOS Sonoma 14.5. Also tested on 2013 Macbook Pro running Ventura (using OpenCore Legacy Patcher)
**ALTSERVER:** Version 1.7.1 (also tested with versions 1.7, 1.6,2, 1.5b5)
**ALTSTORE:** Version 1.7

Below is a video of what happens with AltServer and AltStore.

https://github.com/altstoreio/AltStore/assets/130403950/ea1b7d33-c5c4-4453-9c0a-aa87550f7d66

**Comment by rkennedy2016** [comment]
This is what happened with me

**Comment by TheWhiteDogYT** [comment]
this is happening to me too but im on the latest version of ios, altserver, and altstore
