### ISSUE TITLE
Add GitHub link to https://altstore.io

### ISSUE THREAD

**Issue by sayo-melu** [rileytestut/AltStore#15]
People cannot find this repository on https://altstore.io, they:

- may not think this is an open source project.
- cannot star this repository.
- contribute to this repository.
- contribute feedback.
- ...

**Comment by Mornwind** [comment]
@sayo-melu You may find it in the up-right corner.
![IMG_6552](https://user-images.githubusercontent.com/38060040/65945992-b8850300-e467-11e9-8c41-4363ef0e6a5a.jpeg)
