### ISSUE TITLE
SSL Error issues(bug?)

### ISSUE THREAD

**Issue by Aragamiz** [rileytestut/AltStore#151]
---------------------------
Installation Failed
---------------------------
SSL Error: WINHTTP_CALLBACK_STATUS_FLAG_CERT_REV_FAILED failed to check revocation status.
---------------------------
 it's a bug?

**Comment by ustcpetergu** [comment]
I met the same problem and solved it by using a proxy/VPN. Seems something is blocked by the Firewall.

**Comment by Aragamiz** [comment]
> I met the same problem and solved it by using a proxy/VPN. Seems something is blocked by the Firewall.

can you tell me altserver's work domain?

**Comment by ustcpetergu** [comment]
Sorry, I don't know that. I'm using a global proxy. By the way, I'm running altserver in Win7 Virtualbox.

**Comment by Chuyun-Shen** [comment]
I'm running it in win10, and I met the same problem and I tried to use a global proxy but still not work.

**Comment by Chuyun-Shen** [comment]
I tried reboot my PC, set itunes Sync with your phone via wifi, it works

**Comment by Soontao** [comment]
Thanks for @ustcpetergu suggestion , when I set a global proxy in windows PC, it can be installed successful on my iOS device .

**Comment by bernalazo** [comment]
@Soontao How did you do that? I’ve been trying to solve this problem for an hour but I can’t.

**Comment by noah978** [comment]
As others suggested, you should be able to solve this by creating an exception for AltServer in Windows Firewall. Closing this issue now.

**Comment by vOuii** [comment]
I am getting the internal error one

**Comment by vOuii** [comment]
Solution FOUND! If you have Malwarebytes, or any antivirus software. add f000.backblazeb2.com to the allow/exclusion list! thank me later!

**Comment by AliceDutchie** [comment]
it didnt seem to work for me im still getting the same error

**Comment by iThesmoke** [comment]
> Solution FOUND! If you have Malwarebytes, or any antivirus software. add f000.backblazeb2.com to the allow/exclusion list! thank me later!

i use windows 10 and i don't use any antivirus software. help me out, where and how to add f000.backblazeb2.com to the allow/exclusion list?
