### ISSUE TITLE
Remove dependency on Mail plugin

### ISSUE THREAD

**Issue by dancojocaru2000** [rileytestut/AltStore#152]
The point of the Mail plugin isn’t clearly explain. I dislike the Apple Mail app and prefer not to use it, and I would gladly manually input required stuff from emails using a third party email app I use in order to avoid a Mail plugin

**Comment by kyelewis** [comment]
I agree in that the project would benefit at least from an explanation of the Mail Plugin on the main page.

I had to read through the plugin code to get an understanding of why the plugin exists, it does feel there could be a better / more transparent way to attack the problem.

If the easiest way to do this is for now the plugin, please consider explaining what it does in the same place where you ask users to use it.

**Comment by laosb** [comment]
It's just used to make use of Apple's own implementation of some required authentication process for properly signing apps with your Apple ID. It's hard to reverse engineer the implementation of the process so AltStore just go with Apple's own code.

**Comment by privatenumber** [comment]
I'd prefer a manual alternative as well.

I'm using my Mac to side-load to a friends iPad (her MBP is outdated), and signing into her email on my laptop wasn't an option.

It's generally very convenient to automate, but in this case, having a manual alternative would've been convenient too.

**Comment by noah978** [comment]
The Mail app plugin is used to produce something called "Anisette Data" which is required by Apple to sign applications. The Mail app conveniently contains the exact data needed which is why the plugin exists.

Technically speaking, the use of the mail app is an easy workaround to obtain the data. The end goal is to be able to fully reverse engineer the Xcode signing process so AltServer can create it's own Anisette data. However, due to the difficulty of the reverse engineering process, this likely won't happen for quite some time unless someone else is able to figure it all out.

**Comment by privatenumber** [comment]
Thanks for the explanation @noah978 . I think this would be really relevant in a FAQ as it has some pretty big privacy implications.

As a follow up, does this mean that I don't need to be signed in on the Mail app to use AltServer?

**Comment by noah978** [comment]
> As a follow up, does this mean that I don't need to be signed in on the Mail app to use AltServer?

@privatenumber I'm actually not sure about that one, feel free to test it. All I know is that the Mail app *does* have to running.

**Comment by strafe** [comment]
@noah978 out of curiosity, how does the Windows version of AltStore get around not having Mail.app available? I too find it annoying keeping Mail open in the background constantly just so AltStore can refresh.

**Comment by noah978** [comment]
@strafe Since AltServer now needed Anisette Data to use the new signing methods, users on windows were required to download and install iCloud. The windows version of AltServer uses iCloud to gather the Anisette Data.
