### ISSUE TITLE
Can't install ipa

### ISSUE THREAD

**Issue by Kian738** [rileytestut/AltStore#154]
Everytime I try to install a ipa file it loads some time but nothing happens

**Comment by ssrlive** [comment]
My issue is, I can install ipa file, but can NOT run it. The app keeps crash. like [this demo](https://drive.google.com/file/d/1YHn78afVC8eOOLymVN_e7JJIv3YeUzYt/view?usp=sharing)

**Comment by ssrlive** [comment]
My issue is, I can install ipa file, but can NOT run it. The app keeps crash. like [this demo](https://drive.google.com/open?id=1EvyWzBU_PQjssHzdI-ZfjG1yFqpMwXby)

**Comment by Charley-Tang** [comment]
Yes，·The name for this app is invalid· always show after I choose an ipa ... never success

**Comment by noah978** [comment]
@Charley-Tang This issue is separate from the current topic, but it is also fixed in the latest AltServer and AltStore.

**Comment by noah978** [comment]
@Kian738 I need more information:
* What iOS version?
* Mac or Windows?
* What specific IPA?

**Comment by Charley-Tang** [comment]
> @Charley-Tang This issue is separate from the current topic, but it is also fixed in the latest AltServer and AltStore.

@noah978 No，it‘s related，while I choose a ipa to install , if the app name (display on desk) contain Chinese words, altstore will toast "The name for this app is invalid"
Then I  use "iOS App Signer" to change the app display name, app id and app version.
and install the new repackaged app, it works. Now the new altstore was released, but my 10 IDs were run out, I will check the new altstore again after 2 days my IDs are expired.

> altstore v1.3.3 on iPhone 8 with iOS 12.4.1
> macOS Mojave 10.14.6

**Comment by geron2020** [comment]
Brother, I found the solution
用Sideloadly打开APP，打开“Advanced Options”
1. Change app name 修改名字
2. Signing mode 选择 Export
3. 点击start导出修改名字后的APP
再用altstore安装试试

Open the app with Sideloadly and open "Advanced Options".
1. Check "Change app name", fill in the modified name
2. ”Signing mode“ select ”Export“
3. Click ”start“ to export the app after changing the name

Try to install it with altstore again
