### ISSUE TITLE
Invalid anisette data

### ISSUE THREAD

**Issue by Ayman19971997** [rileytestut/AltStore#156]
I have my icloud and itunes downloaded from apple directly, my altstore running on its latest version. However, today i wanted to refresh my apps, connected the phone to the same internet as laptop, connected by cable, Wifi sync is on and when I click refresh it says cannot refresh 2 apps, invalid anisette data. Please help ASAP

**Comment by thvozdovic** [comment]
Same here

**Comment by noah978** [comment]
Please try using the [latest version of AltServer](https://altstore.io/altserver/beta) and if the error still persists, try seeing if a different Apple ID produces the same results.

**Comment by noah978** [comment]
It seems others still have this issue so @thvozdovic  or @Ayman19971997, can someone please provide the following information:
* Mac or Windows
* iOS version

**Comment by Kici33** [comment]
Windows
iOS 13.5

Same issue

**Comment by 1287300464** [comment]
以兼容模式（windows7）运行icloud

**Comment by 1287300464** [comment]
我是用了兼容模式以后成功的，希望对你同样有用。

**Comment by lucidyan** [comment]
For anyone who get `invalid anisette data close itunes and icloud` error on Windows, try to reinstall both iCloud and iTunes and after that restart the system.

**Comment by 0x7ee** [comment]
For windows users, if non of the above solved your problem try this:

- open icloud, then close it (leave it running in the background)
- if you just installed a fresh copy of itunes
  - open itunes, accept the user agreement
  - sign in to itunes with your apple id
 - close itunes
try installing again it should work now.

**Comment by raulsiles** [comment]
In Windows, the last entry in issue #227 helps to solve this error:
1) Delete all files in this folder: C:\ProgramData\Apple Computer\iTunes\adi.
2) Run iTunes, to regenerate some of these files, and close iTunes.
3) iCloud can be running in the background

**Comment by SAINtPL0** [comment]
I had just updated my itunes and i followed someone elses suggestion of opening it and signing into the apple id and that worked. Also restarted my phone.

**Comment by secret223** [comment]
> I have my icloud and itunes downloaded from apple directly, my altstore running on its latest version. However, today i wanted to refresh my apps, connected the phone to the same internet as laptop, connected by cable, Wifi sync is on and when I click refresh it says cannot refresh 2 apps, invalid anisette data. Please help ASAP

**Comment by SAINtPL0** [comment]
Make sure to check that you’re signed in on iTunes on the computer and make sure to click your network connection on the computer and sign in through WiFi as well as the Ethernet connection. It also had me input a 2FA on my PC and my phone

**Comment by vritme** [comment]
ios 13.3.1 se gen1 win7, same problem, can't install

**Comment by the-wes** [comment]
ios 12.5.6, iphone 6, win7. "The operation couldn’t be completed. (AKAnisetteError error -8004.)"

tried:

deleting C:\ProgramData\Apple Computer\iTunes\adi
logging in to itunes
ending and re-starting icloud
logging out of icloud and back in
restarting computer and phone

no change.

**Comment by ermolay1880** [comment]
I was helped by "deauthorize/authorize this computer". Altstore 1.5.1.0 didn't want to re-sign applications. iOS 15.1 Win8.1

**Comment by hzalupa** [comment]
just log in to iTunes
![image](https://user-images.githubusercontent.com/115055714/205068128-7e132674-d6ac-421a-b6c3-15daae59a518.png)

**Comment by bahillybeans** [comment]
I can't authorize this computer because it says "an unknown error occurred"
