### ISSUE TITLE
Refresh apps from PC

### ISSUE THREAD

**Issue by jamescastells** [rileytestut/AltStore#162]
A good thing would be to refresh the apps from the PC. That is, a menu from AltServer to refresh manually the apps. I know the AltStore is supposed to do it automatically, but a manual refresh from AltServer would be nice.

**Comment by noah978** [comment]
You can do a manual refresh from within AltStore? AltServer won't be able to find AltStore at any given moment while its running in the background, you would have to open AltStore. So essentially, there would be no point to this.
