### ISSUE TITLE
Altstore using wrong apple id and name

### ISSUE THREAD

**Issue by CosmicGunners** [rileytestut/AltStore#165]
I installed the altstore no problem but whenever i put in my apple account it shows me an older email and name my account had years ago instead of my current one,

The error code thats displayed is:-20101
My device is an Iphone xs, IOS:13.4.5 (Beta 1)

**Comment by crazycarl008** [comment]
exact same issue - it's showing an older email that has since been removed from my apple account. 

worked to set up 2 apps yesterday but now shows the same error as you if i try to add another app or refresh an app.

ipad pro 2020   13.4.1

**Comment by hiswillbedun** [comment]
I am having the same issue.  Has anyone found a fix?

**Comment by uceieluez** [comment]
I'm having the same issue as well, unfortunately without any progress made. However, I did make an observation that may possibly lead to something but this is merely speculation at this point.

I only today installed and signed into AltStore for the first time ever. After I realized what was happening (the aforementioned issue), I realized that the old, incorrect email was the same email that was listed under my contact card in my phone as my "home" email address. I still use both the older and newer email addresses regularly, but I switched my Apple ID to the newer one years ago.

Because of this, the "Predictive" keyboard feature suggested my home email address (the older email account) when entering my login information in the app. I've since then changed my contact card information and reinstalled the app but to no avail.

Again, this is only speculation of what may be going on and I doubt it'll lead to anywhere useful, but hopefully this can help influence someone who is better at computers than I am to look into this problem more.

**Comment by rexbarrett** [comment]
Exact same thing is happening to me. Hoping a fix can come along. Can't refresh without a fix.

**Comment by crazycarl008** [comment]
I don't recall if I had to do any other steps, but this was resolved for me after uninstalling altstore and the sideloaded apps, and starting over. haven't had an issue with it again for about a month. good luck to you guys.

**Comment by uceieluez** [comment]
I found a quick and dirty fix to our problem.

While in the Altstore app, first log out of your account under the Settings tab, then go to add or resign an app under the My Apps tab. It'll then ask you for your login credentials. Logging in to your account this way instead of logging in under the settings tab should work once. This process has to be done once per app you sign using the Altstore app.

I hope this helps some of you!

**Comment by hiswillbedun** [comment]
Just tried your dirty trick and it worked!!   Thanks

**Comment by rexbarrett** [comment]
This worked for me too! Thanks so much.

**Comment by Reiza1993** [comment]
Same problem, so annoying to be honest. 
This bug doesn’t make any sense.

**Comment by cpiekacz** [comment]
Plus one. Please fix it.

**Comment by sethpaschal** [comment]
Plus one please fix this. Same problem with altstore alpha and altdameon. 
Im really surprised this has been going on so long.

**Comment by lSANCHOl** [comment]
I'm still having this issue too.

**Comment by dereklanz517** [comment]
Still happening in January 2021

**Comment by Ethryan** [comment]
This is still a problem

**Comment by pmgart** [comment]
its still a problem, can understand why its not showing the email am trying to use when signing in

**Comment by Dr-DaNk** [comment]
still an issue.

**Comment by 20kluu** [comment]
> I found a quick and dirty fix to our problem.
> 
> While in the Altstore app, first log out of your account under the Settings tab, then go to add or resign an app under the My Apps tab. It'll then ask you for your login credentials. Logging in to your account this way instead of logging in under the settings tab should work once. This process has to be done once per app you sign using the Altstore app.
> 
> I hope this helps some of you!

This works, but you just have to sign out every time you install an app. Thanks so much for posting this solution!

**Comment by lSANCHOl** [comment]
I've found and even better solution. Download ReProvision reborn

**Comment by timmay2019** [comment]
Somehow I managed to get the email address to update in the AltStore app. The steps I have done: 
1. Delete the app on the phone under Settings > General > iPhone Storage.  Reinstalled AltStore but not sign in.
2. Logged in to https://developer.apple.com/account and log in. Agree to terms and get to the dashboard. (do nothing else)
3. Logged in to https://appleid.apple.com/ and just checked if it has the correct email address (which it did)
4. Signed in to your account on AltStore and see if it updated.

Not sure if doing step 2 done the trick or multiple sign in/outs on the AltStore done it but I got it working by doing the above. Maybe it was pure luck idk?

**Comment by onthecliff** [comment]
> Somehow I managed to get the email address to update in the AltStore app. The steps I have done:
> 
>     1. Delete the app on the phone under Settings > General > iPhone Storage.  Reinstalled AltStore but not sign in.
> 
>     2. Logged in to https://developer.apple.com/account and log in. Agree to terms and get to the dashboard. (do nothing else)
> 
>     3. Logged in to https://appleid.apple.com/ and just checked if it has the correct email address (which it did)
> 
>     4. Signed in to your account on AltStore and see if it updated.
> 
> 
> Not sure if doing step 2 done the trick or multiple sign in/outs on the AltStore done it but I got it working by doing the above. Maybe it was pure luck idk?

Wow. This just worked perfectly for me as well! I'm thinking it must be something to do with joining Apple Developer and refreshing some data? Thanks.

**Comment by thiag0mei** [comment]
@timmay2019's suggestion worked for me too! I guess this is not a bug then!

**Comment by earthplusthree** [comment]
@timmay2019 Same here, the number one thing that solved this for me was logging into https://developer.apple.com/account and accepting the new terms of service. Signed out of AltStore without uninstalling and signed back in and it's fixed! This should be the accepted answer for now.

**Comment by Ultcrt** [comment]
> Somehow I managed to get the email address to update in the AltStore app. The steps I have done:
> 
> 1. Delete the app on the phone under Settings > General > iPhone Storage.  Reinstalled AltStore but not sign in.
> 2. Logged in to https://developer.apple.com/account and log in. Agree to terms and get to the dashboard. (do nothing else)
> 3. Logged in to https://appleid.apple.com/ and just checked if it has the correct email address (which it did)
> 4. Signed in to your account on AltStore and see if it updated.
> 
> Not sure if doing step 2 done the trick or multiple sign in/outs on the AltStore done it but I got it working by doing the above. Maybe it was pure luck idk?

Thank you! It worked for me.

**Comment by snowsign** [comment]
What worked for me was going to [developer.apple.com/enroll](https://developer.apple.com/enroll/), starting the application for a paid developer account, then canceling the application before the payment step. That updated the developer name displayed in AltStore after signing out and back in.

To update the iOS app library category name (which apparently displays the developer name that was used to sign the app) I had to go to `~/Library/Application Support/com.rileytestut.AltServer/Certificates` (should be somewhere in the AppData folder on Windows) and delete the .p12 certificate then reinstall AltStore. I reinstalled both AltStore and AltServer several times during the process as well as disabling and re-enabling developer mode, but I think it was the certificate that did the trick.

**Comment by amemoia** [comment]
didn't work for me, could apple have changed how the name is updated? on the main apple developer page it shows my new name, but the moment i try to enroll it reverts to my old one so it doesn't get updated

**Comment by RonnieG19** [comment]
> What worked for me was going to [developer.apple.com/enroll](https://developer.apple.com/enroll/), starting the application for a paid developer account, then canceling the application before the payment step. That updated the developer name displayed in AltStore after signing out and back in.
> 

Thanks @snowsign, this just worked for me today!
