### ISSUE TITLE
What is backblazeb2.com domain during installation?

### ISSUE THREAD

**Issue by miriaford** [rileytestut/AltStore#167]
During installation, my firewall intercepts requests to a very shady-looking domain called `backblazeb2.com`, with subdomain `f000.backblazeb2.com`.  If I block the connection, I won't be able to send my Apple credentials or install the Mail plugin. I can't find this URL anywhere in the source code. 

What is this sketchy domain? Why are my credentials sent there?

**Comment by Terrain2** [comment]
It’s the domain where the default altstore repository (https://apps.altstore.io) hosts all it’s files

It needs to download altstore from this url: https://f000.backblazeb2.com/file/altstore/altstore.ipa

**Comment by noah978** [comment]
As the commentor above mentioned, Backblaze is the low-cost hosting service where the IPAs and AltServer files are stored. Your credentials are never sent there, it only uses Backblaze to download the AltStore IPA.
