### ISSUE TITLE
Failed to verify code signature (windows 10, latest version, iOS 13.4.1 iPhone 7 Plus)

### ISSUE THREAD

**Issue by marleyqp** [rileytestut/AltStore#168]
This has never happened to me before. I tried going into ReProvision and revoking certificates but that didnt work either.

**Comment by noah978** [comment]
Please try using the [latest version of AltServer](https://altstore.io/altserver/beta)

**Comment by noah978** [comment]
Duplicate of #94. Closing this.

**Comment by imnisp** [comment]
the problem (for some of us on windows 10) is that using the newest version of altstore generates:
"the procedure entry point IsWow64Process2 could not be located.."
