### ISSUE TITLE
Can't install AltStore from Windows

### ISSUE THREAD

**Issue by Redemption198** [rileytestut/AltStore#17]
I've installed the AltServer on my Windows 10 (1809/17763.737) machine (iTunes is 64 bit and not from the Microsoft Store), when I select the phone, click on install and log-in with my Apple ID, nothing appens on my iPhone 7 (12.1.2). 
If I try again it says that AltStore is already installed on another device but nothing happens. 
I've already tried revoking apps from Cydia Impactor to check if it was a certificate issue but nothing.

**Comment by codexss** [comment]
try this
https://support.apple.com/en-us/HT208079

**Comment by netzherpes** [comment]
Did not work, sorry. Same error.
Will try a different computer tomorrow
But thanks

**Comment by Redemption198** [comment]
Didn’t work :(

**Comment by Redemption198** [comment]
Apparently iOS 12.2 or higher is required, so I'll close the issue
