### ISSUE TITLE
unc0ver 4.3.1: AltStore says "vector<T> too long"

### ISSUE THREAD

**Issue by IngwiePhoenix** [rileytestut/AltStore#173]
Whilst trying to install unc0ver 4.3.1, the following was reported:

![image](https://user-images.githubusercontent.com/2893716/80436519-9f5e0b00-88ff-11ea-818a-c0c9cc38ed51.png)

Also, after this, AltServer seemingly just crashed. What options do I have to peek at logs? I'd like to look at what is actually going on, possibly debugging the issue to find a solution.

**Comment by IngwiePhoenix** [comment]
I found the issue. And it is far away from where I expected it to be... XD

Apparently, Windows 10's realtime detection can mess things up as it does indeed block the expoit from being copied to the device and alike. It blocks temporary files and such.

Disable the Real Time Protection in the security settings and THEN try to install the app.

**Comment by noah978** [comment]
That is exactly the issue and the issue should result in a [better error message.](https://github.com/rileytestut/AltServer-Windows/commit/d9aac3e0ed85b605ac2a7d8becf8f2797d46edcf) Closing this issue.
