### ISSUE TITLE
Getting -22411 error Need help please

### ISSUE THREAD

**Issue by Spidy123222** [rileytestut/AltStore#175]
Hi I’m wondering if there’s a way to fix the error I get when trying to install Altstore to my iPhone 8+ 
I get error “This action can not be completed at this time (-22411)”

I’ve been getting this error for 2.5 months and what I tried to solve the problem.
I tried reinstalling Altstore, iTunes (not Microsoft store) and iCloud (not Microsoft store). I also tried changing password and making new accounts, also tried accepting developer agreement thing when you first login in apples developer page. I tried making app specific password and had no success.

I was told the issue was a Xcode error from apple forcing people to update to a newer Xcode version. 

This is on windows 10 using over WiFi (computer isn’t near Ethernet If it’s relevant) for internet connection. dose this have to do with using a iCloud email as Apple ID?

Edit: my firewall isn’t blocking it

Combined reply I dd not realizing I could edit below.

May 3rd

I did a test with a account with a gmail account and no change on error and I also updated to latest version of windows 10 if that helps.

Edit: I went through full account setup for these accounts and seems to not allow me to use altserver.

It’s been about 3 months by now sense I have been trying to get it working.

May 8th Edit: still no success I have tried using different forks and no differences. I asked helped on the delta server but It seemed they didn’t know how to help so I assumed people would help here.

**Comment by Spidy123222** [comment]
I did a test with a account with a gmail account and no change on error and I also updated to latest version of windows 10 if that helps.

**Comment by noah978** [comment]
@Spidy123222 Try updating to the latest version of [AltServer Beta.](https://altstore.io/altserver/beta/)

**Comment by Spidy123222** [comment]
> @Spidy123222 Try updating to the latest version of [AltServer Beta.](https://altstore.io/altserver/beta/)

It didn’t work got same error. :/

**Comment by noah978** [comment]
@Spidy123222 Can you try deleting the "adi" folder in iTunes' file directory? If it doesn't immediately work after that you should restart your computer and open iTunes, then try again.

**Comment by Spidy123222** [comment]
> @Spidy123222 Can you try deleting the "adi" folder in iTunes' file directory? If it doesn't immediately work after that you should restart your computer and open iTunes, then try again.

I have done these steps and it seems that it dose not work and I get same error as before.

**Comment by ReAnzu** [comment]
I've seen -22411 in another context. Adding AltStore to a phone with a different primary AppleID, resulted in error -22411 when trying to install AltStore.

Is the AppleID that you're using for AltStore the same as the main AppleID on the iPhone8+? If not is it a new AppleID that hasn't been put on any devices? If it's a new AppleID it may need to be enabled on a device before it can be used to authenticate (Due to 2FA). The simplest way I've found to do this, is to go to Settings -> Passwords & Accounts -> Add Account (on the device you're trying to add AltStore to) and add a new iCloud account for the AppleID that you're trying to use for AltStore. You can disable all syncing with that iCloud account without issue. The next time you attempt to install AltStore you should get a 2FA authentication request on the device that you'll need to allow and enter the 2FA code on the computer.

**Comment by Spidy123222** [comment]
> I've seen -22411 in another context. Adding AltStore to a phone with a different primary AppleID, resulted in error -22411 when trying to install AltStore.
> 
> 
> 
> Is the AppleID that you're using for AltStore the same as the main AppleID on the iPhone8+? If not is it a new AppleID that hasn't been put on any devices? If it's a new AppleID it may need to be enabled on a device before it can be used to authenticate (Due to 2FA). The simplest way I've found to do this, is to go to Settings -> Passwords & Accounts -> Add Account (on the device you're trying to add AltStore to) and add a new iCloud account for the AppleID that you're trying to use for AltStore. You can disable all syncing with that iCloud account without issue. The next time you attempt to install AltStore you should get a 2FA authentication request on the device that you'll need to allow and enter the 2FA code on the computer.

It is a Apple ID that’s not the main for the device but it has been logged into on the phone as the main before for trying to make the account on it. I’ll be sure to try that.

**Comment by Spidy123222** [comment]
> I've seen -22411 in another context. Adding AltStore to a phone with a different primary AppleID, resulted in error -22411 when trying to install AltStore.
> 
> 
> 
> Is the AppleID that you're using for AltStore the same as the main AppleID on the iPhone8+? If not is it a new AppleID that hasn't been put on any devices? If it's a new AppleID it may need to be enabled on a device before it can be used to authenticate (Due to 2FA). The simplest way I've found to do this, is to go to Settings -> Passwords & Accounts -> Add Account (on the device you're trying to add AltStore to) and add a new iCloud account for the AppleID that you're trying to use for AltStore. You can disable all syncing with that iCloud account without issue. The next time you attempt to install AltStore you should get a 2FA authentication request on the device that you'll need to allow and enter the 2FA code on the computer.

That fixed the problem. This should be part of the FAQ imo!!

**Comment by davidmcmann** [comment]
> > I've seen -22411 in another context. Adding AltStore to a phone with a different primary AppleID, resulted in error -22411 when trying to install AltStore.
> > Is the AppleID that you're using for AltStore the same as the main AppleID on the iPhone8+? If not is it a new AppleID that hasn't been put on any devices? If it's a new AppleID it may need to be enabled on a device before it can be used to authenticate (Due to 2FA). The simplest way I've found to do this, is to go to Settings -> Passwords & Accounts -> Add Account (on the device you're trying to add AltStore to) and add a new iCloud account for the AppleID that you're trying to use for AltStore. You can disable all syncing with that iCloud account without issue. The next time you attempt to install AltStore you should get a 2FA authentication request on the device that you'll need to allow and enter the 2FA code on the computer.
> 
> @ReAnzu
> That fixed the problem. This should be part of the FAQ imo!!
> 
> @noah978 There’s the fix. Is it possible to add it to a FAQ or some type way for others can read how to fix -22411

This is the fix, Super legit. I tried every other method and only this method works! Amazing and thank you!

**Comment by noah978** [comment]
Thanks everyone for helping the figure out and confirm this other fix. Riley will look into it to see if there is anything he can do with AltServer to automatically fix the issue or prevent it from happening in the first place. At the very least, we might get an improved error message for this case and the solution will likely be added to the FAQ.

**Comment by ih4wk** [comment]
Have you tried using overall vpn?

**Comment by Spidy123222** [comment]
> Have you tried using overall vpn?

The problem was I hat I needed to add the account to the device at always so I had to add it in accounts via iCloud for an alt account. Idk what that vpn is and most vpns won't work with altstore period.

**Comment by MrConfigAfonso** [comment]
I think this is the resolve of my problem.

```
When I was installing altstore on it, it gave me an error on my main pc

It's not giving the error on my other pc, so I installed the AltStore using it.
[Thanks Grammarly for making this smaller :)]
 
And I was trying to use the main pc as a server, and it was giving the error -22411

But then, when i changed to my other pc, it worked well!

Aparently AltStore does not like contacting to their's not born server.
```

**Comment by ItsMeAubey** [comment]
Having this issue on an iphone 6s running ios 15.2. there is no "Passwords & Accounts"" subsection so I cannot add my new apple id to the phone. Please help.

**Comment by Spidy123222** [comment]
> Having this issue on an iphone 6s running ios 15.2. there is no "Passwords & Accounts"" subsection so I cannot add my new apple id to the phone. Please help. 

Instead of there since ios changed location. You go into mail in settings and accounts and that's the same location specified. Seems to work best with iCloud accounts.

**Comment by ItsMeAubey** [comment]
> mail in settings and then in accounts

Worked perfectly. Thanks!

**Comment by Peiprjs** [comment]
> I've seen -22411 in another context. Adding AltStore to a phone with a different primary AppleID, resulted in error -22411 when trying to install AltStore.
> 
> Is the AppleID that you're using for AltStore the same as the main AppleID on the iPhone8+? If not is it a new AppleID that hasn't been put on any devices? If it's a new AppleID it may need to be enabled on a device before it can be used to authenticate (Due to 2FA). The simplest way I've found to do this, is to go to Settings -> Passwords & Accounts -> Add Account (on the device you're trying to add AltStore to) and add a new iCloud account for the AppleID that you're trying to use for AltStore. You can disable all syncing with that iCloud account without issue. The next time you attempt to install AltStore you should get a 2FA authentication request on the device that you'll need to allow and enter the 2FA code on the computer.

Thanks! It works with that.

**Comment by FIocker** [comment]
There's no more "Settings -> Passwords & Accounts" in ios 15 anymore is there?

I only see passwords

**Comment by Spidy123222** [comment]
> There's no more "Settings -> Passwords & Accounts" in ios 15 anymore is there?
> 
> 
> 
> I only see passwords, which is for autofill

Instead of "Settings -> Passwords & Accounts" which is how it was before now you "Settings -> mail -> accounts" this only works for iCloud accounts by the way.

**Comment by Onik97** [comment]
For iOS 18.3

Settings -> Apps -> Mail -> Mail Accounts -> Add Account -> iCloud

As long as you have a iCloud account, doesnt matter which email (I used gmail and it worked fine)

**Comment by KangHidro** [comment]
I noticed that if you use an account with the region set to Mainland China and don’t have a linked Chinese phone number, you’ll still run into the error (-22411). I don’t have a Chinese phone number myself, so I’m not sure if linking one would allow the account to log in successfully.
