### ISSUE TITLE
Inactive Apps Count Towards Total of 3 Apps

### ISSUE THREAD

**Issue by junaidchhipa** [rileytestut/AltStore#176]
Hi thanks so much for the AltStore Service it works amazingly. Sorry if this is dumb to post because I am using beta software, but on iOS 13.4.5 public beta, I am having an issue. Even if an app is inactive, it is counting toward the “cannot activate more than 3 apps” limit. I will add some screenshots for proof. Deleting an app rather than deactivating it allows me to install additional apps. 

![4AA69027-3476-4601-8E2D-FD283D44A993](https://user-images.githubusercontent.com/15900558/80633900-8e101e00-8a27-11ea-88ab-27d351b71790.png)
![38B8D5A4-07C9-47BD-AC8E-577DD185BCF1](https://user-images.githubusercontent.com/15900558/80633906-8ea8b480-8a27-11ea-9cf2-71edf5ac966e.png)

**Comment by CrCrate** [comment]
Goblin sword might have app extensions, those count towards the limit.

**Comment by LegitEzra** [comment]
Click View App IDs. There you can see if "Goblin Sword" is using more than one.

**Comment by junaidchhipa** [comment]
Thanks you guys, but I tried it with different combinations of apps. If I uninstall Goblin Sword, I am able to activate another app. But the limit still remains at 3. No matter which apps, the limit is just stuck at 3. I understand that you can not have more than 3 _active_, but it won’t even let me have more than 3 _installed_.

![A9A0F754-2C68-4425-AA9B-DA2A8457B924](https://user-images.githubusercontent.com/15900558/80897772-77d5bc80-8cca-11ea-8dd3-9efc375ea213.png)

**Comment by noah978** [comment]
@junaidchhipa Please try again with the latest versions of AltStore and AltServer.
