### ISSUE TITLE
Do not blindly trust apps with Psychic Paper entitlements

### ISSUE THREAD

**Issue by mologie** [rileytestut/AltStore#180]
This is more-or-less of a feature request: I noticed that AltSign now processes Psychic Paper'd apps properly. That's awesome, but users might be unaware of the consequences and believe that apps installed through AltStore are still properly sandboxed.

Psychic Paper enables doing some Pretty Nasty Things(tm), such as wiping the device (obliteration entitlement) or stealing iCloud tokens (keychain/debugging entitlements). I suggest adding a warning when installing apps that use Psychic Paper, ideally with a list of granted entitlements.

**Comment by Spidy123222** [comment]
What I see it tells you the entitlements it going to use but I’d agree that there should be maybe like a more info option about what the entitlement dose. For example dolphinios uses code signing entitlement and it tells you in the altstore but some people wouldn’t know what it’s for so having a more info button will tell you what it dose.

**Comment by mologie** [comment]
Indeed, the feature was added/announced on Twitter after I created the issue here. It was probably already in development.

**Comment by noah978** [comment]
This feature has been successfully added, thanks for the input. Closing this issue.

**Comment by malhal** [comment]
Is there any alternative to Psychic Paper for using private entitlements in our apps?

**Comment by Spidy123222** [comment]
> Is there any alternative to Psychic Paper for using private entitlements in our apps?

You can use latest sandbox escapes that's for jailbreaking newer iOS versions. But you would need to code the sandbox escape into the app.
