### ISSUE TITLE
Lowest version of iTunes iCloud that Alt Server can work with? Have to use older iTunes for certain reasons. 

### ISSUE THREAD

**Issue by xbliss** [rileytestut/AltStore#182]
Lowest version of iTunes iCloud that Alt Server can work with? Have to use older iTunes for certain reasons. 

Or will have to do a separate Windows install just for this.

**Comment by noah978** [comment]
Not really sure actually. I'd just give it a shot and see if it works. The only issue I could see arising is if your version of iTunes doesn't have support for communicating with the iOS of your device.
