### ISSUE TITLE
AltStore couldn’t be found

### ISSUE THREAD

**Issue by JustBlan1984** [rileytestut/AltStore#183]
I have Altstore installed on my phone but when I try to install an ipa with altstore app it tells me altstore couldn’t be found. I also have paid for $5 Patreon.

**Comment by devinprater** [comment]
Try unchecking and checking again the "Show this iPhone when on Wi-Fi" box. That helped me. I mean, do that on your computer. If on Windows, its the iTunes Wifi Sync.

**Comment by noah978** [comment]
@JustBlan1984 If you are still having issues, I will need more information:
* What iOS version?
* Mac or Windows?
* Have you tried using the [latest AltServer Beta?](https://altstore.io/altserver/beta)
