### ISSUE TITLE
The file "SettingsHeaderFooterView.nib" couldn't be saved in the folder "AltStore.app"

### ISSUE THREAD

**Issue by SkyforgerCFW** [rileytestut/AltStore#185]
I get this error when trying to install AltStore to my iPhone X running iOS 13.4.1 from AltServer 1.3 on macOS 10.15.4.
![img](https://user-images.githubusercontent.com/26817180/81508525-db806b00-9304-11ea-8172-e46d0a904db3.png)
Attempting to compile AltServer myself, Xcode throws the same error as #56.

**Comment by SkyforgerCFW** [comment]
Trying AltStore installation from Windows gives a very nondescript error.

![AltServer_hsrSIKONP8](https://user-images.githubusercontent.com/26817180/81729694-aef75b00-948c-11ea-9201-5d4635b7c207.png)

**Comment by rileytestut** [comment]
Trying to figure out the cause of this issue. Are you still unable to compile AltServer for Mac? Haven't been able to reproduce myself, but apparently this is somehow tied to the iOS device. Installing to second iOS device has worked for others with that issue, does that happen to work for you too?

**Comment by noah978** [comment]
@SkyforgerCFW Have you trusted the device in iTunes and do you have your device unlocked during the installation?

**Comment by PLanB2008** [comment]
Trying to install altserver on my phone I receive a very similar error:
<img width="452" alt="grafik" src="https://user-images.githubusercontent.com/26460239/82735288-ca7e2380-9d20-11ea-9de3-3ff3e227db63.png">

Is this a problem with my phone or my computer? Is there anything I can do to provide some debug information? Does altstore write any kind of log?

**Comment by megnaumdes** [comment]
I have same error as PLanB2008. 

![Screen Shot 2020-05-26 at 1 13 03 pm](https://user-images.githubusercontent.com/29483869/82857127-67280780-9f53-11ea-8acf-eb0aec89432b.png)

AltServer Version 1.3.2 (24)
macOS Version 10.15.4
iOS Version 13.4.1 (no jailbreak)

**Comment by megnaumdes** [comment]
However it works fine I connect an iOS 12.4.6 device to the same laptop.

**Comment by PLanB2008** [comment]
My installation attempp was on ios13.5.

Could this in anyway be ios version related? But in general the process works on ios13. It would really help to get some information on how to debug this...

**Comment by medkannouch** [comment]
I have a similar error to this when trying to install AltStore using AltServer (1.4.4) on iphone (ios 14.4) using MacOs  Big Sur (lastest version) however I had no problem installing it on Ipad (iPadOS 14.4)
<img width="370" alt="Screenshot 2021-03-17 at 11 09 54" src="https://user-images.githubusercontent.com/17469577/111452016-56c76000-8712-11eb-8d89-e65a5cc4ddfa.png">

**Comment by abdullahmujahidali** [comment]
> I have a similar error to this when trying to install AltStore using AltServer (1.4.4) on iphone (ios 14.4) using MacOs Big Sur (lastest version) however I had no problem installing it on Ipad (iPadOS 14.4)
> <img alt="Screenshot 2021-03-17 at 11 09 54" width="370" src="https://user-images.githubusercontent.com/17469577/111452016-56c76000-8712-11eb-8d89-e65a5cc4ddfa.png">

Did you find any solution?

**Comment by theMIGwelder** [comment]
I corrected this error by using a different USB to lightning cable and deleting and reinstalling the Altserver app
