### ISSUE TITLE
Can sideload some apps but can’t sideload others

### ISSUE THREAD

**Issue by IMINCANE711** [rileytestut/AltStore#188]
I am on an IPhone 6 that was jail broken before. I have had this issue in the beta version too before it went to the public. I can sideload IPA’s like NineAnimator but I could not sideload an Unc0ver ipa. I don’t know what it was but something in the iPad is making it so I can sideload some and not others.

**Comment by noah978** [comment]
Need more info here:
* What iOS version?
* What error are you getting?
* Which specific IPAs are giving issues?
