### ISSUE TITLE
New Installation error

### ISSUE THREAD

**Issue by jamesmurdoch** [rileytestut/AltStore#189]
Im getting this installation error. Help?

![Screen Shot 2020-05-19 at 1 27 21 PM](https://user-images.githubusercontent.com/65624344/82369598-857e8800-99d4-11ea-8914-b8b4e24665d3.png)

**Comment by noah978** [comment]
Assuming you are on iOS 13.5, this is actually a bug introduced by Apple. You can see the [AltStore tweet here.](https://twitter.com/altstoreio/status/1263608325465202688?s=20)

Since it's not something we can fix, I'll close this issue.
