### ISSUE TITLE
Can you respond to issues?

### ISSUE THREAD

**Issue by ZebTheWizard** [rileytestut/AltStore#190]
I think your project is brilliant and I want to help as much as I can, but I can't do anything when there is no documentation and no answers to issues. Do you really want help with this project?

**Comment by jbmagination** [comment]
Likely not. He hardly ever merges any PRs in the small chance they pop up

**Comment by noah978** [comment]
Not sure whether Riley intends to engage any more than he currently is with Github Issues and PRs, but I am at least going to start cleaning up and managing the Issues section.
