### ISSUE TITLE
i can't download apps

### ISSUE THREAD

**Issue by sarxhz** [rileytestut/AltStore#194]
I've just downloaded AltStore, I'm logged with my iCloud account, but when I'm trying to download spotify++ from the file it says "could not find AltServer"

**Comment by noah978** [comment]
Please refer to the [AltStore FAQ](https://altstore.io/faq) for assistance regarding "Cannot find AltServer." Likely the Apple Mobile Device Service has stopped and needs to be restarted (it's rather finicky). You can try [AltCheck](https://github.com/DiscordDigital/AltCheck) and see if it works for you.
