### ISSUE TITLE
AltStore is taking 6.67 Gb of space on my iPhone 7 and increases on refresh.

### ISSUE THREAD

**Issue by FellFromTheSky** [rileytestut/AltStore#196]
**Describe the bug**
<img width="375" alt="Capture d’écran, le 2020-05-23 à 21 09 16" src="https://user-images.githubusercontent.com/47761913/82743451-bdb9f980-9d39-11ea-8c9e-f2d3e37cb9a5.png">

**Comment by FellFromTheSky** [comment]
Now that I've unninstalled AltStore and installed RetroArch trough it, it's now taking 1 Gb on the iDevice, it's still too much.

**Comment by FellFromTheSky** [comment]
I think I'll just ditch QltStore until the issue is fixed by dev team.

**Comment by noah978** [comment]
To supply more information on the bug, this has been a strange recurring bug with AltStore where refreshing applications causes the app data size to increase. Will hopefully get fixed soon.

**Comment by FellFromTheSky** [comment]
Thanks

**Comment by ap46281** [comment]
Hey just wanted to note I'm on v1.5 on my iPad Pro M1 with only UTM loaded. Altstore is currently taking up 70gb of my internal storage.
