### ISSUE TITLE
"Could not find AltServer"

### ISSUE THREAD

**Issue by alexkibler** [rileytestut/AltStore#2]
Hey there, just installed AltServer and AltStore.  

Altserver is on Windows 10 version 1903,

Altstore is on iPhone 11, iOS 13.1

Brand new installation of iTunes (because who wants iTunes on a windows pc am I right?)

Connected the iPhone and enabled wifi sync (and trusted my PC), AltServer running in the background.  Tried rebooting PC, restarting iTunes, restarting altserver, all to no avail. 

Any time I try to install any app on AltStore, I'm getting Could Not Find AltServer.

Am I missing a step?

**Comment by alexkibler** [comment]
I found a [reddit thread](https://www.reddit.com/r/iOSBeta/comments/c8scj3/feature_itunes_wifi_sync_is_no_longer_showing_up/) talking about wifi sync being removed from iOS 13.

**Comment by eni9889** [comment]
@alexkibler I don't think WiFi sync is needed here since there are still OTA installs that can be done from Xcode it must be something else

**Comment by noah978** [comment]
Your problem is most likely related to the installation of iTunes you have. You need the iTunes from [here](https://www.apple.com/itunes/download/win64) not from the windows store.

**Comment by alexkibler** [comment]
@eni9889 I was able to figure it out with someone else's help. The issue was that I had the windows store version of iTunes, which doesn't install bonjour

**Comment by alexkibler** [comment]
Yup Noah, that was me you helped earlier. Thanks again!

**Comment by mr3j** [comment]
@noah978 your link solved my problem. Unc0ver's page just refers to Apple, and Apples page only offers Windows download now, at least I did not spot any way to download the Apple download myself.
