### ISSUE TITLE
Linux Support for AltServer

### ISSUE THREAD

**Issue by jmanpenilla** [rileytestut/AltStore#20]
Is there any plan to support Linux? libimobiledevice and Cydia Impactor work. Is there a missing component blocking it from working or is it simply not targeted? Thanks

**Comment by jagge1988** [comment]
Would love to run the altserver on my Raspberry bc it runs 24/7.

**Comment by nighto** [comment]
Duplicate of #6

**Comment by fennectech** [comment]
i dont have any windows boxes that stay on   Id love to run altserver on my linux box but it doesnt detect it in wine even after transfering its regestry settings.. Just says "cannot find the altserver"  Impactor works on linux so altserver should be possible

**Comment by jmanpenilla** [comment]
Closing this. Works for me in a VM, but I don't want to keep that open. I'm just using ReProvision for Delta. #6 is a duplicate of this that has more technical discussion as to the reason and possible workarounds. Wi-Fi sync components are missing, only the components for Cydia Impactor/initial install exist on Linux.
