### ISSUE TITLE
can't run altsever

### ISSUE THREAD

**Issue by Trantienloc2411** [rileytestut/AltStore#200]
**Describe the bug**

**To Reproduce**
1. Go to 'AltSever.exe'
2. Click on 'AltSever.exe'
3. See error

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/62489239/82745200-ccd98f80-9dab-11ea-8a62-444f5756e2d0.PNG)

**Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Version: 8.1

**iPhone (please complete the following information):**
 - Device: iPhone 7 Plus
 - iOS: 13.4

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by noah978** [comment]
Windows 8.1 is an unsupported version. You can try running in compatibility mode, but other than that, there isn’t much I can do for you.
