### ISSUE TITLE
Error - Already installed and session expired 1100? 

### ISSUE THREAD

**Issue by MickLesk** [rileytestut/AltStore#206]
**Describe the bug**
i will install iSpoofer with the install manual from there:
https://www.ispoofer.com/how-to-install-ios-app-via-altstore/

I always get the error that the session expired. I've already tried various things, but found no solution.

- new ITunes (Version: Version 12.10.7.3) 
- new iCloud (Version: 7.18)
- AltServer (Version: 1.3.2.0 latest)

**To Reproduce**
1. Windows 10 -> Go to Taskbar -> Right-Click -> Install AltServer -> "Iphone 6" (Device-Name)
2. dialogue with Apple-ID + Password filled => Click "Install" 
3. After 5-10 secounds Dialog "Altstore already installed on another device" 
=> Why? This Apple-ID is a new one, 
3.1 i take a look in Settings -> Apple-ID and there is a "MacBook Pro" Device?
4. After a few minutes i get "Installation Failed" -> "Your session has expired. Please log in (1100)."

After this: i delete the device (MacBook Pro) and do the same
=> Apple-ID + Password
=> 2-factor-authentif.
=> dialogue already show "Apps installed with Altstore on your other devices will stop working. Are you sure you want to continue?"
=> dialogue in Taskbar "This will take a few minutes".
=> "Your session has expired. Please log in (1100)."

**Expected behavior**
Installation should work without problems, I want to download the .ipa for iSpoofer via the AltServerPatcher and install it directly on the device.

**Screenshots**
picture for secound step:
![2020-05-24 15_24_08-Window](https://user-images.githubusercontent.com/47820557/82755667-649fa380-9dd5-11ea-98ce-24d370619503.png)

picture for third step: 
![2020-05-24 15_38_54-Window](https://user-images.githubusercontent.com/47820557/82755675-74b78300-9dd5-11ea-98db-92cb983d6df4.png)

picture for last step (failed):
![2020-05-24 15_38_18-Window](https://user-images.githubusercontent.com/47820557/82755687-83059f00-9dd5-11ea-853d-ee5ea2a9bb3b.png)

**Desktop (please complete the following information if applicable):**
 - OS + Version / Build: Windows 10 Pro  (1909 - Build: 18363.836)

**iPhone (please complete the following information):**
 - iPhone 6 (64GB) -> MG4H2ZD/A
 - iOS: 12.4.7 

**Additional context and logs**
- ? Where can i find logs for AltServer?

**Comment by noah978** [comment]
You cannot delete the MacBook Pro device from your Apple ID, AltServer uses it to trick Apple into thinking the signing request is coming from a Mac device instead of windows.

**Comment by noah978** [comment]
We also avoid taking AltServer patcher issues here since that is outdated and we recommend using the on-device AltStore to sideload apps instead.

**Comment by MickLesk** [comment]
The MacBook device is Back with the secound run, thats mit the Problem..

**Comment by noah978** [comment]
Can you get AltStore to install using a fresh installation (not using AltServer patcher)?

**Comment by MickLesk** [comment]
> Can you get AltStore to install using a fresh installation (not using AltServer patcher)?

I have already do a Clean Install.
No Change. I Install all tomorrow @ my secound Computer and Take a Look.

Device with this iOS-Version is supported?

**Comment by MickLesk** [comment]
I have installed AltServer on my other computer, there it works. I have no idea why it does not work on my Microsoft Surface. 

I close the bug once by myself :-)
