### ISSUE TITLE
Installation Failed Invalid anisette data Please close both itunes and icloud and try again

### ISSUE THREAD

**Issue by Alphaltz** [rileytestut/AltStore#208]
Shows this but itunes and icloud are closed 
![image](https://user-images.githubusercontent.com/61337318/82760248-bd1c7400-9dc8-11ea-86a5-249416d23032.png)

**Comment by noah978** [comment]
Duplicate of #156.

**Comment by Alphaltz** [comment]
It isnt a duplicate it is different issue.
