### ISSUE TITLE
An on device signer for jailbroken users

### ISSUE THREAD

**Issue by SarKaa** [rileytestut/AltStore#211]
**Is your feature request related to a problem?
With the new Unc0ver jb for iOS 13.5, you can’t sign apps on device anymore, and seeming as you have this for non-jb users that need a conputer, is it not possible to have an altstore app without altserver needed for jailbroken users to use

**Comment by SarKaa** [comment]
Actually, there is an unofficial version on http://repo.ipodhacks142.com/

**Comment by jankais3r** [comment]
Official alpha version also has this feature.
