### ISSUE TITLE
The operation couldn’t be completed. Cannot activate more than 3 apps and app extensions.

### ISSUE THREAD

**Issue by kolossboss** [rileytestut/AltStore#214]
I cant install altstore on my iPhone XS with iOS13.5

First I get this message:
**AltStore already installed on another device.
Apps installed with AltStore on your other devices will stop working. Are you sure you want to continue?**

Then I see this error:
**The operation couldn’t be completed. Cannot activate more than 3 apps and app extensions....
If you are running iOS13.5.....**

<img width="418" alt="Bildschirmfoto 2020-05-24 um 21 12 12" src="https://user-images.githubusercontent.com/11015086/82763054-f96dc580-9e04-11ea-95a6-b5f4547219f8.png">

Offload Unused Apps is disabled.  I have currently no other apps activated on my device. A few months ago i installed altstore, but its deleted long ago.
I tried three different Apple IDs always with the same error.

Is there any way to see or delete this ghost apps?

I'm running altserver on MacOS Catalina v10.15.4.

Thanks for helping.

**Comment by thatrobotdev** [comment]
I have the same issue! 

macOS Catalina, v10.15.4 (19E87)
AltServer Version 1.3.2 (24)
iOS 13.5 on my iPhone 7
Mail plugin "Bundle version" = 1
I have 2-factor auth on my icloud account.

I've installed altstore a couple of months before this but I've deleted it,
disabled offloaded apps.

No 3rd party apps are on my system.

Before I install I get this warning: 
![Screenshot of AltServer: AltStore already installed on another device. Apps installed with AltStore on your other devices will stop working. Are you sure you want to continue? Cancel, Continue](https://user-images.githubusercontent.com/18013689/82768046-899e1180-9de9-11ea-90bf-d35ab38561e7.png)

**Comment by thatrobotdev** [comment]
The only thing I can think of is that it is counting PWAs, or web shortcuts on the home screen as an installed app.

**Comment by btcmaster** [comment]
Hi!
You just need to remove all offloaded apps.
After this, try again.

**Comment by kolossboss** [comment]
I dont have any offloaded apps.
Offload apps is disabled and was never enabled

**Comment by kolossboss** [comment]
> Hi!
> You just need to remove all offloaded apps in your iphone.
> After this, try again.

OK. For any reasons I had 4 Offloaded apps (Apps on Homescreen with cloud symbol). I deleted/reinstalled them and now its working.
Thanks a lot

**Comment by JosephDuffy** [comment]
I went through my home screen and couldn't find any offloaded apps. I think the issue might have been that I had deleted some of the stock apps. After reinstalling the stock apps it works.

**Comment by davidbailey00** [comment]
I am the same as @JosephDuffy - I haven't offloaded any apps, but I have deleted some stock apps, and I get this error

**Comment by thatrobotdev** [comment]
Is there a full list of stock apps? Or is there a way to see all of the
offloaded stock apps?

>

**Comment by thatrobotdev** [comment]
I can confirm that after downloading all of the stock apps, I was able to install AltStore on my device! If this is true across the board, we should edit the error message to something like the following:

"The operation couldn't be completed. Cannot activate more than 3 apps and app extensions.

If you're running iOS 13.5 or later, make sure "Offload Unused Apps" is disabled in Settings > iTunes & App Stores, then install or delete all offloaded apps to prevent them from erroneously counting toward this limit. Stock apps that have been deleted also count toward this limit, so make sure that all stock apps are downloaded."

**Comment by th3sn3k** [comment]
I have all the stock apps installed but I still can’t get it to work maybe I have to change iTunes reigion

**Comment by th3sn3k** [comment]
Checked after reinstalling all AIDS Sumi doesn’t work

**Comment by caeye** [comment]
If you are using macos, here is solution - https://stackoverflow.com/a/61978102

**Comment by th3sn3k** [comment]
> If you are using macos, here is solution - https://stackoverflow.com/a/61978102

Using windows any workaround?

**Comment by Guneetgstar** [comment]
Make sure Automatic sync is enabled in Finder. 
Open Fider->Select iPhone->General->Check Automatically sync when this iPhone is connected. 
This resoves the issue.

**Comment by Guneetgstar** [comment]
> Using windows any workaround?

Try the same for iTunes for windows, hope this would work for you as well.

**Comment by th3sn3k** [comment]
> > Using windows any workaround?
> 
> 
> 
> Try the same for iTunes for windows, hope this would work for you as well. 
> 
> 

It is enabled

**Comment by ewpandaa** [comment]
Has anyone figured this issue out? I am still having this issue

**Comment by RoblKyogre** [comment]
Having this issue as well. I'm not missing any stock apps, and I only have AltStore activated right now.
