### ISSUE TITLE
Unknown services response error -1

### ISSUE THREAD

**Issue by DankBladeZS** [rileytestut/AltStore#215]
I'm getting this error where it says "Unknown services response error -1" Whenever I try to install AltStore on my phone.

iOS Version: 13.5

Windows 10 Version: 1909 (OS Build 18363.836)

AltStore Version: Latest

Screenshot:
![image](https://user-images.githubusercontent.com/59133811/82764292-5756d900-9e16-11ea-8848-115f13956427.png)

I also get this error whenever I connect my phone to iTunes.
![image](https://user-images.githubusercontent.com/59133811/82764304-663d8b80-9e16-11ea-9e48-c806fc58c553.png)

**Comment by noah978** [comment]
I would try reinstalling your iTunes. Is it installed in the default location or is it somewhere else?

**Comment by DankBladeZS** [comment]
I tried reinstalling iTunes but that didn't work. Yes it's in the default location.

**Comment by DankBladeZS** [comment]
I forgot to say that I'm using an iPhone XR.

**Comment by DankBladeZS** [comment]
Okay so now i restarted my computer and iTunes works but AltStore still doesn't work.

**Comment by DankBladeZS** [comment]
If you have a Discord could I possibly screenshare and show you?

Discord: DankBladeZS#4627

**Comment by DankBladeZS** [comment]
For some reason it worked...... I don't know what I did but it worked. Yay!

**Comment by DankBladeZS** [comment]
I guess you just had to wait.

**Comment by wyeet16** [comment]
Ok I am having the same issue and you said you just waited right and that fixed it

**Comment by DankBladeZS** [comment]
Maybe try reinstalling iTunes, restarting your phone and closing and reopening AltStore. I **think** that's what i did

**Comment by muhammedaksam** [comment]
This issue still continues.

**Comment by Panak252** [comment]
This error just started coming up for me too. Restarted iPhone, and altserver. I logged out and back in, but problem persists.
