### ISSUE TITLE
Incorrect Password or apple ID (-22406)

### ISSUE THREAD

**Issue by Wisplings** [rileytestut/AltStore#217]
**Describe the bug**
If i want to login into altservers, with my apple id, i put in my information and i says incorrect password or id, but im 100% sure that i didnt wrote something wrong
**To Reproduce**
1. Go to 'Instal Altstore'
2. Click on Device name.'
3. Enter Apple Id And Password
4. See error: Your apple ID or password is incorrect (-22406)

**Expected behavior**
Install the app on your iphone or ipad

**Desktop (please complete the following information if applicable):**
 - OS:Windows
 - Version: Windows 10

**iPhone (please complete the following information):**
 - Device: [e.g. iPhone7]
 - iOS: [e.g. 13.5]

**Additional context and logs**

**Comment by oSinkz** [comment]
install what on our ipad?

**Comment by noah978** [comment]
I would recommend creating a throwaway Apple ID and use that instead. Leave a comment if the issue persists.

**Comment by Wisplings** [comment]
made a throwaway apple ID, but i still get the same issue

**Comment by Wisplings** [comment]
so if i try to use my id it says now 'this action cannot be completed at this time (-22411)

**Comment by noah978** [comment]
@Wisplings Are there capitals in the email you were using for your Apple ID? Make sure that you are using lowercase letters only.

**Comment by noah978** [comment]
@Wisplings Please first try deleting the "Adi" folder in "C://Program Data/Apple Computer/Adi". Then if that doesn't work, try the solution in #175
