### ISSUE TITLE
Unable to find AltServer in Menu bar

### ISSUE THREAD

**Issue by tripp396** [rileytestut/AltStore#219]
**Describe the bug**
AltServer is supposed to appear in menu bar. It does not. I can see from Activity Monitor that it is running.

**To Reproduce**
1. Download AltServer for Mac.
2. Copy “AltServer.app” to your Applications folder.
3. Launch AltServer 

**Expected behavior**
Expect the icon to appear in the menu bar, it does not/

**Desktop (please complete the following information if applicable):**
 - OS: Mac
 - Version: 10.15 (Catalina I believe)

**iPhone (please complete the following information):**
 - Device: iPhone 11 pro max
 - iOS: 13.5

**Additional context and logs**
n/a

**Comment by noah978** [comment]
Try restarting your computer?

**Comment by tripp396** [comment]
Unfortunately that doesn't solve the issue. Still not showing up in the menu bar as the instructions state.

**Comment by noah978** [comment]
Hmm, as I recall this issue popped up awhile back, but it turned out to just be a bug with macOS. Could you try updating your macOS?
