### ISSUE TITLE
issue with the newest version on windows 10

### ISSUE THREAD

**Issue by imnisp** [rileytestut/AltStore#224]
the procedure entry point IsWow64Process2 could not be located

**Comment by jack980517** [comment]
I'm having this problem as well, and according to [a Reddit thread](https://www.reddit.com/r/AltStore/comments/gpjd9u/dll_error_after_updating_altstore/), downgrading to 1.3.1 beta 1 fixes it.

**Comment by noah978** [comment]
Duplicate of #205. Closing.
