### ISSUE TITLE
Cannot activate more than 3 apps and app extensions.

### ISSUE THREAD

**Issue by OMN30** [rileytestut/AltStore#225]
Every time I try to install AltStore on my iPhone it gives me the error 'Cannot activate more than 3 apps and app extensions.'

I have disabled Offload Unused Apps and reinstalled the offloaded apps, but it still gives me the error.

I am on iOS 13.5 and macOS 10.14.6

**Comment by noah978** [comment]
I would double check to make sure all of your offloaded apps have been removed. I also remember hearing that some people found it worked after waiting a little while.

**Comment by OMN30** [comment]
Apparently I had some Unused apps in some folders, which I found with the console on my mac

**Comment by 53lect** [comment]
Hoy did u do that? Mi hacina the salme Isauro situado mi iPad Pro, but never had on the offload setting and checked Homescreen, could’t fine any.
