### ISSUE TITLE
problem installing altstore iphone x 13.5

### ISSUE THREAD

**Issue by razyel88** [rileytestut/AltStore#226]
i'm having hard time re-installing altstore on an iphone x 13.5,
altstore was installed previously and work right, after delete it from the phone and want to reinstall on the same phone i got an error

ssl error:winhttp_callback_status_flag_cert_cn_invalid ssl common name does not match.

please help i've tried everything

**Comment by noah978** [comment]
* Delete the folder named "adi" in the iTunes file directory.
* Make sure your computer and iPhone have time/date to set automatically.

**Comment by razyel88** [comment]
now it prompts me to enter the code displayed on iphone, then ask me_

AltStore already installed on another device.
---------------------------
Apps installed with AltStore on your other devices will stop working. Are you sure you want to continue?
 
Go with ok
and got this same error as before

---------------------------
Installation Failed
---------------------------
SSL Error: WINHTTP_CALLBACK_STATUS_FLAG_CERT_CN_INVALID SSL common name does not match.

**Comment by razyel88** [comment]
deleted altserver from win10, then reinstalled it and i was able to install altstore on device.
Thanks

**Comment by noah978** [comment]
Glad you got it to work. I'll go ahead and close this.
