### ISSUE TITLE
Invalid anisette data

### ISSUE THREAD

**Issue by azizo555** [rileytestut/AltStore#227]
im trying to install altserver on my iphone 8 plus ios 13.5 on windows
but i keep getting this error Invalid anisette data close itunes and i cloud and try later 
please any help ?

**Comment by noah978** [comment]
Duplicate of #156. Closing.

**Comment by lucidyan** [comment]
For anyone who get `invalid anisette data close itunes and icloud` error on Windows, try to delete all files in this folder: `C:\ProgramData\Apple Computer\iTunes\adi`.

Source: official Altstore twitter
https://twitter.com/altstoreio/status/1264285607427104768
