### ISSUE TITLE
"Your account information was entered incorrectly -20101"

### ISSUE THREAD

**Issue by iamdedd** [rileytestut/AltStore#228]
I received this error when unc0ver is downloading after safari. When I login to altstore using my @gmail.com apple ID, it will successfully login but then show a @yahoo.com email that I had changed several years before on the apple website. Logging to the correct icloud account but shows old @yahoo email address. 

Reproduced every time I try to downloading unC0ver after clicking the link in safari. 

![20200527_052938000_iOS](https://user-images.githubusercontent.com/65252346/82981534-1dfea480-9fa1-11ea-9423-0bed99762303.jpg)
![20200527_053040000_iOS](https://user-images.githubusercontent.com/65252346/82981541-20f99500-9fa1-11ea-9283-a2df6d707e25.jpg)

Windows 10

 - Device: iPhone 11 Pro
 - iOS: 13.5

**Comment by noah978** [comment]
Are there capital letters in your email address? Try using only lowercase.

**Comment by iamdedd** [comment]
No capital letters, all lower case were typed.

**Comment by rexbarrett** [comment]
This is the same thing happening to me. I log in with my Apple ID, which is a .mac email address only for AltStore to swap it out with a gmail address in the settings.

**Comment by hubby02** [comment]
Sign in on the apple developer website with your apple id and it then won't change when you sign in on the app.

**Comment by iamdedd** [comment]
logging into the apple developer site seems to have fixed the problem. I am now jailbroken.

**Comment by cpiekacz** [comment]
I've signed on the apple developer website but I still see the gmail address for my @mac.com account and still cannot re-sign the apps. Any other ideas?

**Comment by hubby02** [comment]
Obvious question but have you logged out on AltStore and logged back in again?

**Comment by cpiekacz** [comment]
Of course.

**Comment by hubby02** [comment]
Sorry have no idea then. I had this issue and the Apple developer website was the first thing I tried. Maybe double check you account details on the Apple developer website and ensure that they are the same as the ones you are entering on AltStore

**Comment by cgreg33** [comment]
If you haven't figured this out yet, I think I have a solution for you. Log out completely and try to install unc0ver. When it downloads, it will ask you to log in. Since you're putting your correct email address in during this time, it should work. For some reason, if you're already logged in, it has a hard time recognizing it.

**Comment by cpiekacz** [comment]
Thanks, but that's not the problem. AltStore correctly logs in and is able to sing the apps. it just unable to re-sign them again. But it does not matter, installed Reprovision and the problem is solved.

**Comment by ysalam** [comment]
Has anyone found a solution to this problem? 
Last week everything was fine and this week im getting the  error. 

Everything is as it should be: icloud is open on PC and logged in, iTunes is open as well and logged in. and I have my phone connected via cable to PC 
Ive changed my password via iForgot and it didnt help.
Ive signed out and in of altstore and it didnt help

Running iOs 13.2.2 on a  iPhone 7+ and using a Windows 10 PC.  
PS Im using altstore fo rthe emulators

**Comment by luixiuno** [comment]
Please post this: DUUUUH it’s already fixed for me duh

**Comment by ggg-ctrl** [comment]
The problem has also appeared for me, have you solved the problem?

**Comment by ysalam** [comment]
> The problem has also appeared for me, have you solved the problem?
I opened up a separate issue thread for it (#247 ). What happened was that it just suddenly started working normally  @ggg-ctrl

**Comment by Samuelngala3** [comment]
> If you haven't figured this out yet, I think I have a solution for you. Log out completely and try to install unc0ver. When it downloads, it will ask you to log in. Since you're putting your correct email address in during this time, it should work. For some reason, if you're already logged in, it has a hard time recognizing it.

This worked just fine for me 
Thanks
