### ISSUE TITLE
Unknown Error when installing AltStore Beta

### ISSUE THREAD

**Issue by wey-gu** [rileytestut/AltStore#230]
**Describe the bug**
I had left AltStore not updating/refreshing for days, today when deploying the AltStore via macOS AltServer(1.3.2(24)), I still cannot update/re-install the Beta AltStore.

**To Reproduce**
1. AltStore and Beta expired, reinstalled AltStore via AltServer
2. Try updating(with both cabled and Wi-Fi), Error
3. Try deleted Beta, install again, Error

**Expected behavior**
Updated/Reinstalled 

**Screenshots**
![IMG_0025](https://user-images.githubusercontent.com/1651790/83225459-63de8700-a1b2-11ea-9822-d351124e5dee.PNG)

**Desktop (please complete the following information if applicable):**
 - OS: Mac
 - Version: Catalina

**iPhone (please complete the following information):**
 - Device: iPad Pro Gen 2
 - iOS: iPadOS 13.5

**Additional context and logs**
How could I provide logs? If it's possible kindly help give hints on how to enable debugging log generation :-).
Thanks.

**Comment by littlewey** [comment]
Still, I cannot bypass this issue... cannot use UTM and delta T__T...

**Comment by ImJellyUJelly** [comment]
I have the same issue, would really like to see a fix for this :)
