### ISSUE TITLE
The app could not be found

### ISSUE THREAD

**Issue by brownbruce** [rileytestut/AltStore#234]
I have windows 7 and my iPhone has 13.4 ios version.When i try to install altserver there is this problem.

**To Reproduce**
1. I click on altserver exe
2. Click on install altstore
3. I put apple id and pass 
4. Click on install
5. Then this message appears: 
Apps installed with altserver om your other device will stop working. Are you sure you want to continue?
6. I click on ok.
7.then appears: the app could not be found.

**Comment by noah978** [comment]
We don't provide support for Windows 7 here. But if you look around on Google, and use the [AltStore FAQ](https://altstore.io/faq, you should be able to solve your issue with troubleshooting.
