### ISSUE TITLE
Why my apple ID was attempted to log in in another place right after I entered my Apple ID???

### ISSUE THREAD

**Issue by Yogurt2019** [rileytestut/AltStore#236]
WTF is this software doing?
my apple ID was attempted to log in in another place right after I entered my Apple ID and  password
IS THIS SERIOUS MAN

**Comment by somethingwrng** [comment]
I believe this is supposed to happen. Happened to me the first time, and I assume it is just a server logging in to then install app files.

**Comment by Yogurt2019** [comment]
> I believe this is supposed to happen. Happened to me the first time, and I assume it is just a server logging in to then install app files.

the point is my account was attempted to login in Beijing China, and the author of this project does not seem like a Chinese.

**Comment by Assfugil** [comment]
@Yogurt2019 which country do you live in?

**Comment by Yogurt2019** [comment]
> @Yogurt2019 which country do you live in?

China

**Comment by Assfugil** [comment]
That device is you PC emulating a Mac. (MacBook Pro if I recall correctly)

**Comment by Mikasa-san** [comment]
Yes Me too I get message to log in my account in another place after using Altstore 3 days ago

**Comment by Mikasa-san** [comment]
Change your password!!!

**Comment by Terrain2** [comment]
On windows, AltServer has to emulate a mac to sign your apps - On mac you don't get this since it can just use the mac you're on

**Comment by noah978** [comment]
It was not a result of AltStore. All credentials are sent securely to Apple (using the same way as Xcode signing) and no where else.

**Comment by JustinRampage** [comment]
I had the same exact thing happen RIGHT after logging into AltStore.
