### ISSUE TITLE
Error installing AltStore "Failed to write app data to device"

### ISSUE THREAD

**Issue by somethingwrng** [rileytestut/AltStore#239]
When installing on Windows 10 AltServer gives the install error "Failed to write app data to device". Previously working now is no longer. 

![image](https://user-images.githubusercontent.com/61095526/83363416-e6a44500-a35e-11ea-8015-973bc33676b9.png)

**Comment by bentsionmp** [comment]
hey, how were you able to fix this issue?

**Comment by somethingwrng** [comment]
I had to reinstall altserver on a different machine but for some reason a couple weeks ago uninstalling and then reinstalling it worked for me. Could be that my phone updated and fixed something also.
