### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by tbodt** [rileytestut/AltStore#24]
Without a license on the repository I'm not legally allowed to even build the project. @rileytestut

**Comment by rileytestut** [comment]
Added 👍 Licensed under AGPLv3, but with explicit permission to do whatever you want with it   https://github.com/rileytestut/AltStore/blob/master/README.md#licensing

**Comment by tbodt** [comment]
Would you be willing to make that more formal with a dual MIT and AGPL license?

**Comment by tbodt** [comment]
Also what dependencies do you have that are AGPL?
