### ISSUE TITLE
Error installing AltStore "Failed to write app data to device"

### ISSUE THREAD

**Issue by somethingwrng** [rileytestut/AltStore#240]
**Describe the bug**
When installing on Windows 10 AltServer gives the install error "Failed to write app data to device". Previously working on iPhone 11 with 13.5 now is no longer.

**To Reproduce**
1. Go to Altserver
2. Click on Install to iPhone
3. Altserver currently installing notification pop up.

**Expected behavior**
Altstore to install to iPhone without error.

**Screenshots**
![83363416-e6a44500-a35e-11ea-8015-973bc33676b9](https://user-images.githubusercontent.com/61095526/83366632-ebc0be80-a375-11ea-8706-1e6515db9d5e.png)

**Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Version: 10

**iPhone (please complete the following information):**
 - Device: IPhone 11
 - iOS: 13.5

**Additional context and logs**
Has not done this before and I have no clue why.

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing issues?

**Comment by somethingwrng** [comment]
No, I don’t believe so as I don’t even remember what the original email entailed, sorry you had to dig up this old thread! On Thu, Jan 19, 2023 at 11:01 AM shanegillio ***@***.***> wrote:
hi there! sorry for the lack of response - are you still experiencing issues?

**Comment by shanegillio** [comment]
No problem! Just going through and cleaning up all the old issues is all
