### ISSUE TITLE
Error -20203: The application you have selected does not exist.

### ISSUE THREAD

**Issue by tedog123456789** [rileytestut/AltStore#241]
This just happened today when I tried refreshing my apps. I had just deleted sideloaded spotify++ which may have had an effect. When I try to refresh my other two apps (cercube and altstore) it says that they do not exist even though they are on my device and function. I'm on the lasted version of altstore and I have restarted so I'm not sure why this is happening. I tried deleting them all and reinstalling altstore and it I get the same error when installing it from my computer. Now I can't get altstore back.

**Comment by Unsettling-Baboon** [comment]
i've got the same issue.

**Comment by tedog123456789** [comment]
> i've got the same issue.

@Unsettling-Baboon Had you just uninstalled a sideloaded app or did it just happen out of the blue?

**Comment by imohkir** [comment]
I'm getting the same error too. Was just refreshing my apps and tried to update my unc0ver version but they were loading endlessly so I thought I'd reinstall AltStore....then this happened.

**Comment by Unsettling-Baboon** [comment]
@tedog123456789 it just happened out of the blue. altstore was fine about a week ago, now I need to configure it again and it acted up with error -20203. not sure how to fix this, altstore's faq section on their site has no info on how to troubleshoot this.

**Comment by imohkir** [comment]
@Unsettling-Baboon @tedog123456789 looks like iCloud servers are down, so it's *probably* not an issue with our systems.  https://twitter.com/altstoreio/status/1267969039185309701?s=20

**Comment by marticztn** [comment]
@imohkir is right, iCloud is down, and Apple just released iOS 13.5.1 that patches out the unc0ver jailbreak, DO NOT upgrade to iOS 13.5.1 if you wanna jailbreak your devices.

**Comment by marticztn** [comment]
You can close this issue now, iCloud is back online
