### ISSUE TITLE
[Windows] rename Access is Denied in Temp for AltStore.app

### ISSUE THREAD

**Issue by 0xspade** [rileytestut/AltStore#243]
Hi,

I tried all the possible troubleshooting before I submitted a ticket here. Tried running as Admin in windows, Already tried changing the Temp folder properties > security blah blah blah without success and still, this error comes out. Anyway, I tried the version from 1.3b3 up to the latest and still the same.

![2020-06-04_12-43-08](https://user-images.githubusercontent.com/18681023/83716110-929ca780-a661-11ea-8c5d-67859fe82b9b.png)

**Comment by alexneri** [comment]
Reporting the same error for me, same troubleshooting steps

Thanks!

-A

**Comment by madankumar-p** [comment]
Try again after you disable you anti-virus program...

**Comment by marcocose** [comment]
try in wireless mode instead of wired.
that worked for me :D

**Comment by cam1170** [comment]
Just tried this, same error, weird.

**Comment by Boygamer1234** [comment]
It doesn’t work for me either

**Comment by Boygamer1234** [comment]
> Try again after you disable you anti-virus program...
> 
> Regards, MK

Ima try it

**Comment by davex2012** [comment]
Any fixed?

**Comment by nickcrv06** [comment]
If you are updating/Downloading any sideload apps, try not combining either wired or wifi together. I was having the same issue over and over and I realized that I was using both wired and wifi. After turning off wifi on my iPhone, then it worked fine.
