### ISSUE TITLE
Your account information was entered incorrectly -20101"

### ISSUE THREAD

**Issue by ysalam** [rileytestut/AltStore#247]
Has anyone found a solution to this problem?
Last week everything was fine and this week im getting the error. I cant seem to refresh the DS Emulator app that I have side loaded. Nor can i download any new apps.

Everything is as it should be: icloud is open on PC and logged in, iTunes is open as well and logged in. and I have my phone connected via cable to PC
Ive changed my password via iForgot and it didnt help.
Ive signed out and in of altstore and it didnt help

Was Running iOs 13.2.2, now running 13.5.1 on a iPhone 7+ and using a Windows 10 PC.

UPDATE: I completely uninstalled AltStore and reinstalled it. It signed me in normally, but when i try to download an app (delta for example) i still get the same error. The same is true for any apps that I try to side load.

Second UPDATE: ive updated my iOS to 13.5.1. Yet the issue remains.
Third UPDATE: If I stay logged out from the AltStore settings and click refresh apps (while logged out), it than asks me to sign in after which the apps refresh normally.

Final Update: So for whatever reason its working normally now. I can refresh the apps when im logged in via AltStore settings. The email displayed in AltStore is my updated gmail associated with my apple ID (Same one thats listed in Apple Dev Portal)

![image](https://user-images.githubusercontent.com/66516214/84148566-dfb8b900-aa67-11ea-8024-8f92444ffb34.png)

**Comment by Reiza1993** [comment]
Similare problem I have. 
Can You check in the settings tab is displayed Your correct Mail? 
What Mail Provider are You using? (EX: Gmail, Yahoo etc)

**Comment by ysalam** [comment]
Im using a Gmail account. 

And the email its displaying was the old email that my Apple ID was associated with. I updated it via Apple to a newer Gmail account.  When i signed out of AltStore and resigned in,  I typed the newer Gmail account and logged in normally, but the settings screen still showed the old email.

**Comment by Reiza1993** [comment]
Seems like AltStore gets the mail from AppleDev Portal. Can You go check It out. 

Just search on Google “AppleDev Portal” and log in, go in “Account” and Click Your name, check the mail displayed.

**Comment by ysalam** [comment]
AppleDev Portal is displaying my updated email that is associated with my Apple ID and not the old one that AltStore displays,

**Comment by Reiza1993** [comment]
I m not sure why, but for me is displayed my very old mail and the same as AltStore show up. 

This bug is a mystery! Just take my goddam mail 🤣

**Comment by Hackin420** [comment]
> Im using a Gmail account.
> 
> And the email its displaying was the old email that my Apple ID was associated with. I updated it via Apple to a newer Gmail account. When i signed out of AltStore and resigned in, I typed the newer Gmail account and logged in normally, but the settings screen still showed the old email.

that fixed my issue for some reason I cant use my gmail email because in the cloud settings it has my email changed to icloud.com I tried that and it worked

**Comment by Bmmaroni** [comment]
> Seems like AltStore gets the mail from AppleDev Portal. Can You go check It out.
> 
> Just search on Google “AppleDev Portal” and log in, go in “Account” and Click Your name, check the mail displayed.

Was having the same issue went to the "Apple Dev Portal" and then signed in made sure it was attached to my updated appleid acount. Then I went back into altstore clicked on settings and then signed out. I signed back in with my appleid as before and this solved my problem. Apps now successfully refresh! Thanks for the suggestions Reiza1993 and thanks Riley and the team for such an incredible emulator. Have been using it for years!

**Comment by doasu** [comment]
Can confirm to have "solved" this issue by replacing my regular email with my icloud email when logging into the AltStore app.
So myemail@icloud.com instead of myemail@protonmail.com

**Comment by FIocker** [comment]
None of the plentiful fixes actually fix this.

I suppose the only thing that fixes this is time if you recently changed your AppleID. Even when logging into the Apple Dev page it will show you your old appleid. Even when logging in with a newly created icloud mail.

And I assume AltStore uses that information somehow and hits a wall.

**Comment by daddecima** [comment]
**FIXED** just type the email in capital letters EXAMPLE@GMAIL.COM and whatever email you have.
