### ISSUE TITLE
Allow altdaemon to be used as altserver for non jailbreak device

### ISSUE THREAD

**Issue by CrCrate** [rileytestut/AltStore#254]
**Is your feature request related to a problem? Please describe.**
It would be helpful for people whiteout constant access to a computer

**Describe the solution you'd like**
Add a separate altserver app/tap in altstore and allow contention with other device via wifi sync

I have no idea if this is even possible but it would be amazing

**Comment by Assfugil** [comment]
It is technically possible by using a VPN that fakes a local network and then sync from that network (iOS blocks sync request from localhost). However, this requires a $99 developer account due to the extra entitlements needed (Can psychic paper bypass this? I don't know).

**Comment by Assfugil** [comment]
@rileytestut can psychic paper allows normal developer accounts to do the thing stated above?

**Comment by shanegillio** [comment]
closing just as a duplicate request
