### ISSUE TITLE
Unable to sight apps with the Cydia version installed

### ISSUE THREAD

**Issue by CoatlMictlan** [rileytestut/AltStore#257]
Here is what I get,

Running IOS 13.4.1 

![DAE95F42-ACE7-4D3B-8C7E-009431618AAC](https://user-images.githubusercontent.com/66653944/84207360-11308500-aa66-11ea-9110-443a84e37958.jpeg)

**Comment by brennanleblanc0** [comment]
Two things:

1: There is no official Cydia version of AltStore. The only official way is through https://altstore.io

2: That can happen when there are invalid permissions on `/var/MobileDevice/ProvisioningProfiles` Make sure the properties menu in Filza matches this one: ![image](https://user-images.githubusercontent.com/66458247/84578639-773a4680-ad9d-11ea-991f-3401fb652739.png)

**Comment by CoatlMictlan** [comment]
The permissions for  /var/MobileDevice/ProvisioningProfiles are all the
same, I have updated the application trough Cydia and now is working
properly, I do thank you for all of your help as well as the prompt
response! Thank you for all that you do!
