### ISSUE TITLE
Altdaemon Issue

### ISSUE THREAD

**Issue by ReeRee420** [rileytestut/AltStore#262]
Getting this issue when trying to refresh with altdaemon
![A9169859-D7E9-46C1-9D1D-D4CDC6EA2CFC](https://user-images.githubusercontent.com/66804336/84442959-923e7680-ac36-11ea-91e7-011e7405c763.png)

**Comment by JamesLutzke** [comment]
I have this issue as well.

**Comment by brennanleblanc0** [comment]
That is a currently known issue. It is not currently causing and seems mostly spontaneous. I would try this mini write-up I did: If you’re having the “Operation not permitted” error, try installing “NewTerm (iOS 10-13)", then install the package “file-cmds”, then try running the command `chflags nouchg /var/MobileDevice/ProvisioningProfiles`, then run `chflags nouchg /var/MobileDevice/ProvisioningProfiles/*`, then try refreshing with AltStore again.

**Comment by ReeRee420** [comment]
Those commands don’t do anything when I try them

**Comment by brennanleblanc0** [comment]
Do they give an error or does AltStore still give “Operation not permitted”?

**Comment by JamesLutzke** [comment]
The commands don’t give me any errors, but they don’t fix the signing issue either.

**Comment by ReeRee420** [comment]
No errors still can’t sign, have also done a respring to see if that was needed and still nothing

**Comment by ReeRee420** [comment]
I can’t even refresh when connected to my pc with a wire anymore so it’s definitely broke something

**Comment by ReeRee420** [comment]
As soon as I uninstall altdaemon it all starts working again 🤷‍♂️

**Comment by brennanleblanc0** [comment]
In the terminal, run `su`, then enter the password “alpine”, then run the command `rm -r /var/MobileDevice/ProvisioningProfiles/*`, then try AltStore again

**Comment by ReeRee420** [comment]
@brennanleblanc0 
![CC1B57BC-D6A8-49EE-B24C-DC20C7CE2538](https://user-images.githubusercontent.com/66804336/84607737-e485ce80-aea6-11ea-9850-453c4230b68c.png)

**Comment by brennanleblanc0** [comment]
Okay, back to the drawing board I guess 😅

**Comment by ReeRee420** [comment]
@rileytestut is this an issue you’re working on at all?

**Comment by brennanleblanc0** [comment]
We have found a solution to this issue. Try running a standard clean with iCleaner, reboot into a jailed state, then re-jailbreak. After that, run AltStore and see if it refreshes your apps with AltDaemon.

**Comment by JamesLutzke** [comment]
That fixed the issue for me!

**Comment by ReeRee420** [comment]
That didn’t work for me

**Comment by brennanleblanc0** [comment]
Is it still giving you the same error?

**Comment by ReeRee420** [comment]
Yes and yes

**Comment by brennanleblanc0** [comment]
What tweaks do you have installed, and where did you install AltStore from?

**Comment by ReeRee420** [comment]
Quite a few 😂 and I assume you mean altdaemon which was directly from altstore if you mean altstore then I used altserver on my pc to get it and then installed the beta from altstore itself

**Comment by ReeRee420** [comment]
Think I fixed it by rejailbreaking with unc0ver 5.2.0 I was using 5.0.0

**Comment by brennanleblanc0** [comment]
That's is actually very helpful information! Also, glad you could fix it! :smile:

**Comment by peterchrzan** [comment]
I had the same issue as well, rejailbroke with unc0ver 5.2 and then it worked fine

**Comment by r-plus** [comment]
Thanks to this issue, I have same error with unc0ver 5.0.0. 
It fixed after rejailbreaking with unc0ver 5.3.1.
