### ISSUE TITLE
This action could not be completed Try again (-22421)

### ISSUE THREAD

**Issue by Keya-arch** [rileytestut/AltStore#264]
![779C88B5-A620-4C65-918E-3F364C60A1CE](https://user-images.githubusercontent.com/62631680/84542386-599aad80-acc7-11ea-8a28-6aa131d46d73.png)

*Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Version: Windows 10

**iPhone (please complete the following information):**
 - Device: iPhone 6s
 - iOS: 13.5

**Comment by harshsingh7** [comment]
Try having correct time on both your PC/Mac and your iDevice, that fixed it for me

**Comment by goldtomato** [comment]
Had the same issue for a long time. Installing the latest versions of iTunes and iCloud and having them open while installing the ipa fixed it for me. This was on Windows.
