### ISSUE TITLE
Altstore Won't Download On Phone. AltServer Crashing On Windows 10

### ISSUE THREAD

**Issue by SnorlaxUsedGit** [rileytestut/AltStore#265]
I use iPhone 8, ios 13.5. So I reset my iPhone, which caused all my jailbreak stuff to crash. I deleted uncovered and Altstore. I tried re-installing altstore from my computer but it doesn't work. I click on Install AltStore > My iPhone > I put in my apple ID > I click ok to the "Altstore already installed on another device" prompt. It runs for a bit, then I hover over the altstore diamond icon, and then it disappears.  Ive already tried reinstalling iTunes, iCloud, AltServer, nothing works. When I restart my computer, AltStore does not open even though the checkmark is on.
**Things I have Tried:**

-  Reinstalling iTunes and iCloud from the right sources.
- Trying another Apple ID
- Reinstalling AltServer
- Using older versions of AltServer
- Trying the solution from this apple thread: https://discussions.apple.com/thread/7234775
- Switching iPhone Cables
- Deleting Apps to free up space

Please help, I miss my tweaks.

**Comment by Bart274** [comment]
I'm experiencing something similar. I noticed my AltServer is crashing all the time.
When I checked the event viewer I saw AltServer is crashing and it has something to do with ucrtbase.dll.
I already installed the Windows SDK, but it didn't fix it.

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-07-06T09:33:55.082535600Z" /> 
  <EventRecordID>5107</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>LAPTOP-8O8SNN9V</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>AltServer.exe</Data> 
  <Data>1.3.2.0</Data> 
  <Data>5ec97872</Data> 
  <Data>ucrtbase.dll</Data> 
  <Data>10.0.18362.815</Data> 
  <Data>bea5fce0</Data> 
  <Data>c0000409</Data> 
  <Data>0009e6eb</Data> 
  <Data>13c4</Data> 
  <Data>01d6537872003474</Data> 
  <Data>C:\Program Files (x86)\AltServer\AltServer.exe</Data> 
  <Data>C:\Windows\System32\ucrtbase.dll</Data> 
  <Data>9bf47fab-f962-4256-abc3-46f62c31dfbc</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by Bart274** [comment]
@SnorlaxUsedGit I managed to solve my issue by repairing everything related to Microsoft Visual Studio for C++ and rebooting my pc

**Comment by Bart274** [comment]
ok, that only solved my issue once :s it's crashing again :s

**Comment by UInt2048** [comment]
Did you install iCloud for Windows?

**Comment by Bart274** [comment]
@UInt2048 sorry for the late reply. I gave it another try after some try, the issue still is there. iCloud for Windows is installed.
