### ISSUE TITLE
Altstore and Delta crash on iPhone

### ISSUE THREAD

**Issue by brotherelric** [rileytestut/AltStore#267]
When I open the app, the screen gets fully white for 1 second and then goes back to the homescreen.

This has happened for the first time to me, and I've been using Delta and Altstore for a month now. I think it has to do with the iOS version (mentioned above)

I'm using an iPhone 6 with iOS 12.4.7

**Comment by brennanleblanc0** [comment]
Are you sure the certificate hasn’t expired? This can be checked by going to your certificates in the Settings app.

**Comment by brotherelric** [comment]
Do you mean going into the configuration profiles? There's nothing of Altstore there.

**Comment by brennanleblanc0** [comment]
That means the profile expired and you’ll need to reinstall AltStore. You don’t need to delete the apps though, they’re data is still there

**Comment by brotherelric** [comment]
Oh shoot, that's right. Sorry for nothing D:
