### ISSUE TITLE
Mail plugin doesn't support macOS 11.0 Beta

### ISSUE THREAD

**Issue by ygzok** [rileytestut/AltStore#271]
The Mail app which comes with latest macOS 11.0 Beta (20A4299v) doesn't support AltPlugin.mainbundle. This makes the app unusable.

1.Install the Mail plugin on AltServer app.
2.Open(restart if already open) Mail app & go to the Preferences
3.Click "Manage Plug-ins..."
4.Check "AltPlugin.mailbundle"
5.Click "Apply and Restart Mail"
6. Observe

![incompatible](https://user-images.githubusercontent.com/25876327/85423693-ac098300-b57f-11ea-8202-bfb24569c2ae.png)

 - OS: macOS 11.0 Beta (20A4299v)
 - Version: Big Sur

**Comment by lemons990** [comment]
afaik this should be an easy fix, if you know where the mail plugin is installed ( I don't) you can probably edit the package contents and change the mail version to 13

**Comment by ifrit05** [comment]
Add this to "/Library/Mail/Bundles/AltPlugin.mailbundle/Contents/info.plist" **after** the last </array> tag and **before** the last </dict> tag:


[fix.txt](https://github.com/rileytestut/AltStore/files/4823116/fix.txt)

(Sorry for the download, was the best way to keep the formatting)

**Comment by ygzok** [comment]
Thanks to @ifrit05, his solution solved the problem.

**Comment by catara** [comment]
I am getting this and don't know how to go around it
![Uploading image.png…]()

**Comment by KizzyCode** [comment]
@ygzok May I ask why the issue has been closed if the patch hasn't been merged into the sourcecode yet? I mean, even if I can apply it manually, this still needs to be fixed… Or do you use an off-site todo/issue system?

**Comment by lemons990** [comment]
go to security & privacy prefpane, and enable allow apps downloaded from anywhere
