### ISSUE TITLE
Altserver can’t find ICloud 

### ISSUE THREAD

**Issue by PlsHelpFast** [rileytestut/AltStore#275]
Hello I have a problem with AltServer when I start it it says it can’t find ICloud I didn’t download it from Microsoft store I downloaded it from the internet and it doesn’t work I’m on Windows 10

**Comment by noah978** [comment]
Do you have both iTunes and iCloud?

**Comment by Achilles76** [comment]
Got the same problem

**Comment by Achilles76** [comment]
Did you fix it at all
