### ISSUE TITLE
Add PPSSPP support

### ISSUE THREAD

**Issue by nighto** [rileytestut/AltStore#28]
It'd be nice to add [PPSSPP](https://github.com/hrydgard/ppsspp) to the list of apps available.

**Comment by nighto** [comment]
Could be done manually if user is a Patreon supporter, like #50.

**Comment by noah978** [comment]
The appearance of PPSSPP in AltStore is related to the AltStore Sources feature that is currently in the Patreon Beta. Adding AltStore Sources allows any app to appear and download through AltStore.

Closing this issue now.
