### ISSUE TITLE
[Question] If AltServer runs on Windows then why not on iOS?

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [rileytestut/AltStore#282]
I went thro’ the FAQ page hoping to find the reason why the mail plugin is required but I couldn’t. I understand that AltServer runs on Windows as well (I saw you have a Beta version listed on the website) and also wrote “ AltServer is significantly less complex than AltStore though, and for that reason consists of only a handful of file” on the README.

So why not create an iOS version (perhaps a jailbreak app) that acts as the server as well. That way there won’t be a need to have an external dependency on a mac to be running. You could even hook into the iOS Mail app (whatever the reason is for it) so it solves the Mail plugin too. Wouldn’t that be possible?

Also, another question: Can I install AltServer on Linux? I have a raspberry pi that runs a custom server 24x7 for me. I figured if there is a linux version I could at-least put AltServer in that (or is the source code for AltServer public? so that I could port it perhaps).

**Comment by Assfugil** [comment]
iOS books iTunes WiFi sync requests from `localhost`.

**Comment by Tiebe** [comment]
@Assfugil Can't that be changed if we make it a jailbreak module?

@SaifurRahmanMohsin For the last question, [only the Windows source code is available that I can see](https://github.com/rileytestut/AltServer-Windows)

**Comment by Assfugil** [comment]
well this already exist and is called AltDaemon

**Comment by noah978** [comment]
AltDaemon exists for this purpose. Closing this issue.
