### ISSUE TITLE
Altstore independent app

### ISSUE THREAD

**Issue by adinatsu** [rileytestut/AltStore#284]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hello 
I just wanna say that yu should try to make an altstore app that works on ios device itself without requiring a pc or laptop

**Comment by DumbGameMaker** [comment]
AltServer 1.4 has this. It's called AltDaemon. You need to jailbreak in order for it to work and as of now it is in beta to only available to patrons on patreon.

**Comment by noah978** [comment]
As previously stated, AltDaemon exists so I will be closing this issue.
