### ISSUE TITLE
AltServer Crashes when Sideloading Apps

### ISSUE THREAD

**Issue by DumbGameMaker** [rileytestut/AltStore#285]
**Describe the bug**
When I try to sideload an app I get the error "Could Not Connect to Altserver" and altserver crashes without an error. I tried reinstalling AltStore and AltServer, retrusting my phone with itunes, connecting with usb instead of Wi-Fi, switching Wi-Fi networks, deleting all the apps signed by AltStore, running altserver as admin, and refreshing all the apps from AltStore.

**To Reproduce**
1. install altserver on windows and altstore
2. connect with wifi or usb
3. sideload an app
4. error pops up

**Expected behavior**
App sideloads

**Screenshots**
![Could not connect to altserver](https://user-images.githubusercontent.com/61807031/86191169-33fd0900-bafb-11ea-8bb4-735d7ad3fcc5.png)
![Unknown error](https://user-images.githubusercontent.com/61807031/86191368-ba194f80-bafb-11ea-836b-d7aeba8bcba8.png)

**Desktop (please complete the following information if applicable):**
 - OS: Windows 10
 - Version: 1903 Build 18917.1000
EDIT: Windows Update being Windows Update windows forced me to upgrade to version 2004 build 19041.330. AltServer still doesn't work

**iPhone (please complete the following information):**
 - Device: iPhone11,8 (Xr)
 - iOS: 13.6

**Additional context and logs**
Add any error logs or any other context about the problem here.
Where do I find AltServer error logs?

**EDIT 1:** Updated title to clarify what's happening.

**Comment by Invisible40** [comment]
I've gotten the same error before a lot of times.  I've never been able to refresh AltStore on my iPhone 8 wirelessly from my Windows 10 PC, so I have to connect.

I was just getting your problem with installing unc0ver, but after a few times, I got it to work while connected (after trying both wirelessly and connected multiple times). I'm still gonna keep an eye on this thread because I get the same error time and time again.

**Comment by DumbGameMaker** [comment]
You guys need to implement error logging - it would help us troubleshoot errors and it would help you to squash bugs

**Comment by DumbGameMaker** [comment]
Closing issue. Bug seems to have been fixed. anyway, i think it was caused by a corrupted or broken .ipa because iOSAppSigner on mac threw an error with it too.
