### ISSUE TITLE
Y 

### ISSUE THREAD

**Issue by nto9090** [rileytestut/AltStore#286]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: [Mac or Windows]
 - Version: [e.g. Catalina]

**iPhone (please complete the following information):**
 - Device: [e.g. iPhone8]
 - iOS: [e.g. 13.1]

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by DumbGameMaker** [comment]
umm... what?

**Comment by flarely** [comment]
what?

**Comment by DumbGameMaker** [comment]
Does ‘Y’ mean ‘why?’ If so why what?

**Comment by HPaulson** [comment]
This is just the issue template. Please do not create spam issues with no content or reason for them. Please close this.

**Comment by IIWare** [comment]
@HPaulson He did this once but if spam he did this more than once.
