### ISSUE TITLE
macOS - Mail 13.0 macOS 11 Support

### ISSUE THREAD

**Issue by ovxrfl0w** [rileytestut/AltStore#289]
**Is your feature request related to a problem? Please describe.**
I have updated to macOS Big Sur Beta but the Mail plugin doesn't work with the Mail app anymore.

**Describe the solution you'd like**
Add support for Mail 13.0

**Comment by Kingrui380** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> I have updated to macOS Big Sur Beta but the Mail plugin doesn't work with the Mail app anymore.
> 
> 
> 
> **Describe the solution you'd like**
> 
> Add support for Mail 13.0

So why do you update?

**Comment by DumbGameMaker** [comment]
You can get the AltStore/AltServer source code [here](https://github.com/rileytestut/AltStore/tree/ios-14/ ) with fixes for iOS 14/MacOS Big Sur. If you have access to a mac then you can compile it to install on iOS 14.

**Comment by vmshaneeb** [comment]
@DumbGameMaker not working.... 

even tried #278 plist as well...

<img width="267" alt="Screen Shot 2020-07-19 at 2 33 35 AM" src="https://user-images.githubusercontent.com/12519511/87861906-6c5c6e00-c968-11ea-89aa-43686b4c1863.png">

**Comment by psharma04** [comment]
Still broken on (Dev) Beta 3

**Comment by jimmyshadow1** [comment]
The fix for this has been out since the 15th. You can download it from here: https://altstore.io/altserver/beta/, although this does not fix the new error introduced with iOS 14 beta 3. The fix for that was released in alpha today.

**Comment by noah978** [comment]
Please move all discourse related to this topic to #278
