### ISSUE TITLE
can't build using Xcode 10.3

### ISSUE THREAD

**Issue by Mr-se7enX** [rileytestut/AltStore#29]
I can't build using Xcode 10.3 on high sierra. Xcode runs normally and I built Retroarch with no problem. But for ALTstore I get this error:
Your development team, "XXX xxxx", does not support the Push Notifications capability.
I change the Bundle identifier to so whatever but no success. 
ALTserver I have no problem. I'm Using free Apple id. I used the "iOS-device-support-files" upto 13.1. I Connected the phone  7 plus on software version 13.1.1. Also I changed the minimum firmware versions for ALTStore and ALTServer to be compatible with my mac and iPhone. I would love to someone help me with this or at least build it for High Sierra 10.13.6

**Comment by Smethan** [comment]
If you go to the capabilities section, you can just remove the capability for push notifications, the app works fine without them

**Comment by Mr-se7enX** [comment]
thanks for the quick reply. that was helpful. I end up another error
![Screen Shot 2019-10-01 at 4 12 51 PM](https://user-images.githubusercontent.com/28022408/65997244-03eae180-e467-11e9-8068-a89c281c4503.png)

![Screen Shot 2019-10-01 at 4 15 53 PM](https://user-images.githubusercontent.com/28022408/65997255-08af9580-e467-11e9-89ec-1b1789293add.png)

**Comment by Mr-se7enX** [comment]
@Smethan I can't build it. Can you please  build it for me. Supports High Sierra 10.13.6

**Comment by burritosoftware** [comment]
Still having this issue :(

**Comment by rileytestut** [comment]
As of [this commit](https://github.com/rileytestut/AltStore/commit/d3623aa55e038bc47b9d3768d31b7a3e15c1df15), AltStore should now build + run fine with Xcode 11, so considering this issue closed.
