### ISSUE TITLE
unable to login error

### ISSUE THREAD

**Issue by dani-rulu** [rileytestut/AltStore#295]
i usually get "an unknown error occured" or "could not connect to altserver"

**Comment by DumbGameMaker** [comment]
i got the issue too, it ended up being my computer wasn't trusted by my phone.
1) install altstore
2) dismiss error
3) **MAKE SURE THAT YOUR PHONE IS TRUSTED**
   3a) if it is trusted, go to general > reset > reset privacy settings then trust the computer again
   3b) if it is not trusted, look for a popup saying "Trust this computer?" and click trust.
4) install altstore
