### ISSUE TITLE
Add the Ability to allow us to sign our own iPA’s like Spos Jailed and etc.

### ISSUE THREAD

**Issue by ghost** [rileytestut/AltStore#3]
It would be just like reprovision and remove my need of jailbreaking. Please make the possible!

**Comment by eni9889** [comment]
@sachangregory this is a beta feature that can be accessed by joining @rileytestut Patreon at https://www.patreon.com/rileytestut and then linking your patreon account inside the AltStore app then installing the beta version of AltStore

**Comment by git200iq** [comment]
> @sachangregory this is a beta feature that can be accessed by joining @rileytestut Patreon at https://www.patreon.com/rileytestut and then linking your patreon account inside the AltStore app then installing the beta version of AltStore

Is that essentially a subscription feature? Or are you saying we can donate once, get permanent access to the beta, and continue using our own IPAs in perpetuity, across updates, factory resets, uninstalls and reinstalls of the altstore, new phones, etc?

**Comment by noah978** [comment]
The ability to sign IPAs was released a short while ago. Closing this issue.
