### ISSUE TITLE
Add a guide to re-enable security features disabled on macOS Big Sur's AltServer Beta

### ISSUE THREAD

**Issue by jawshoeadan** [rileytestut/AltStore#300]
**Is your feature request related to a problem? Please describe.**
Yes, it would be extremely helpful to have a guide alongside the beta installation guide on the AltStore website that tells how to re-enable SIP and AMFI. With the security risks present when disabling these, being able to re-enable them is something that should be described on the AltStore website.

**Describe the solution you'd like**
Add a guide for how to re-enable SIP and AMFI on https://altstore.io/altserver/beta/

**Comment by DumbGameMaker** [comment]
Follow the current instructions in reverse but where there is 1 make it 0, yes turns to no, 0x01 turns to 0x00, etc
