### ISSUE TITLE
The name for this app is invalid

### ISSUE THREAD

**Issue by coder2z** [rileytestut/AltStore#310]
**Describe the bug**

# The name for this app is invalid

**Comment by yinqiangw** [comment]
I have the same problem

**Comment by KYLN24** [comment]
I have the same problem

**Comment by KYLN24** [comment]
+1

**Comment by ventusyu** [comment]
I have the same problem on iOS 1.4.8 with this app

**Comment by geron2020** [comment]
Brother, I found the solution
用Sideloadly打开APP，打开“Advanced Options”

Change app name 填入一个其他名字
Signing mode 选择 Export
点击start导出修改名字后的APP
再用altstore安装试试
Open the app with Sideloadly and open "Advanced Options".

Check "Change app name", Fill in the name you want（Must be changed）
”Signing mode“ select ”Export“
Click ”start“ to export the app after changing the name
Try to install it with altstore again

**Comment by testpassword** [comment]
> 实测已解决 Actual test, solved
> 
> 用Sideloadly打开APP，打开“Advanced Options”
> 
>     1. Change app name 填入一个其他名字
> 
>     2. Signing mode 选择 Export
> 
>     3. 点击start导出修改名字后的APP
> 
>     4. 再用altstore安装试试
> 
> 
> Open the app with Sideloadly and open "Advanced Options".
> 
>     1. Check "Change app name", Fill in the name you want（Must be changed）
> 
>     2. ”Signing mode“ select ”Export“
> 
>     3. Click ”start“ to export the app after changing the name
> 
>     4. Try to install it with altstore again

You're my hero, thanks!

**Comment by 0x1af2aec8f957** [comment]
This has always been a problem.
This problem should not be solved through external methods.

**Comment by arielherself** [comment]
A new tested method might be more convenient:

1. Open the `.ipa` file with an archive manager (you occasionally need to rename the extension to `.zip`);
2. Navigate to Payload -> xxxx(some name) -> Info.plist;
3. Open it with a text editor, and replace all the occurrences of the name of the app to an English name;
4. Install the app with AltStore/AltServer again.
