### ISSUE TITLE
App installation logs

### ISSUE THREAD

**Issue by ghost** [rileytestut/AltStore#314]
**Is your feature request related to a problem? Please describe.**
I'm adding a big app, say 100+ MB or so... it takes a lot of time using the AltServer on my Mac.. if the installation fails due to some reason.. the reason is just shown for a few secs..  n just disappears... if its a big app, we may not be looking at the phone all the time.. its easy to miss the those error msgs.

**Describe the solution you'd like**
An installation log similar to the refresh attempts section in the settings app would be a good idea... we may not be looking at the screen all the time, esp. if it's a big app. If we need to crosscheck the error msg.. either it should be connected via the Xcode or reinstall the app again to get the see these error msgs... possibly a share/export option as well for future bug reporting as well..

**Comment by shanegillio** [comment]
This should now be solved via the error log which will list any information related to app install attempts
