### ISSUE TITLE
Allow altservers to refresh different devices

### ISSUE THREAD

**Issue by DumbGameMaker** [rileytestut/AltStore#315]
**Is your feature request related to a problem? Please describe.**
If you have multiple devices with altstore and multiple altservers each device will only refresh with the one used to install altserver.

**Describe the solution you'd like**
The altserver should be able to refresh apps for different devices even if they are on different apple ids or a different altserver installed altstore on it. This would be an opt-in feature because if you are at a friends house or something the person who owns the router can see your internet traffic and as such your apple id and password.

**Comment by jimmyshadow1** [comment]
This is already how AltServer works. Any AltServer is used with any AltStore on any device, as long as the host PC is trusted by the device.

**Comment by DumbGameMaker** [comment]
Oh, I didn’t know that.
