### ISSUE TITLE
Failed to Verify Code Signature

### ISSUE THREAD

**Issue by yung40oz84** [rileytestut/AltStore#319]
**Issue**

Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.VEcQjb/extracted/AltStore.app : 0xe8008029 (The code signature version is no longer supported.)

**To Reproduce**

unsure

**Expected behavior**

I expected the app to install on my phone

**Desktop (please complete the following information if applicable):**
 - OS: Mac
 - Version: Big Sur

**iPhone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - iOS: 14 Beta 4

AltStore Version: 1.4b1

**Comment by jimmyshadow1** [comment]
AltServer beta, which is available to patrons, is the only way to install apps to iOS 14 beta 3 and 4 devices as of right now. Apple make some codesigning changes in those versions. This update will be public soon.

**Comment by yung40oz84** [comment]
I am actually on version 1.4b1 of AltStore which I thought was the beta and I am signed up for patron.

**Comment by yung40oz84** [comment]
I also followed the directions, booted into recovery and entered the commands into the terminal.

**Comment by jimmyshadow1** [comment]
I assume you mean AltServer 1.4b1. Are you getting that error when you try to launch AltServer or trying to install AltStore to your phone?

**Comment by yung40oz84** [comment]
I get the error when trying to install it on my phone. I goes through the entire process, I got the notification saying it’s installing and then about 5 seconds or so that error message pops up.

**Comment by jimmyshadow1** [comment]
Can you confirm that you're using AltServer 1.4b1 by clicking "Check for update" on AltServer and seeing what version it says it is. If you are I would recommend fully deleting it and redownloading the AltServer from the Patreon post. And make sure you move AltServer into the /Applications folder or it causes errors.

**Comment by DumbGameMaker** [comment]
yeah you probably have altserver [1.4b1](https://altserver.io/altserver/beta/) with the big sur fixes but since its not from the patreon it installs altstore 1.3 on your phone

**Comment by yung40oz84** [comment]
I am a patreon... what do u mean not from the patreon?

**Comment by DumbGameMaker** [comment]
If you downloaded it from https://altstore.io/altserver/beta then it won't install the altstore beta because that open beta was just so that people on the macos big sur beta can use altstore. you need to install it from the patreon page - i dont know where exactly you get it cuz im not a patron tho.

**Comment by noah978** [comment]
Please check for duplicates before opening a new issue (#94)

**Comment by parindaulat** [comment]
![image](https://user-images.githubusercontent.com/78580131/106989344-fd295880-6797-11eb-8009-19f1968c4d31.png)
I am gettign this eeror on windows
is there any way to solve this issue

**Comment by starmanya** [comment]
> ![image](https://user-images.githubusercontent.com/78580131/106989344-fd295880-6797-11eb-8009-19f1968c4d31.png)
> I am gettign this eeror on windows
> is there any way to solve this issue

me too, in my ipad....

**Comment by parindaulat** [comment]
I had to retroe my iphone and than I was bale to get the suceess

Try reinstall alt store on windows and also itunes

Major problem I faced with itunes

I habe reinstall again and again to get the sucees

**Comment by davex2012** [comment]
any solutions? Dev is not responding here anymore.
