### ISSUE TITLE
altstore not opening on ios 14 beta 4

### ISSUE THREAD

**Issue by CrCrate** [rileytestut/AltStore#320]
Here we go again...

**Describe the bug**
Altstore doesnt open on beta 4. Unlike on beta 3, non AS apps do open, but altstore itself doesnt.

**Expected behavior**
Altstore should open.

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Version: 10

**iPhone (please complete the following information):**
 - Device: iPhone XR
 - iOS: 14.0 developer beta 4

**Comment by jimmyshadow1** [comment]
This means AltStore got untrusted or expired. Just reinstall AltStore using AltServer.

**Comment by aboode13579** [comment]
does it work on beta 4 or 3 ???/

**Comment by CrCrate** [comment]
yes it works, but only one alpha/beta versions. public release is probably coming with public 1.4

**Comment by ImOldGregg** [comment]
Tried reinstall with Patreon altserver. It will install AltStore successfully but it will not install other apps it just crashes when it finishes loading them.￼ after a reboot App Store doesn't open at all. iOS 14 beta 4￼

**Comment by DumbGameMaker** [comment]
#302

**Comment by ImOldGregg** [comment]
This is an issue resulting in beta 4, not beta 3.

**Comment by DumbGameMaker** [comment]
I mean its pretty much the same issue because pb4 has the same codesigning changes as pb3

**Comment by aboode13579** [comment]
I know so did it get fixed yet or no without me paying for a premium account cause I’m young

**Comment by CrCrate** [comment]
@aboode13579 it’s out. if you’re already on beta 3/4 download the latest public altserver beta (1.3.3b2) from https://altstore.io/altserver/beta/ and install altstore with that.
