### ISSUE TITLE
AltServer sources: specify minimum supported iOS version

### ISSUE THREAD

**Issue by osy** [rileytestut/AltStore#321]
For UTM, I would like to distribute one version for iOS 11-13 and one for iOS 14+. Yes, I can merge it into one app but I want to phase out the “legacy” version and not have to wrap everything in availability macros. Long story short, it would be nice if the AltStore json repo supports specifying the minimum iOS version supported and hide any app AND updates whose min version is higher than the currently running one.

Additionally (I’m not sure if this is already implemented), when installing an IPA there should be a warning if the minimum version in the Info.plist is too high.

**Comment by jimmyshadow1** [comment]
This _is_ a planned feature for sources once it comes to public. You can check out that and more upcoming features [here.](https://trello.com/b/mMyuC0QS/altstore-roadmap)

**Comment by osy86** [comment]
Thanks, I wasn’t able to find anything on minimum version. Can you link to the specific card?

**Comment by jimmyshadow1** [comment]
https://trello.com/c/EIc4fxfK/44-minimum-and-maximum-ios-version-listings

**Comment by shanegillio** [comment]
Update! We have done this and the public release is coming soon :)
