### ISSUE TITLE
Can't connect two devices to the same Patreon account

### ISSUE THREAD

**Issue by hazae41** [rileytestut/AltStore#322]
**Describe the bug**
I can't connect both my iPhone and my iPad to my Patreon account

**To Reproduce**
When I connect AltStore on my iPhone to my Patreon account, then when I connect AltStore on my iPad with my patreon account, the AltStore on my iPhone is disconnected from my Patreon account

**Expected behavior**
Be able to connect multiple devices with the same Patreon account because that's what we expect when we pay for something

**Comment by DumbGameMaker** [comment]
I think it doesn't work as an anti-piracy measure so ppl can't share (or worse, sell) access to betas with other ppl that didn't pay for it
