### ISSUE TITLE
Go to

### ISSUE THREAD

**Issue by WanYiHo** [rileytestut/AltStore#323]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: [Mac or Windows]
 - Version: [e.g. Catalina]

**iPhone (please complete the following information):**
 - Device: [e.g. iPhone8]
 - iOS: [e.g. 13.1]

**Additional context and logs**
Add any error logs or any other context about the problem here.
Be link

**Comment by DumbGameMaker** [comment]
*sigh* Please stop posting empty bug reports.
