### ISSUE TITLE
I get this error when trying to install altstore on my device again (ios14 pb4)

### ISSUE THREAD

**Issue by ahsan-a** [rileytestut/AltStore#327]
**Describe the bug**
When i try and install altstore on windows 10 i seem to get an error. A screenshot is attatched.

**To Reproduce**
1. Go to 'install altstore on your device'
2. Type in your apple ID details
3. Hit enter

**Expected behavior**
Altstore to install on my device without an error message

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: Windows 
 - Version: 2004 version 19041.450

**iPhone (please complete the following information):**
 - Device: iPhone 7
 - iOS: iOS 14 Public Beta 4

**Additional context and logs**
Add any error logs or any other context about the problem here.
![Annotation 2020-08-17 103216](https://user-images.githubusercontent.com/50714675/90381303-16690c00-e075-11ea-9e64-e0acea768409.jpg)

**Comment by Duf1220** [comment]
The same here. iP XS, iOS 14, db4
[https://github.com/rileytestut/AltStore/issues/331](url)

**Comment by jimmyshadow1** [comment]
You need to use AltServer 1.3.3 beta 2 from https://AltStore.io/altserver/beta. Make sure you uninstall the previous AltServer before installing this one.

**Comment by Duf1220** [comment]
Thank you!

Odesláno z iPhonu

**Comment by ahsan-a** [comment]
> You need to use AltServer 1.3.3 beta 2 from https://AltStore.io/altserver/beta. Make sure you uninstall the previous AltServer before installing this one.

Thanl you! this worked fine.
