### ISSUE TITLE
website suggestion: minimal system requirements

### ISSUE THREAD

**Issue by mailinglists35** [rileytestut/AltStore#329]
on altserver download page for windows it should be noted that itunes is not a requirement and the minimal msi files to install from unpacking the itunes and icloud installers are:

bonjour

apple mobile device support

apple application compatibility support (32 is a must even on 64 bit platforms!)

icloud (only installed, does not need to be running!)

![image](https://user-images.githubusercontent.com/2054302/90452513-e0ac3d80-e0dd-11ea-82e7-9bc46ec408ab.png)

**Comment by UInt2048** [comment]
Thank you so much! This solved #265 for me.

**Comment by seppestas** [comment]
I can confirm iCLoud does not need to be running.
