### ISSUE TITLE
Unable to refresh or download anything.

### ISSUE THREAD

**Issue by harper-coding-stuff** [rileytestut/AltStore#33]
See title. On my laptop I am running the latest version of Windows 10, have AltServer installed and got the latest version of iTunes from Apple's website instead of the Microsoft Store. On my iPhone Xʀ, I am running iOS 13.1.2 and have AltStore installed. I tried downloading Delta but couldn't; the downloading bar freezes up when it's about 2/5 of the way finished or just grazing that spinning circle thing. Same thing happened with Delta Lite. Then I tried refreshing I checked the FAQ and tried to troubleshoot. I'm on my private home WiFi, AltServer is allowed public and private according to Windows Defender Firewall, my computer & iPhone trust each other _and_ I'm signed into my Apple ID on iTunes. Still doesn't work. I even tried making a hotspot on my phone and connecting to it on my laptop. The bar gets halfway finished and then stops and says, "AltServer could not find this device." Note it doesn't just freeze up like on my home WiFi. Maybe that's a good thing? I really don't know. I can reinstall AltStore in five days but for what? It's not like I can use it for anything besides looking cool. If anyone knows why this is happening please let me know.

**Comment by juhguu** [comment]
Same problem for me. I can't refresh my app certifcates.

**Comment by mrhuangbh** [comment]
me too

**Comment by mylxsw** [comment]
Connect your iphone with laptop using USB cable can solve the problem

**Comment by git200iq** [comment]
> Connect your iphone with laptop using USB cable can solve the problem

Doesn't that defeat the whole purpose of automated background refreshing?

**Comment by noah978** [comment]
This should be fixed on the latest versions of AltStore/AltServer. Closing this issue now.

**Comment by TheSmilez** [comment]
Lol, they stole your credentials.
