### ISSUE TITLE
Error 0xe8008029

### ISSUE THREAD

**Issue by Duf1220** [rileytestut/AltStore#331]
Hello, whats with that? Thanks
<img width="1680" alt="snap" src="https://user-images.githubusercontent.com/44775323/90540219-371e8800-e181-11ea-9e6e-f695cd3342fe.png">

**Comment by Duf1220** [comment]
Not work for me with iOS 14 db4

Thank you;)

**Comment by noah978** [comment]
Are you running macOS Big Sur? You need to use a special beta version of AltServer in that case: https://altstore.io/altserver/beta

**Comment by Duf1220** [comment]
I am running catalina.
But I will try to update my phone to iOS developer beta 5.

**Comment by Duf1220** [comment]
![image](https://user-images.githubusercontent.com/44775323/91034651-053c7400-e60e-11ea-9be8-188560eaa4e5.png)

Dobe! :)

**Comment by Heloop** [comment]
I have the same problem in windows 10
![image](https://user-images.githubusercontent.com/70140766/91034790-6d616a80-e5ba-11ea-9e36-c16c65bf0038.png)
