### ISSUE TITLE
Port scans

### ISSUE THREAD

**Issue by AcidEx** [rileytestut/AltStore#332]
Hi, my antivirus (bullguard) started constantly blocking port scan attempts, stating it was blocking an intrusion. I checked it wasn’t anything else i recently installed and the port scan seemed to come from my phone (even though I hadn’t installed alt server on it since I’m on beta 14) and a remote host that wasn’t on my network. Once I uninstalled altserver i stopped getting the intrusion alerts.

**Comment by noah978** [comment]
It is entirely possible that you could get false negatives from AltServer. I'd recommend setting a file exception in your antivirus for AltServer. It needs to access the ports to communicate with your iOS device over WiFi.
