### ISSUE TITLE
altstore

### ISSUE THREAD

**Issue by YASIRR989** [rileytestut/AltStore#334]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: [Mac or Windows]
 - Version: [e.g. Catalina]

**iPhone (please complete the following information):**
 - Device: [e.g. iPhone8]
 - iOS: [e.g. 13.1]

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by jimmyshadow1** [comment]
Please stop sending blank issues.
