### ISSUE TITLE
iOS 14 Beta 6 issue?

### ISSUE THREAD

**Issue by JuniorJailbreaker** [rileytestut/AltStore#340]
Not sure if the problem is on my end but I just installed the latest OTA iOS 14 Beta Update; iOS 14 Developer Beta 6. When trying to resign apps I get the error "Failed to refresh 2 apps. Could not find Altserver." I am running windows 10 and I am trying to sign/sideload apps on my iPhone 11 64GB. I tried restarting my PC and my iOS device, I used a different cable, and even deleted and reinstalled the AltServer I had on my computer. I am running version 1.3.3.2 of AltServer on my Windows 10 PC.

**Comment by noah978** [comment]
Probably just a beta issue.
