### ISSUE TITLE
You can get altstore 1.4 beta without patreon

### ISSUE THREAD

**Issue by DumbGameMaker** [rileytestut/AltStore#341]
# I deleted this to try and stop as many people as possible from using the AltStore beta w/o Patreon. 
## If you're Riley Testut or someone who can tell him about this, please message me on [Discord](https://www.google.com/search?q=my%20discord%20username%20is%20«»%236536)

**Comment by DumbGameMaker** [comment]
@rileytestut @noah978

**Comment by rursache** [comment]
you know that the history of the post is available, right?
to save others the time, all the details are here for months: https://www.reddit.com/r/AltStore/comments/fzvsyt/sources_for_altstore/

**Comment by Assfugil** [comment]
imo you can't pirate AltStore beta by just using it because of the AGPL-3.0. (You don't even need to agree to AGPL-3.0 to use it)

**Comment by Assfugil** [comment]
to pirate AltStore beta you will have to do something like distributing modified binaries without disclosing the source code.

**Comment by DumbGameMaker** [comment]
did you know that I'm dumb, it says so in my name
