### ISSUE TITLE
Open up the AltStore Discord 

### ISSUE THREAD

**Issue by DumbGameMaker** [rileytestut/AltStore#342]
**Is your feature request related to a problem? Please describe.**
Right now, to report a bug or submit a suggestion you need to go on the github, to get general support you need to use reddit, and if you have something very extremely urgent that you need to tell Riley Testut like right this instant (like #341) you're pretty much screwed. 

**Describe the solution you'd like**
Open up the AltStore Discord server to the public with a role for patrons or make a new discord server for non-patrons that might have less stuff in it (i. e. non-patron server might have #support, #general, #questions, etc. while the server for $5+ patrons might have #giveaways, #development-updates, etc.) or something.

**Comment by jimmyshadow1** [comment]
The Delta discord is public, and is the official support server for both AltStore and Delta.

**Comment by DumbGameMaker** [comment]
Ok
