### ISSUE TITLE
failed to verify code of signature

### ISSUE THREAD

**Issue by aboode13579** [rileytestut/AltStore#343]
i am on ios14 beta 5 altstore was working but it stopped today because i didnt refresh the apps thats ok but when i try to reinstall the altstore it shows me this message
![image](https://user-images.githubusercontent.com/68856095/91542629-d0d6f980-e926-11ea-9377-d408f95dbd50.png)

**Comment by jimmyshadow1** [comment]
Use AltServer 1.3.3 beta 2 from https://AltStore.io/AltServer/beta

**Comment by noah978** [comment]
Please check for duplicates before opening a new issue (#94)
