### ISSUE TITLE
Configurable time of day to refresh apps

### ISSUE THREAD

**Issue by lukefor** [rileytestut/AltStore#345]
**Is your feature request related to a problem? Please describe.**
The app currently picks seemingly random times of day to attempt to refresh apps. My instance of altserver is available roughly during the hours 01:00-08:00 (ie overnight), but AltStore rarely picks these times to attempt a refresh. I usually see it attempt to refresh during morning, afternoon and evening times, all outside these hours

**Describe the solution you'd like**
- Support a user configurable time to attempt to refresh daily (users will do a better job of predicting a given time that their PC will be on)
- Or, when apps are about to expire, try to refresh more often

**Comment by jimmyshadow1** [comment]
AltStore has no control over when it refreshes. That is 100% up to ios background refresh scheduling. And that is based on when you open the app throughout the day.

**Comment by lukefor** [comment]
> AltStore has no control over when it refreshes. That is 100% up to ios background refresh scheduling. And that is loosely based on when you open the app throughout the day.

That’s a shame, the time when i want it to refresh is also when my phone is on charge, surprised no background refreshing takes place during charging, ie no power cost. It seems illogical to not refresh during this time so assumed it was a conscious choice

**Comment by jimmyshadow1** [comment]
When it background refreshes is up to some hidden algorithm that Apple made. You can try to train it by opening AltStore every time you wish it would refresh.

**Comment by jawshoeadan** [comment]
Actually, this issue isn't a problem anymore due to the release of AltStore 1.4. With AltStore 1.4 you can add a Siri shortcut and with iOS 14, you can set it as a timed automation at whichever time you want. I guess this issue should be closed.

**Comment by lukefor** [comment]
Siri shortcuts in 1.4  are a perfect solution for this
