### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by System0x20** [rileytestut/AltStore#348]
Apple software is restrictive enough in general at least for me.
Please work on Windows version of AltServer and make it available for other Windows versions as well as Spyware 10

**Comment by DumbGameMaker** [comment]
Umm, windows version works? If you are having issues with windows 7, just upgrade to ~~windows 10~~ ~~ubuntu~~ umm, windows 10? (iCloud and iTunes is only on windows and Mac)
