### ISSUE TITLE
Devices can't locate Altserver when on Enterprise WiFi networks

### ISSUE THREAD

**Issue by v7rzlhb3xg** [rileytestut/AltStore#350]
**Describe the bug**
Having trouble getting Altstore on my iPad to discover Altserver on my MacBook while on Enterprise WiFi. I suspect it's because each device is assigned to a different VLAN and they're not able to see each other on the network.

**Desktop**
 - OS: macOS Catalina 

**iPad**
 - Device: iPad 7th Gen
 - iOS: 14b7

**Comment by LiterallyUnknown** [comment]
Does AltServer and AltStore recognize each other on the same network at all?

**Comment by v7rzlhb3xg** [comment]
I don’t believe so, at least not on an enterprise WPA2 network. It works normally on a personal WPA2 network, however.

**Comment by v7rzlhb3xg** [comment]
Still an issue.

**Comment by ronaldsb** [comment]
I'm having the same problem. Not sure if have to be related to Enterprise. Just can't see my devices while on WIFI.

**Comment by ronaldsb** [comment]
WPA2/WPA3 personal
