### ISSUE TITLE
Incompatible Plug-ins Disabled when trying to install plugin on MacOS 11 (Big sur beta)

### ISSUE THREAD

**Issue by LyhourChhen** [rileytestut/AltStore#351]
<p align="center">
  <img  src="https://i.ibb.co/qgyBm4G/Screen-Shot-2020-09-09-at-7-52-57-PM.png">
</p>

**Comment by jimmyshadow1** [comment]
Please look at other issues before submitting a new one as this has been answered many times. Follow the instructions at https://AltStore.io/altserver/beta
