### ISSUE TITLE
Cannot find server. 

### ISSUE THREAD

**Issue by Septembersrain** [rileytestut/AltStore#359]
Cannot find server on beta nor on original. Updated to Beta 7 and Altdaemon won't work with it. Installed original, won't connect either. iOS 13.3. iPhone 11 Pro Max.

**Comment by Septembersrain** [comment]
Finally fixed it. Had to remove everything and reinstall original AltStore then update to Beta, then reinstall AltDaemon.

**Comment by Septembersrain** [comment]
It stopped again. 
![Uploading B447F282-7D68-4BD1-83CE-3F52B63AEC57.png…]()

**Comment by Assfugil** [comment]
> Uploading B447F282-7D68-4BD1-83CE-3F52B63AEC57.png…
broken image

**Comment by Septembersrain** [comment]
https://imgur.com/a/QhON8Gy

**Comment by Septembersrain** [comment]
Had to reinstall AltDaemon through Filza rather than uninstall and reinstall through Cydia. Beta 7 is finally working again. Sorry for the hassle!

**Comment by Assfugil** [comment]
still doesn't work for me
