### ISSUE TITLE
(Request) port it to linux please

### ISSUE THREAD

**Issue by minhajsixybte** [rileytestut/AltStore#360]
Saw this app on youtube, you guys have done amazing work.
Unfortunately I can’t install it on my ipad air 3 because I use GNU/Linux on my machine. If you guys can port it to Linux, it would help a lot of people I’m sure. 

I will have to borrow a friend’s laptop sometime soon to try this. However, this is an amazing project guys,

**Comment by rylyguy** [comment]
I don’t believe that’s currently possible because altserver uses iTunes which isn’t on linux

**Comment by Assfugil** [comment]
Duplicate of #6

**Comment by minhajsixybte** [comment]
okay! understood. closing the issue. thanks everyone
