### ISSUE TITLE
You do not have permission to open the application “AltServer.app” Big Sur Beta 8

### ISSUE THREAD

**Issue by nyandrianinamamy** [rileytestut/AltStore#362]
Cannot open Altserver on macOS Big Sur Beta 8.

**To Reproduce**
1. Open 'AltServer.app'

**Screenshots**
<img width="276" alt="Screenshot 2020-09-28 at 10 56 34" src="https://user-images.githubusercontent.com/32381091/94411918-71fcde00-0179-11eb-9979-9682206af2c0.png">

**Desktop (please complete the following information if applicable):**
 - OS: Mac
 - Version: Big Sur Beta 8

**Additional context and logs**
Steps listed on altserver beta already done.

**Comment by nyandrianinamamy** [comment]
It looks like updating a beta removes all of the previous step, so I needed to deactivate SIP and AMFI again after updating macOS then AltServer can be launched again

**Comment by kakapunk71** [comment]
I upgraded to Big Sur  and I  get the popup window above,  I  tried changing permissions but it did not work.  Any help is appreciated. Thanks in advance.

**Comment by austinarchibald** [comment]
Having the same issue with with my M1 MBA in Big Sur. Tried `chmod -R` `chmod +x` `xattr -rd` and `upx -d` on the app itself and the `x.app/Contents/MacOS/x` executable as well.

**Comment by AlexCrescentini** [comment]
> I upgraded to Big Sur and I get the popup window above, I tried changing permissions but it did not work. Any help is appreciated. Thanks in advance.

Did you solve it?

**Comment by Yesca47m** [comment]
Open terminal | Command+Space and type Terminal and press enter/return key.

Paste following code

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null

Wait for the command to finish. After completion run following code :

brew install upx

now run this command:

sudo upx -d /Applications/my_app.app/Contents/MacOS/my_app

Then run the application normally.

**Comment by Yesca47m** [comment]
> Cannot open Altserver on macOS Big Sur Beta 8.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Open 'AltServer.app'
> 
> **Screenshots**
> <img alt="Screenshot 2020-09-28 at 10 56 34" width="276" src="https://user-images.githubusercontent.com/32381091/94411918-71fcde00-0179-11eb-9979-9682206af2c0.png">
> 
> **Desktop (please complete the following information if applicable):**
> 
> * OS: Mac
> * Version: Big Sur Beta 8
> 
> **Additional context and logs**
> Steps listed on altserver beta already done.

Open terminal | Command+Space and type Terminal and press enter/return key.

Paste following code

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null

Wait for the command to finish. After completion run following code :

brew install upx

now run this command:

sudo upx -d /Applications/my_app.app/Contents/MacOS/my_app

Then run the application normally.

**Comment by Yesca47m** [comment]
> > I upgraded to Big Sur and I get the popup window above, I tried changing permissions but it did not work. Any help is appreciated. Thanks in advance.
> 
> Did you solve it?

Open terminal | Command+Space and type Terminal and press enter/return key.

Paste following code

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null

Wait for the command to finish. After completion run following code :

brew install upx

now run this command:

sudo upx -d /Applications/my_app.app/Contents/MacOS/my_app

Then run the application normally.

**Comment by CelticWebSolutions** [comment]
The above fix didn't work for me UPX says not packed by UPX.  Any further tips?  This has only just happened when I updated to the latest Beta of Big Sur 11.2

**Comment by CelticWebSolutions** [comment]
What I tried was 

`sudo upx -d /Applications/AltServer.app/Contents/MacOS/AltServer`

**Comment by sherief055-aa** [comment]
This video describes the procedure to solve this problem:-
[https://youtu.be/dmNhKjHuhH0](https://youtu.be/dmNhKjHuhH0)
[YOUTUBE VIDEO TO DESCRIBE THE PROCEDURE
](https://youtu.be/dmNhKjHuhH0)(SOLVED) "you do not have permission to open the application" only 3 steps to open apps on Big Sur

**Comment by davidhenley** [comment]
@sherief055-aa you're the man
