### ISSUE TITLE
SSL common name does not match

### ISSUE THREAD

**Issue by KNO3-dev** [rileytestut/AltStore#364]
I was trying to reinstall Altstore on my iPhone 11 after i forgot to refresh it and then the following error appeared  

"SSL Error:WINHTTP_CALLBACK_STATUS_FLAG_CERT_CN_INVALID SSL common name does not match"

<img width="296" alt="Cattura" src="https://user-images.githubusercontent.com/61994658/94737296-e9935e80-036d-11eb-9814-f8f89f71a440.PNG">

I'm trying to install Altstore on an iPhone 11 running iOS 14.0 (Not Jailbroken) via Altserver on Windows 10 Home 64 bit running the latest version, i also have the latest version of iTunes and iCloud (both not downloaded via Microsoft store).

I already tried reinstalling every software, adding exeptions on firewall and deleting the "adi" folder from the iTunes path.

**Comment by CHN-STUDENT** [comment]
i get same issue too.
By the way, it is so diffcult to download ipa cross GFW, could you tell me how to install it from other ways? Or could you add the function which installs from local? 

@rileytestut

**Comment by CHN-STUDENT** [comment]
Hi everyone, i get new ways to download ipas.
If your system installed with python, you can use `python -m http.server 9900` as a local web server.
Then use altServer patcher to choose your web server.
Just like this:
![image](https://user-images.githubusercontent.com/21209416/95169464-7d897e00-07e5-11eb-9c65-24395fc60d22.png)
![image](https://user-images.githubusercontent.com/21209416/95169433-72cee900-07e5-11eb-90c0-1eb10f02d5c7.png)

**Comment by vOuii** [comment]
Solution FOUND! If you have Malwarebytes, or any antivirus software. add f000.backblazeb2.com to the allow/exclusion list! thank me later!
