### ISSUE TITLE
How is third-party apps coming along?

### ISSUE THREAD

**Issue by BenSova** [rileytestut/AltStore#365]
This is pretty off topic for being in a tab called "Issues", but I have no idea how to contact you and ask this, so I'm asking this here.

I was wondering when third party apps would be supported, because I was hoping to get my app on AltStore. 

I am working on a custom icon themer app, so you can add custom icons to your Home Screen without going through shortcuts or anything. It is still in development, but I thought it would be good to ask so I have time to get a response.

**Comment by CrCrate** [comment]
if you have the altstore beta you can add a source containing your app, this will likely become public in the 1.4 versions. until then I suggest you share the ipa via your website or redirect non beta users [here](https://altsource.by.lao.sb/browse/).

**Comment by BenSova** [comment]
Any prediction on when 1.4 might become available to the public?

**Comment by BenSova** [comment]
I ran into a problem while trying to create a source. The source didn't show any errors to AltStore or AltSource Browse, but AltSource Browse showed nothing, just the footer on a green background and AltStore got the name, author (me), that it is beta, it's tint color, subtitle, description and release notes, but none of the images, like the app icon and screenshots. 
On top of that, the app only shows up if I have I hit the search bar at least once and will sometimes disappear after that and when I try to install it it goes for a little bit then AltStore crashes. It doesn't even create an App ID.
