### ISSUE TITLE
altstore/apps not working on ios 14.2 beta

### ISSUE THREAD

**Issue by CrCrate** [rileytestut/AltStore#366]
ever since I updated apps are broken, even after reinstalling.

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - windows
- 10

**iPhone (please complete the following information):**
 - iPhone xr, 14.2 developer beta

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by CrCrate** [comment]
> ever since I updated apps are broken, even after reinstalling. They crash when trying to open them, even via shortcuts. issue persists after reboot.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information if applicable):**
>  - windows
> - 10
> 
> **iPhone (please complete the following information):**
>  - iPhone xr, 14.2 developer beta
> 
> **Additional context and logs**
> Add any error logs or any other context about the problem here.

**Comment by MisutaaUrufu** [comment]
I'm having the same issue. iPhone Xʀ (coral), 14.2 Beta.

It works on my iPad Pro 9.7" running 14.2 Beta, so it's not the OS alone. Just a combination of the device & OS version.

Computer is running macOS Big Sur, here.

**Comment by kobaro97** [comment]
I have kinda the same issue. Using Windows 10 Altserver 1.4.0.0
iPhone Xs iOS 14.2 Beta 3.
Altstore installs on my iPhone, I go to profiles and Trust it. But when I try to start the app, it crashes and closes without even opening at first place. I have tried to reinstall Altserver on my windows and iPhone, but no luck. 
I also can't find anything about it online!

**Comment by CrCrate** [comment]
> I have kinda the same issue. Using Windows 10 Altserver 1.4.0.0
> iPhone Xs iOS 14.2 Beta 3.
> Altstore installs on my iPhone, I go to profiles and Trust it. But when I try to start the app, it crashes and closes without even opening at first place. I have tried to reinstall Altserver on my windows and iPhone, but no luck.
> I also can't find anything about it online!

install the app, trust it in settings, reboot your phone and open altstore via shortcuts. once altstore is installed you can refresh the app instead of rebooting

**Comment by kobaro97** [comment]
I have now tried what you said, but still the same issue...
I have also tried to make a shortcut for the app itself but got the same error as in the pic.
![2020-10-22 20_10_14-Films en tv](https://user-images.githubusercontent.com/73277252/96912489-c35f6b00-14a2-11eb-8873-97ce6068769d.png)
![2020-10-22 20_10_34-Films en tv](https://user-images.githubusercontent.com/73277252/96912496-c3f80180-14a2-11eb-9d70-f14e41bbfd50.png)
![2020-10-22 20_11_11-Films en tv](https://user-images.githubusercontent.com/73277252/96912499-c4909800-14a2-11eb-820c-068e929e9a5e.png)

**Comment by deltaryz** [comment]
Same issue here. AltServer 1.4.0.0 on Windows 10 Pro, using an Apple Developer account.
App “successfully” installs but immediately crashes upon opening. Shortcuts fail after a timeout.
Immediately after updating to the beta (from 14.1), all of my previously installed apps broke the same way - instant crash on launch.

![IMG_0776](https://user-images.githubusercontent.com/4731368/97092064-4816ca00-1606-11eb-8564-d6cf60baa765.png)


![IMG_0777](https://user-images.githubusercontent.com/4731368/97092061-43521600-1606-11eb-9d38-9481e7decfc2.jpeg)

**Comment by infinytum** [comment]
Even on the release build of 14.2 the altstore app is immediately crashing when you open it. Just tested.

**Comment by MisutaaUrufu** [comment]
> Here is a crash log from AltStore. Same as #385 
> 
> [AltStore-2020-10-22-071736.txt](https://github.com/rileytestut/AltStore/files/5433698/AltStore-2020-10-22-071736.txt)
That actually mentions the thread crashing on keychain access. Does AltStore try to access the device' keychain on launch? Between that and the crash being due to a "kernel protection failure", it sounds like AltStore is accessing something it possibly shouldn't?

---- 

I'm still having crashes. As others, launching from Shortcuts has no effect. Running 14.2 (18B91).

Error Log appears to match @deltaryz's: https://pastebin.com/4d3qv50g

**Comment by MisutaaUrufu** [comment]
Update: Building AltStore from XCode 12.0.1, _without push notifications entitlement_ (free developer accounts cannot use Push Notifications), _and a modified bundle ID_ (XCode cannot use "existing" bundle IDs associated with another Apple ID, a common problem with open source software, requiring an altered name), results in successful launch. However, Alt Store reports that it cannot log in, either reporting a generic login failure, or reporting a failure to communicate with the mail plugin, when attempting to install an app.
