### ISSUE TITLE
Altstore

### ISSUE THREAD

**Issue by 122oa** [rileytestut/AltStore#367]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: [Mac or Windows]
 - Version: [e.g. Catalina]

**iPhone (please complete the following information):**
 - Device: [e.g. iPhone8]
 - iOS: [e.g. 13.1]

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by ConfolidelBiins** [comment]
ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ ᴺᴵᴳᴳᴬ

**Comment by MyCatCondo** [comment]
Ugh

**Comment by IIWare** [comment]
please someone delete this issue...
