### ISSUE TITLE
High Sierra 10.13.6

### ISSUE THREAD

**Issue by romanmorozov81** [rileytestut/AltStore#369]
Hi, can you make it run on Mac High Sierra 10.13.6 ?

**Comment by drmnx1** [comment]
+1

**Comment by BenSova** [comment]
Quoting the README:

> Why iOS 12.2+ and macOS 10.14.4+? Doing so allows me to distribute all AltStore apps without embedding Swift libraries inside them. This helps me afford bandwidth costs by reducing download sizes by roughly 30%, but also noticeably improves how long it takes to install/refresh apps with AltStore. If you're compiling AltStore and/or AltServer yourself, however, you should be able to lower their deployment targets to iOS 12.0 and macOS 10.14.0, respectively, without any issues.

**Comment by xxdevildeckerxx** [comment]
I have iOS High Sierra 10.13.6 in my Macbook Air, and I was wondering if some expert knows how to download Altstore to my device? I thank you in advance for your help! :)

**Comment by DavidCohty** [comment]
we re still waiting for a solution for users who doesn't want to go for catalina .

**Comment by BenSova** [comment]
1. Cydia Impactor
2. Sideloady
3. I'm sure there's others.

**Comment by DavidCohty** [comment]
> 1. Cydia Impactor
> 
> 2. Sideloady
> 
> 3. I'm sure there's others.

1. Cydia impactar require a developer     Account 
2. Sidelody work better for jailbreak

**Comment by BenSova** [comment]
Well, if you really don't want to go to Catalina (or Big Sur, the latest version of macOS that I haven't had a single problem with on my Mac that doesn't even support it), then go to Mojave, it's basically High Sierra with Dark Mode.

**Comment by DavidCohty** [comment]
> Well, if you really don't want to go to Catalina (or Big Sur, the latest version of macOS that I haven't had a single problem with on my Mac that doesn't even support it), then go to Mojave, it's basically High Sierra with Dark Mode.

I never stated that I don't want to get catalina , however I have. a early 2011 MPRO , and im not yet convinced to get a patcher .

**Comment by romanmorozov81** [comment]
> Well, if you really don't want to go to Catalina (or Big Sur, the latest version of macOS that I haven't had a single problem with on my Mac that doesn't even support it), then go to Mojave, it's basically High Sierra with Dark Mode.

The thing is that Mojave works slower than High Sierra, it's not only Dark Mode. I've tested on my Mac Book Pro 2014. So don't want to upgrade also.

**Comment by DavidCohty** [comment]
> > Well, if you really don't want to go to Catalina (or Big Sur, the latest version of macOS that I haven't had a single problem with on my Mac that doesn't even support it), then go to Mojave, it's basically High Sierra with Dark Mode.
> 
> The thing is that Mojave works slower than High Sierra, it's not only Dark Mode. I've tested on my Mac Book Pro 2014. So don't want to upgrade also.

if you have a MBP2014 you will still be able to download catalina from apple .

**Comment by tcookj66** [comment]
I can't believe nobody has answered the question and closed this issue... Does any Dev have an answer? Ive googled the crap out of this. Is there a way to run this on High Sierra?
