### ISSUE TITLE
Build is successful, but "install claimed to have succeeded"

### ISSUE THREAD

**Issue by burritosoftware** [rileytestut/AltStore#37]
Hey again. AltStore has been updated to work on Xcode 11, however I can't compile it due to Push Notifications not being present on a free Dev account. So, I removed that capability, but AltStore won't install, with an "Install claimed to have succeeded" error and no app is installed to the device. I already tried cleaning the build folder and purging the Derived Data, but nothing is working. Any solution?

**Comment by burritosoftware** [comment]
@rileytestut Suggestion to maybe add build instructions for free developer accounts?

**Comment by Smethan** [comment]
did you set your device UDID in the info.plist? If you don't set that, the apps won't install to your device

**Comment by burritosoftware** [comment]
@Smethan yup, still no show. I'm not talking about AltStore installing apps for me, I'm having trouble installing the actual AltStore app.

**Comment by burritosoftware** [comment]
I should also comment that I am having the same issue as https://github.com/rileytestut/AltStore/issues/29

**Comment by noah978** [comment]
Similar to #29, the issue should be fixed with this [commit](https://github.com/rileytestut/AltStore/commit/25ff5b566f7b90a3b2e9de872b80ff5af6b9153e). Closing the issue now.
