### ISSUE TITLE
WinHttpSendRequest: 12007: The server name or address could not be resolved

### ISSUE THREAD

**Issue by quyleanh** [rileytestut/AltStore#371]
**Describe the bug**
Cannot connect through proxy network in Windows 10

**To Reproduce**
1. Click AltStore notification icon in Windows 10
2. Click on Install Alstore
3. Select Apple Device
4. Enter Apple ID and Password
5. See error

**Expected behavior**
AltStore is installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/9365035/95414482-3243ac80-0958-11eb-80f3-7d615061b983.png)

**Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Version: 10 Buil 2004 Build 19041.546

**iPhone (please complete the following information):**
 - Device: iPhone6
 - iOS: 12.4.8

**Additional context and logs**
No log

**Comment by quyleanh** [comment]
By the way, I cannot update AltStore through proxy network as well. 
When I check, it shows the new version available dialog

![image](https://user-images.githubusercontent.com/9365035/95414759-c6ae0f00-0958-11eb-8abf-96de30127285.png)

But when I click Install update, the Update Error! is appeared.

![image](https://user-images.githubusercontent.com/9365035/95414779-df1e2980-0958-11eb-8c8d-4f5382e8a9ab.png)

**Comment by Titanius** [comment]
_How can I configure the proxy for the WinHTTP Services?_
There is a simple way to do that, by issuing the following command on a command prompt with elevated privileges:

Windows + R 
**cmd**

**netsh winhttp set proxy <server IP or FQDN>:<Port> "<Exclusion list, separated by ";">"**

As an example, this command will configure the address proxy.contoso.com in port 8080, with the exclusion of "localhost" and "contoso.com" domain:

**netsh winhttp set proxy proxy.contoso.com:8080 "localhost;*.contoso.com"**

You can also import the settings from the Internet Settings Control Panel (Browser), but bear in mind the WinHTTP Services do not support the use of Scripts (like PAC or DAT files). For such behavior you can use following command:

**netsh winhttp import proxy source=ie**

The last part would be to check and ensure your proxy settings got properly applied to the WinHTTP Services. You can achieve that by issuing the following command:

**netsh winhttp show proxy**

If you have everything properly set up and want to get back to direct connection, you'll need to issue the following command:

**netsh winhttp reset proxy**

**Comment by gpavelski** [comment]
I had a similar error while trying to enable JIT on the DolphiniOS through the AltServer.
The issue disappeared after I followed this tutorial: 
https://www.jilaxzone.com/2021/07/30/dolphinios-waiting-for-jit-workaround-fix-ios-14-4-ios-15-and-up/

**Comment by im-Kalix** [comment]
> 我在尝试通过 AltServer 在 DolphiniiOS 上启用 JIT 时遇到了类似的错误。 在我按照本教程进行操作后，问题消失了： [https ://www.jilaxzone.com/2021/07/30/dolphinios-waiting-for-jit-workaround-fix-ios-14-4-ios-15-and-up /](https://www.jilaxzone.com/2021/07/30/dolphinios-waiting-for-jit-workaround-fix-ios-14-4-ios-15-and-up/)

It's helpful, thanks a lot!
