### ISSUE TITLE
Altstore Alpha Download 404 Error

### ISSUE THREAD

**Issue by sonny-dev** [rileytestut/AltStore#372]
**AltStore ALPHA Download 404 Error**
Downloading AltStore ALPHA in Zebra throws 404 Error. 

**To Reproduce**
1. Find and Install AltStore ALPHA on Zebra.app 
2. Download attempt fails
3. Throws Error 404 indicating server request failed. 

**iPhone (please complete the following information):**
 - Device: A12 iPhone XS Max
 - iOS: 13.5

**Additional context and logs**
I'm assuming this error is known already, and is potentially just a server hosting issue but I wanted to leave this here in case others had the issue, so they can see it's being addressed.

**Comment by jimmyshadow1** [comment]
AltStore is, and never will be, available through installing via zebra, Cydia, etc. What you're installing is a pirated version of AltStore.

**Comment by chrismonster13** [comment]
Yea you should probably just close and delete this cuz this is embarrassing. AltStore is only available one way, and that is by following the directions on their official website.

**Comment by sonny-dev** [comment]
Oh wtf awkward... Thanks for letting me know!!!

Regards, 

Michael

**Comment by sonny-dev** [comment]
This is where I’ve installed it from..




Regards, 

Michael
