### ISSUE TITLE
AltStore Crashing When Side-loading IPA/Downloading Third-party App

### ISSUE THREAD

**Issue by BenSova** [rileytestut/AltStore#375]
**Describe the bug**
I'm working on an app for AltStore and no matter what I do AltStore crashes when side-loading the IPA or downloading it from my AtSource. Other third party apps work fine though...

**To Reproduce**
1. Add source https://bensova.github.io/altstore/apps.json
2. Find Project ICNS Beta in the browse tab (you'll have to click on the search bar to show beta apps)
3. Try downloading the app.
4. Observe the crashing

You could also use the IPA that you can download from the AltSource Browse website, since that crashes AltStore too.

**Expected behavior**
AltStore installing/sideloading the app like normal.

**Desktop (please complete the following information if applicable):**
 - OS: Mac
 - Version: Big Sur Beta 9

**iPhone (please complete the following information):**
 - Device: iPhone 6s
 - iOS: 14.2 Beta 2

**Comment by jimmyshadow1** [comment]
I am experiencing the crash as well. Is this project open source? I can try compiling it myself to see if its an issue with the app itself. I've never seen an AltStore crash like this before.

**Comment by BenSova** [comment]
@jimmyshadow1 I was on the edge about making it open source or not, but I uploaded it to GitHub anyway, for the time being. 
[Here it is.](https://github.com/BenSova/ProjectICNS)

**Comment by telepati** [comment]
It's just crashing I tried 50 ipa from iPhoneCake all apps just crashing or some of them installed but this time crashing when you try to open. I overwhelmed and delete the AltStore from my iPhone.

**Comment by BenSova** [comment]
Well, it's now working for me. I changed the name of the folder I compressed, and in turn the resulting ipa file, from v1_0b4 to Payload and everything worked fine. It makes no sense, but at least I figured out something that works.
