### ISSUE TITLE
Install Error "Appex bundle at... does not have expected identifier prefix..."

### ISSUE THREAD

**Issue by Dansco** [rileytestut/AltStore#378]
**Describe the bug**
Installed AltStore on my iPad Air 2 on iOS 14.0.1 yesterday with AltStore v1.3.3 (as I can't update to v1.4 due to been on a work latptop) and it worked. Then I tried to install Cercube and got error (-22411) so removed Altstore from my iPad. Then used same Apple ID and get the above error. 

**To Reproduce**
1. Open AltStore
2. Install AltStore on device
3. Input Apple ID and Password 
4. Click Install
5. AltStore already installed on another device
6. Click OK
7. Installing AltStore on iPad popup
8. Popup "Installation Failed" (see screenshot for full error)

**Expected behavior**
AltStore application to install on iPad to use. 

**Screenshots**
![cjohbfoqc0s51 1](https://user-images.githubusercontent.com/6923435/95605951-9302e000-0a51-11eb-828c-e9b2c727ed86.jpg)

**Desktop (please complete the following information if applicable):**
 - OS: Windows 10 Pro 
 - Version: 19041.508

**iPhone (please complete the following information):**
 - Device: iPad Air 2
 - iOS: 14.0.1

**Additional context and logs**
Other users having this issue on Reddit
https://www.reddit.com/r/AltStore/comments/j7tjtr/anyone_had_this_problem/

**Comment by bxnjamin** [comment]
I had the same problem. I reinstalled Altserver and that did the job for me.

**Comment by Dansco** [comment]
That is nice to know is how to fix it. Shame it's a work laptop so will have to see if I can get help from them. Cheers

**Comment by bxnjamin** [comment]
Ahhh, didn't fully read the post. Thats too bad, hope you get it sorted out.

**Comment by Dansco** [comment]
I’m going to see if I can use another computer to manually copy the files over. Otherwise will have to wait til work is open again.

**Comment by bxnjamin** [comment]
I'm probably misunderstanding the issue here, but if you have a second computer, why don't you download AltServer on that pc and then install AltStore off of that?

**Comment by Dansco** [comment]
My personal laptop is a POS! Windows 7 32 Bit so I can only run an old beta on it. Installed last updated but it won't run on it.

**Comment by bxnjamin** [comment]
Ok, my bad. Hope you find some way to fix this problem.

**Comment by Dansco** [comment]
Sadly nothing is simple. At least with my iOS 13.5 devices Altdaemon works a treat. 
Thanks for trying and you have helped me.
