### ISSUE TITLE
AltStore crashing immediately after opening, after clean install

### ISSUE THREAD

**Issue by jleadlove** [rileytestut/AltStore#380]
iPhone XR on iOS 13.3.1, AltServer on Windows 10 19041.508.

I tried to refresh my AltStore via USB, but after attempting to do so I got an error "could not find provisioning profile". So I uninstalled the app, reinstalled AltServer, ran it as admin mode, and this time it worked, but the app would crash every time I opened it.

I've tried clean installing different versions of AltServer, untrusting my computer, and using a different Apple ID to no avail. Anyone have a solution?

**Comment by EGNL** [comment]
I’m having the same problem too. My device is an iPad Air 3 on iPadOS 13.3.1

**Comment by xgore** [comment]
Bonjour , j ai le même problème iPhone XS iOS 13.3.1

**Comment by jleadlove** [comment]
I was able to find a workaround by using the program 3utools to sign the IPA for me and install it on my phone.

**Comment by notnoof** [comment]
> 
> 
> I was able to find a workaround by using the program 3utools to sign the IPA for me and install it on my phone.

Could you please elaborate what exactly the workaround is? I cant seem to install unc0ver using 3u. Thank you in advance!

**Comment by notnoof** [comment]
nevermind, figured it out. thank you for posting about 3u!

**Comment by ydnacp** [comment]
@notnoof Could you tell how did you figure out?

**Comment by BenSova** [comment]
If you guys haven't figured it out, it's because AltStore dropped support for iOS 13.3.1 in general.

**Comment by jleadlove** [comment]
lmao why

**Comment by cyoussef8** [comment]
AltServer on windows keeps crashing all of a sudden when trying to refresh apps. Please fix!! :(

I have tried reopening and it just fails over and over and altserver crashes. (Happens whenever trying to refresh apps)
