### ISSUE TITLE
Altstore app crashes after fresh install. 

### ISSUE THREAD

**Issue by someguyontheinterweb** [rileytestut/AltStore#381]
After a new installation of Altstore the app will consistently crash upon opening. 
Yesterday I needed to refresh my apps so I installed altdaemon to give it a try. I saw that it required altstore version 1.4.  Before i could upgrade to 1.4 my phone died and i lost jailbreak. Now after uninstalling altstore and attempting to reinstall it via usb, it will crash whenever i attempt to open the app. I am unable to uninstall altdaemon as I lost jailbreak, and I'm not certain if this could be causing the conflict.
Im running an iphone xs max on 13.3.1 jailbroken via uncover and a mac running 10.15.4

**Comment by EGNL** [comment]
I’m having the same problem too. My device is an iPad Air 3 on iPadOS 13.3.1 (Jailed)

**Comment by xgore** [comment]
Idem après une nouvelle installation suite au redémarrage de mon iPhone à cause d la batterie j ai réinstallé altstore il s installe sans problème j’autorise l application dans le menu 
Et après quand j ouvre altstore il se referme aussitôt 
iPhone XS iOS 13.3.1

**Comment by jxjot** [comment]
Same problem. Updated server on windows but cant open the app. My device is iPhone 6s iOS13.3.1 no jailbreak.

**Comment by grusmou** [comment]
yes same thing everything was fine yesterday my phone ran out of battery and when i charged it and tried opening odyssey wont open so went back to altstore wont open either they just do the opening animation and crashes goes back to homescreen so i tried reinstalling altstore same thing if anyone finds a fix please tell me

**Comment by ikevinsolomon** [comment]
Same issues here on Mac OS Catalina and AltStore 1.4, can someone please advice ?

**Comment by psharma04** [comment]
Issue also occurs on iOS 14.2 with latest AltStore. AltServer running on MacOS Big Sur Beta 8.

**Comment by jimmyshadow1** [comment]
#387 Note my response to this. The crashing occurring on 14.2 betas is unrelated and will be fixed next AltStore update.

**Comment by JGoldz75** [comment]
Same issue here - iPhone X - iOS 13.3.1. App force closes on start. Any fix for this?

**Comment by jimmyshadow1** [comment]
I literally already answered this question. Please read past issues and responses before blindly asking the same question over and over again guys.

**Comment by xgore** [comment]
Do you know when the next 13.3.1 compatible update is due because I can't get back to the old version which worked fine

**Comment by Aerozolic** [comment]
> #387 Note my response to this. The crashing occurring on 14.2 betas is unrelated and will be fixed next AltStore update.

Any ETA when the next update will be released?

**Comment by marioloco** [comment]
same problem on my xs max ios 13.3.1, crashes altstore when i try to open , i used mac os 14 with the lates version of altstore

**Comment by marioloco** [comment]
how can i fix altstore? :(

**Comment by xgore** [comment]
can you send us a link to the old version which will work for ios 13.3.1

**Comment by Korabi20-dev** [comment]
yes please..

**Comment by marioloco** [comment]
:ooooooo000o0o0o

**Comment by marioloco** [comment]
heyyyy here is the solution!! 

https://github.com/rileytestut/AltStore/issues/387#issuecomment-708918827

**Comment by YuppY** [comment]
@marioloco 
This is way to jailbreak without AltStore, but it has nothing to do with original problem of AltStore crash under iOS 13.3.1.

Though I have found the fix:
1. Download AltStore 1.3.6: https://f000.backblazeb2.com/file/altstore/apps/altstore/1_3_6.ipa
2. Install [Charles](https://www.charlesproxy.com/): `brew install charles`
3. Configure SSL proxying: install Charles root certificate, enable SSL proxy and change network settings.
4. Map requests to https://f000.backblazeb2.com to local file:
![Снимок экрана 2020-11-15 в 19 50 12](https://user-images.githubusercontent.com/448231/99188050-d56bbb00-277b-11eb-8578-ebb8972e94fb.png)
5. Run "Install AltStore" with AltServer.

AltServer downloads and signs the latest version of AltStore during each installation. With this configuration Charles replaces the latest version with 1.3.6.

**Comment by mike5j1999** [comment]
> @marioloco
> This is way to jailbreak without AltStore, but it has nothing to do with original problem of AltStore crash under iOS 13.3.1.
> 
> Though I have found the fix:
> 
> 1. Download AltStore 1.3.6: https://f000.backblazeb2.com/file/altstore/apps/altstore/1_3_6.ipa
> 2. Install [Charles](https://www.charlesproxy.com/): `brew install charles`
> 3. Configure SSL proxying: install Charles root certificate, enable SSL proxy and change network settings.
> 4. Map requests to https://f000.backblazeb2.com to local file (Alt-Cmd-L):
>    ![Снимок экрана 2020-11-15 в 19 50 12](https://user-images.githubusercontent.com/448231/99188050-d56bbb00-277b-11eb-8578-ebb8972e94fb.png)
> 5. Run "Install AltStore" with AltServer.
> 
> AltServer downloads and signs the latest version of AltStore during each installation. With this configuration Charles replaces the latest version with 1.3.6.

Could you by any chance give me a step to step guild on this? It's not working for me, I believe I am doing something wrong. I've never used Charles before and I am on Mac also.

**Comment by YuppY** [comment]
@mike5j1999 
Try this guide on configuring Charles: https://medium.com/@yash3x/charles-proxy-macos-setup-guide-cfde50262b91
All steps before "Now we need to install the Root Certificate on the Test Mobile Device" are required.

**Comment by mike5j1999** [comment]
Thank you. Trying it right now.

**Comment by mike5j1999** [comment]
> @mike5j1999
> Try this guide on configuring Charles: https://medium.com/@yash3x/charles-proxy-macos-setup-guide-cfde50262b91
> All steps before "Now we need to install the Root Certificate on the Test Mobile Device" are required.

Update: You're the goat.

**Comment by Eleveres** [comment]
@YuppY You're a life saver, thank you!

**Comment by Mxkkxa** [comment]
Really need a fix on this.

**Comment by jxjot** [comment]
This worked for me maybe you can try it? 
https://www.reddit.com/r/jailbreak/comments/joiwnz/guide_fix_altstore_crashing_on_1331_video_included/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by ralphieb2t** [comment]
> After a new installation of Altstore the app will consistently crash upon opening.
> Yesterday I needed to refresh my apps so I installed altdaemon to give it a try. I saw that it required altstore version 1.4. Before i could upgrade to 1.4 my phone died and i lost jailbreak. Now after uninstalling altstore and attempting to reinstall it via usb, it will crash whenever i attempt to open the app. I am unable to uninstall altdaemon as I lost jailbreak, and I'm not certain if this could be causing the conflict.
> Im running an iphone xs max on 13.3.1 jailbroken via uncover and a mac running 10.15.4

Pretty much the same issue here— however, I have Alt daemon/AltStore on my main device and now, when I attempt to install AltStore on another Device, that’s exactly the problem I have. I attempted using a separate Appleid and that doesn’t seem to work at all either, it just pops up with some kind of error msg. Then when I say screw it, I’ll just use my main acct, the install goes through and AltStore claims it was “successful” however, when I go into the device and then AFTER clicking “trust” it just immediately crashes. Still no solutions for this??
