### ISSUE TITLE
Cannot install altstore windows

### ISSUE THREAD

**Issue by Oliverkiller** [rileytestut/AltStore#382]
**Describe the bug**
I try installing altstore and it gives me a error : The identity used to sign the executable is no longer valid .error code :0xe8008018
**To Reproduce**

**Expected behavior**
Install altstore 
**Screenshots**
![Uploading 95683771...]![Uploading 95683772...]
**Desktop (please complete the following information if applicable):**
 - OS: [Windows]
 - Version: [Windows 10 build 20221.Ed prerelease.200919-1857]

**iPhone (please complete the following information):**
 - Device: [iPhone 6s ]
 - iOS: [14.0]

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by jimmyshadow1** [comment]
Make sure your PC and device are both on the correct time. You can sync the time by right clicking the clock in the bottom right corner, clicking adjust date/time and then clicking "Sync now"

**Comment by Oliverkiller** [comment]
Works now thanks
