### ISSUE TITLE
App ID but no apps

### ISSUE THREAD

**Issue by andrewjay20** [rileytestut/AltStore#384]
I’ve been downloading apps such as twitter++ and WhatsApp watusi from the iOS ninja ipa library and the app ID a downloads but not the app itself, can I get some assistance please, when I download Instagram ++ it works, or well it used to ever since the new update it hasn’t been downloading anything other than the app ID itself

**Comment by jimmyshadow1** [comment]
This is normally due to corrupt or broken ipa files. Hacked or cracked ipas are especially susceptible to this. So they are extremely hit or miss if they will actually install.
