### ISSUE TITLE
K

### ISSUE THREAD

**Issue by a0ahmad** [rileytestut/AltStore#386]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: [Mac or Windows]
 - Version: [e.g. Catalina]

**iPhone (please complete the following information):**
 - Device: [e.g. iPhone8]
 - iOS: [e.g. 13.1]

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by IIWare** [comment]
can you please stop creating blank issues, it's kind of annoying.

**Comment by onedr0p** [comment]
k

**Comment by IIWare** [comment]
thx

**Comment by MyCatCondo** [comment]
Close this

**Comment by onedr0p** [comment]
k
