### ISSUE TITLE
iOS 13.3.1, crashes.

### ISSUE THREAD

**Issue by Ruckingfetarded** [rileytestut/AltStore#387]
**Describe the bug**
I have downloaded the latest version of Altserver, iTunes & iCloud, yet the app still crashes even when I redownload it completely.. I'm on iOS 13.3.1 and do not wish to update my phone. Is there any fix?? It installs fine and even altserver notifies me that the application was installed successfully, but then when I go to open it it crashes. The app is signed, I tried two different Apple IDs, I tried some settings, different computer, but it just wouldn't work. Everytime it'll crash.

**Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Version: 10

**iPhone (please complete the following information):**
 - Device: iPhone xR
 - iOS: 13.3.1

**Additional context and logs**
No error logs

**Comment by jimmyshadow1** [comment]
iOS 13.3.1 has a bug that doesn't allow apps with frameworks to be sideloaded with free accounts. AltStore 1.4 now uses frameworks to enable widgets on iOS 14 and to make it easier to add features in the future. Due to this it will no longer work on iOS 13.3.1. You can either revert back to AltStore 1.3.6, or update your phone to the latest iOS version.

**Comment by Ruckingfetarded** [comment]
How would I revert back to Altstore 1.3.6?

**Comment by Ruckingfetarded** [comment]
> iOS 13.3.1 has a bug that doesn't allow apps with frameworks to be sideloaded with free accounts. AltStore 1.4 now uses frameworks to enable widgets on iOS 14 and to make it easier to add features in the future. Due to this it will no longer work on iOS 13.3.1. You can either revert back to AltStore 1.3.6, or update your phone to the latest iOS version.

I tried downgrading to the 1.3.3 beta and still didn't work, when I tried the 1.3.1 beta it just told me there was an issue with the provisioning profile.

**Comment by madcable** [comment]
Same issue. I'm on 13.3.1 iPhone 11 Pro Max. Tagging on this instead of creating a new issue

**Comment by madcable** [comment]
@jimmyshadow1 Where do i get 13.6 please? I tried 13.3b, 13.4. both provisioning profile error.

**Comment by BenSova** [comment]
Wait, why are you guys on iOS 13.3.1 if the latest version supported by your device is iOS 14? Especially since you have new iPhones.

**Comment by ikevinsolomon** [comment]
Where can I get 13.6 ?

**Comment by ikevinsolomon** [comment]
> Wait, why are you guys on iOS 13.3.1 if the latest version supported by your device is iOS 14? Especially since you have new iPhones.

Because we want to remain jailbroken :)

**Comment by madcable** [comment]
> Wait, why are you guys on iOS 13.3.1 if the latest version supported by your device is iOS 14? Especially since you have new iPhones.
Especially for A12 chips, we cannot jailbreak iOS 14 yet

**Comment by JGoldz75** [comment]
Same issue here! iPhone X iOS 13.3.1. Altstore installs perfectly fine but force closes upon opening. Anyone know a fix or where to install 1.3.6 as mentioned previously?

**Comment by JGoldz75** [comment]
Update: Temporarily fixed the issue through other means.
1.) search google sideloadly download it and install the pc window only.
2.) connect your device iphone to pc then trust this computer.
3.) download site from unc0ver v5.3.1, drag drop ipa file into sideloadly tool.
4.) fill it as your account apple id. Then verified it using the Apple ID verification code.
5.) click START wait processing install unc0ver_5.3.1 then you DONE happy jailbreak!

**Comment by SaifurRahmanMohsin** [comment]
@Ruckingfetarded I had [the same issue](https://github.com/rileytestut/AltStore/issues/379#issue-718555293) and I'm running iOS 13.3.1 as well but on iPhone Xs. I solved it by compiling AltStore from source, pushing it to my device and then installing **AltStore (Beta)** from it. Now I got two AltStore's, so I removed the one I compiled.

**Comment by medkura** [comment]
@JGoldz75  it works finally !! you saved my life dude ? THANK YOU

**Comment by SaifurRahmanMohsin** [comment]
@medkura Ok, that's clearly an exaggeration unless you were literally being held at gunpoint to jailbreak. But you're welcome 👍

**Comment by Ruckingfetarded** [comment]
@SaifurRahmanMohsin I appreciate the help but I found another method instead because I was just trying to re-install a jailbreak. I didn't feel like waiting so I installed a VM, used a macos & an impactor to install my jb to my device.

**Comment by Ruckingfetarded** [comment]
@JGoldz75 I've been told sideloadly is partnered with piracy sites, so just be careful. @medkura You too.

**Comment by SaifurRahmanMohsin** [comment]
No problem! Glad you were able to fix it @Ruckingfetarded

**Comment by buntys82** [comment]
Issue with Altstore 1.4 Crashing on iphone xr 13.3.1 - Jb with Unc0ver.
Did a lot of permutation and combination to re jail break my iPhone however it failed with Altstore.
Tried below and works flawless - on windows 10
Download 3uTools & install them - Update them if available 
Download the unc0ver IPA

Connect your iPhone close all iTunes related software's
Click on 3utools
Click on IPA signature
Add IPA files - and tick the tab
Press sign with apple id
in Below certificate tab tick the tab unc0ver
and click on start signing.
Once you get the signature succeed
click on open the singed IPA location

you will find the signed IPA - right click n click on 3utools
Click install
once completed the Unc0ver will be on your phone - trust the app and re jailbreak

I just tried the combination post watching the below video.

https://burhangee.wordpress.com/2020/09/04/how-to-install-odyssey-jailbreak-1-0-2-1-0-1-with-3utools-jailbreak-ios-13-5-13-0-2020-odyssey-getodyssey-checkra1n-unc0ver-ios13-cydia-jailbreak-jailbreaking-apple-iphone-odyss/

**Comment by houdini5** [comment]
@JGoldz75 hey on sideloadly it keeps saying there are no iOS certificate with this serial number , do you know how I can fix it

**Comment by extraarya** [comment]
hey, any update on this issue?

**Comment by BenSova** [comment]
It's not going to change. It should be closed. It's an Apple bug, not anything with AltStore.

**Comment by extraarya** [comment]
> It's not going to change. It should be closed. It's an Apple bug, not anything with AltStore.

why’s it only occurring on the later updates? was there a new feature that was released that broke compatibility?

**Comment by noah978** [comment]
> > It's not going to change. It should be closed. It's an Apple bug, not anything with AltStore.
> 
> why’s it only occurring on the later updates? was there a new feature that was released that broke compatibility?

It was because Riley went through the painstaking effort of converting all dynamic frameworks to static. It was removed from newer versions of AltStore because was an absolute pain to maintain and caused a plethora of other bugs.
