### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by a0ahmad** [rileytestut/AltStore#388]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: [Mac or Windows]
 - Version: [e.g. Catalina]

**iPhone (please complete the following information):**
 - Device: [e.g. iPhone8]
 - iOS: [e.g. 13.1]

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by MyCatCondo** [comment]
Uhh relevance check...

**Comment by MyCatCondo** [comment]
Is this an issue?

**Comment by onedr0p** [comment]
lol

**Comment by BenSova** [comment]
It's not. But, I guess it is a thanks, which is fine, but isn't a reason to open an "issue".

**Comment by MyCatCondo** [comment]
I'd like to request that this "issue" gets closed,

**Comment by MyCatCondo** [comment]
?

**Comment by BenSova** [comment]
How about you close it and never reopen it?

**Comment by onedr0p** [comment]
thanks

**Comment by haeteyhuo54LOLXDHAHA** [comment]
booo y'all are Gaàáâäãåāæèéeêëēėęe!!!!!!!

**Comment by cuj** [comment]
thanks

**Comment by a0ahmad** [comment]
J

**Comment by cuj** [comment]
@a0ahmad can you please close this issue and never re-open it?

**Comment by onedr0p** [comment]
> @a0ahmad can you please close this issue and never re-open it?

You are assuming he speaks human.

**Comment by cuj** [comment]
> > @a0ahmad can you please close this issue and never re-open it?
> 
> You are assuming he speaks human.

well,

@MyCatCondo requests this issue to get closed and the blob spammer closed it

**Comment by MyCatCondo** [comment]
> > > @a0ahmad can you please close this issue and never re-open it?
> > 
> > 
> > You are assuming he speaks human.
> 
> well,
> 
> @MyCatCondo requested this issue to get closed and the blob spammer closed it and reopen it

Yes that is true

**Comment by onedr0p** [comment]
[Truth](https://youtu.be/xN4eqz8fQw4)
