### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by D-EVE-R** [rileytestut/AltStore#389]
6s ios 14
Failed to verify code signature of
![Screenshot from 2020-10-16 14-48-44](https://user-images.githubusercontent.com/66891134/96268277-c64cee00-0fc0-11eb-9091-e91931dfe85e.png)
this is the folder of the path above
![IMG_0003](https://user-images.githubusercontent.com/66891134/96268538-1c219600-0fc1-11eb-89a7-1ba3283ef36f.PNG)

**Comment by noah978** [comment]
Please check for duplicates before opening a new issue (#94)
