### ISSUE TITLE
support to select the default bundleIdentifier during installation

### ISSUE THREAD

**Issue by livefaceu** [rileytestut/AltStore#396]
There are some apps that will verify the bundleIdentifier.
Once the id is wrong, it may cause a crash or even the account is blocked.

So...Is it possible to support to select the default bundleIdentifier during installation?
Pop up a dialog box, select mode？

**Comment by Aerozolic** [comment]
I think I'm having this problem here.
![image](https://user-images.githubusercontent.com/25500346/97235591-d4361680-17eb-11eb-8913-77ea920c13a0.jpeg)
