### ISSUE TITLE
When will AltStore not need you to destroy the entire macOS security chain on Big Sur?

### ISSUE THREAD

**Issue by cheesycod** [rileytestut/AltStore#399]
**Is your feature request related to a problem? Please describe.**
Big Sur is in its tenth beta. When will AltStore support it without needing to disable SIP and AMFI and making your mac more prone to bugs?
**Describe the solution you'd like**

**Comment by BenSova** [comment]
Isn't that what 1.4 fixes? I can't test that (because in my case I have to have things setup that way), but that's what the release notes say, and the mail plugin is back.

**Comment by cheesycod** [comment]
I can't find a 1.4 release

**Comment by cheesycod** [comment]
@BenSova where did u find this 1.4.0. Can you share a link?

**Comment by BenSova** [comment]
@cheesycod Go download the latest version from [altstore.io](https://altstore.io)
