### ISSUE TITLE
Unable to compile due to missing libimobiledevice

### ISSUE THREAD

**Issue by eni9889** [rileytestut/AltStore#4]
It looks like https://github.com/rileytestut/libimobiledevice and https://github.com/rileytestut/ldid.git are still private. I'd love to help with development and submit PRs but not sure if libimobiledevice and ldid being private is an oversight or intentional.

**Comment by rileytestut** [comment]
Thanks for this! Definitely an oversight, trying to keep track of everything today but it’s been a lot 😅

Just made those repos public though 👌

**Comment by eni9889** [comment]
No worries thanks @rileytestut I will see if I can help with any of the issues I'm experiencing :)

**Comment by eni9889** [comment]
Sorry to re-open this @rileytestut but it looks like there is some issue with libplist: 

![image](https://user-images.githubusercontent.com/360222/65656849-4b98e580-dfef-11e9-897b-6615e5ef47e0.png)

**Comment by chrisspankroy** [comment]
How'd you fix this? I'm getting the same thing

**Comment by chrisspankroy** [comment]
Not sure if this is the intended way to do it, but I ran the install commands for `ldid` to get past this
