### ISSUE TITLE
AltServer showing No Connected Devices

### ISSUE THREAD

**Issue by Aerozolic** [rileytestut/AltStore#401]
**Describe the bug**
AltServer shows No Connected Devices while wifi sync is actually enabled and working fine in Finder and other apps.

**To Reproduce**
Open AltServer -> Install AltStore

**Expected behavior**
My wifi sync enabled device(s) should show up

**Desktop (please complete the following information if applicable):**
 - OS: macOS
 - Version: Catalina 10.15.7

**iPhone (please complete the following information):**
 - Device: iPhone 11
 - iOS: 14.2 Beta 4

**Additional context and logs**
AltServer 1.4.1

**Comment by crcoppin** [comment]
Same issue for me on Big Sur beta. No devices are visible as install destinations and when I try to update from the AltStore app I receive the following error: Failed to perform the authentication handshake with the server.

**Comment by jzielke84** [comment]
Confirmed. Once I use usb the device shows up.

**Comment by SeyfullahNazikkol** [comment]
![Ekran Resmi 2020-11-02 11 46 42](https://user-images.githubusercontent.com/45606291/97847812-3ec1e780-1d01-11eb-8b26-b3a9e5f84a99.png)
Same Problem.
When  I use usb the device shows up.

**Comment by iepngs** [comment]
> Confirmed. Once I use usb the device shows up.

Hi, after installed Altstore, then should be connect iPhone by usb again when refresh on next time?

**Comment by ronaldsb** [comment]
I've also reported this bug many times. Hope to see this fixed. 💪🏻

**Comment by flowerpeople** [comment]
same problem here. Seems it's not being fixed yet?

**Comment by jzielke84** [comment]
It has been fixed l, though the automatic refresh via WiFi is still not working.

**Comment by worm4d** [comment]
Try plugging in your mac power adapter. It works on my side.

**Comment by Bhavinjain260** [comment]
It was working fine in big sur 
When i updated to monterey and got a plug-in update 

I have two devices both have wifi sync enabled 
Out of two only one shows 
Mine does not

Even did network reset that didn't help

Any solutions??

**Comment by DetachHead** [comment]
make sure wifi sync is enabled, that seemed to fix it for me
![image](https://user-images.githubusercontent.com/57028336/144765909-79e003e9-b5d3-4250-932c-026df97f9395.png)
