### ISSUE TITLE
AltDaemon crashes on iOS 12

### ISSUE THREAD

**Issue by Randomblock1** [rileytestut/AltStore#402]
**Description**
Upon installing AltDaemon and AltStore via Filza (which worked just fine on my iOS 13 device), AltDaemon crashes

**To Reproduce**
1. Be on iOS 12
2. Install AltDaemon
3. Try installing something from AltStore using AltDaemon
4. See crash

**Expected behavior**
AltDaemon doesn’t crash and just installs the app.

**iPhone:**
 - Device: iPhone 6
 - iOS: 12.4.8

**Additional context and logs**
Cr4shed log: https://hastebin.com/poceruwola

**Comment by rbits0** [comment]
Same here on an iPhone 6 Plus iOS 12.4.9
[2020-12-03_301_pm.log](https://github.com/rileytestut/AltStore/files/5633602/2020-12-03_301_pm.log)

**Comment by PluppPlopp** [comment]
same here...
Device:iPhone 6 plus
iOS: 12.4.8  (16G201)
