### ISSUE TITLE
Thanx

### ISSUE THREAD

**Issue by a0ahmad** [rileytestut/AltStore#412]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by MyCatCondo** [comment]
Seriously?

**Comment by a0ahmad** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
