### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by a0ahmad** [rileytestut/AltStore#413]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if applicable):**
 - OS: [Mac or Windows]
 - Version: [e.g. Catalina]

**iPhone (please complete the following information):**
 - Device: [e.g. iPhone8]
 - iOS: [e.g. 13.1]

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by a0ahmad** [comment]
Thanx

**Comment by MyCatCondo** [comment]
???

**Comment by BenSova** [comment]
This is getting dumb.

**Comment by a0ahmad** [comment]
🧡
