### ISSUE TITLE
asks to "update to 13.4 on 13.3IOS

### ISSUE THREAD

**Issue by ralphieb2t** [rileytestut/AltStore#420]
If you're on 13.3IOS(not sure about 13.31+) ALTStore asks if you want to "upgrade to 13.4" cause it "fixes app crashes?" 
It is unsigned now. will ALTStore still force it to 13.4ios?

**Comment by JohnnyIsDumb** [comment]
just update to latest, it will still work

**Comment by ralphieb2t** [comment]
...when you open alt store I mean. You’re talking about updating to the latest fw through iOS? Does alt store use blobs? I’m guessing it prob just brings you over to the latest signed fw. I’m just saying it doesn’t change, stays at 13.4

**Comment by noah978** [comment]
iOS 13.3 should still be fine with AltStore, iOS 13.3.1 however, is not. Regardless, AltStore will continue working on iOS 14.
