### ISSUE TITLE
Windows version is outdated

### ISSUE THREAD

**Issue by yamashi** [rileytestut/AltStore#422]
**Describe the bug**
The Windows version is outdated and the update suggested installs the old version.

**To Reproduce**
Install the latest version from the website, see it is at version 1.3.2.0, perform update, still at 1.3.2.0

**Expected behavior**
The installed version is 1.4.1

**Desktop:**
 - OS: Windows
 - Version: 10

**Comment by rizkyramadhan** [comment]
Also, now apple is redirecting icloud and itunes download to microsoft store, as per FAQ it should directly download instead of installing from ms store.
