### ISSUE TITLE
Feature Request: ability to have more apps than 2

### ISSUE THREAD

**Issue by Spidy123222** [rileytestut/AltStore#423]
Currently I'm unable to sideload 2 apps and want to be on latest version. I was wondering if it possible to make it so you can choose if you want the altstore widget for signing outside of altstore. 

This will make it so that we can sign like before by signing 2 apps and altstore like before. 
This is important for people who can't have altstore on 24/7 to activate apps to go back and fourth to. I personally don't use the front screen widgets so would be nice to have more apps instead alt store taking 2 id's for the ability to make widgets.

Btw I'm not sure how it can be implemented but maybe a toggle or when installing you can select the one without widgets.

**Comment by Bugallow** [comment]
So it's the altostore widget what doesn't let me install two apps? Is there a way to disable it now?

**Comment by Spidy123222** [comment]
> So it's the altostore widget what doesn't let me install two apps? Is there a way to disable it now?

That's what I see in appID's wich takes a app slot from what I'm experiencing.

![image](https://user-images.githubusercontent.com/64176728/103146193-beb17000-46fa-11eb-89ce-7713d090aa03.png)

**Comment by Spidy123222** [comment]
![image](https://user-images.githubusercontent.com/64176728/109088420-346a9580-76c4-11eb-80b8-efdb6917f35d.png)

Pretty annoying. This is for more imagery context
