### ISSUE TITLE
Altserver crashes after being on for a few hours

### ISSUE THREAD

**Issue by Spidy123222** [rileytestut/AltStore#424]
**How to Reproduce**
The only way I can reproduce it is by downloading altserver on windows 10 and leaving it on all day on my desktop with no sleep mode or hibernation. 

I timed it to crash every 30min to 1-3 hours

**Expected behavior**
I expect it to be able to run without problems all day and all night without closing altserver.

**Additional context and logs**
I have went in event viewer to check for errors and errors about the easyinstaller not having permissions so I added permissions and now they are gone but it still crashes without any errors. I've reinstalled altserver multiple times without success. 

What I'm trying to achieve is to be able to have a old laptop with screen off and put in a corner and just sign when it needs to any time of day but it's not doable because of this. I tried doing sleep/hibernation mode on laptop but it just stops everything running.

**Comment by shanegillio** [comment]
hey, just saying here in case it wasn't obvious - there's some reliability bugs we are continuing to work on. going to close this
