### ISSUE TITLE
Crash after iOS 14.2 Upgrade

### ISSUE THREAD

**Issue by next2non** [rileytestut/AltStore#425]
Hi,

After updating my iPhone Xs Max to iOS 14.2 the AltStore app won't open and keeps crashing on launch. I tried reinstalling the app, deleting and reinstalling, rebooting the phone, but non of the methods worked. The installed ipa still works fine only the AlStore won't launch.

Regards,
Tariq

**Comment by itsthomas** [comment]
Yes, I have the same issue.

**Comment by neokumar23** [comment]
Yes, I just updated to iPadOS 14.2 last night and when I go to AltStore, the app shows the white screen for a half-second and crashes and returns me to the home page. Any solutions as to how I can fix this? It might be a bug
