### ISSUE TITLE
Account or password error (-1001)

### ISSUE THREAD

**Issue by giammi56** [rileytestut/AltStore#427]
Dear all,

I am trying to flash h3lix cr6 from panda helper into an iphone 5 ios 10.3.4 from a win 10 with altsigner, but I am gettin the error in the title. The app is onen in admin mode. Itune is configured and working. I reset the Apple ID, no app specific ID, no two-steps autentication. It say Sign failed and then the -1001 error

Thank you for your support.

**Desktop (please complete the following information if applicable):**
 - OS: win
 - Version: 10

**iPhone (please complete the following information):**
 - Device: iphone 5.2
 - iOS: 10.3.4

**Comment by kittoka** [comment]
I'm been having the same issue for a few months now still can't find an answer to this problem.

**Comment by SpiderOnTheNet** [comment]
Hi,
I had the same issue, and I reload Icloud on my computer after clear cache in AltSigner.
But now I got the "unknown error(-1007)"   -__-'
Maybe it can help some one ;)

**Comment by PadraigHalstead** [comment]
> Hi,
> I had the same issue, and I reload Icloud on my computer after clear cache in AltSigner.
> But now I got the "unknown error(-1007)" -__-'
> Maybe it can help some one ;)

I just fixed the error on my device. Make sure that both devices are on the same network. I was using my pc originally which has a wired connection but i swapped to my laptop and connected both to the same network and it worked for me :)
