### ISSUE TITLE
AltStore still doesn't install after deleting all Offloaded apps

### ISSUE THREAD

**Issue by adonshoko** [rileytestut/AltStore#428]
**Describe the bug**
when i try to install, shows a messege "offloaded apps...." i had offloaded apps but i deleted them so it shoud work.

**To Reproduce**
1. Go to 'install altstore'
2. Click on ('phone name')
3. Type In email and password

**Expected behavior**
Install AltStore

![‏‏צילום מסך (68)](https://user-images.githubusercontent.com/74173642/98511495-6cf97700-226d-11eb-907e-99538970ece7.png)

**Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Version: 10

**iPhone (please complete the following information):**
 - Device: iphone 11
 - iOS: 14.2

**Comment by adonshoko** [comment]
> **Describe the bug**
> when i try to install, shows a messege "offloaded apps...." i had offloaded apps but i deleted them so it shoud work.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'install altstore'
> 2. Click on ('phone name')
> 3. Type In email and password
> 4. See error
> 
> **Expected behavior**
> Install AltStore
> 
> ![‏‏צילום מסך (68)](https://user-images.githubusercontent.com/74173642/98511495-6cf97700-226d-11eb-907e-99538970ece7.png)
> 
> **Desktop (please complete the following information if applicable):**
> 
> * OS: Windows
> * Version: 10
> 
> **iPhone (please complete the following information):**
> 
> * Device: iphone 11
> * iOS: 14.2

**Comment by adonshoko** [comment]
i also turned on my pc to automatclly sync when iphone connected

**Comment by albert8002** [comment]
Go to Settings and then search for the AppStore Icon. Click on it. When you scroll down to the bottom you should see: Offload Unused App's. Make sure that this is disabled.

**Comment by FlipperPlz** [comment]
This doesn't help, my device literally cannot sideload anything now whatsoever. All I did was uninstall an app to replace it with another and ended up fucking myself. Thanks apple for this malicious implementation of sideloading, im on ios 17.0.1
