### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by meadowsr** [rileytestut/AltStore#429]
**Describe the bug**
Installation to device (iPhone XS, iOS 14.0.1) fails with:

> Installation Failed
> This action cannot be completed at this time (-22411)

Installing from macOS 10.15.7; device is connected directly with USB-C cable (not WiFi); Mail plug-in is installed and Mail is running; the device is "trusted" and shows up in Finder; a new Apple ID was created specifically for this purpose (and works to log in).

**Comment by pachz** [comment]
Same issue here.
macOS 11.0.1
Tested both USB-C Cable and Wifi.

**Comment by qinyuhang** [comment]
Same issue here 
macOS 11.5.1 (20G80)
test both wifi and usbc cable
