### ISSUE TITLE
AltStore install - "server returned an invalid response" on iPad Air 2 / iOS 13.5

### ISSUE THREAD

**Issue by tomchr9** [rileytestut/AltStore#432]
Hello,

I'm trying to install AltStore on an iPad Air 2 / iOS 13.5.  I am using AltServer 1.4.1.0 on Windows 10.
After I have entered the 6-digit security code, I keep getting the "Server returned an invalid response" error message.
How do I solve this?

**Comment by fightingserpent** [comment]
Delete iTunes, iCloud and altstore and reinstall everything from altstore website links

It worked for me in iPhone 7 in iOS 15.7.
