### ISSUE TITLE
AltStore Failed to Log In Error code -22411

### ISSUE THREAD

**Issue by mhm199** [rileytestut/AltStore#434]
Whenever I Log In/Sign In Apple ID to AltStore its giving me an error saying "Failed to Log In This action cannot be completed at this time comes with an error (-22411). Please help. Thanks in advanced!

**Comment by Catta1997** [comment]
Try using the same Apple ID as your iCloud ID on that device

**Comment by Spidy123222** [comment]
> Whenever I Log In/Sign In Apple ID to AltStore its giving me an error saying "Failed to Log In This action cannot be completed at this time comes with an error (-22411). Please help. Thanks in advanced!

Try searching the closed ones there's many solutions. https://github.com/rileytestut/AltStore/issues/175
