### ISSUE TITLE
Sideloaded ipa's dont show up

### ISSUE THREAD

**Issue by albert8002** [rileytestut/AltStore#436]
whenever I sideload an ipa, it does it successfully without any error and even the app id counter gies down, but the app doesn't show up neither in active nor in inactive.

**Comment by IIWare** [comment]
what ios version are you in?

**Comment by albert8002** [comment]
14.2

**Comment by bradobryhim** [comment]
I experienced this after side loading Dolphin, a restart caused the app to show up in the App Library and on my Home Screen.

**Comment by QuarterSwede** [comment]
Same is happening to me on 14.2 and my 12 Pro Max. Shows in AppID and not on the home screen, App Library, and can't be searched for. A restart did not help.

**Comment by albert8002** [comment]
> I experienced this after side loading Dolphin, a restart caused the app to show up in the App Library and on my Home Screen.

Coincidentally I sideloaded  Dolphin aswell, restarted but nothing happened. But thanks for the reply anyway.

**Comment by albert8002** [comment]
> Same is happening to me on 14.2 and my 12 Pro Max with Dolphin. Shows in AppID and not on the home screen, App Library, and can't be searched for. A restart did not help. A restart did help with Provenance. And now it says I can't reinstall it because I don't have anymore AppIDs (even though I've only used 6).

Yup exactly the same as me.

**Comment by QuarterSwede** [comment]
So I ended up deactivating a sideloaded app and reinstalled Dolphin. After rebooting Dolphin showed up.

**Comment by CaptioDev** [comment]
On IOS 17 Dev Beta 3, Same thing happens. But with all IPAs. AltServer says unable to connect, did nothing wrong. My apps sometimes go to APP ID but not Active. AltServer on Windows 11.
