### ISSUE TITLE
"Installation Succeeded" but nothing changes on my iOS 14.2

### ISSUE THREAD

**Issue by 0xma12k** [rileytestut/AltStore#438]
I install AltServer 1.4.1.0 on WIndows 10 (2004) and use cable to connect with iOS

**Comment by typeRob** [comment]
I've got the same issue this morning, I can't understand why...

**Comment by hprobotic** [comment]
Hey @markusama , @typeRob: You guys have to restart your devices. That will show up on screen.

**Comment by typeRob** [comment]
@hprobotic thanks man now it works!!
