### ISSUE TITLE
About the error: ISwOW64Process2 for Windows

### ISSUE THREAD

**Issue by hkthomas** [rileytestut/AltStore#439]
My operating system is Windows Server 2016 Essentials.

Several versions tried have prompted this error message.

The final release was Version 1.3 Beta 3, and the issue was resolved.

Just for your reference.

**Comment by plok5202008** [comment]
Solved by ultraedit AltServer.exe and replace all IsWow64Process2 to IsWow64Process
see this https://www.youtube.com/watch?v=_JTp0yPliJw
