### ISSUE TITLE
"Could not connect to AltServer" error every time I try to install

### ISSUE THREAD

**Issue by M1ghtyboyPersonal** [rileytestut/AltStore#44]
![image](https://user-images.githubusercontent.com/29181101/66504125-6de73480-eac0-11e9-8448-2c7cdb8a568e.png)

Oh also can we have the IPA file pls I want to sideload this with cydia impactor or ReProvision

dont really know what else to say apart from pc specs??
i3 6100
8gb ddr4-2400 RAM
gtx 1070 8gb

**Comment by iamtheyammer** [comment]
Seems like the error is coming from around [https://github.com/rileytestut/AltStore/blob/820b1fb7183b845043f58e6c602c8677a3c358e4/AltServer/Devices/ALTDeviceManager.mm#L177](here). I’ll build it myself and see if I can narrow it down.

**Comment by gorxk** [comment]
Yep same thing

**Comment by noah978** [comment]
Please use the FAQ to help with questions related to "Could not connect to AltServer".

The issue likely stems from your Firewall. Make sure to have your device plugged in and use the latest version of AltServer.
