### ISSUE TITLE
.ipa release for Jailbroken users?

### ISSUE THREAD

**Issue by The-SamminAter** [rileytestut/AltStore#45]
I am running jailbroken iOS 10.3.3, and since I don't have access to a computer running macOS or a Windows computer with the admin password, would like to be able to install AltStore via an .ipa file.

Is this possible?

**Comment by dlevi309** [comment]
> I am running jailbroken iOS 10.3.3, and since I don't have access to a computer running macOS or a Windows computer with the admin password, would like to be able to install AltStore via an .ipa file.
> 
> Is this possible?

Unfortunately that sounds a bit unlikely because of 
1. AltStore’s reliance on your computer running the AltServer
2. Delta’s build specifies a deployment version of 12.2/4 and above. 
Sorry ;(

**Comment by The-SamminAter** [comment]
So I won't be able to run Delta :/
Would Delta maybe work if I changed the minimumosversion in info.plist, or is iOS 10.3.3 missing something that is required?

**Comment by dlevi309** [comment]
> So I won't be able to run Delta :/
> Would Delta maybe work if I changed the minimumosversion in info.plist, or is iOS 10.3.3 missing something that is required?

id go out on a limb to bet its much more intricate than that, but by all means you can try, i just uploaded a mirror for the officially released ipa so ill leave that link for you here: https://www.dropbox.com/s/yt7k7oza58w63yt/delta.ipa?dl=0

**Comment by The-SamminAter** [comment]
Is the official release the same version that got released on it's GitHub page, or newer?

**Comment by dlevi309** [comment]
> Is the official release the same version that got released on it's GitHub page, or newer?

this is just the version that's currently being pushed out on the AltStore as if you'd had it installed. you'd have to resign it manually or through ReProvision. Out of curiosity what device are you running?

**Comment by The-SamminAter** [comment]
iPhone 6s, iOS 10.3.3 w/ doubleH3lix
