### ISSUE TITLE
Not working on iOS 13.2 (Public Beta 2)?

### ISSUE THREAD

**Issue by derthobo** [rileytestut/AltStore#49]
After updating from iOS 13.1.2 to iOS 13.2 (Public Beta 2) the applications Delta (Beta) and AltStore (Beta) didn't open. I've deleted them and tried a new installation with AltStore Server. That wasn't possible (screenshot is attached)! :(

AltServer V. 1.0.1 (1)
macOS Catalina 10.15
iPhone 11 Pro Max with iOS 13.2 Public Beta 2

![Fail to install](https://user-images.githubusercontent.com/56515540/66719192-ef0a3880-edec-11e9-9170-292a7443e764.png)

**Comment by valpinkman** [comment]
I have the same issue

**Comment by jaylamping** [comment]
I'm experiencing the same on 12.2 PB2 and Windows

**Comment by g2bb** [comment]
I just upgraded to 13.3 PB3 and was able to get it to work right away! Apple fixed it for him :P

**Comment by derthobo** [comment]
You‘re right! :) Perfect!

**Comment by DeXtmL** [comment]
Same for public release of iOS 13.2. It just crashes on start.

**Comment by noah978** [comment]
This was just a problem with an iOS beta, closing this issue.
