### ISSUE TITLE
The provisioning profile is invalid

### ISSUE THREAD

**Issue by dezdeepblue** [rileytestut/AltStore#52]
I installed the Altserver on Win10.
iTunes is already installed.
When I clicked on install AltStore on my iPhone, after asking my apple ID and credentials and some downloading it return an error:
![image](https://user-images.githubusercontent.com/8181591/67092169-6cea8d00-f1bb-11e9-8490-785cef1487d3.png)

The iPhone is 6 and the OS version is 12.4

**Comment by IronMan805** [comment]
I have same error did you fix?

**Comment by AzodFR** [comment]
same error here

**Comment by DrissiReda** [comment]
Same error

**Comment by noah978** [comment]
This should be fixed on the latest versions of AltStore/Altserver. Closing this issue.

**Comment by Pflegusch** [comment]
I'm on 1.3.2.0 and this still happens

**Comment by Arthur2012** [comment]
> I'm on 1.3.2.0 and this still happens

same version, same issue.
Shall we keep icloud and iTunes in login status? same account?

**Comment by noah978** [comment]
Please try the following:
* Use a throwaway Apple ID
* Restart both your computer and iPhone
* Delete the “adi” folder in iTunes’ file directory

Let me know if something here fixes it for you.

**Comment by sferia82** [comment]
same error. help please. :(

**Comment by sferia82** [comment]
> Please try the following:
> 
> * Use a throwaway Apple ID
> * Restart both your computer and iPhone
> * Delete the “adi” folder in iTunes’ file directory
> 
> Let me know if something here fixes it for you.

Doesn’t Work

**Comment by Pflegusch** [comment]
I've also tried multiple Apple IDs now and tried adding a signing certificate in Xcode, doesn't work. Also quitted the developer team of my company on my original ID but absolutely nothing works..

**Comment by Pflegusch** [comment]
But I mean, if even a completely brand new Apple ID doesn't work, the issue clearly lies on the phone doesn't it? What can one check over there if theres something missing/at fault?

**Comment by mailinglists35** [comment]
getting this on ios 12.4 windows 10 latest, icloud latest, itunes latest, altstore latest

how to fix it?
