### ISSUE TITLE
Problems Sideloading

### ISSUE THREAD

**Issue by jimathy** [rileytestut/AltStore#54]
Having alot of trouble sideloading, out of around 10 apps, only 2 worked so far.

First batch I tried only 2 apps worked and the others just had the spinner constantly turning with no loading bar. Shortly after giving up on it, I realized the altstore had risen to 10gb with no way of emptying its cache. 

After reinstalling the beta, i attempted the same batch again and the same result, only 2 apps.

On my third try with 3 apps, 1 did the constant spinner trick, and the other 2 threw a message "Unknown error occurred" and failed to install.

Edit: After trying these it's apparently used my 10 weekly signings, even though I only managed to get 2 apps :(

**Comment by noah978** [comment]
Most of these issues should be fixed in the latest versions of AltServer and AltStore. Leave a comment if there are certain IPAs you are still having issues with, but for now I will close this issue.

**Comment by CrCrate** [comment]
im having issues sideloading giovanni (gameboy emulator for apple watch). I get the "unknown error" prompt every time i try to sideload it. Im on the latest altserver and altstore 1.4a9.
