### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by ByteOfBacon** [rileytestut/AltStore#549]
Altserver cannot install Altstore. Error code: 0xe8008001 (An unknown error has occured._

![image](https://user-images.githubusercontent.com/23367134/100178408-cedaf300-2ea1-11eb-8d92-1c769f59b322.png)

Altserver version: 1.4.1.0
Device: IPad 6th Generation, A10, Wifi-only.
IOS ver: 13.2
Jailbreak version: 5.3.0 Unc0ver 

The IPad had AltDaemon installed, but was left powered off for over a week, thus altstore + jailbreak expired. I believe this may be the cause of the issue, as other issues mention unjailbreaking to be a common cause for this.

**Comment by ByteOfBacon** [comment]
Edit:

Computer installing from is Windows, Ver 20H2, build ver, 19042.630

**Comment by JasonAsaad** [comment]
Try uninstalling it and reinstalling it

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
shut up, and your name is written big, below:
```
__    _  _______  _______  __   __   __   __  
|  |  | ||       ||   _   ||  | |  | |  | |  | 
|   |_| ||    ___||  |_|  ||  | |  | |  | |  | 
|       ||   | __ |       ||  | |  | |  | |  | 
|  _    ||   ||  ||       ||__| |__| |__| |__| 
| | |   ||   |_| ||   _   | __   __   __   __  
|_|  |__||_______||__| |__||__| |__| |__| |__|

**Comment by noah978** [comment]
This issue is usually solved by setting the time set in your computers BIOS to automatic. (Or sometimes just in the Windows time settings)
