### ISSUE TITLE
Build Issue: Missing package product AltSign-Static

### ISSUE THREAD

**Issue by mohsin** [rileytestut/AltStore#550]
Hello

I followed the build instructions and resolved the signing key + add my DeviceID to the plist. But I still key getting one error viz.
```
Missing package product 'AltSign-Static', please fix package resolution errors before building
```

Not sure why this happens. Any fix?

**Comment by ModdedGamers** [comment]
This is happening to me, and I am wondering if you've fixed this or how I can fix it. Pinging @rileytestut as it's been quite a long time and this issue's still open.

**Comment by andre4ik3** [comment]
I'm having this same issue, I suspect this is due to AltSign dependency. I have tried uninstalling & re-installing submodule to no avail. I am trying to build branch 1.4.3.

**Comment by zhushenwudi** [comment]
+1

**Comment by CobreDev** [comment]
Also facing this issue

**Comment by jkcoxson** [comment]
Found the solution, download all submodules and run ``pod install`` in both AltStore and Dependencies/AltSign, then open the xcworkspace.

**Comment by CobreDev** [comment]
> Found the solution, download all submodules and run ``pod install`` in both AltStore and Dependencies/AltSign, then open the xcworkspace.

This seems to work for me!
