### ISSUE TITLE
[AltServer] Can I specify a different AltStore.ipa to push into my device?

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [rileytestut/AltStore#552]
My phone restarted and I came out of jailbreak recently. I'm trying to re-install AltStore again so I could run unc0ver and jailbreak again. However, every time I re-install altstore using altserver, it [keeps crashing](https://github.com/rileytestut/AltStore/issues/379) on open. The last time, I was able to recompile this repo and then push AltStore manually to my device, after which I installed "AltStore-Beta" from it which came as a separate app (coz I believe that mine had my own custom package name which I used for compilation) whereas the one installed from the AltStore had yours rileytestut package name. The AltStore Beta ipa did not crash on open so I had removed my own and used the jailbreak until this phone restart.

So now I'm stuck with an unjailbroken phone (iOS 13.3.1) and would like to get back to jailbreak. Tried pushing unc0ver ipa directly with Cydia Impactor but I realized that I'm on an old mac running 10.14.6 and Apple had [closed that too](https://twitter.com/saurik/status/1196888477830221824) for non-dev accounts.

So I figured, if there's some way I can configure AltServer to sign a different ipa before it pushes to my phone i.e. the AltStore Beta ipa then it may make it possible for me to open AltStore Beta with whatever patches it has that makes it work on my phone without crashing. Is there any way I can do that?

I see that there is a [string](https://github.com/rileytestut/AltStore/blob/master/AltServer/Devices/ALTDeviceManager+Installation.swift#L16) which I could change to https://f000.backblazeb2.com/file/altstore/altstore-beta.ipa to make it work. However, I'm unable to compile AltServer and there doesn't seem to be instructions either so I'm stuck.

**Comment by jxjot** [comment]
Maybe try installing unc0ver by using 3utool? Then you can after you run the jailbreak you can install the altstore latest version

**Comment by SaifurRahmanMohsin** [comment]
I found [an alternative solution](https://www.reddit.com/r/jailbreak/comments/etekwx/tutorial_how_to_use_altstore_to_install_most_ipas/) and got rejailbroken again. Thanks thou @jxjot
