### ISSUE TITLE
Invalid value of WKCompanionAppBundleldentifier key

### ISSUE THREAD

**Issue by bumbie** [rileytestut/AltStore#557]
An error occured while installing the app.

Invalid value of WKCompanionAppBundleldentifier key in com.cinegenix.filmic.pro (expected com.cinegenix.filmic.pro.544VVR3JWZ)

App File [https://drive.google.com/file/d/1fVWuM7GKMeL0AbE_AUj4oTFjgMAUoRP2/view?usp=sharing](url) (Downloaded from iPhoneCake)
AltServer 1.4.1
Big Sur 11.0.1

**Comment by K9Paradox** [comment]
Same issue here.

**Comment by 3ig** [comment]
Extract .ipa (rename it to zip). Go to Payload => Appname.app => delete “Watch” folder. Then go back to Payload => compress Payload to Payload.zip => change name “Payload.zip” to “payload.ipa

**Comment by thibauddavid** [comment]
Hi, I have the same issue. I bypassed it by manually renaming bundleIdentifier in `Watch Extension.appex` plist.
Is there anyway to make it work without that, as it means appId is hardcoded in my patched versions, leading to other people's AltStore won't be able to dynamically update it without leading to the same error ?
