### ISSUE TITLE
AltDaemon Refresh Invalidates Apps

### ISSUE THREAD

**Issue by ecumber** [rileytestut/AltStore#559]
When AltDaemon refreshes my apps, they become invalidated and refuse to load because of an untrusted developer. This only happens when an automatic refresh happens, and not if I go into AltStore and refresh them manually.
![image](https://user-images.githubusercontent.com/14047530/101121969-34b43280-35a6-11eb-8593-b831d43fac68.png)
The developer is trusted in settings, under the same email and serial number that the apps are asking for.
![image](https://user-images.githubusercontent.com/14047530/101122167-b0ae7a80-35a6-11eb-902d-8b9f6ac39821.png)
In order to get my apps back, I have to reinstall AltStore and refresh the other apps.
I'm on a checkra1n'd iPhone 7 Plus on iOS 14.2. All of the Alt* apps are on their latest versions.

**Comment by dareal68** [comment]
I have the exact same issue but iPhone 6s (14.2 checkra1n 0.12.1)

**Comment by ecumber** [comment]
Update, both refreshing manually and automatically now invalidates the apps. I have to reinstall AltStore to refresh the others properly.
