### ISSUE TITLE
no such module 'altsign'

### ISSUE THREAD

**Issue by andyjhall** [rileytestut/AltStore#56]
`//
//  OperationError.swift
//  AltStore
//
//  Created by Riley Testut on 6/7/19.
//  Copyright © 2019 Riley Testut. All rights reserved.
//

import Foundation
import AltSign`

Ive built the Altsign project, but no idea what else needs doing to prevent this issue with the altstore project.

**Comment by dlevi309** [comment]
start over -

git clone https://github.com/rileytestut/AltStore.git --recurse-submodules

cd to the directory, run these:
pod update
carthage update

when changing the bundle identifier of altstore, tap "build settings" up top, make sure you go through each of the four targets and set your account iD from "6XVYFGDV" (whatever it is) to yours and make sure you change the build settings from "MacOS 14.00" to 15 in Libmobiledevice and Altkit. 

Voila'

**Comment by andyjhall** [comment]
Tried this several times but still hitting the same error, where would xcode be looking for this import?

**Comment by dlevi309** [comment]
can you upload a screenshot of this along with possibly the steps you take to install? and do you have a paid develop account?
