### ISSUE TITLE
Filzaescaped not asking for permissions 

### ISSUE THREAD

**Issue by FrostDevGithub** [rileytestut/AltStore#560]
So i was downloading Filzaescaped a long time ago
when i downloaded it back then Altstore showed a notification Filza wants acces to files

Now i wanted to install Filza again and when i sideload it with altstore it doesnt give that notification
Then when i open Filza it doesnt show any files

So is there any change i am doing something worng or is this a bug
Also is there a way to manualy give a sideloaded ipa aplication permissions

And this is the Filzaescaped for ios13 file:
https://mega.nz/file/N2A1nIhS#KKC-82tDeztZGMU59Dxcwpq10xr24Jo526XhHpJS18A

**Comment by guteSeite** [comment]
Me too, Filzaescaped is signed, but not working anymore
