### ISSUE TITLE
AltServer - Deezer - Não funciona

### ISSUE THREAD

**Issue by Lemosbeats** [rileytestut/AltStore#561]
Baixei recentemente o Deezer com IPA no altserver, porém quando abro ele, boto meu número para conectar, vai para uma tela de aceitar cookies...porém quando aperto em aceitar, aparece uma mensagem ' ocorreu um erro ' , ou as vezes nem chega nessa parte, eu boto email/número de telefone como login e vai direto para a tela inicial novamente !Alguém sabe me ajudar, ou tem algum IPA  disponibilizar para eu baixar?

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
shut up, and your name is written big, below:
```
__    _  _______  _______  __   __   __   __  
|  |  | ||       ||   _   ||  | |  | |  | |  | 
|   |_| ||    ___||  |_|  ||  | |  | |  | |  | 
|       ||   | __ |       ||  | |  | |  | |  | 
|  _    ||   ||  ||       ||__| |__| |__| |__| 
| | |   ||   |_| ||   _   | __   __   __   __  
|_|  |__||_______||__| |__||__| |__| |__| |__|

**Comment by noah978** [comment]
Isso parece ser um problema com o Deezer, não com o AltStore. Minha sugestão é tentar encontrar um Deezer IPA em algum outro site.
