### ISSUE TITLE
altstore crashes when open with/without unc0ver

### ISSUE THREAD

**Issue by xdapx14** [rileytestut/AltStore#564]
i am having trouble downloading altstore and getting unc0ver to work, may i get some help? i am on ios 13.3.1. i have been jailbroken for sometime but i had to reboot my phone today and i have not been able to get my jailbreak working again. please help!
altstore ver says 1.4 and i am unable to downgrade to alt ver 1.3.6

**Comment by GraceMelody** [comment]
Following. I can't find Altstore ver 1.3.6 anywhere

**Comment by jxjot** [comment]
@xdapx14 Have you tried installing unc0ver with 3utool?
