### ISSUE TITLE
When I use nullximpactor install ipa file poped error

### ISSUE THREAD

**Issue by i19870503** [rileytestut/AltStore#565]
My device is in ios 11.3.1 and macOS big sur, macOS need the latest mail plug-in, so I install the newest AltServer v1.4.1. Then I use the nullximpactor(v1.0.1) to install Electra1141-1.3.2.ipa for my iphone. However, when I try to revoke certificates the nullximpactor poped this error:

> `2020-12-07 10:57:23.028 nullxImpactor[59447:2906692] ERROR: Invalid neg prot hmac.
Error Domain=com.rileytestut.ALTAppleAPI Code=19 "Failed to perform authentication handshake with server."`

Unfortunately, I also could not install altStore for my device since it need the at least ios 12.2+. So what should I do for my device?

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
shut up, and your name is written big, below:
```
__    _  _______  _______  __   __   __   __  
|  |  | ||       ||   _   ||  | |  | |  | |  | 
|   |_| ||    ___||  |_|  ||  | |  | |  | |  | 
|       ||   | __ |       ||  | |  | |  | |  | 
|  _    ||   ||  ||       ||__| |__| |__| |__| 
| | |   ||   |_| ||   _   | __   __   __   __  
|_|  |__||_______||__| |__||__| |__| |__| |__|

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
> So what should I do for my device?

Just stick it up ur ass till 100 Gallons of poop comes out from ur ass, you b,t!,c;h
