### ISSUE TITLE
Sideloading and iOS 14 Question

### ISSUE THREAD

**Issue by gh0sti** [rileytestut/AltStore#566]
This question relates to Altstore but is not an issue with altstore, more about sideloading. I was wondering if someone could take a look at this. Nov 20th I had my developer account expire and didn't renew my subscription. However it's been almost 3 weeks now and I noticed my sideloaded apps, provenance and retroarch, are still working. My question is shouldn't my apps have stopped working a week after my dev account expired? Did Apple change sideloading rules on iOS 14? I was wondering if anyone else has seen this and can confirm. I have used cydia impactor and sideloadly to sideload my apps.

Device: iPhone 11 Pro Max
iOS 14.2

**Comment by noah978** [comment]
Interestingly enough, this is a bug with Apples developer services that has been around for quite some time. Even after the developer account expires, the sideloading privileges don’t go away. As far as I know, this is more of a bug on Apples server side. But I would take the benefits as long as they last.
