### ISSUE TITLE
"Please update to Xcode 7.3 or later" error

### ISSUE THREAD

**Issue by solverbak** [rileytestut/AltStore#57]
When trying to refresh an app I receive the message "Please update to Xcode 7.3 or later to continue developing with your Apple ID. (3018)" (green bubble). iOS version is 13.2, AltStore 1.1b2, and I have Catalina installed with Xcode 11.2 and Altserver 1.0.1. I have had AltStore installed for weeks with no issues before this.

**Comment by Ethan-BB** [comment]
I have same issue on Windows 10 1903, iOS 13.2
Started happening today.

**Comment by WilliamLCobb** [comment]
Apple dropped support for the Xcode 7 protocol today effecting everyone using AltStore. `ALTAppliApi.m` needs to be updated to use the Xcode 7.3 api or later for AltStore to start working again

**Comment by nighto** [comment]
Just to add 2¢, tried to update Xcode CLI with the following steps but it wasn't enough, the error persisted.

```bash
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

![image](https://user-images.githubusercontent.com/397851/68349000-64121a80-00da-11ea-8d47-033efd04872b.png)

**Comment by rileytestut** [comment]
Looking into this right now, sorry for the inconvenience everyone!

**Comment by rileytestut** [comment]
So the server returns a DSESSIONID value in the response headers, but trying to use that value for subsequent network requests still fails. Getting closer though...

**Comment by aovestdipaperino** [comment]
>  It doesn't seem like the value for `X-Apple-GS-Token` matters
I am not convinced.

**Comment by rileytestut** [comment]
I guess I should note the value for `X-Mme-Device-Id` I'm getting is the same as the `machineId` field for my development certificate (EEF1E570-F961-596D-A316-C39806EA65F4). I assume this doesn't mean anything and is just because Xcode has given my computer that identifier, but honestly who knows for sure at this point 🤷‍♂️

**Comment by pdso** [comment]
```
X-Apple-I-MD-RINFO: 17106176
X-Apple-App-Info: com.apple.gs.xcode.auth
Accept: text/x-xml-plist
Connection: close
Content-Type: text/x-xml-plist
X-MMe-Client-Info: <MacBookPro11,5> <Mac OS X;10.11.3;15D21> <com.apple.AuthKit/1 (com.apple.dt.Xcode/10188.1)>
X-Mme-Device-Id: F2EBF5E2-B84C-515F-B11B-CD0C233ACA31
X-Apple-I-Identity-Id: 000693-10-42646a38-c731-434a-abf0-48f0e253d901
X-Apple-I-MD-M: b6WnbD3fo+SVbTSTMnSNt4IN4pBhyAFvMJoINl4LNXVieV0yOqc87KpWIA1jQXHJ22Lk5oHuiUfQcGEO
Accept-Encoding: gzip, deflate
X-Apple-I-MD: AAAABQAAABAARQ4pSs743V6UmXliedkhAAAAAQ==
X-Apple-I-Client-Time: 2019-11-07T12:00:52Z
X-Apple-GS-Token: AAAABLwIAAAAAF3EB1sRDWdzLnhjb2RlLmF1dGi9AAHm7o4BQPhRf0w5hh5ns77X8oX5sm8LrSYLepYCdk5VocAYjyKROec8o6DN61FSBV3x1qc5esTjl+LUj5TxAPk0lDC/QMSm7UY7w1HEUpa10H5M7T7NKLXgQcUP05r4MCVUK47pdqhigiuiwyn94ffva45d
User-Agent: Xcode
Content-Length: 528
Accept-Language: zh-cn
X-Xcode-Version: 7.3.1 (7D1014)
```

**Comment by WilliamLCobb** [comment]
Which Xcode version are you using to test this? 7.3?

**Comment by qhu91it** [comment]
I got the same error, the version Xcode I use is 11.2

**Comment by rileytestut** [comment]
@WilliamLCobb was using Xcode 11.1, but am now downloading Xcode 7.3

**Comment by Boris-TR** [comment]
I get a similar error when attempting to download the AltStore from my Windows 10 computer to my Iphone X. I'm on iOS 13.2. I'm also using the windows version of iTunes.
![Clipboard Nov 7, 2019 at 6 37 PM](https://user-images.githubusercontent.com/57509028/68437100-f0c9e080-018d-11ea-9239-8ae260400c47.jpeg)

**Comment by nieheyong** [comment]
same issue when install altStore

![image](https://user-images.githubusercontent.com/9368693/68443704-b86ae680-020f-11ea-8df6-949baf3bc17e.png)

**Comment by khius** [comment]
same here
<img width="752" alt="Screen Shot 2019-11-08 at 12 45 04 PM" src="https://user-images.githubusercontent.com/6244107/68498755-ac8a1f00-0225-11ea-8c2b-4fa7c4cd6ff6.png">

**Comment by horsejockey** [comment]
@rileytestut did downgrading to xcode 7.3 fix the issue?

**Comment by Quzzzyrk** [comment]
Man these past few days have been so fucking bad without Spotify. You never truly appreciate something till it’s gone :(

**Comment by marcoEDU** [comment]
any update on a possible fix?:/

**Comment by M3-PO** [comment]
Rip altstore

**Comment by rowdya22** [comment]
Let's let the man work. This is related to Apple and their security changes: 
https://support.apple.com/en-us/HT201222

@rileytestut has been working on Delta for YEARS. It always comes back. If you are going to complain about something that he is doing (largely just because it's awesome) I sure hope that you're a long time [Patreon](https://www.patreon.com/rileytestut). If you want to complain, there's the link so you can sign up and donate and then have some right. Even so, it's been 3 days. Give the guy a break! 

Wait patiently for an announcement, or fork the code and fix it yourself ¯\_(ツ)_/¯ 
It sucks but that's all we can do.

**Comment by rileytestut** [comment]
Sorry y’all, you can see some of the progress going on over here, which is in addition to all the stuff we’re doing more behind the scenes: https://github.com/Matchstic/ReProvision/issues/96

We’re making good progress, but no ETA at this time 😕

**Comment by sangshuduo** [comment]
waiting fix

**Comment by JiaYuanfangDeveloper** [comment]
waiting fix

**Comment by rileytestut** [comment]
Good news, I’ve found a workaround for this issue! Expect an update in the next couple of days, and I’ll detail it more then 👌

**Comment by aovestdipaperino** [comment]
Have you seen this?
https://github.com/gergul/xhASOios/blob/996956aca9ad8b49a0fb03826466eb69ff237bb7/xhwork/xhwork.cpp#L2290

**Comment by hexindent** [comment]
> 
> 
> Good news, I’ve found a workaround for this issue! Expect an update in the next couple of days, and I’ll detail it more then ok_hand

Thanks for today's fix! I installed the plugin and AltStore onto my iPad successfully. However, when I signed in my iCloud account in the App, it crashed therefore I can't refresh AltStore or Delta. iPad mini 5 running iOS 12.4

**Comment by hacknug** [comment]
It would be great if you could add a note letting users know they need to use their Apple ID password and that app-specific passwords don't work 👍

**Comment by rileytestut** [comment]
@hexindent mind sending a crash report to riley [at] rileytestut.com? You can find them in Settings > Privacy > Analytics > Analytics Data.

**Comment by hexindent** [comment]
> 
> 
> @hexindent mind sending a crash report to riley [at] rileytestut.com? You can find them in Settings > Privacy > Analytics > Analytics Data.

I've sent 3 crash reports to you. Hope it can help!

**Comment by mkrch1** [comment]
hello everyone i iuse ios12.4 and i got same error i dont know much about programming can u tell me what should i do thanks id advance all i need is download uncover for jaibreak my phone again :( @rileytestut

**Comment by Apocrifo99** [comment]
Hola a todos me pasa igual X-code 7.3 or latter quiero volver a instalar PopCorn Time 
ya hice de todo quitar cable, reiniciar, revocar certificados 
actucalizar Itunes tengo Windows ayuda ,,,,

**Comment by annidy** [comment]
The `- (void)fetchAccountForSession:(ALTAppleAPISession *)session completionHandler:(void (^)(ALTAccount *account, NSError *error))completionHandler ` get 403 Forbidden

**Comment by greyw0lv** [comment]
i have no idea what im doing wrong i downloaded altstore for windows, extracted the file ran the installer and setup file, launched it, and hit install, and after putting in my info got the "must install xcode7.3 or later" is there a fix yet? am i doing anything wrong?

**Comment by SEWsam** [comment]
Still getting the issue

**Comment by HigeMynx** [comment]
Still getting the issue, too.
Downloaded and installed just now.
![2019-11-26 15_43_27-Installation Failed](https://user-images.githubusercontent.com/21042065/69643397-8fe24980-1063-11ea-9064-e701185fa257.png)

**Comment by yikefengshu** [comment]
Any luck we could have a fix for windows 10 this week?

**Comment by greyw0lv** [comment]
i doubt it but lets remain optomistic

**Comment by moalshalabi** [comment]
Fix please update to xcode 7.3 or later
1- On your Windows computer, download 3uTools ( http://www.3u.com/ ) from the link above.
2- Open it and, if required, install any missing iTunes drivers
3- Use the USB lightning cable to connect your iPhone or iPad to your computer
4- If asked, Trust the computer on your device
5- From the app menu, click on Flash & JB
6- Next, click the Jailbreak tab and choose iOS 11.4 – iOS 12.4 from the options
7- Click on the Jailbreak button and wait; Unc0ver will be installed.
8- Before you use it, open your iOS settings app
9- Tap General > Profiles & Device Management and find the app profile
10 -Trust it and close Settings – Unc0ver jailbreak is ready for use.
Enjoy :)

**Comment by Ethan-BB** [comment]
You kinda missed the part on  AltStore webpage, where it says:
NO JAILBREAK REQUIRED!

**Comment by avipars** [comment]
Apparently there is a beta build from here:

https://twitter.com/altstoreio/status/1200133575800176640

Doesn't work on my iPad (iOS 9) with a windows 10 computer

**Comment by Ethan-BB** [comment]
@avipars Thank you, I missed that tweet, Riley should maybe consider making a mailing list for stuff like this.
Works on iPhone X and 13.2.3.

**Comment by effek70** [comment]
anyone try the iOS 9.3.5?

**Comment by avipars** [comment]
> anyone try the iOS 9.3.5?

I am also on the same versopm and it isn't working.

**Comment by djderan** [comment]
I'm on ios 13.3, have iCloud and iTunes installed on my Windows 10 PC and it is now working for me using that link in the tweet! (https://twitter.com/altstoreio/status/1200133575800176640) :-)

**Comment by FISIORODRIGO** [comment]
> Fix please update to xcode 7.3 or later
> 1- On your Windows computer, download 3uTools ( http://www.3u.com/ ) from the link above.
> 2- Open it and, if required, install any missing iTunes drivers
> 3- Use the USB lightning cable to connect your iPhone or iPad to your computer
> 4- If asked, Trust the computer on your device
> 5- From the app menu, click on Flash & JB
> 6- Next, click the Jailbreak tab and choose iOS 11.4 – iOS 12.4 from the options
> 7- Click on the Jailbreak button and wait; Unc0ver will be installed.
> 8- Before you use it, open your iOS settings app
> 9- Tap General > Profiles & Device Management and find the app profile
> 10 -Trust it and close Settings – Unc0ver jailbreak is ready for use.
> Enjoy :)

I WOULD LIKE TO THX YOU... I'M IN IOS 11.0.3 AND WORK FOR ME!!!!!

**Comment by SEWsam** [comment]
> > Fix please update to xcode 7.3 or later
> > 1- On your Windows computer, download 3uTools ( http://www.3u.com/ ) from the link above.
> > 2- Open it and, if required, install any missing iTunes drivers
> > 3- Use the USB lightning cable to connect your iPhone or iPad to your computer
> > 4- If asked, Trust the computer on your device
> > 5- From the app menu, click on Flash & JB
> > 6- Next, click the Jailbreak tab and choose iOS 11.4 – iOS 12.4 from the options
> > 7- Click on the Jailbreak button and wait; Unc0ver will be installed.
> > 8- Before you use it, open your iOS settings app
> > 9- Tap General > Profiles & Device Management and find the app profile
> > 10 -Trust it and close Settings – Unc0ver jailbreak is ready for use.
> > Enjoy :)
> 
> I WOULD LIKE TO THX YOU... I'M IN IOS 11.0.3 AND WORK FOR ME!!!!!

But the Jailbreak is for 11.4-12.4, how could you have gotten it to work on 11.03? Also, again, altstore's website says NO JAILBREAK REQUIRED. This isn't a proper fix

**Comment by FISIORODRIGO** [comment]
> This isn't a proper fix

I don't know... just follow the instructions and "voila" Electra it Works again.... But, I'm not the best person to discuss this cause i'm a noob in this thing of jailbreak...

**Comment by SEWsam** [comment]
> > This isn't a proper fix
> 
> I don't know... just follow the instructions and "voila" Electra it Works again.... But, I'm not the best person to discuss this cause i'm a noob in this thing of jailbreak...

?????

**Comment by bbmodern** [comment]
works perfectly till ios 9.3.5

**Comment by cruz666** [comment]
Actually the 1st Jailbreak that actually worked for a change. Semi un-tethered but better than nothing.
Thanks moalshalabi......

**Comment by noah978** [comment]
This issue was fixed awhile ago. Closing this issue now.
