### ISSUE TITLE
Always says Unknown Services Response error

### ISSUE THREAD

**Issue by JasonAsaad** [rileytestut/AltStore#572]
Whenever I try installing altstore I get Unknown Services Response Error, and I tried unistalling, closing and opening it, and I tried using a different apple id.

**Comment by JasonAsaad** [comment]
oh and in parantheses (-1)

**Comment by jacklolidk** [comment]
me too.

**Comment by Diddo17** [comment]
Same here. Reinstalling iTunes/iCloud didnt work, using a different cable didnt work either. Read somewhere that revoking certificates fixes the issue but I dont know how to do that without cydia impactor.

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing issues?

**Comment by Diddo17** [comment]
Hello,

I am not experiencing issues anymore, thanks :)
