### ISSUE TITLE
Big Sur 11.1 disables Mail Plugin

### ISSUE THREAD

**Issue by john2691** [rileytestut/AltStore#573]
I receive the following message using AltServer 1.4.1 after updating macOS to 11.1.

<img width="231" alt="Screen Shot 2020-12-14 at 1 21 31 PM" src="https://user-images.githubusercontent.com/25827600/102125534-bf681d80-3e41-11eb-8115-c68a0929b748.png">

Re-enabling in Mail preferences does not fix it, as it becomes disabled again on relaunch.

**Comment by mikperk** [comment]
I can confirm this.

**Comment by Folky63** [comment]
Same. Gotta downgrade if it won't be fixed in 7 days I guess

**Comment by mikperk** [comment]
It's fixed with v1.4.2!

**Comment by john2691** [comment]
> It's fixed with v1.4.2!

Confirmed, working perfectly again.
