### ISSUE TITLE
Multiple Free Developer IDs

### ISSUE THREAD

**Issue by minmossi** [rileytestut/AltStore#579]
Currently, to use more than two(three including AltStore itself) apps with AltStore requires $99/yr paid developer ID.

Is there a way to log in multiple free developer ID with multiple signature in single AltStore, or at least multiple AltStore signed by each different developer ID?

**Comment by alphabrav0** [comment]
I have 3 Emails and 1/3 usually work for me but for some reason I'm having the same issue:(

**Comment by greenish-guy-tech-1-h33aha-777555378477** [comment]
then deal with it, ภɠค

**Comment by noah978** [comment]
Sadly, even using different Apple IDs you will still be limited to 3 active apps. Using multiple Apple IDs can help you overcome the weekly limit of 10 App IDs but that's about it.

**Comment by Fredolx** [comment]
now that we can bypass the 3 app limit using dirtycow, could this be implemented?

**Comment by doccstat** [comment]
Second this, multiple accounts would be great with MacDirtyCow
