### ISSUE TITLE
Sever returned invalid response

### ISSUE THREAD

**Issue by duizhenpeng** [rileytestut/AltStore#58]
ios13.2
windows10

**Comment by toomanylegos** [comment]
I get the same thing.

**Comment by desmondjj** [comment]
I experienced the same issue.

**Comment by ifyour** [comment]
How to fix it? Does anybody know?

**Comment by cavesrd** [comment]
issue happens for me too, ios 13.3

**Comment by lelouch-LL** [comment]
same here. running on windows 10 and ios 13.1 iphone XS MAX help!

**Comment by FunGamer1112** [comment]
iOS 12.4.3
Windows 10
Gives me the same thing

**Comment by vupli** [comment]
https://twitter.com/altstoreio/status/1192547623317585920

**Comment by noah978** [comment]
This should be fixed on the latest versions of AltStore/Altserver. Closing this issue.
