### ISSUE TITLE
You are not a member of any development teams.

### ISSUE THREAD

**Issue by thebruge** [rileytestut/AltStore#59]
Getting this error when installing using the Mac client, any suggestions?

**Comment by whosphp** [comment]
@thebruge I met this too

**Comment by nighto** [comment]
Did you try with a second Apple account? Getting this error also when trying to use a secondary account, after the first one not being possible to use due to #61.

**Comment by noah978** [comment]
This issue is likely resolved in the latest versions of AltStore and AltServer. I will be closing this issue for now, but if the issue has persisted, please leave a comment below.

**Comment by ksboy** [comment]
> This issue is likely resolved in the latest versions of AltStore and AltServer. I will be closing this issue for now, but if the issue has persisted, please leave a comment below.

I still met the problem using the latest versions of AltServer.

**Comment by nikolaJosifovic** [comment]
I get this error when I'm using my username and password.
Then I found that I need to use app specific password.
When I use app specific password I get the error that I entered wrong credentials :)

**Comment by DunkieGaming** [comment]
> I get this error when I'm using my username and password.
> Then I found that I need to use app specific password.
> When I use app specific password I get the error that I entered wrong credentials :)

I have that ploblem too on windows

**Comment by captainstag** [comment]
I'm having the same issue now on mac (OS 10.14.6) and iPhone 11 Pro iOS 14.6
Can anyone lend a hand?
