### ISSUE TITLE
Service blocked by Adguard DNS

### ISSUE THREAD

**Issue by tonysprenk** [rileytestut/AltStore#592]
When downloading, updating the app, or installing on a new device the service is blocked by my Aduard dns. I think it blocks the http://backblazeb2.com url.

**Comment by noah978** [comment]
In that case, I would recommend whitelisting the download links since all of Riley’s apps are hosted there. If you were worried about the authenticity of the website, trust me, it is a perfectly legitimate file hosting service.

**Comment by QuarterSwede** [comment]
I know this is closed but this isn't an Adguard DNS issue. I'm not using the adguard DNS (8.8.8.8 and 1.1.1.1) and I'm still having the same message pop-up when trying to access the 1.4 link. It doesn't matter what browser I'm using or what DNS I try (I've tried a lot). Seems like Adguard got it's hooks into this somehow as someone flagged it as malware. May warrant a look just in case everyone is having the same issue.
