### ISSUE TITLE
Invalid anisette data When refreshing

### ISSUE THREAD

**Issue by JohnnyIsDumb** [rileytestut/AltStore#599]
When I try to refresh I get Invalid anisette data

**Comment by HelloIAmTheBoiCalledSeGuymkszxg** [comment]
ok, ҭђἔᾗ ṩҭὄῥ  bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!

**Comment by JohnnyIsDumb** [comment]
> ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!

Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
> > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> 
> Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu

your name is john, your github name, spittin' facts, and I forgot to say **NO U**

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
urDmb

**Comment by JohnnyIsDumb** [comment]
> urDmb

Shut yo bitch was up get better spelling 6 yea old I ain't talking to u nigger

**Comment by JohnnyIsDumb** [comment]
> > > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> > 
> > 
> > Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu
> 
> your name is john, your github name, spittin' facts, and I forgot to say **NO U**

No u is dead fat fuck 🤡🐒

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
> > > > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> > > 
> > > 
> > > Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu
> > 
> > 
> > your name is john, your github name, spittin' facts, and I forgot to say **NO U**
> 
> No u is dead fat fuck 🤡🐒

Ok, Imma sue you with ray mark for gogolplexillions becuz ray mark is recommending me preston the garbege can vids and you just called me a f𝘬ᑎ bad word! THAT FACE BELOW YOU IS THE PERSON YOU SHOULD HAVE 丂乇乂 with!!

<img width="262" height="10000" alt="Screen Shot 2020-12-23 at 11 11 12 PM" src="https://user-images.githubusercontent.com/76535961/103033952-d363fb80-4574-11eb-8e62-35c688a387d9.png">

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
> > > > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> > > 
> > > 
> > > Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu
> > 
> > 
> > your name is john, your github name, spittin' facts, and I forgot to say **NO U**
> 
> No u is dead fat fuck 🤡🐒

AND YOUR A ᖴᗩT ᑎGᗩ ᖴᑕK!!!!

**Comment by JohnnyIsDumb** [comment]
> > > > > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> > > > 
> > > > 
> > > > Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu
> > > 
> > > 
> > > your name is john, your github name, spittin' facts, and I forgot to say **NO U**
> > 
> > 
> > No u is dead fat fuck 🤡🐒
> 
> AND YOUR A ᖴᗩT ᑎGᗩ ᖴᑕK!!!!

You scared to get banned so u used a fontkey wow! Go c ry to your mommy lil nigga

**Comment by JohnnyIsDumb** [comment]
> > > > > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> > > > 
> > > > 
> > > > Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu
> > > 
> > > 
> > > your name is john, your github name, spittin' facts, and I forgot to say **NO U**
> > 
> > 
> > No u is dead fat fuck 🤡🐒
> 
> Ok, Imma sue you with ray mark for gogolplexillions becuz ray mark is recommending me preston the garbege can vids and you just called me a f𝘬ᑎ bad word! THAT FACE BELOW YOU IS THE PERSON YOU SHOULD HAVE 丂乇乂 with!!
> 
> <img alt="Screen Shot 2020-12-23 at 11 11 12 PM" width="262" height="100" src="https://user-images.githubusercontent.com/76535961/103033952-d363fb80-4574-11eb-8e62-35c688a387d9.png">

You can't even have good comebacks lil nigga get better comebacks u bitch go suck penis and cum pussy vagina

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
> When I try to refresh I get Invalid anisette data

and the ƒҟղ cause of the ƒҟղ error is your existence, so stick a pole up ur дѕѕ till ƳƠƲ ƑƲƇƘЄƊ ƳƠƲƦ ƧЄԼƑ ƛƝƊ ƘƖԼԼЄƊ ƳƠƲƦ ƧЄԼƑ!! ᙖIᘜ ᘜᗩᙓ ᑎᘜᗩ!!

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
and seems that ray mark is not recommending preston vids to me becuz he's busy making weapons to kill you, and preston.

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
ὗ ғќᾗ вƈђ!

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
> > > > > > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> > > > > 
> > > > > 
> > > > > Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu
> > > > 
> > > > 
> > > > your name is john, your github name, spittin' facts, and I forgot to say **NO U**
> > > 
> > > 
> > > No u is dead fat fuck 🤡🐒
> > 
> > 
> > Ok, Imma sue you with ray mark for gogolplexillions becuz ray mark is recommending me preston the garbege can vids and you just called me a f𝘬ᑎ bad word! THAT FACE BELOW YOU IS THE PERSON YOU SHOULD HAVE 丂乇乂 with!!
> > <img alt="Screen Shot 2020-12-23 at 11 11 12 PM" width="262" height="100" src="https://user-images.githubusercontent.com/76535961/103033952-d363fb80-4574-11eb-8e62-35c688a387d9.png">
> 
> You can't even have good comebacks lil nigga get better comebacks u bitch go suck penis and cum pussy vagina

and I wish you d,!e you lil 𝒇̲̅𝒌̲̅𝒏̲̅ 𝒃̲̅𝒊̲̅𝒕̲̅𝒄̲̅𝒉̲̅ 𝒂̲̅𝒔̲̅𝒔̲̅ 𝒍̲̅𝒊̲̅𝒇̲̅𝒆̲̅𝒍̲̅𝒆̲̅𝒔̲̅𝒔̲̅ 𝒔̲̅𝒉̲̅𝒊̲̅𝒕̲̅𝒕̲̅𝒆̲̅𝒓̲̅ 𝒃̲̅𝒊̲̅𝒕̲̅𝒄̲̅𝒉̲̅𝒆̲̅𝒓̲̅ 𝒏̲̅𝒊̲̅𝒈̲̅𝒈̲̅𝒂̲̅!! 𝐲𝐨𝐮 𝐡𝐚𝐯𝐞 𝐧𝐨 𝐦𝐨𝐦, 𝐧𝐨 𝐝𝐚𝐝, 𝐧𝐨 𝐟𝐚𝐦𝐢𝐥𝐲, 𝐲𝐨𝐮𝐫 𝐟𝐚𝐦𝐢𝐥𝐲 𝐡𝐚𝐭𝐞𝐬 𝐲𝐨𝐮 𝐚𝐧𝐝 𝐲𝐨𝐮 𝐬𝐡𝐨𝐮𝐥𝐝 𝐤𝐢𝐥𝐥 𝐲𝐨𝐮𝐫𝐬𝐞𝐥𝐟!!!

**Comment by JohnnyIsDumb** [comment]
> > > > > > > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> > > > > > 
> > > > > > 
> > > > > > Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu
> > > > > 
> > > > > 
> > > > > your name is john, your github name, spittin' facts, and I forgot to say **NO U**
> > > > 
> > > > 
> > > > No u is dead fat fuck 🤡🐒
> > > 
> > > 
> > > Ok, Imma sue you with ray mark for gogolplexillions becuz ray mark is recommending me preston the garbege can vids and you just called me a f𝘬ᑎ bad word! THAT FACE BELOW YOU IS THE PERSON YOU SHOULD HAVE 丂乇乂 with!!
> > > <img alt="Screen Shot 2020-12-23 at 11 11 12 PM" width="262" height="100" src="https://user-images.githubusercontent.com/76535961/103033952-d363fb80-4574-11eb-8e62-35c688a387d9.png">
> > 
> > 
> > You can't even have good comebacks lil nigga get better comebacks u bitch go suck penis and cum pussy vagina
> 
> and I wish you d,!e you lil 𝒇̲̅𝒌̲̅𝒏̲̅ 𝒃̲̅𝒊̲̅𝒕̲̅𝒄̲̅𝒉̲̅ 𝒂̲̅𝒔̲̅𝒔̲̅ 𝒍̲̅𝒊̲̅𝒇̲̅𝒆̲̅𝒍̲̅𝒆̲̅𝒔̲̅𝒔̲̅ 𝒔̲̅𝒉̲̅𝒊̲̅𝒕̲̅𝒕̲̅𝒆̲̅𝒓̲̅ 𝒃̲̅𝒊̲̅𝒕̲̅𝒄̲̅𝒉̲̅𝒆̲̅𝒓̲̅ 𝒏̲̅𝒊̲̅𝒈̲̅𝒈̲̅𝒂̲̅!! 𝐲𝐨𝐮 𝐡𝐚𝐯𝐞 𝐧𝐨 𝐦𝐨𝐦, 𝐧𝐨 𝐝𝐚𝐝, 𝐧𝐨 𝐟𝐚𝐦𝐢𝐥𝐲, 𝐲𝐨𝐮𝐫 𝐟𝐚𝐦𝐢𝐥𝐲 𝐡𝐚𝐭𝐞𝐬 𝐲𝐨𝐮 𝐚𝐧𝐝 𝐲𝐨𝐮 𝐬𝐡𝐨𝐮𝐥𝐝 𝐤𝐢𝐥𝐥 𝐲𝐨𝐮𝐫𝐬𝐞𝐥𝐟!!!

Stay mad kid 🤡

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
> > > > > > > > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> > > > > > > 
> > > > > > > 
> > > > > > > Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu
> > > > > > 
> > > > > > 
> > > > > > your name is john, your github name, spittin' facts, and I forgot to say **NO U**
> > > > > 
> > > > > 
> > > > > No u is dead fat fuck 🤡🐒
> > > > 
> > > > 
> > > > Ok, Imma sue you with ray mark for gogolplexillions becuz ray mark is recommending me preston the garbege can vids and you just called me a f𝘬ᑎ bad word! THAT FACE BELOW YOU IS THE PERSON YOU SHOULD HAVE 丂乇乂 with!!
> > > > <img alt="Screen Shot 2020-12-23 at 11 11 12 PM" width="262" height="100" src="https://user-images.githubusercontent.com/76535961/103033952-d363fb80-4574-11eb-8e62-35c688a387d9.png">
> > > 
> > > 
> > > You can't even have good comebacks lil nigga get better comebacks u bitch go suck penis and cum pussy vagina
> > 
> > 
> > and I wish you d,!e you lil 𝒇̲̅𝒌̲̅𝒏̲̅ 𝒃̲̅𝒊̲̅𝒕̲̅𝒄̲̅𝒉̲̅ 𝒂̲̅𝒔̲̅𝒔̲̅ 𝒍̲̅𝒊̲̅𝒇̲̅𝒆̲̅𝒍̲̅𝒆̲̅𝒔̲̅𝒔̲̅ 𝒔̲̅𝒉̲̅𝒊̲̅𝒕̲̅𝒕̲̅𝒆̲̅𝒓̲̅ 𝒃̲̅𝒊̲̅𝒕̲̅𝒄̲̅𝒉̲̅𝒆̲̅𝒓̲̅ 𝒏̲̅𝒊̲̅𝒈̲̅𝒈̲̅𝒂̲̅!! 𝐲𝐨𝐮 𝐡𝐚𝐯𝐞 𝐧𝐨 𝐦𝐨𝐦, 𝐧𝐨 𝐝𝐚𝐝, 𝐧𝐨 𝐟𝐚𝐦𝐢𝐥𝐲, 𝐲𝐨𝐮𝐫 𝐟𝐚𝐦𝐢𝐥𝐲 𝐡𝐚𝐭𝐞𝐬 𝐲𝐨𝐮 𝐚𝐧𝐝 𝐲𝐨𝐮 𝐬𝐡𝐨𝐮𝐥𝐝 𝐤𝐢𝐥𝐥 𝐲𝐨𝐮𝐫𝐬𝐞𝐥𝐟!!!
> 
> Stay mad kid 🤡

your such a:
```
 ___      ___   _______  _______  ___      _______  _______  _______    __    _  _______  _______    _______  __   __  _______  _______    _______  __   __  _______  __   __  ___      ______     _______  _______  _______    _______    _______  _______  ___   _  __    _  _______    ___      ___   _______  _______    _______  __   __  _______  _______    _______  __   __  _______  __   __  ___      ______     ___   _  ___   ___      ___        __   __  ___   __   __    _______  _______  ___      _______ 
|   |    |   | |       ||       ||   |    |       ||       ||       |  |  |  | ||       ||   _   |  |       ||  | |  ||   _   ||       |  |       ||  | |  ||       ||  | |  ||   |    |      |   |       ||       ||       |  |   _   |  |       ||       ||   | | ||  |  | ||       |  |   |    |   | |       ||       |  |       ||  | |  ||   _   ||       |  |       ||  | |  ||       ||  | |  ||   |    |      |   |   | | ||   | |   |    |   |      |  | |  ||   | |  |_|  |  |       ||       ||   |    |       |
|   |    |   | |    ___||    ___||   |    |    ___||  _____||  _____|  |   |_| ||    ___||  |_|  |  |_     _||  |_|  ||  |_|  ||_     _|  |  _____||  |_|  ||   _   ||  | |  ||   |    |  _    |  |    ___||    ___||_     _|  |  |_|  |  |    ___||       ||   |_| ||   |_| ||    ___|  |   |    |   | |    ___||    ___|  |_     _||  |_|  ||  |_|  ||_     _|  |  _____||  |_|  ||   _   ||  | |  ||   |    |  _    |  |   |_| ||   | |   |    |   |      |  |_|  ||   | |       |  |  _____||    ___||   |    |    ___|
|   |    |   | |   |___ |   |___ |   |    |   |___ | |_____ | |_____   |       ||   | __ |       |    |   |  |       ||       |  |   |    | |_____ |       ||  | |  ||  |_|  ||   |    | | |   |  |   | __ |   |___   |   |    |       |  |   |___ |       ||      _||       ||   | __   |   |    |   | |   |___ |   |___     |   |  |       ||       |  |   |    | |_____ |       ||  | |  ||  |_|  ||   |    | | |   |  |      _||   | |   |    |   |      |       ||   | |       |  | |_____ |   |___ |   |    |   |___ 
|   |___ |   | |    ___||    ___||   |___ |    ___||_____  ||_____  |  |  _    ||   ||  ||       |    |   |  |       ||       |  |   |    |_____  ||       ||  |_|  ||       ||   |___ | |_|   |  |   ||  ||    ___|  |   |    |       |  |    ___||      _||     |_ |  _    ||   ||  |  |   |___ |   | |    ___||    ___|    |   |  |       ||       |  |   |    |_____  ||       ||  |_|  ||       ||   |___ | |_|   |  |     |_ |   | |   |___ |   |___   |       ||   | |       |  |_____  ||    ___||   |___ |    ___|
|       ||   | |   |    |   |___ |       ||   |___  _____| | _____| |  | | |   ||   |_| ||   _   |    |   |  |   _   ||   _   |  |   |     _____| ||   _   ||       ||       ||       ||       |  |   |_| ||   |___   |   |    |   _   |  |   |    |     |_ |    _  || | |   ||   |_| |  |       ||   | |   |    |   |___     |   |  |   _   ||   _   |  |   |     _____| ||   _   ||       ||       ||       ||       |  |    _  ||   | |       ||       |  |   _   ||   | | ||_|| |   _____| ||   |___ |       ||   |    
|_______||___| |___|    |_______||_______||_______||_______||_______|  |_|  |__||_______||__| |__|    |___|  |__| |__||__| |__|  |___|    |_______||__| |__||_______||_______||_______||______|   |_______||_______|  |___|    |__| |__|  |___|    |_______||___| |_||_|  |__||_______|  |_______||___| |___|    |_______|    |___|  |__| |__||__| |__|  |___|    |_______||__| |__||_______||_______||_______||______|   |___| |_||___| |_______||_______|  |__| |__||___| |_|   |_|  |_______||_______||_______||___|

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
𝐽𝑜ℎ𝑛𝑛𝑦𝐼𝑠𝑆𝑢𝑐ℎ𝐴𝑆𝑒𝑥𝐸𝑎𝑡𝑒𝑟𝑇ℎ𝑎𝑡𝐶ℎ𝑒𝑤𝑠𝑂𝑛𝐻𝑖𝑠𝑂𝑤𝑛𝐵𝑎𝑛𝑎𝑛𝑎𝑎𝑎𝑎𝑎𝑎𝑎𝑎𝑎

**Comment by noah978** [comment]
I don't know what happened here, so I'm going to close this issue. As for the invalid anisette data, delete everything in C:\ProgramData\Apple Computer\iTunes\adi to fix it. Make sure to have "Show hidden files, folders, and drives" enabled in the File Explorer "View" tab. You might need to reboot your PC after.

**Comment by haeteyhuo54LOLXDHAHA** [comment]
@noah978 YOUR LOCATION IS WHERE THE ƒ.υ_¢кι!ηg preston LIEVS!!!!

**Comment by haeteyhuo54LOLXDHAHA** [comment]
> > > > > > > > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> > > > > > > 
> > > > > > > 
> > > > > > > Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu
> > > > > > 
> > > > > > 
> > > > > > your name is john, your github name, spittin' facts, and I forgot to say **NO U**
> > > > > 
> > > > > 
> > > > > No u is dead fat fuck 🤡🐒
> > > > 
> > > > 
> > > > Ok, Imma sue you with ray mark for gogolplexillions becuz ray mark is recommending me preston the garbege can vids and you just called me a f𝘬ᑎ bad word! THAT FACE BELOW YOU IS THE PERSON YOU SHOULD HAVE 丂乇乂 with!!
> > > > <img alt="Screen Shot 2020-12-23 at 11 11 12 PM" width="262" height="100" src="https://user-images.githubusercontent.com/76535961/103033952-d363fb80-4574-11eb-8e62-35c688a387d9.png">
> > > 
> > > 
> > > You can't even have good comebacks lil nigga get better comebacks u bitch go suck penis and cum pussy vagina
> > 
> > 
> > and I wish you d,!e you lil 𝒇̲̅𝒌̲̅𝒏̲̅ 𝒃̲̅𝒊̲̅𝒕̲̅𝒄̲̅𝒉̲̅ 𝒂̲̅𝒔̲̅𝒔̲̅ 𝒍̲̅𝒊̲̅𝒇̲̅𝒆̲̅𝒍̲̅𝒆̲̅𝒔̲̅𝒔̲̅ 𝒔̲̅𝒉̲̅𝒊̲̅𝒕̲̅𝒕̲̅𝒆̲̅𝒓̲̅ 𝒃̲̅𝒊̲̅𝒕̲̅𝒄̲̅𝒉̲̅𝒆̲̅𝒓̲̅ 𝒏̲̅𝒊̲̅𝒈̲̅𝒈̲̅𝒂̲̅!! 𝐲𝐨𝐮 𝐡𝐚𝐯𝐞 𝐧𝐨 𝐦𝐨𝐦, 𝐧𝐨 𝐝𝐚𝐝, 𝐧𝐨 𝐟𝐚𝐦𝐢𝐥𝐲, 𝐲𝐨𝐮𝐫 𝐟𝐚𝐦𝐢𝐥𝐲 𝐡𝐚𝐭𝐞𝐬 𝐲𝐨𝐮 𝐚𝐧𝐝 𝐲𝐨𝐮 𝐬𝐡𝐨𝐮𝐥𝐝 𝐤𝐢𝐥𝐥 𝐲𝐨𝐮𝐫𝐬𝐞𝐥𝐟!!!
> 
> Stay mad kid 🤡

JohnnyIsDumb
lmao ur name says it all about your actions on this issue!!!! LMAO

**Comment by haeteyhuo54LOLXDHAHA** [comment]
> > > > > > > > ok, ҭђἔᾗ ṩҭὄῥ bᵗ¢ʰᑎᵍ and ɠ0 ɠєt a ʟіғе, you fᵏⁿ Ɲᵍ卂!
> > > > > > > 
> > > > > > > 
> > > > > > > Shut up bitch as up nigga u scared to cuss fat kid fuck u bigger and go fuck you self faggot stfu
> > > > > > 
> > > > > > 
> > > > > > your name is john, your github name, spittin' facts, and I forgot to say **NO U**
> > > > > 
> > > > > 
> > > > > No u is dead fat fuck 🤡🐒
> > > > 
> > > > 
> > > > Ok, Imma sue you with ray mark for gogolplexillions becuz ray mark is recommending me preston the garbege can vids and you just called me a f𝘬ᑎ bad word! THAT FACE BELOW YOU IS THE PERSON YOU SHOULD HAVE 丂乇乂 with!!
> > > > <img alt="Screen Shot 2020-12-23 at 11 11 12 PM" width="262" height="100" src="https://user-images.githubusercontent.com/76535961/103033952-d363fb80-4574-11eb-8e62-35c688a387d9.png">
> > > 
> > > 
> > > You can't even have good comebacks lil nigga get better comebacks u bitch go suck penis and cum pussy vagina
> > 
> > 
> > and I wish you d,!e you lil 𝒇̲̅𝒌̲̅𝒏̲̅ 𝒃̲̅𝒊̲̅𝒕̲̅𝒄̲̅𝒉̲̅ 𝒂̲̅𝒔̲̅𝒔̲̅ 𝒍̲̅𝒊̲̅𝒇̲̅𝒆̲̅𝒍̲̅𝒆̲̅𝒔̲̅𝒔̲̅ 𝒔̲̅𝒉̲̅𝒊̲̅𝒕̲̅𝒕̲̅𝒆̲̅𝒓̲̅ 𝒃̲̅𝒊̲̅𝒕̲̅𝒄̲̅𝒉̲̅𝒆̲̅𝒓̲̅ 𝒏̲̅𝒊̲̅𝒈̲̅𝒈̲̅𝒂̲̅!! 𝐲𝐨𝐮 𝐡𝐚𝐯𝐞 𝐧𝐨 𝐦𝐨𝐦, 𝐧𝐨 𝐝𝐚𝐝, 𝐧𝐨 𝐟𝐚𝐦𝐢𝐥𝐲, 𝐲𝐨𝐮𝐫 𝐟𝐚𝐦𝐢𝐥𝐲 𝐡𝐚𝐭𝐞𝐬 𝐲𝐨𝐮 𝐚𝐧𝐝 𝐲𝐨𝐮 𝐬𝐡𝐨𝐮𝐥𝐝 𝐤𝐢𝐥𝐥 𝐲𝐨𝐮𝐫𝐬𝐞𝐥𝐟!!!
> 
> Stay mad kid 🤡

And Your 𝒂̲̅ 𝒇̲̅𝒄̲̅.𝒖̲̅𝒌̲̅!𝒊̲̅𝒏̲̅𝒈̲̅ 𝒏̲̅!𝒈̲̅_-𝒈̲̅𝒂̲̅ 𝒕̲̅𝒉̲̅𝒂̲̅𝒕̲̅ 𝒉̲̅𝒂̲̅𝒔̲̅ 𝒏̲̅𝒐̲̅ 𝒍̲̅𝒊̲̅𝒇̲̅𝒆̲̅ 𝒍̲̅𝒊̲̅𝒍̲̅ 𝒏̲̅!𝒈̲̅𝒈̲̅𝒂̲̅ 𝒂̲̅𝒔̲̅𝒔̲̅𝒉̲̅𝒐̲̅𝒍̲̅𝒆̲̅ 𝒍̲̅𝒊̲̅𝒇̲̅𝒆̲̅𝒍̲̅𝒆̲̅𝒔̲̅𝒔̲̅ 𝒈̲̅.𝒂̲̅-𝒚̲̅ 𝒕̲̅𝒉̲̅𝒂̲̅𝒕̲̅ 𝒔̲̅𝒉̲̅𝒐̲̅𝒖̲̅𝒍̲̅𝒅̲̅ 𝒉̲̅𝒂̲̅𝒗̲̅𝒆̲̅ $𝒆̲̅𝒙̲̅ 𝒘̲̅𝒊̲̅𝒕̲̅𝒉̲̅ 𝒑̲̅𝒓̲̅-𝒆̲̅𝒔̲̅𝒕̲̅!𝒐̲̅𝒏̲̅𝑷̲̅𝒍̲̅!𝒂̲̅𝒚̲̅𝒁̲̅ 𝒔̲̅𝒐̲̅ 𝑺̲̅𝒉̲̅-𝒖̲̅𝒕̲̅ 𝒖̲̅𝑷̲̅ 𝒍̲̅!𝒊̲̅𝒇̲̅𝒆̲̅𝒍̲̅-𝒆̲̅𝒔̲̅𝒔̲̅ 𝒏̲̅!𝒊̲̅𝒈̲̅.𝒈̲̅𝒆̲̅𝒓̲̅ 𝒚̲̅.𝒐̲̅𝒖̲̅'𝒍̲̅.𝒍̲̅ 𝒅̲̅.𝒊̲̅!𝒆̲̅ 𝒔̲̅0̲̅0̲̅𝒏̲̅ 👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎

**Comment by noah978** [comment]
And we are done here. Thank you gentlemen.
