### ISSUE TITLE
Can't install AltStore - iOS 13.2.3 and AltServer 1.1 

### ISSUE THREAD

**Issue by SeriousMax** [rileytestut/AltStore#60]
Hi! I have problem trying to install AltStore on my iPhone (((

2019-11-19 20:51:08.824 AltServer[1169:37333] -[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x7fff8f141050
2019-11-19 20:51:08.825 AltServer[1169:37333] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x7fff8f141050'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3650ef53 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6c5d4835 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff36599106 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff364b56cb ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff364b50a8 _CF_forwarding_prep_0 + 120
	5   libswiftCore.dylib                  0x00007fff6cf284ca $ss18_bridgeCocoaStringys01_C4GutsVyXlF + 122
	6   libswiftCore.dylib                  0x00007fff6cf28702 $sSS12_cocoaStringSSyXl_tcfC + 18
	7   libswiftFoundation.dylib            0x00007fff6d3a5c1c $sSS10FoundationE36_unconditionallyBridgeFromObjectiveCySSSo8NSStringCSgFZ + 28
	8   AltServer                           0x000000010420905e AltServer + 41054
	9   AltServer                           0x0000000104210f25 AltServer + 73509
	10  AltServer                           0x000000010420b79e AltServer + 51102
	11  AltSign                             0x00000001045d1d52 __66-[ALTAppleAPI fetchCertificatesForTeam:session:completionHandler:]_block_invoke + 183
	12  AltSign                             0x00000001045d68a2 __87-[ALTAppleAPI sendServicesRequest:additionalParameters:session:team:completionHandler:]_block_invoke_3 + 198
	13  CFNetwork                           0x00007fff34cb8072 CFURLCredentialStorageCopyAllCredentials + 24893
	14  CFNetwork                           0x00007fff34c02232 _CFNetworkErrorGetLocalizedRecoverySuggestion + 1590
	15  Foundation                          0x00007fff38b3ac1d __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	16  Foundation                          0x00007fff38b3ab15 -[NSBlockOperation main] + 98
	17  Foundation                          0x00007fff38cabd80 __NSOPERATION_IS_INVOKING_MAIN__ + 17
	18  Foundation                          0x00007fff38b11524 -[NSOperation start] + 731
	19  Foundation                          0x00007fff38cac18e __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
	20  Foundation                          0x00007fff38b3a8e8 __NSOQSchedule_f + 182
	21  libdispatch.dylib                   0x00007fff6d8f3134 _dispatch_block_async_invoke2 + 83
	22  libdispatch.dylib                   0x00007fff6d8e750e _dispatch_client_callout + 8
	23  libdispatch.dylib                   0x00007fff6d8e96c0 _dispatch_continuation_pop + 414
	24  libdispatch.dylib                   0x00007fff6d8e8dbe _dispatch_async_redirect_invoke + 703
	25  libdispatch.dylib                   0x00007fff6d8f57e2 _dispatch_root_queue_drain + 326
	26  libdispatch.dylib                   0x00007fff6d8f5f22 _dispatch_worker_thread2 + 92
	27  libsystem_pthread.dylib             0x00007fff6db406d5 _pthread_wqthread + 220
	28  libsystem_pthread.dylib             0x00007fff6db4057b start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by noah978** [comment]
@SeriousMax Is still an issue on the latest version of AltServer/AltStore?
