### ISSUE TITLE
altstore mailplugin doesn't work with mail 14.0

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [rileytestut/AltStore#604]
I always receive the can't enable plugin when I try to enable the mail plugin error
<img width="280" alt="ภาพถ่ายหน้าจอ 2563-12-24 เวลา 20 25 06" src="https://user-images.githubusercontent.com/66320961/103091231-1df18080-4626-11eb-871e-aba9ac4339ef.png">
sorry I'm using Thai language

**Comment by IIWare** [comment]
can you please translate the thai language to english? if you cannot do that can you atleast please type it in as a comment in this issue? this is (almost) the only way I can find a solution.

**Comment by scratchusernamemrtbts** [comment]
ok

**Comment by scratchusernamemrtbts** [comment]
```
incompatible plugin have been disabled
mail have disabled these plug in:
AltPlugin.mailbundle
contact the developers of these plugin for the version that can use with mail 14.0
```

**Comment by IIWare** [comment]
it seems that the plug in isn't compatible.. have you used the latest version?

**Comment by scratchusernamemrtbts** [comment]
> it seems that the plug in isn't compatible.. have you used the latest version of altserver?

I download it just yesterday from the official site
P.S. I’m using macOS beta

**Comment by jonwelsch** [comment]
It's because apple keeps changing their Mail app version.

For a bandaid:

See this thread:
https://github.com/rileytestut/AltStore/issues/443

Fixable by adding this: https://github.com/rileytestut/AltStore/issues/443#issuecomment-731877006
Instructions here: https://github.com/rileytestut/AltStore/issues/443#issuecomment-741026179

**Comment by scratchusernamemrtbts** [comment]
i fixed this by making a bootcamp partiton and installing it on windows
