### ISSUE TITLE
An error occured while installing the app

### ISSUE THREAD

**Issue by AlawiYNWA** [rileytestut/AltStore#608]
An error occured while installing the app. Failed to verify code signature of /var/installd/ Library/Caches/ com.apple.mobile.installd.staging/ temp.JUWzxd/extracted/App.app/ Frameworks/HYChatroomSDK.framework: Oxe8008016 (The executable was signed with invalid entitlements.)

Hi
i’m facing this issue 

anyway to fix it ☹️

**Comment by kohotli** [comment]
I've been having this problem too. It's not for everything I sideload though, just retroarch (which aside from altstore was the only thing I had side loaded prior to the update). I'm waiting for the app id for retroarch to expire on my devices and I'll try again then. Will report back if that fixes things

**Comment by noah978** [comment]
Please check for duplicates before opening a new issue (#94)
