### ISSUE TITLE
Latest Win10 can't install iCloud from Apple website

### ISSUE THREAD

**Issue by SnowballPitcher** [rileytestut/AltStore#609]
Latest Win10 (version 20H2) seems to only be able to install iCloud from Microsoft Store. When I try to run the install.exe which was downloaded from Apple website, it always comes to error. Is there any solution?

**Comment by TheConfax** [comment]
I opened a similar issue here https://github.com/rileytestut/AltStore/issues/563 but no one replied yet...

**Comment by SnowballPitcher** [comment]
> I opened a similar issue here #563 but no one replied yet...

If this issue can't be solved, sadly, updated win10 users will have no way to use altstore but virtual machine.

**Comment by TheConfax** [comment]
> > I opened a similar issue here #563 but no one replied yet...
> 
> If this issue can't be solved, sadly, updated win10 users will have no way to use altstore but virtual machine.

I actually tried a Mac VM but Altstore didn’t work on that, any luck on a Win10 one?

**Comment by SnowballPitcher** [comment]
> > > I opened a similar issue here #563 but no one replied yet...
> > 
> > 
> > If this issue can't be solved, sadly, updated win10 users will have no way to use altstore but virtual machine.
> 
> I actually tried a Mac VM but Altstore didn’t work on that, any luck on a Win10 one?

I tried a Mac VM and it did work.

**Comment by TheConfax** [comment]
> I tried a Mac VM and it did work.

Any suggestions then? Were you logged in with Apple ID? I never do that on VMs cause once it took me 1 month with Apple support in order to restore the ID to working conditions.

**Comment by SnowballPitcher** [comment]
> > I tried a Mac VM and it did work.
> 
> Any suggestions then? Were you logged in with Apple ID? I never do that on VMs cause once it took me 1 month with Apple support in order to restore the ID to working conditions.

Yes, I logged in with my Apple ID. It will be easy to use altstore then only if your VM recognizes your iphone device.

**Comment by hi1213345446231** [comment]
https://support.apple.com/en-us/HT204283 and go into the here's what you need section, you should see a small bit of text saying:

* On Windows 7 and Windows 8, you can download iCloud for Windows on Apple's website. 

Click the link and you can use that (it doesn't matter if you are on win 10, not 7 or 8)

this apparently worked for the person who made this post: https://www.reddit.com/r/AltStore/comments/klddp7/is_there_any_other_way_to_download_icloud_for/gh8lj02?utm_source=share&utm_medium=web2x&context=3

**Comment by TheConfax** [comment]
> https://support.apple.com/en-us/HT204283 and go into the here's what you need section, you should see a small bit of text saying:
> 
> * On Windows 7 and Windows 8, you can download iCloud for Windows on Apple's website.
> 
> Click the link and you can use that (it doesn't matter if you are on win 10, not 7 or 8)
> 
> this apparently worked for the person who made this post: https://www.reddit.com/r/AltStore/comments/klddp7/is_there_any_other_way_to_download_icloud_for/gh8lj02?utm_source=share&utm_medium=web2x&context=3

The OP is saying that that installer causes error, not that he is not able to find the installer.
By the way, iTunes downloaded from Apple Website is not installing for anything lower than Windows 10, don't know about iCloud.

**Comment by SnowballPitcher** [comment]
> > https://support.apple.com/en-us/HT204283 and go into the here's what you need section, you should see a small bit of text saying:
> > 
> > * On Windows 7 and Windows 8, you can download iCloud for Windows on Apple's website.
> > 
> > Click the link and you can use that (it doesn't matter if you are on win 10, not 7 or 8)
> > this apparently worked for the person who made this post: https://www.reddit.com/r/AltStore/comments/klddp7/is_there_any_other_way_to_download_icloud_for/gh8lj02?utm_source=share&utm_medium=web2x&context=3
> 
> The OP is saying that that installer causes error, not that he is not able to find the installer.
> By the way, iTunes downloaded from Apple Website is not installing for anything lower than Windows 10, don't know about iCloud.

I have installed win10 1803 and everything works fine now.

**Comment by SnowballPitcher** [comment]
new test: win10 21h1 can install icloud normally
