### ISSUE TITLE
Failed to verify code signature | Installation Failed

### ISSUE THREAD

**Issue by an0n8o** [rileytestut/AltStore#614]
Failed to verify code signature of
/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.14QgoA/extracted/AltStore.app : 0xe800800d (There was an error communicating with your device.)

Alt Ver: 1.4.1.0
Device: iPhone 6s **(Bypassed) (Unjailed)**
iOS: 14.2
System: Windows
Widows Time Zone: Synchronized and Same as iPhone but still didn't work.

Why Bypassed? = My Original Motherboard end up Dead. then bought a cheap Mother Board from my local repair shop. Just to Clarify upcoming question.

**Comment by noah978** [comment]
Sometimes having the windows time zone synchronized is not enough. Please check your PC's BIOS and ensure the time and date is correct there.

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
NOAG 978i IS IN DALLAS TWXAS AVIODD HERRRRRRRRRRERRTTTTTTTT SHYE LIVED T^HE SAME LIOCATIO{N AS PRES+_~TON!!!! OH NOLOOLOIPO(OOLOOO(LOOP(IOIOPOOOOOOOOOOOOOOO!!!!!!!!!!!!!@!@!±@!±@!±@!±!@±Q@#$%^&*(&^*UIR%^&$%^&(*^*&%^^&*^(&*&^((*&^)$%&()*^%&(%^)*%&$*(^#$%(&^@%#$*^&#%W&$^@#*&^%@&*^#$@@&*^#@*&#@#&$*%*&#@%*&&$@#^&*^#$%#$&^*@$&%^#%^$EY$%

**Comment by noah978** [comment]
Please check for duplicates before opening a new issue (#94)
