### ISSUE TITLE
Installing Mail plugin hangs and has to be killed

### ISSUE THREAD

**Issue by snowball7241** [rileytestut/AltStore#62]
MacBook Pro 13' 2017
macOS 10.15 19A558d
AltServer 1.1, checked for update

Willing to provide more info if needed

**Comment by zwsn** [comment]
I also encountered the same situation, Macos 10.15.1

**Comment by snowball7241** [comment]
Reinstalling altserver fixed it, steps:
Uninstall mail plug in
Restart mail
Install altserver to ~/Applications again
Open altserver
Install mail plugin
Restart mail and follow instructions
Install altstore
