### ISSUE TITLE
Widget not working / accurate

### ISSUE THREAD

**Issue by OscarMoore** [rileytestut/AltStore#621]
The widget (iOS 14) never displays the real number of days remaining (expires in). What is the point in this widget if it doesn’t even work properly?

**Comment by noah978** [comment]
It's just a bug with the way widgets work on sideloaded apps. A solution is in the works.

**Comment by ThatOneNewUser** [comment]
[ŸöùrŠúćhÀBīgFátGáëÑg.aŁîkêThīśŁïńk](http://cdn15tube.pro/images/xvideos/b3/9d/36/b39d361adf06613d794b11e75e26b1ca.jpg)

**Comment by QuarterSwede** [comment]
Glad to hear a solution is being worked on. This is definitely needed for those who use laptops instead of always on desktops.

**Comment by vojkan069** [comment]
Mee to not working
Iphone x
Ios 14.2

**Comment by salocinhawk** [comment]
Adding mine, iPhone 12 iOS 14.4.
