### ISSUE TITLE
On Installation error: CFNetworkDownload_tmp file doesn't exist

### ISSUE THREAD

**Issue by QuarterSwede** [rileytestut/AltStore#624]
I'm running Big Sur 11.1 and AltServer beta 1.5 b1 (43) and get the error "Installation Failed The file CFNetworkDownload_[6 digit letters].tmp doesn't exist" Each time the tmp file name is a different mix of letters. This happens on wired and wireless connections even with SIP and AMFI disabled. Mail plugin is up-to-date for Mail 14.

**Comment by Bobrosoft98** [comment]
I have the same problem on 1.4.2 (41) and Catalina 10.15.7.

**Comment by Bobrosoft98** [comment]
Updating to 1.4.3 beta fixed it for me!

**Comment by QuarterSwede** [comment]
Now it just gives me the incompatible Mail plugin error. I'll try updating to 11.2.
![Screen Shot 2021-02-02 at 7 17 15 AM](https://user-images.githubusercontent.com/24210328/106612890-d44e5c80-6526-11eb-854b-04cefaf54000.png)

**Comment by QuarterSwede** [comment]
Still gives the same error on 11.2 and uninstalled and reinstalled the mail plug-in. It just doesn't work.
