### ISSUE TITLE
Solve :AltStore Mail plug-in not compatible with big sur

### ISSUE THREAD

**Issue by Romntic** [rileytestut/AltStore#628]
to solve this problem

https://i.imgur.com/m31olnS.jpg

just update altsore to Version 1.4.2 (41)

and do this one :) 

Turn off your Mac (Apple > Shut Down).
Hold down Command-R and press the Power button. ...
Wait for OS X to boot into the OS X Utilities window.
Choose Utilities > Terminal.
Enter csrutil disable.
Enter reboot.

then well work with plug mail without problem :)

**Comment by FlorianTDK** [comment]
> to solve this problem
> 
> https://i.imgur.com/m31olnS.jpg
> 
> just update altsore to Version 1.4.2 (41)
> 
> and do this one :)
> 
> Turn off your Mac (Apple > Shut Down).
> Hold down Command-R and press the Power button. ...
> Wait for OS X to boot into the OS X Utilities window.
> Choose Utilities > Terminal.
> Enter csrutil disable.
> Enter reboot.
> 
> then well work with plug mail without problem :)

Hi,

I've got the issue even with csrutil disabled.
I'm running on : 
- AltStore 1.4.2 (41) 
- Big Sur 11.2 Beta
- Mail 14.0 (3654.60.0.2.2)

Thanks

**Comment by thisIsP0G11** [comment]
ur a ń.gï-á

**Comment by QuarterSwede** [comment]
Disabling SIP is a terrible idea (and doesn’t work for everyone anyway).

**Comment by Romntic** [comment]
> Disabling SIP is a terrible idea (and doesn’t work for everyone anyway).

why ?

**Comment by QuarterSwede** [comment]
> > Disabling SIP is a terrible idea (and doesn’t work for everyone anyway).
> 
> why ?

It disables a good bit of macOS’ security.

**Comment by dkmahakur** [comment]
> to solve this problem
> 
> https://i.imgur.com/m31olnS.jpg
> 
> just update altsore to Version 1.4.2 (41)
> 
> and do this one :)
> 
> Turn off your Mac (Apple > Shut Down).
> Hold down Command-R and press the Power button. ...
> Wait for OS X to boot into the OS X Utilities window.
> Choose Utilities > Terminal.
> Enter csrutil disable.
> Enter reboot.
> 
> then well work with plug mail without problem :)


If you have updated to bigsur 11.4 beta 1 then you might have seen the annoying the plugin is not supported with mail version 14

here is the solution

step1.

On terminal:

sudo nano /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist

Step 2.

add the below content to the key section of the file you can see them before couple of lines before the and of the file,

<key>Supported11.4PluginCompatibilityUUIDs</key>

<array>

<string>D985F0E4-3BBC-4B95-BBA1-12056AC4A531</string>

</array>

Step 3.

Press CTRL+x Enter type Yes to save

Step 4.

sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle

Step 5.

sudo spctl --master-disable

Step 6.

Restart the mail activate the plugin and restart again

There it is everything works again!!

Enjoy, have a nice day don't forget to ask me questions if you face any issues with the above process or want to understand the steps.

**Comment by jokerham** [comment]
Seems none of the solution works for AltServer version 1.4.4 (51)

**Comment by rohankalgutkar** [comment]
dkmahakur's steps worked for me.

Would just like to add that in step 2, make the changes as per your macOS version. Since I was on macOS 11.4, I had to change it accordingly. And the exact syntax is as follows:

<key>Supported11.4PluginCompatibilityUUIDs</key>
<array>
        <string>D985F0E4-3BBC-4B95-BBA1-12056AC4A531</string>
</array>

**Comment by vertrix** [comment]
when i follow the steps, after activate the plugin in mail preferences,restart,the plugin its unchecked,how fix this.

**Comment by batoo696** [comment]
Works!!! Thank you very much!

**Comment by variable324** [comment]
@vertrix it happens to me too

**Comment by variable324** [comment]
how do I fix it

**Comment by MysticalOS** [comment]
So, i came here after re-enabling sip after resolving all other software that didn't like it enabled, and this is last thing that just won't work as long as sip is enabled. I find it hard to believe Riley wants people to run with SIP disabled to use altserver so there has to be another solution? I've tried all above work arounds but they all hinge on having SIP disabled. besides, the 11.4 and 11.5 uuids aren't missing. In fact to avoid THAT problem going forward he just added all the way up to 11.9. So waht else can be done besides disabling SIP?
