### ISSUE TITLE
Can't install AltStore - "server installed invalid response"

### ISSUE THREAD

**Issue by bugthug** [rileytestut/AltStore#63]
tried enabling 2FA, uninstalling both iTunes and AltServer ext. but nothing worked.

I get a "server installed invalid response" error each time I type in the password correctly:
![Capture22](https://user-images.githubusercontent.com/48732230/69277974-0279a200-0bea-11ea-9b2b-fa8ae1ba5874.PNG)

**Comment by Wycube** [comment]
The fix for Windows hasn’t been released yet.

**Comment by DeadEye423** [comment]
When will the fix be released?

**Comment by noah978** [comment]
This should be fixed on the latest versions of AltStore/Altserver. Closing this issue.
