### ISSUE TITLE
Cannot refresh AltStore with AltDaemon, even purchased beta.

### ISSUE THREAD

**Issue by gpolanco21** [rileytestut/AltStore#646]
Currently running IOS 12.3.1 on an iPad Pro, I have it successfully working on my other devices but have tried everything and cannot get it to refresh with out a computer on this device. Does anyone know what to do? I have restarted my device, I have deleted both AltStores and AltDaemon, then reinstalled both AltStores before AltDaemon, I have tried to find an IPA or deb file to install AltDaemon through Filza but have had no luck finding the file. (So if anyone has it I’d like to try that.) or any other ideas. Thanks for reading hope we can figure out.

**Comment by Doregon** [comment]
Get the Cr4shed app from Cydia and then try resigning an app/installing without a computer. Cr4shed should get a log. 

When you get the log, at the top it should say EXECUTION_TYPE, next to that does it say SIGTRAP?
