### ISSUE TITLE
Installation Failed: The data couldn’t be read because it isn’t in the correct format.

### ISSUE THREAD

**Issue by SEWsam** [rileytestut/AltStore#65]
Title.
Mail Plugin is installed, not sure if my logged in mail account needs to be my iCloud account, but it is currently not. My apple ID is typed correctly, I am NOT using an app-specific password. What should I do?

**Comment by damianvila** [comment]
Maybe Keychain related? No idea, but I'm on the same camp. I ensured I was using the same email address as my Apple ID (I normally use one of the aliases), but it didn't work. Changed my Apple ID password (it cleared app-specific passwords), still didn't work. Re-installed plugin, didn't work. Re-installed AltSore, didn't work. I've run out of ideas.

**Comment by Samplasion** [comment]
It just happened to me and I'm on a clean install of Catalina. I remember it working a couple of months ago on Mojave, so the OS version may be the issue?

**Comment by SEWsam** [comment]
> Maybe Keychain related? No idea, but I'm on the same camp. I ensured I was using the same email address as my Apple ID (I normally use one of the aliases), but it didn't work. Changed my Apple ID password (it cleared app-specific passwords), still didn't work. Re-installed plugin, didn't work. Re-installed AltSore, didn't work. I've run out of ideas.

So, wait, It just stopped working again for you? Because, two days ago, you said this on a different issue:

> Was in this camp too. Had to change my Apple ID password (that erased all the app-specific passwords), and it worked. It seems that, for some reason, macOS ties the app with the app-specific password and that prevents from correctly signing-in.

What has changed on your system since? Could you try to track down the issue?

**Comment by suderman** [comment]
I’m having this same problem on Mojave. The mail plugin is installed and the only account I have enabled is my iCloud.

![](https://i.suderman.net/LNjYny.jpg)

**Comment by orisraeli** [comment]
I'm also having this issue.
First time install on a XS Max (iOS 13.2.3), MacOS Mojave 10.14.6

**Comment by nahcir** [comment]
Same here. Just tried it on two different MacBooks, even went on ahead and tried creating new Admin-accounts on both of them, same always the same results. It sends the 2FA-code to my phone, I enter it in the AltServer-prompt and shortly after, this error occurs :-/

**Comment by stevewalshbuds** [comment]
+1 here. Worked fine a few days ago for my iPhone XS, but now it's not working for my iPad Pro 11".

**Comment by nighto** [comment]
Same here. Tried restarting both Mail and AltServer and it does not work.

**Comment by SEWsam** [comment]
Hello. Now I am having a new issue. I tried re-installing the mail plugin again, hoping to fix the original issue, and now AltServer always freezes when installing the mail plugin

**Comment by quarroz** [comment]
> Hello. Now I am having a new issue. I tried re-installing the mail plugin again, hoping to fix the original issue, and now AltServer always freezes when installing the mail plugin

I add the same yesterday. Have you try to install "manually" the mail plug-in ? You just copy the mail plug-in folder in the Altserver app and put that in /library/Mail/bundle. Then you go in the Mail app - > preferences - > bundle and you accept that Mail use this plug-in.

**Comment by SEWsam** [comment]
> > Hello. Now I am having a new issue. I tried re-installing the mail plugin again, hoping to fix the original issue, and now AltServer always freezes when installing the mail plugin
> 
> I add the same yesterday. Have you try to install "manually" the mail plug-in ? You just copy the mail plug-in folder in the Altserver app and put that in /library/Mail/bundle. Then you go in the Mail app - > preferences - > bundle and you accept that Mail use this plug-in.

Do you still get the original issue mentioned in this thread, or did this fix it for you?

**Comment by quarroz** [comment]
> > > Hello. Now I am having a new issue. I tried re-installing the mail plugin again, hoping to fix the original issue, and now AltServer always freezes when installing the mail plugin
> > 
> > 
> > I add the same yesterday. Have you try to install "manually" the mail plug-in ? You just copy the mail plug-in folder in the Altserver app and put that in /library/Mail/bundle. Then you go in the Mail app - > preferences - > bundle and you accept that Mail use this plug-in.
> 
> Do you still get the original issue mentioned in this thread, or did this fix it for you?

No I still get the original issue afterward. But first I was having exactly the freezing issue with the installation of the plug-in

**Comment by rmilejcz** [comment]
This started happening to me after upgrading to iOS 13.2.3

**Comment by neoyoli** [comment]
Same problem here, plugin is supposedly installed but can't see it in Mail.

**Comment by nahcir** [comment]
> 
> 
> Same problem here, plugin is supposedly installed but can't see it in Mail prefs.
Then that's a different issue, I suppose. The plugin does get installed and loaded, at least for me.

**Comment by neoyoli** [comment]
Actually I was stupid, plugin is enabled now, but two things:
- Altserver can only see my phone when it is connected to the mac (even though iTunes sees it over WiFi)
- Doesn't accept AppleID/password, even though it's the correct one.
![Screenshot 2019-11-27 at 18 52 49](https://user-images.githubusercontent.com/2356354/69748077-db6e2380-1147-11ea-86d7-782a5080b0ae.png)

**Comment by SEWsam** [comment]
> Actually I was stupid, plugin is enabled now, but two things:
> 
> * Altserver can only see my phone when it is connected to the mac (even though iTunes sees it over WiFi)
> * Doesn't accept AppleID/password, even though it's the correct one.
>   ![Screenshot 2019-11-27 at 18 52 49](https://user-images.githubusercontent.com/2356354/69748077-db6e2380-1147-11ea-86d7-782a5080b0ae.png)

Huh, still seems like a different issue. I’m still getting the originally mentioned “Data isn’t in the correct format” issue. This thread is getting a decent amount of attention, I’m surprised Riley doesn’t seem to have taken a look at this yet.

**Comment by junbao1314** [comment]
i have the same issue. and i search pages, found this https://www.reddit.com/r/Delta_Emulator/comments/e0ssa9/altstore_trouble/
Riley (author) had found a fix, so i think altstore will be updated as soon.

good luck! thanks Riley.

**Comment by lbibass** [comment]
I am also having the same issue.

**Comment by lbibass** [comment]
Okay, nevermind! According to twitter, there was an update about an hour ago, and it's fixed the issue for me.

**Comment by SEWsam** [comment]
> Okay, nevermind! According to twitter, there was an update about an hour ago, and it's fixed the issue for me.

I can confirm this update has fixed the issue for me. Thanks everyone who participated in this post. 
I'm closing the issue
