### ISSUE TITLE
The operation couldn't be completed. (kCFErrorDomainCFNetwork error -1200.)

### ISSUE THREAD

**Issue by wavewav** [rileytestut/AltStore#650]
I was not able to re-verify my apps using AltStore so I deleted them along with AltStore as they were no longer signed. I got access to my AppleID again and tried to reinstall AltStore on my iPhone 6 and this error message popped up, this has never occurred before.

![Screen Shot 2021-01-27 at 16 59 53](https://user-images.githubusercontent.com/78089890/106000920-c8970c00-60c8-11eb-97cf-d3d010a7727b.png)

**Comment by alialiali63** [comment]
Am sorry am not answering but I have the same issue 
![Uploading image.jpg…]()

**Comment by alialiali63** [comment]
Anyone with a solution

**Comment by jamie1192** [comment]
@alialiali63 and @wavewav try connecting to a VPN, oddly enough this solved this same issue for me.

**Comment by efcboy** [comment]
> @alialiali63 and @wavewav try connecting to a VPN, oddly enough this solved this same issue for me.

worked for me, thanks!
