### ISSUE TITLE
Installing a fresh copy of the AltStore app crashes on startup.

### ISSUE THREAD

**Issue by DesperatePea** [rileytestut/AltStore#652]
I recently had to re-install Altstore on my Iphone X. However, after successfully reinstalling the app, and verifying it, attempting to open it makes it simply crash on startup.

I have an Iphone X, running iOS 14.3

**Comment by fuguangxin** [comment]
I have same the error when using AltDeploy.It only happens above ios12.
Here are some error messages.
kernel	AMFI: '/private/var/containers/Bundle/Application/E26B8752-978B-4D7B-9897-89E1561D048E/unc0ver.app/Undecimus' does not pass CT evaluation, result: 0x80008
kernel	AMFI: '/private/var/containers/Bundle/Application/E26B8752-978B-4D7B-9897-89E1561D048E/unc0ver.app/Undecimus': Unrecoverable CT signature issue, bailing out.
kernel	AMFI: code signature validation failed.

**Comment by duongdev** [comment]
Same here, after the latest iOS 14 update...

**Comment by WillMons** [comment]
Same for me; running iPadOS 14.3 as well as iOS 14.3.

**Comment by MirTeiwaz** [comment]
Happens on iPadOS 13.4.1 as well (iPad Pro 2018, 12.9"). 
This happened also on my iPhone 12 mini (iOS 14.1).

**Comment by oshigoto** [comment]
Cannot launch the AltStore after re-installing with AltServer.
Didn't get any notification or alert on Desktop while trying to install the AltStore.
I'm on iOS 13.1.3 with iPhone 7

**Comment by Unrealluver** [comment]
same for me

**Comment by aizuchan** [comment]
Same. After a fresh install, it crashed on startup.
I also tried with AltStore 1.5.1 Beta, Same result.

iPadOS 14.1 with iPad Mini 5

**Comment by Fradri** [comment]
Same after a fresh install, crash on startup.
IOS 13.7 on iPhone 8

**Comment by saifotain** [comment]
- [ ]

**Comment by sethbryant** [comment]
iPhone 12 Pro, iOS 14.1. 
Tried AltServer 1.3.3 and 1.4.1. 
Allows me to trust profile, but AltStore crashes on open.

**Comment by huozhiwei** [comment]
Same as you when I reinstall altstore, now I am in jail~~~

**Comment by huozhiwei** [comment]
iPhone 7,iOS 13.5

**Comment by CoreISP** [comment]
It looks like Apple revoked the trust certificates yesterday when they deployed their new intermediate certificates. Not sure what AltStore does that causes this behaviour, as sideloaded apps installed through MacOS methods continue to function without any problem and do not hit the CT evaluation errors, but I'm sure it can probably be fixed.

**Comment by reubn** [comment]
There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
Restart AltServer.

Just resigned all my apps with no trouble.

**Comment by aa1201** [comment]
How can i replace it from my pc (Window)?

**Comment by reubn** [comment]
> How can i replace it from my pc (Window)?

I don't have a Windows installation to test on, sorry.

**Comment by Civa030203** [comment]
> How can i replace it from my pc (Window)?

go to program files / program files(x86) (if you using 64bit os) and altserver, replace apple.pem

**Comment by Civa030203** [comment]
> There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> Restart AltServer.
> 
> Just resigned all my apps with no trouble.

it works also windows, thank you so much!

**Comment by MirTeiwaz** [comment]
> There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> Restart AltServer.
> 
> Just resigned all my apps with no trouble.

This worked on my iPhone 12 mini (iOS 14.1), but the problem somehow still persits on my iPad Pro 2018/12.9" (iPadOS 13.4.1)...still crashes upon launch even after replacing the apple.pem file.

**Comment by DesperatePea** [comment]
> There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> Restart AltServer.
> 
> Just resigned all my apps with no trouble.

This worked on my iphone X! The app opened with no problem and everything seems to work just fine :D

**Comment by Vinogradov-Mikhail** [comment]
> > There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> > Restart AltServer.
> > Just resigned all my apps with no trouble.
> 
> it works also windows, thank you so much!

I tried this on Windows but the app still crashes after launch (everything works fine for my Mac after replacing same apple.pem)

**Comment by Tony-Sol** [comment]
same

**Comment by skeebsy** [comment]
> > How can i replace it from my pc (Window)?
> 
> go to program files / program files(x86) (if you using 64bit os) and altserver, replace apple.pem

hi, I don't know much about anything / don't know how to use github (would have messaged privately if I could figure out how) but I want my tweaked apps back, so... how does one replace the apple.pem? I found it in the folder and all but I don't know how  to replace it
thanks guys 
please be nice I know I am extremely out of my domain here

**Comment by reubn** [comment]
> > > How can i replace it from my pc (Window)?
> > 
> > 
> > go to program files / program files(x86) (if you using 64bit os) and altserver, replace apple.pem
> 
> hi, I don't know much about anything / don't know how to use github (would have messaged someone privately if I could figure out how) but I want my tweaked apps back, so... how does one replace the apple.pem? I found it in the folder and all but I don't know how to replace it. I'm on windows
> thanks guys
> please be nice I know I am extremely out of my domain here

Download the file, rename the old one to something else, and copy the new `apple.pem` into the folder

**Comment by SpoonMcForky** [comment]
Replacing the `apple.pem` allows AltStore to be opened, but for me, sideloaded apps crash on launch.

**Comment by WillMons** [comment]
> Replacing the `apple.pem` allows AltStore to be opened, but for me, sideloaded apps crash on launch.

same for me

**Comment by DesperatePea** [comment]
> > Replacing the `apple.pem` allows AltStore to be opened, but for me, sideloaded apps crash on launch.
> 
> same for me

Sadly i spoke too soon.  I was able to reinstall and open AltStore, but sideloaded apps crash on startup :(

**Comment by stev0760** [comment]
I replaced the apple.pem file and got Altstore reinstalled on my phone but my sideloaded apps also still crash.  I'm on windows but I also have access to a Mac, I just haven't tried using the Mac with Altstore yet since it's not my main machine.  Any ideas? Are the sideloaded apps still stuck using the old certificate maybe?  I'm still somewhat new as to how all this works.

**Comment by baldurr12** [comment]
not working in windows

**Comment by SpoonMcForky** [comment]
https://twitter.com/altstoreio/status/1355624901093322762

**Comment by skeebsy** [comment]
> > > > How can i replace it from my pc (Window)?
> > > 
> > > 
> > > go to program files / program files(x86) (if you using 64bit os) and altserver, replace apple.pem
> > 
> > 
> > hi, I don't know much about anything / don't know how to use github (would have messaged someone privately if I could figure out how) but I want my tweaked apps back, so... how does one replace the apple.pem? I found it in the folder and all but I don't know how to replace it. I'm on windows
> > thanks guys
> > please be nice I know I am extremely out of my domain here
> 
> Download the file, rename the old one to something else, and copy the new `apple.pem` into the folder

am I missing something? when I click the link to the new apple.pem file it takes me to another tab that's just the "certificate" (no idea if it's actually called that but idk what else to call it). I don't see anywhere to download it from

**Comment by SpoonMcForky** [comment]
> > > > > How can i replace it from my pc (Window)?
> > > > 
> > > > 
> > > > go to program files / program files(x86) (if you using 64bit os) and altserver, replace apple.pem
> > > 
> > > 
> > > hi, I don't know much about anything / don't know how to use github (would have messaged someone privately if I could figure out how) but I want my tweaked apps back, so... how does one replace the apple.pem? I found it in the folder and all but I don't know how to replace it. I'm on windows
> > > thanks guys
> > > please be nice I know I am extremely out of my domain here
> > 
> > 
> > Download the file, rename the old one to something else, and copy the new `apple.pem` into the folder
> 
> am I missing something? when I click the link to the new apple.pem file it takes me to another tab that's just the "certificate" (no idea if it's actually called that but idk what else to call it). I don't see anywhere to download it from

You need to save the text as a txt document and rename is to apple.pem, although the issue should be fixed in a bit

>https://twitter.com/altstoreio/status/1355624901093322762

**Comment by affanblaze** [comment]
> > There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> > Restart AltServer.
> > Just resigned all my apps with no trouble.
> 
> This worked on my iphone X! The app opened with no problem and everything seems to work just fine :D

Hey brother how did u do it? Can u tell me please?

**Comment by affanblaze** [comment]
> There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> Restart AltServer.
> 
> Just resigned all my apps with no trouble.

Did it on my Xr 13.5 still crashing

**Comment by DesperatePea** [comment]
> > > There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> > > Restart AltServer.
> > > Just resigned all my apps with no trouble.
> > 
> > 
> > This worked on my iphone X! The app opened with no problem and everything seems to work just fine :D
> 
> Hey brother how did u do it? Can u tell me please?

Sorry, as i stated in a previous message, i spoke too soon. AltStore opens, but not sideloaded apps: However, a fix will come out soon: https://twitter.com/altstoreio/status/1355624901093322762

**Comment by affanblaze** [comment]
> > > > There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> 
> > > > Restart AltServer.
> 
> > > > Just resigned all my apps with no trouble.
> 
> > > 
> 
> > > 
> 
> > > This worked on my iphone X! The app opened with no problem and everything seems to work just fine :D
> 
> > 
> 
> > Hey brother how did u do it? Can u tell me please?
> 
> 
> 
> Sorry, as i stated in a previous message, i spoke too soon. AltStore opens, but not sideloaded apps: However, a fix will come out soon: https://twitter.com/altstoreio/status/1355624901093322762 

Patch came 👌🏻😄 go check @altstore.io on twitter.

**Comment by DesperatePea** [comment]
> > > > > There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> > 
> > 
> > > > > Restart AltServer.
> > 
> > 
> > > > > Just resigned all my apps with no trouble.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > This worked on my iphone X! The app opened with no problem and everything seems to work just fine :D
> > 
> > 
> > > 
> > 
> > 
> > > Hey brother how did u do it? Can u tell me please?
> > 
> > 
> > Sorry, as i stated in a previous message, i spoke too soon. AltStore opens, but not sideloaded apps: However, a fix will come out soon: https://twitter.com/altstoreio/status/1355624901093322762
> 
> Patch came 👌🏻😄 go check @altstore.io on twitter.

well i installed the patch, updated altstore and then tried to install a sideloaded app...but still no luck. Sideloaded apps still crash on startup.

**Comment by allyalla** [comment]
Search fresh sideloadly (windows) for loading uncover and then jb (use aeroplane mode)=on 13.5 and in JB state again. Altserver is not fixed (what was the point to write in those stpd tweets like "it is recomended" to not refresh yor apps signature? It is "not recomended" to jump from the 10th floor too? But ... you can anyways). "Forbiden" and "disable background refresh" would be much suitable words in this context - nope?

**Comment by Puschkin-Vodka** [comment]
THX.. sideloady worked for me! ;)

**Comment by FrancoOppini** [comment]
Hi all, I solved yesterday with the beta version of altserver ( with a windows PC). Here the link of the guide and version I followed: https://www.idownloadblog.com/2021/01/31/altstore-1-4-3-beta-fix-app-crashing/
I hope it work also for you

**Comment by DesperatePea** [comment]
After updating and installing the latest version of altstore, i can confirm now that sideloaded apps and altstore is working 100% fine.

**Comment by Masoud-Studio** [comment]
thank developer of altserver
but is dosent work yet... iOS 12.4.8, iPhone 6
i install new version (1.4.3) restart my pc : altstore install sucsess, but crash on launch
replace 1.5 apple.pem : altstore install sucsess, but crash on launch

nobody solved this problem?
anybody have apple.pem works right?

**Comment by Puschkin-Vodka** [comment]
> 
> 
> thank developer of altserver
> but is dosent work yet... iOS 12.4.8, iPhone 6
> i install new version (1.4.3) restart my pc : altstore install sucsess, but crash on launch
> replace 1.5 apple.pem : altstore install sucsess, but crash on launch
> 
> nobody solved this problem?
> anybody have apple.pem works right?

Try "Sideloady" ..and use it like Cydia Impactor

**Comment by Masoud-Studio** [comment]
> 
> 
> > thank developer of altserver
> > but is dosent work yet... iOS 12.4.8, iPhone 6
> > i install new version (1.4.3) restart my pc : altstore install sucsess, but crash on launch
> > replace 1.5 apple.pem : altstore install sucsess, but crash on launch
> > nobody solved this problem?
> > anybody have apple.pem works right?
> 
> Try "Sideloady" ..and use it like Cydia Impactor
whts sideloady? i search it, but cant found anything about is
can u link me? thanks

**Comment by Masoud-Studio** [comment]
> 
> 
> > thank developer of altserver
> > but is dosent work yet... iOS 12.4.8, iPhone 6
> > i install new version (1.4.3) restart my pc : altstore install sucsess, but crash on launch
> > replace 1.5 apple.pem : altstore install sucsess, but crash on launch
> > nobody solved this problem?
> > anybody have apple.pem works right?
> 
> Try "Sideloady" ..and use it like Cydia Impactor

whts sideloady? i search it, but cant found anything about is
can u link me? thanks

**Comment by Masoud-Studio** [comment]
> 
> 
> > > thank developer of altserver
> > > but is dosent work yet... iOS 12.4.8, iPhone 6
> > > i install new version (1.4.3) restart my pc : altstore install sucsess, but crash on launch
> > > replace 1.5 apple.pem : altstore install sucsess, but crash on launch
> > > nobody solved this problem?
> > > anybody have apple.pem works right?
> > 
> > 
> > Try "Sideloady" ..and use it like Cydia Impactor
> 
> whts sideloady? i search it, but cant found anything about is
> can u link me? thanks

ok.
i search in youtube, finally found sideloadly. (for who dosent know what is sideloadly: this is an windows app for install ipa on iphone) its easy to install your ipa
watch this video: https://www.youtube.com/watch?v=D6f3ZzJS3qg
by the way: if there is the orginal app on ur phone: sideloadly cant install the ipa (i wanted to install insta rocket, i use orginal instagram too, but sideloadly app couldn't install insta rocket! finally i removed orginal instagram from my phone, then sideloadly install insta rocket sucess!)

untill the problem of altstore be solve, its better to use sideloadly application

**Comment by AlexOnGithub69** [comment]
What if I couldn't update further than 13.3.1? I have enough space for ios 14 but I can't update (The phone is the iPhone XR) and apparently newer versions don't work on 13.3.1 due to it having some glitch (I forgot but I think it's related to ios 14 widgets). I believe I can't update because I used to be jailbroken a few months ago through Altstore and I incorrectly disabled the jailbreak before deleting both unc0ver and Altstore. Also, old versions of Altstore do not work for me either and they always crash on opening.

**Comment by AlexOnGithub69** [comment]
(I'm currently using Windows)
