### ISSUE TITLE
Alt Store Crashes Up On Opening

### ISSUE THREAD

**Issue by joe-gannon11** [rileytestut/AltStore#653]
Hello All, 

I had to redownload alr store as I forgot to refresh my apps and now it won’t open I can provide a video to show you guys if needed I am using;

iPhone 12 Pro Max 

Mac 2015 - Big Sur 

I am NOT willing to jailbreak my phone that’s why I used alt store

please help I bought some tweaks and can’t get them back!

**Comment by Volkki** [comment]
on my device iphone 11 with IOS 14.5 wasnt open alt store, its crashing every time.
can anyone help me?

**Comment by Navjot67** [comment]
Same here on ios 14.3 ip12promax crash on click

**Comment by huozhiwei** [comment]
The same as yours, my device is iPhone 7, ios 13.5, it cost me one day,，but I didn't solve the crash up problem, I even changed at least three apple id.

**Comment by joe-gannon11** [comment]
It’s very frustrating! I’m not sure why this is hopefully someone will have a solution!

**Comment by qDave17** [comment]
Same for me iPhone 11 iOS 14.0, i wanted to reinstall altstore because it expired. It just crashed on startup.

https://user-images.githubusercontent.com/78225290/106303753-2cedd300-6263-11eb-92e4-c6395f1a33cf.MP4

**Comment by cuongluong** [comment]
> Same for me iPhone 11 iOS 14.0, i wanted to reinstall altstore because it expired. It just crashed on startup.
> 
>  proof.MP4

same

**Comment by maxsonboy** [comment]
Same for my phone 11 pro iso 13.3🤦🏽‍♂️

**Comment by maria-canals** [comment]
same for my iphone X

**Comment by hansdampf01** [comment]
Didnt Apple just revoked their certificates or something?

**Comment by yifc** [comment]
Is there any way to bypass it for now?

**Comment by reubn** [comment]
There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
Restart AltServer.

Just resigned all my apps with no trouble.

**Comment by joe-gannon11** [comment]
Please could you give a step by step guide to instal?

**Comment by reubn** [comment]
This is only for macOS. 

There are only 3 steps:

1. Download [this file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem) (the new certificate)
2. Replace `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem` (the old certificate) with the file you've downloaded (Right Click -> Show Package Content on the `.app` and `.bundle`)
3. Restart AltServer

**Comment by joe-gannon11** [comment]
Okay thanks when I try download the certificate it domes up with a loads of letter and numbers is this correct?

**Comment by reubn** [comment]
> Okay thanks when I try download the certificate it domes up with a loads of letter and numbers is this correct?

Yes!

**Comment by joe-gannon11** [comment]
How do I download it?

**Comment by reubn** [comment]
> How do I download it? And replace the other one?

`Cmd-S`, and then just copy the new file on top of the old one

**Comment by joe-gannon11** [comment]
So do I need to delete the old one?

**Comment by reubn** [comment]
> So do I need to delete the old one?

Yes, or rename it to `apple.pem.old` or anything you'd like really

**Comment by joe-gannon11** [comment]
The file has downloaded as a pen.webarchive is this correct?

**Comment by reubn** [comment]
> The file has downloaded as a pen.webarchive is this correct?

Nope, should be `apple.pem`

**Comment by joe-gannon11** [comment]
I managed to get it as a pem file and now I install as normal?

**Comment by joe-gannon11** [comment]
Managed to get the right file and instal correctly but once I open alt sever and try to instal it crashes?

**Comment by Navjot67** [comment]
Does this method work?

**Comment by reubn** [comment]
> Managed to get the right file and instal correctly but once I open alt sever and try to instal it crashes?

I can't really help anymore I'm afraid. The steps I took are the exact same as I illustrated above. I have resigned all my apps, and they're fully functional after swapping the `.pem`.

**Comment by joe-gannon11** [comment]
Thanks for trying I can not get it working do you know when the next update is?

**Comment by nahcir** [comment]
> 
> 
> > Managed to get the right file and instal correctly but once I open alt sever and try to instal it crashes?
> 
> I can't really help anymore I'm afraid. The steps I took are the exact same as I illustrated above. I have resigned all my apps, and they're fully functional after swapping the `.pem`.

The swapping of the PEM-file worked for me on Windows, too. However, after successfully installing AltStore, whenever I try to refresh my sideloaded apps, now they just crash immedeately after opening them up. Hm ...

**Comment by qDave17** [comment]
we should wait for the fix from the dev, because he is aware of the bug.

**Comment by joe-gannon11** [comment]
Do we know when the new update is coming?

**Comment by qDave17** [comment]
he said soon, idk what soon means for him...

**Comment by fuguangxin** [comment]
> This is only for macOS.
> 
> There are only 3 steps:
> 
> 1. Download [this file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem) (the new certificate)
> 2. Replace `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem` (the old certificate) with the file you've downloaded (Right Click -> Show Package Content on the `.app` and `.bundle`)
> 3. Restart AltServer



> > Managed to get the right file and instal correctly but once I open alt sever and try to instal it crashes?
> 
> I can't really help anymore I'm afraid. The steps I took are the exact same as I illustrated above. I have resigned all my apps, and they're fully functional after swapping the `.pem`.

I suspect that AltDeploy has the same error, but after trying your method, the same opening crashes, can you give me some help? Thank you.

**Comment by sunnyyylai** [comment]
> 1. this file

Hi.  I tried applied this method and confirm alt store does work after replacing the cert file.  However any ipa installs afterward still give force closes.  Any idea?

Thank you In advance!

**Comment by sunnyyylai** [comment]
> > > Managed to get the right file and instal correctly but once I open alt sever and try to instal it crashes?
> > 
> > 
> > I can't really help anymore I'm afraid. The steps I took are the exact same as I illustrated above. I have resigned all my apps, and they're fully functional after swapping the `.pem`.
> 
> The swapping of the PEM-file worked for me on Windows, too. However, after successfully installing AltStore, whenever I try to refresh my sideloaded apps, now they just crash immedeately after opening them up. Hm ...

Just want to say thank you here!  And exact same case here

**Comment by p4cm4n** [comment]
> There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> Restart AltServer.
> 
> Just resigned all my apps with no trouble.

Worked perfectly here in windows, the only difference is the file router, which in windows is:

"C:\Program Files (x86)\AltServer"

**Comment by raddi** [comment]
> This is only for macOS.
> 
> There are only 3 steps:
> 
> 1. Download [this file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem) (the new certificate)
> 2. Replace `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem` (the old certificate) with the file you've downloaded (Right Click -> Show Package Content on the `.app` and `.bundle`)
> 3. Restart AltServer

Thank you so much, it works but i had to do it differently:

Click on this link:
https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem

**Comment by sunnyyylai** [comment]
> > There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
> > Restart AltServer.
> > Just resigned all my apps with no trouble.
> 
> Worked perfectly here in windows, the only difference is the file router, which in windows is:
> 
> "C:\Program Files (x86)\AltServer"

Do sideloaded apps work or will they force close?

**Comment by joe-gannon11** [comment]
I have retried and now it says alt sever is dameaged please move to bin 
 This is what I’ve done I would love to know if it’s correct

**Comment by joe-gannon11** [comment]
https://share.icloud.com/photos/0e8rdsJLNIe2jEkFcvfuXGNIw#Faversham

Use this iCloud link to preview

**Comment by reubn** [comment]
> I have retried and now it says alt sever is dameaged please move to bin
> This is what I’ve done I would love to know if it’s correct

I think you've broken code-signing somehow. `Right Click -> Open` on `AltServer.app`, accept any prompts. You might have to remove extended attributes from `AltServer.app`, or if that fails, resign it.

**Comment by reubn** [comment]
[This](https://we.tl/t-gfAbxkPpLw) is my modified copy of `AltStore.app`, if this doesn't work then other issues are at play.

**Comment by joe-gannon11** [comment]
You are a legend I copied the files and it works if you are looking for the fix use the file attached above until the app is updated therefore this case is closed

**Comment by yifc** [comment]
FYI, I replaced the `.pem` file content and it works. Thanks guys!
