### ISSUE TITLE
Altstore does not open

### ISSUE THREAD

**Issue by yun90s** [rileytestut/AltStore#657]
https://user-images.githubusercontent.com/78266659/106359361-a1337f80-6312-11eb-929a-cf58921e6eb7.mov

**Comment by Tony-Sol** [comment]
same

**Comment by osbre** [comment]
Hello. I have the exact same problem. I installed it from **Big Sur**.

My IOS version: **14.3**
iPhone SE.

**Comment by GiovanH** [comment]
Duplicate of https://github.com/rileytestut/AltStore/issues/652

**Comment by chichiwei** [comment]
> Hello. I have the exact same problem. I installed it from **Big Sur**.
> 
> My IOS version: **14.3**
> iPhone SE.

same

**Comment by OdaFolx** [comment]
This has been addressed on their Twitter ( https://twitter.com/altstoreio/status/1355273701068054532 ).
