### ISSUE TITLE
How to publish an app to AltStore's listing? 

### ISSUE THREAD

**Issue by talhabalaj** [rileytestut/AltStore#659]
Hey, I admire your work a lot. I was wondering how can one publish an app to the AltStore? I have an `apps.json` file that contains a list of apps shown in AltStore (I guess). It would be awesome if someone could guide me?

**Comment by noah978** [comment]
Glad to hear you are interested! AltStore has a Sources feature that is currently in Beta and will be headed to the public release in the future after some more development. For now, please refer to https://noah978.gitbook.io/altstore-docs/sources to learn how to build your own Source for app distribution.

**Comment by talhabalaj** [comment]
Thank you so much
