### ISSUE TITLE
App refresh issue: NSURLErrorDomain error -1011

### ISSUE THREAD

**Issue by Mitch90** [rileytestut/AltStore#66]
First of all, thank you so much for all the work and time that has been put into this amazing project. I have been using Altstore for the past months and it's truly awesome! Unfortunately this week I encountered a problem while trying to refresh my apps.

I cannot seem to be able to refresh Altstore nor Delta, this is the error is giving me:
> The operation couldn't be completed.
> (NSURLErrorDomain error -1011)

macOS: Catalina 10.15.1
iOS: 13.2.3

**Comment by stevewalshbuds** [comment]
I am also experiencing the same issue. iPhone XS. Will need to refresh in a few days.

**Comment by mariomerco** [comment]
I'm also in the same situation. iPhone 11 running here with macos Catalina

**Comment by Zolotkey** [comment]
I have the same issue. I tried installing altstore on a second device and that’s when the issue started. We’re you all doing the same? I am getting an error when I try and reinstall while plugged in stating the data cant be read after putting in my AppleID info.

**Comment by Mitch90** [comment]
> I have the same issue. I tried installing altstore on a second device and that’s when the issue started. Were you all doing the same? I am getting an error when I try and reinstall while plugged in stating the data cant be read after putting in my AppleID info.

Actually no, I've never installed AltStore on a new device. I suspect the issue is somewhat related to the iOS version, since that's the only thing that changed for me last week.

**Comment by Mitch90** [comment]
AltStore 1.1.1 fixed this issue, so I'm closing this issue. @Zolotkey if the new AltStore release does not resolve it for you, it's better if you open a new issue because it must be related to something else.

**Comment by mailinglists35** [comment]
seeing this on device.
ipad air 3 wifi 13.3, altstore windows latest released version, windows 10 1809 64 bit, latest itunes 64 bit

**Comment by mailinglists35** [comment]
I’ve had this apple id previously working on reprovision on another device - then on that device I switched from unc0ver to checkra1n without deleting the certificate first. could that be the cause? altserver warns me on install that it will stop working on other devices then I click OK then installs on device. but further on device altstore gives the 1011 error when attempting to login. it’s strange that the same apple id works okay on altserver but not on altstore. tried even the latest altserver beta...

**Comment by wires160** [comment]
I was receiving this error so tried reinstalling AltStore from my computer. I received an error at that point stating that I needed to accept new terms and conditions from my developer account. After logging in to developer.apple.com and accepting the terms, I am no longer receiving the nsurlerrordomain -1011 error. Wanted to pass this along in case anybody else is receiving the same error.

**Comment by TylerHobanDotCom** [comment]
> I was receiving this error so tried reinstalling AltStore from my computer. I received an error at that point stating that I needed to accept new terms and conditions from my developer account. After logging in to developer.apple.com and accepting the terms, I am no longer receiving the nsurlerrordomain -1011 error. Wanted to pass this along in case anybody else is receiving the same error.

Accepting the new terms also worked for me, thanks man!

**Comment by JMWrpi** [comment]
> > I was receiving this error so tried reinstalling AltStore from my computer. I received an error at that point stating that I needed to accept new terms and conditions from my developer account. After logging in to developer.apple.com and accepting the terms, I am no longer receiving the nsurlerrordomain -1011 error. Wanted to pass this along in case anybody else is receiving the same error.
> 
> Accepting the new terms also worked for me, thanks man!

me2

**Comment by hly3825** [comment]
> I was receiving this error so tried reinstalling AltStore from my computer. I received an error at that point stating that I needed to accept new terms and conditions from my developer account. After logging in to developer.apple.com and accepting the terms, I am no longer receiving the nsurlerrordomain -1011 error. Wanted to pass this along in case anybody else is receiving the same error.

me2

**Comment by Twentyrru** [comment]
Please accept newer License Agreement at https://developer.apple.com/account/
