### ISSUE TITLE
Installation failed: This device is already registered with this team.

### ISSUE THREAD

**Issue by ggeraleal** [rileytestut/AltStore#663]
What does this mean? Already using 1.4.3 beta that fixes the revoked apple pem, but now Altstore won't be installed on my iPad. Already tried installing it on my iPhone and it worked like a charm at first try. But when I try to install it on my iPad (where I do use it) it says this. Was willing to join the Patreon, to use it on both of my devices at the same time. But I fear that this error will keep happening of me not being able to install it on my iPad.. any ideas on what to do?

**Comment by gummykage** [comment]
On reddit someone solved this by uninstalling altstore completely and then reinstalling. He did remove altstore also.

**Comment by cutieshy** [comment]
> On reddit someone solved this by uninstalling altstore completely and then reinstalling. He did remove altstore also.

not working on my side, even tried reinstalling the mail plug-in

**Comment by Unrealluver** [comment]
> > On reddit someone solved this by uninstalling altstore completely and then reinstalling. He did remove altstore also.
> 
> not working on my side, even tried reinstalling the mail plug-in

NOT work for me too

**Comment by parazyt75** [comment]
same message for me on ipad mini 5 ios13.5
When using Altserver 1.4.3 beta -->Installation failed: This device is already registered with this team.
When using Altserver 1.4.2 --> sideload to device OK but the app crash

**Comment by Gal3riel** [comment]
> same message for me on ipad mini 5 ios13.5
> When using Altserver 1.4.3 beta -->Installation failed: This device is already registered with this team.
> When using Altserver 1.4.2 --> sideload to device OK but the app crash

Same behavior here, iPad Pro 4th gen iOS 14.3

**Comment by parazyt75** [comment]
Same behavior with the new beta 1.4.3 (50)

**Comment by parazyt75** [comment]
[SOLVED]

It's working with a new fresh Apple ID that I've create only for sideloading AltStore & Unc0ver
IpadMini5, iOS 13.5, Altserver 1.4.3 (50)

**Comment by ANTONBORODA** [comment]
Same here. iPad Pro, iOS 14.4.
I have a clean appleid just for sideloading on this device and it stopped working with 1.4.3.

**Comment by parazyt75** [comment]
@ANTONBORODA
try to create a new appleID, after sideload AltStore you can use your old "clean appleid" or stay with this new one

**Comment by RealTechyGod** [comment]
unable to reinstall because of this error... why am I being prevented from reinstalling the app that is no longer on the iPad? In no case should someone be prevented from reinstalling the app. as of now all apps are bricked thanks to being unable to install AltStore due to "This device is already registered with this team." every single tine

**Comment by RealTechyGod** [comment]
also creating a new ID doesn't help

**Comment by yahgoo** [comment]
same error message with different Apple ID

**Comment by czh6888** [comment]
4 apple-ids , the same error. 
When I try AltServer 1.4.2   It can install altstore ,  but open with crash

**Comment by KSWagle** [comment]
I'm having the same problem. I tried to install without deleting, and that didn't work. So I deleted it, that didn't work. I tried to use my alternate Apple ID, but after being told I was installing on a new device and it would leave my apps on the old device unusable, I canceled. But apparently AltServer had already sent that info to whatever is causing the problem, so now the alternate ID also produces the error "This device is already registered with this team."

**Comment by AizatHawari** [comment]
I think this happened when I installed Altstore with the same Apple ID on both my iPad and iPhone. No idea how to fix it as of now.

**Comment by GalacticLion7** [comment]
Could we receive an update from an official? I have several apps installed using AltStore that now cannot renew because of this issue.

**Comment by yahgoo** [comment]
I gave up waiting for this issue to be resolved. I reinstalled my app with sideloadly in windows. So far so good 👍

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing issues?

**Comment by yahgoo** [comment]
no longer an issue
