### ISSUE TITLE
SSL Error: WINHTTP_CALLBACK_STATUS_FLAG_SECURITY_CHANNEL_ERROR internal error

### ISSUE THREAD

**Issue by vOuii** [rileytestut/AltStore#665]
What do I even do. I have tried with different apple ID's. I have never had this issue before. Someone explain this to me please?
![AltServer_3wWGruSwQa](https://user-images.githubusercontent.com/38688744/106677977-80ff0b80-6605-11eb-8214-3f54ff687bd2.png)

**Comment by vOuii** [comment]
Solution FOUND! If you have Malwarebytes, or any antivirus software. add f000.backblazeb2.com to the allow/exclusion list! thank me later!

**Comment by natshenk** [comment]
As noted in another thread, using a VPN can be a fix as well. At least that's what worked for me.
I don't have any other antivirus except Windows Defender, and I added the AltServer program file as an exception which didn't help, but once I downloaded and used a VPN (I recommend ProtonVPN: easy setup, free, and it's what worked for me) it downloaded no problem to my phone.

**Comment by jhern115** [comment]
I'm having the issue where this pop up comes in. I have tried using the proton vpn but I'm not having any success ![image](https://user-images.githubusercontent.com/56828580/112673041-7f8dda80-8e21-11eb-9842-c06b615f0242.jpeg)
