### ISSUE TITLE
AltStore has an error when booting up

### ISSUE THREAD

**Issue by Boyyoufachr** [rileytestut/AltStore#667]
It says Unable to launch AltStore the file AltStore.sqlite could not be opened

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing issues?

**Comment by blakekl** [comment]
I haven't seen it again since re-installing. Kind of a pain to go through that process though, and I have no idea if the root cause has been addressed.

**Comment by shanegillio** [comment]
hmm ok, i'll mark this to come back to then. I did see you mentioned you wanted to refresh an expired app, so wanted to say you need to make sure to refresh before expiration as that may cause issues

**Comment by blakekl** [comment]
I usually get them refreshed on time, but sometimes I'm away from home for more than a week. Usually, I can just reinstall the AltStore app to the phone, re-open it, and refresh all the other apps and it works just fine. But not this one time.

**Comment by shanegillio** [comment]
ok, I'll close for now, but send a message here if anything similar happens again
