### ISSUE TITLE
Altstore. Need to login repeatedly

### ISSUE THREAD

**Issue by ocvb** [rileytestut/AltStore#668]
I have already login and when I refresh my apps, I have to keep keying my logins so frustrating.

**Comment by richardjv404** [comment]
I got the same issue, On my iphone 13 pro max 256GB ios 15.2

**Comment by ocvb** [comment]
> I got the same issue, On my iphone 13 pro max 256GB ios 15.2

The fix I resolve was by using another appleid on a Gmail account.
