### ISSUE TITLE
This device is already registered with this team

### ISSUE THREAD

**Issue by Jeanmarchp** [rileytestut/AltStore#669]
This error happens when I try to install altstore on an iPad. Doesn't seem to happen on iPhone. 

Device: iPad Pro 2020 
iOS version: 14.3
macOS version: Catalina latest version
Altserver version: latest version

Let me know if you need any logs. 

![image](https://user-images.githubusercontent.com/9320159/106772029-37162580-6605-11eb-8efb-3f166317ab8d.jpeg)

**Comment by noah978** [comment]
Dupliate of #663

**Comment by parazyt75** [comment]
It's working with a new fresh Apple ID that I've create only for sideloading AltStore & Unc0ver
IpadMini5, iOS 13.5, Altserver 1.4.3 (50)
