### ISSUE TITLE
AltDaemon Crashing, Can’t refresh Altstore

### ISSUE THREAD

**Issue by gpolanco21** [rileytestut/AltStore#670]
Running most recent beta, have had this issue for some time. But haven’t been answered. So making a new post about it. Here are the crash logs. Please help. Thanks

Date: 2/3/21, 10:33 AM
Process: AltDaemon
Bundle id: (null)
Device: iPad Pro (12.9-inch) (3rd generation), iOS 12.3.1

Exception type: EXC_BREAKPOINT (SIGTRAP)
Exception subtype: (null)
Exception codes: 0x0000000000000000, 0x0000000230e62e8c
Culprit: Unknown

Triggered by thread: 2
Thread name: 
Call stack:
0   CoreFoundation                	0x0000000230e62e8c 0x230db3000 + 720524     	// _CFRelease
1   libobjc.A.dylib               	0x00000002300eef7c 0x2300d1000 + 122748     	// (null)
2   AltDaemon                     	0x0000000102ad3dec 0x102ac0000 + 81388      	// specialized XPCConnectionHandler.listener(_:shouldAcceptNewConnection:)
3   AltDaemon                     	0x0000000102ad34f4 0x102ac0000 + 79092      	// @objc XPCConnectionHandler.listener(_:shouldAcceptNewConnection:)
4   Foundation                    	0x0000000231a76db8 0x231833000 + 2375096    	// service_connection_handler_make_connection
5   libxpc.dylib                  	0x0000000230b15470 0x230b09000 + 50288      	// _xpc_connection_call_event_handler
6   libxpc.dylib                  	0x0000000230b15970 0x230b09000 + 51568      	// _xpc_connection_mach_event
7   libdispatch.dylib             	0x00000002308e0950 0x2308dc000 + 18768      	// _dispatch_client_callout4
8   libdispatch.dylib             	0x00000002308f6eac 0x2308dc000 + 110252     	// _dispatch_mach_msg_invoke
9   libdispatch.dylib             	0x00000002308e7ca8 0x2308dc000 + 48296      	// _dispatch_lane_serial_drain
10  libdispatch.dylib             	0x00000002308f7e68 0x2308dc000 + 114280     	// _dispatch_mach_invoke2
11  libdispatch.dylib             	0x00000002308f7abc 0x2308dc000 + 113340     	// _dispatch_mach_invoke
12  libdispatch.dylib             	0x00000002308e7ca8 0x2308dc000 + 48296      	// _dispatch_lane_serial_drain
13  libdispatch.dylib             	0x00000002308e8954 0x2308dc000 + 51540      	// _dispatch_lane_invoke
14  libdispatch.dylib             	0x00000002308f0cc0 0x2308dc000 + 85184      	// _dispatch_workloop_worker_thread
15  libsystem_pthread.dylib       	0x0000000230adba98 0x230ad8000 + 15000      	// _pthread_wqthread
16  libsystem_pthread.dylib       	0x0000000230ae1dc4 0x230ad8000 + 40388      	// start_wqthread

Register values:
PC: 0x230ae1dc0         LR: 0x0                 CPSR: 0x0
x0: 0x16d4df000         x1: 0x0                 x2: 0x16d45c000
x3: 0x16d4deb80         x4: 0x1c4008            x5: 0x1
x6: 0x0                 x7: 0x0                 x8: 0x0
x9: 0x0                 x10: 0x0                x11: 0x0
x12: 0x0                x13: 0x0                x14: 0x0
x15: 0x0                x16: 0x0                x17: 0x0
x18: 0x0                x19: 0x0                x20: 0x0
x21: 0x0                x22: 0x0                x23: 0x0
x24: 0x0                x25: 0x0                x26: 0x0
x27: 0x0                x28: 0x0

Loaded images:
0: /usr/bin/AltDaemon
1: /usr/lib/substitute-inserter.dylib
2: /usr/lib/libsubstitute.dylib
3: /usr/lib/libsubstrate.dylib
4: /usr/lib/dyld
5: /usr/lib/substitute-loader.dylib
6: /usr/lib/libSystem.B.dylib
7: /usr/lib/libc++.1.dylib
8: /usr/lib/libc++abi.dylib
9: /usr/lib/libobjc.A.dylib
10: /usr/lib/system/libcache.dylib
11: /usr/lib/system/libcommonCrypto.dylib
12: /usr/lib/system/libcompiler_rt.dylib
13: /usr/lib/system/libcopyfile.dylib
14: /usr/lib/system/libcorecrypto.dylib
15: /usr/lib/system/libdispatch.dylib
16: /usr/lib/system/libdyld.dylib
17: /usr/lib/system/liblaunch.dylib
18: /usr/lib/system/libmacho.dylib
19: /usr/lib/system/libremovefile.dylib
20: /usr/lib/system/libsystem_asl.dylib
21: /usr/lib/system/libsystem_blocks.dylib
22: /usr/lib/system/libsystem_c.dylib
23: /usr/lib/system/libsystem_configuration.dylib
24: /usr/lib/system/libsystem_containermanager.dylib
25: /usr/lib/system/libsystem_coreservices.dylib
26: /usr/lib/system/libsystem_darwin.dylib
27: /usr/lib/system/libsystem_dnssd.dylib
28: /usr/lib/system/libsystem_info.dylib
29: /usr/lib/system/libsystem_kernel.dylib
30: /usr/lib/system/libsystem_m.dylib
31: /usr/lib/system/libsystem_malloc.dylib
32: /usr/lib/system/libsystem_networkextension.dylib
33: /usr/lib/system/libsystem_notify.dylib
34: /usr/lib/system/libsystem_platform.dylib
35: /usr/lib/system/libsystem_pthread.dylib
36: /usr/lib/system/libsystem_sandbox.dylib
37: /usr/lib/system/libsystem_symptoms.dylib
38: /usr/lib/system/libsystem_trace.dylib
39: /usr/lib/system/libunwind.dylib
40: /usr/lib/system/libxpc.dylib
41: /usr/lib/libicucore.A.dylib
42: /usr/lib/libz.1.dylib
43: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
44: /usr/lib/libbsm.0.dylib
45: /usr/lib/libenergytrace.dylib
46: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
47: /usr/lib/libxml2.2.dylib
48: /usr/lib/libbz2.1.0.dylib
49: /usr/lib/liblzma.5.dylib
50: /usr/lib/libsqlite3.dylib
51: /usr/lib/libMobileGestalt.dylib
52: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
53: /System/Library/Frameworks/Foundation.framework/Foundation
54: /System/Library/Frameworks/Security.framework/Security
55: /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
56: /usr/lib/libCRFSuite.dylib
57: /usr/lib/libapple_nghttp2.dylib
58: /usr/lib/libarchive.2.dylib
59: /usr/lib/libcoretls.dylib
60: /usr/lib/libcoretls_cfhelpers.dylib
61: /usr/lib/liblangid.dylib
62: /usr/lib/libnetwork.dylib
63: /usr/lib/libpcap.A.dylib
64: /System/Library/Frameworks/IOSurface.framework/IOSurface
65: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libBLAS.dylib
66: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLAPACK.dylib
67: /System/Library/Frameworks/Accelerate.framework/Frameworks/vImage.framework/vImage
68: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libSparseBLAS.dylib
69: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libvMisc.dylib
70: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libBNNS.dylib
71: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLinearAlgebra.dylib
72: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libQuadrature.dylib
73: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libSparse.dylib
74: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libvDSP.dylib
75: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/vecLib
76: /System/Library/Frameworks/Accelerate.framework/Accelerate
77: /usr/lib/libcompression.dylib
78: /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
79: /System/Library/PrivateFrameworks/IOAccelerator.framework/IOAccelerator
80: /System/Library/Frameworks/OpenGLES.framework/libCoreFSCache.dylib
81: /System/Library/Frameworks/Metal.framework/Metal
82: /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
83: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
84: /System/Library/PrivateFrameworks/IOSurfaceAccelerator.framework/IOSurfaceAccelerator
85: /System/Library/PrivateFrameworks/AppleJPEG.framework/AppleJPEG
86: /System/Library/Frameworks/ImageIO.framework/ImageIO
87: /System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
88: /System/Library/PrivateFrameworks/AssertionServices.framework/AssertionServices
89: /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/CorePhoneNumbers
90: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
91: /System/Library/PrivateFrameworks/CrashReporterSupport.framework/CrashReporterSupport
92: /System/Library/PrivateFrameworks/AggregateDictionary.framework/AggregateDictionary
93: /usr/lib/libTelephonyUtilDynamic.dylib
94: /System/Library/PrivateFrameworks/ProtocolBuffer.framework/ProtocolBuffer
95: /System/Library/PrivateFrameworks/MobileKeyBag.framework/MobileKeyBag
96: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
97: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
98: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
99: /System/Library/PrivateFrameworks/PowerLog.framework/PowerLog
100: /System/Library/PrivateFrameworks/CommonUtilities.framework/CommonUtilities
101: /usr/lib/liblockdown.dylib
102: /System/Library/Frameworks/CoreData.framework/CoreData
103: /System/Library/PrivateFrameworks/TCC.framework/TCC
104: /usr/lib/libcupolicy.dylib
105: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
106: /System/Library/Frameworks/Accounts.framework/Accounts
107: /System/Library/PrivateFrameworks/AppleSauce.framework/AppleSauce
108: /System/Library/PrivateFrameworks/DataMigration.framework/DataMigration
109: /System/Library/PrivateFrameworks/Netrb.framework/Netrb
110: /System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
111: /usr/lib/libmis.dylib
112: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
113: /usr/lib/libReverseProxyDevice.dylib
114: /usr/lib/libamsupport.dylib
115: /System/Library/Frameworks/OpenGLES.framework/libCoreVMClient.dylib
116: /System/Library/Frameworks/OpenGLES.framework/libCVMSPluginSupport.dylib
117: /usr/lib/libutil.dylib
118: /System/Library/Frameworks/OpenGLES.framework/libGLImage.dylib
119: /System/Library/PrivateFrameworks/APFS.framework/APFS
120: /System/Library/PrivateFrameworks/MediaKit.framework/MediaKit
121: /usr/lib/updaters/libSERestoreInfo.dylib
122: /System/Library/PrivateFrameworks/DiskImages.framework/DiskImages
123: /System/Library/Frameworks/OpenGLES.framework/libGFXShared.dylib
124: /usr/lib/libauthinstall.dylib
125: /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/IOMobileFramebuffer
126: /System/Library/Frameworks/OpenGLES.framework/OpenGLES
127: /System/Library/PrivateFrameworks/ColorSync.framework/ColorSync
128: /System/Library/Frameworks/CoreVideo.framework/CoreVideo
129: /usr/lib/libCTGreenTeaLogger.dylib
130: /System/Library/Frameworks/CoreAudio.framework/CoreAudio
131: /System/Library/PrivateFrameworks/UserFS.framework/UserFS
132: /System/Library/Frameworks/CoreMedia.framework/CoreMedia
133: /usr/lib/libprotobuf-lite.dylib
134: /usr/lib/libprotobuf.dylib
135: /usr/lib/libAWDSupportFramework.dylib
136: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/WirelessDiagnostics
137: /System/Library/Frameworks/VideoToolbox.framework/VideoToolbox
138: /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib
139: /System/Library/PrivateFrameworks/FontServices.framework/FontServices
140: /System/Library/Frameworks/CoreText.framework/CoreText
141: /System/Library/PrivateFrameworks/IntlPreferences.framework/IntlPreferences
142: /System/Library/PrivateFrameworks/RTCReporting.framework/RTCReporting
143: /System/Library/PrivateFrameworks/CoreBrightness.framework/CoreBrightness
144: /usr/lib/libAudioStatistics.dylib
145: /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
146: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
147: /System/Library/Frameworks/MediaAccessibility.framework/MediaAccessibility
148: /usr/lib/libiconv.2.dylib
149: /System/Library/PrivateFrameworks/NetworkStatistics.framework/NetworkStatistics
150: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/MPSCore
151: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/MPSImage
152: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/MPSMatrix
153: /System/Library/PrivateFrameworks/CoreAUC.framework/CoreAUC
154: /System/Library/Frameworks/MediaToolbox.framework/MediaToolbox
155: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/MPSNeuralNetwork
156: /System/Library/Frameworks/MetalPerformanceShaders.framework/MetalPerformanceShaders
157: /System/Library/PrivateFrameworks/FaceCore.framework/FaceCore
158: /System/Library/PrivateFrameworks/GraphVisualizer.framework/GraphVisualizer
159: /usr/lib/libFosl_dynamic.dylib
160: /System/Library/Frameworks/CoreImage.framework/CoreImage
161: /System/Library/Frameworks/CoreBluetooth.framework/CoreBluetooth
162: /System/Library/PrivateFrameworks/PlugInKit.framework/PlugInKit
163: /System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete
164: /System/Library/PrivateFrameworks/StreamingZip.framework/StreamingZip
165: /System/Library/PrivateFrameworks/CoreEmoji.framework/CoreEmoji
166: /System/Library/PrivateFrameworks/CoreLocationProtobuf.framework/CoreLocationProtobuf
167: /System/Library/PrivateFrameworks/SymptomDiagnosticReporter.framework/SymptomDiagnosticReporter
168: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
169: /System/Library/PrivateFrameworks/MobileAsset.framework/MobileAsset
170: /System/Library/PrivateFrameworks/Lexicon.framework/Lexicon
171: /usr/lib/libcmph.dylib
172: /System/Library/PrivateFrameworks/LanguageModeling.framework/LanguageModeling
173: /System/Library/Frameworks/CoreLocation.framework/CoreLocation
174: /System/Library/PrivateFrameworks/PhoneNumbers.framework/PhoneNumbers
175: /usr/lib/libChineseTokenizer.dylib
176: /usr/lib/libmecab_em.dylib
177: /usr/lib/libThaiTokenizer.dylib
178: /usr/lib/libgermantok.dylib
179: /System/Library/PrivateFrameworks/CoreNLP.framework/CoreNLP
180: /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
181: /usr/lib/libheimdal-asn1.dylib
182: /usr/lib/libate.dylib
183: /System/Library/PrivateFrameworks/TextureIO.framework/TextureIO
184: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
185: /System/Library/PrivateFrameworks/MobileIcons.framework/MobileIcons
186: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
187: /System/Library/Frameworks/FileProvider.framework/FileProvider
188: /System/Library/PrivateFrameworks/ProofReader.framework/ProofReader
189: /usr/lib/libAccessibility.dylib
190: /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib
191: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
192: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
193: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
194: /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/AppleIDAuthSupport
195: /System/Library/PrivateFrameworks/AuthKit.framework/AuthKit
196: /System/Library/Frameworks/UIKit.framework/UIKit
197: /System/Library/PrivateFrameworks/DocumentManagerCore.framework/DocumentManagerCore
198: /System/Library/PrivateFrameworks/HangTracer.framework/HangTracer
199: /System/Library/PrivateFrameworks/PhysicsKit.framework/PhysicsKit
200: /System/Library/PrivateFrameworks/StudyLog.framework/StudyLog
201: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
202: /usr/lib/libresolv.9.dylib
203: /usr/lib/libtidy.A.dylib
204: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
205: /System/Library/PrivateFrameworks/DiagnosticLogCollection.framework/DiagnosticLogCollection
206: /System/Library/PrivateFrameworks/Marco.framework/Marco
207: /System/Library/PrivateFrameworks/MessageProtection.framework/MessageProtection
208: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
209: /System/Library/PrivateFrameworks/Engram.framework/Engram
210: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
211: /System/Library/PrivateFrameworks/CaptiveNetwork.framework/CaptiveNetwork
212: /System/Library/PrivateFrameworks/EAP8021X.framework/EAP8021X
213: /System/Library/PrivateFrameworks/MobileWiFi.framework/MobileWiFi
214: /System/Library/PrivateFrameworks/OAuth.framework/OAuth
215: /System/Library/PrivateFrameworks/CommonAuth.framework/CommonAuth
216: /System/Library/PrivateFrameworks/Heimdal.framework/Heimdal
217: /System/Library/Frameworks/GSS.framework/GSS
218: /System/Library/PrivateFrameworks/ApplePushService.framework/ApplePushService
219: /System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
220: /System/Library/PrivateFrameworks/AppleIDSSOAuthentication.framework/AppleIDSSOAuthentication
221: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
222: /System/Library/PrivateFrameworks/CoreUtils.framework/CoreUtils
223: /System/Library/PrivateFrameworks/IDS.framework/IDS
224: /System/Library/PrivateFrameworks/UserManagement.framework/UserManagement
225: /System/Library/PrivateFrameworks/Bom.framework/Bom
226: /System/Library/PrivateFrameworks/PrototypeTools.framework/PrototypeTools
227: /System/Library/PrivateFrameworks/CoreSymbolication.framework/CoreSymbolication
228: /System/Library/PrivateFrameworks/CoreTime.framework/CoreTime
229: /System/Library/PrivateFrameworks/MobileSystemServices.framework/MobileSystemServices
230: /System/Library/PrivateFrameworks/ConstantClasses.framework/ConstantClasses
231: /System/Library/PrivateFrameworks/MobileInstallation.framework/MobileInstallation
232: /System/Library/PrivateFrameworks/CoreFollowUp.framework/CoreFollowUp
233: /System/Library/PrivateFrameworks/SetupAssistantSupport.framework/SetupAssistantSupport
234: /System/Library/PrivateFrameworks/SetupAssistant.framework/SetupAssistant
235: /System/Library/PrivateFrameworks/LinguisticData.framework/LinguisticData
236: /System/Library/PrivateFrameworks/LoggingSupport.framework/LoggingSupport
237: /System/Library/PrivateFrameworks/kperf.framework/kperf
238: /System/Library/PrivateFrameworks/kperfdata.framework/kperfdata
239: /usr/lib/libdscsym.dylib
240: /System/Library/PrivateFrameworks/ktrace.framework/ktrace
241: /System/Library/PrivateFrameworks/DeviceIdentity.framework/DeviceIdentity
242: /System/Library/PrivateFrameworks/SignpostSupport.framework/SignpostSupport
243: /usr/lib/libtailspin.dylib
244: /System/Library/PrivateFrameworks/FontServices.framework/libGSFontCache.dylib
245: /System/Library/PrivateFrameworks/InternationalSupport.framework/InternationalSupport
246: /System/Library/PrivateFrameworks/SignpostCollection.framework/SignpostCollection
247: /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/XCTTargetBootstrap
248: /System/Library/PrivateFrameworks/libEDR.framework/libEDR
249: /usr/lib/libcharset.1.dylib
250: /System/Library/Frameworks/CoreServices.framework/CoreServices
251: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSRayIntersector.framework/MPSRayIntersector
252: /System/Library/Frameworks/Network.framework/Network
253: /System/Library/PrivateFrameworks/ASEProcessing.framework/ASEProcessing
254: /System/Library/PrivateFrameworks/AXCoreUtilities.framework/AXCoreUtilities
255: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
256: /System/Library/PrivateFrameworks/DocumentManager.framework/DocumentManager
257: /System/Library/PrivateFrameworks/IdleTimerServices.framework/IdleTimerServices
258: /System/Library/PrivateFrameworks/OTSVG.framework/OTSVG
259: /System/Library/PrivateFrameworks/ROCKit.framework/ROCKit
260: /System/Library/PrivateFrameworks/SampleAnalysis.framework/SampleAnalysis
261: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
262: /System/Library/PrivateFrameworks/UIKitServices.framework/UIKitServices
263: /System/Library/PrivateFrameworks/URLFormatting.framework/URLFormatting
264: /usr/lib/swift/libswiftCore.dylib
265: /usr/lib/swift/libswiftCoreFoundation.dylib
266: /usr/lib/swift/libswiftCoreGraphics.dylib
267: /usr/lib/swift/libswiftCoreImage.dylib
268: /usr/lib/swift/libswiftDarwin.dylib
269: /usr/lib/swift/libswiftDispatch.dylib
270: /usr/lib/swift/libswiftFoundation.dylib
271: /usr/lib/swift/libswiftMetal.dylib
272: /usr/lib/swift/libswiftNetwork.dylib
273: /usr/lib/swift/libswiftObjectiveC.dylib
274: /usr/lib/swift/libswiftQuartzCore.dylib
275: /usr/lib/swift/libswiftUIKit.dylib

{"ProcessBundleID":"","ProcessName":"AltDaemon","Culprit":"Unknown"}

**Comment by Doregon** [comment]
+1 Exact same error

iPhone 5s
12.5.1

**Comment by rbits0** [comment]
Same problem iPhone 6+ iOS 12.4.9

**Comment by Doregon** [comment]
It's a known issue with iOS 12, according to other issues and Reddit. I suggest using ReProvision and the ReprovisionFix packages for on-devide resigning, as AltDaemon won't work on iOS 12.

**Comment by GunnerBasil** [comment]
Same issue.
iPhone 5s - iOS 12.5.2

**Comment by betteray** [comment]
@gpolanco21 I have created a fix for this crash, you can try it.
[AltDaemon_12.x_Fix](https://github.com/betteray/AltDaemon_12.x_Fix)
