### ISSUE TITLE
Error installing mail plug-in:  SSL Error

### ISSUE THREAD

**Issue by bscheffel** [rileytestut/AltStore#675]
When I attempt to have AltStore install the mail plug-in I get the following error:

Failed to install mail plug-in.
An ASSL error has occurred and a secure connection to the server cannot be made

Any idea?  Internet connection is fine and mail app accesses iCloud email account fine.

**Comment by louius3** [comment]
same issue...

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing issues?

**Comment by bscheffel** [comment]
I got it to work – thanks.

From: shanegillio ***@***.***>
Reply-To: rileytestut/AltStore ***@***.***>
Date: Friday, January 13, 2023 at 12:20 PM
To: rileytestut/AltStore ***@***.***>
Cc: bscheffel ***@***.***>, Author ***@***.***>
Subject: Re: [rileytestut/AltStore] Error installing mail plug-in: SSL Error (#675)


hi there! sorry for the lack of response - are you still experiencing issues?
