### ISSUE TITLE
Does not connect to the mail plug-in

### ISSUE THREAD

**Issue by Sky-git-Cloud** [rileytestut/AltStore#679]
Everything is working, it just says that it could not connect to mail plug-in. I’ve reinstalled mail plug-in, altserver and AltStore multiple times. Same message
![06BC7F38-6DF0-4787-834C-10BF90D7DBEC](https://user-images.githubusercontent.com/60956055/107634752-fffae080-6ca4-11eb-9259-7430d952e5d7.jpeg)
If you’re wondering why the password shows blank, I took a screenshot and it was blank in the screenshots, already checked multiple times.

**Comment by md-siam** [comment]
![Screen Shot 2021-02-12 at 11 11 38 PM](https://user-images.githubusercontent.com/21225918/107799572-c5b63f80-6d87-11eb-893e-8c0d706e1118.png)
Same problem here

**Comment by Sky-git-Cloud** [comment]
> ![Screen Shot 2021-02-12 at 11 11 38 PM](https://user-images.githubusercontent.com/21225918/107799572-c5b63f80-6d87-11eb-893e-8c0d706e1118.png)
> Same problem here

I don’t have that problem, everything else is working, it just won’t accept my Apple ID and only says that it could not connect

**Comment by Sky-git-Cloud** [comment]
I’ve figured it out, it’s the fact that you must use the same altserver you downloaded AltStore from
