### ISSUE TITLE
Cannot refresh base AltStore repo

### ISSUE THREAD

**Issue by themacintoshnerd** [rileytestut/AltStore#681]
I cannot refresh the base repo for AltStore. Every time I try to get the error seen below. I cannot edit the repo for AltStore inside AltStore to fix it either. I don't have any logs or anything (unless someone else knows how to) AltServer and AltStore are running version 1.4.3

![image](https://user-images.githubusercontent.com/32601031/107834370-f4baba00-6d63-11eb-9720-8aaf7ed7f2de.png)

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing issues?

**Comment by themacintoshnerd** [comment]
Nope it's fixed it's self since then :)

**Comment by shanegillio** [comment]
:)
