### ISSUE TITLE
Altdaemon Issue in Jailbroken Mode.

### ISSUE THREAD

**Issue by syafiqshaary** [rileytestut/AltStore#687]
Im on jailbroken device using checkra1n iOS 14.3 just refresh using altserver and working fine. Later when i successfully in jailbroken state go to altdaemon when i refresh working fine but app need to trusted from general profile so reason here App has been refresh cannot open. If want app to working need to be on unjailbroken state mean reboot then app will be normal. I think problem just came from altdaemon.

**Comment by atlantis1975** [comment]
I have been having the same problem the last few weeks. It is only possible to refresh AltStore in the UN-JAILBROKEN state(ie the phone is switched off and then on again). Other people are reporting issues with signing into AltStore on their phone but this problem also goes away in the UN-JAILBROKEN state. I have included a screenshot of the error it is giving 
![ACA80A70-8C1D-4350-AB61-37F98337C46D](https://user-images.githubusercontent.com/4201330/108642111-b4e98600-7479-11eb-8d6b-6979bbb9db51.png)

**Comment by enaloha** [comment]
I ran into this issue as well, but no need to un-jailbreak. I simply go to safe-mode, update, and then respring.

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing this issue?

**Comment by enaloha** [comment]
Good Lord, almost two years ago. No, it's all fine for me. This can be closed I would think.

**Comment by shanegillio** [comment]
hahaha yeah I'm cleaning up the entire issues tab atm! thanks for letting me know all is good
