### ISSUE TITLE
AltStore doesn’t clear cache on a failed ipa install

### ISSUE THREAD

**Issue by Hello-User** [rileytestut/AltStore#689]
![B93DC47C-C7DA-4F32-A206-483AE686037B](https://user-images.githubusercontent.com/6434049/108711886-46a6d100-7516-11eb-8aef-bc1202c53f3e.jpeg)

I can’t find a way to clear the data besides deleting and reinstalling AltStore. This happened after a bunch of failed sideloading attempts cause by an unstable network.

**Comment by Spidy123222** [comment]
I get this problem also. It would be nice to be able to clear cache in settings.

**Comment by Clopaper** [comment]
+1

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing this issue?

**Comment by Spidy123222** [comment]
> hi there! sorry for the lack of response - are you still experiencing this issue?
> 
> 
> 
> 

Yes

**Comment by shanegillio** [comment]
Alright Spidy, well I've definitely marked this as an issue noted in a few places - I'm going to close as a duplicate, and hopefully we can find a fix soon
