### ISSUE TITLE
%1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by Beerpongs** [rileytestut/AltStore#690]
Everything is updated and I keep getting this error. On windows 10 update 20H2. Never had this problem before. Updated and it happens.. Help Please!

**Comment by Pap-Redpaw** [comment]
I've been having this same problem

**Comment by puffycheezball8** [comment]
same here

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing this issue? can you also provide some screenshot or error message so we can better assist?

**Comment by puffycheezball8** [comment]
I reset my computer and then reinstalled altstore (also iTunes and iCloud) and it fixed itself 
Found this screenshot on Reddit
https://preview.redd.it/0684o1i7sc351.jpg?width=224&format=pjpg&auto=webp&v=enabled&s=469b2ae857d1565cdb0db7387fa4e7f66f276afd

**Comment by anggaaasetiyawan** [comment]
> hi there! sorry for the lack of response - are you still experiencing this issue? can you also provide some screenshot or error message so we can better assist?

I having this same problem

![Image](https://github.com/user-attachments/assets/5338eabd-8dd8-4b03-8dbe-177bb300e447)
