### ISSUE TITLE
The provisioning profile is invalid.

### ISSUE THREAD

**Issue by goalie1998** [rileytestut/AltStore#693]
On Windows 10, iPhone 12. No other information is given. I tried reinstalling iTunes and iCloud from the apple website not the windows store, and AltStore. Seems to be a common issue. Tried with iTunes running, iCloud running, both running, neither running... Tried running as administrator... Nothing seems to work.

**Comment by ljfzx** [comment]
same issue

**Comment by brianstoiber** [comment]
Same.

**Comment by A1M4N3** [comment]
The only way I got it to work was by running a clean restore and set it up as a new iPhone. Restoring from an iCloud back up gave me the that error.

**Comment by ljfzx** [comment]
> The only way I got it to work was by running a clean restore and set it up as a new iPhone. Restoring from an iCloud back up gave me the that error.

I regret to know that there is only one solution, because this method is too expensive

**Comment by F-Unction** [comment]
Same

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing this issue?

**Comment by brianstoiber** [comment]
I was. However I no longer have that phone so it is a moot point.

Brian Stoiber
