### ISSUE TITLE
Altdaemon Issue in Jailbroken Mode iOS 14.3

### ISSUE THREAD

**Issue by yun90s** [rileytestut/AltStore#695]
![7153BCB8-A119-48B4-A5F2-2F26D15A5A57](https://user-images.githubusercontent.com/78266659/109423318-3b084e00-79df-11eb-89e8-8e30bf3668b0.jpeg)
![47C04CE9-A3B8-4B1A-AD6B-4AE2227DF8F5](https://user-images.githubusercontent.com/78266659/109423459-cbdf2980-79df-11eb-9cfa-8f3a04c0732c.jpeg)

**Comment by yun90s** [comment]
![Uploading 0E0F471C-BBAB-4833-833D-5ED9DE8BEA5B.jpeg…]()

**Comment by smikkelbakje** [comment]
I have the same issue

**Comment by yun90s** [comment]
Già provato. Funziona solo per qualche giorno. Sembra che la versione 1.4.4b risolva il problema ma non è ancora pubblica

**Comment by GabrielL92I** [comment]
Yes it's true.The 1.4.4b fixed this issue.
