### ISSUE TITLE
after signing on device (Altaemon)

### ISSUE THREAD

**Issue by g0sbv** [rileytestut/AltStore#696]
After signing on device [Altdaemon] I get the following error..yet certificate still is installed and says its ok but neither Altstore or Unc0ver will run just get error.I have to reinstall Altstore from my computer again and unc0ver for it to work again. iphone 11 max pro ios 14.2

![error](https://user-images.githubusercontent.com/37037982/109476709-1cea2e80-7a6f-11eb-9123-a602f1a1447a.png)

**Comment by chased35** [comment]
I had the same issue. I deleted everything with the idea of maybe being able to reinstall everything but then I am now not able to install altstore at all on my phone. Keep getting “kCFErrorDomajnCFNetwork error -1200”

**Comment by liliass** [comment]
Same here. + installed Altdeamon

**Comment by chased35** [comment]
> Same here. + installed Altdeamon

https://twitter.com/chasedressel/status/1366504873185976321?s=21

Go to Twitter. I found the issue. Follow the thread. There are 3 posts

**Comment by GabrielL92I** [comment]
Yes the beta 1.4.4b is the solution!
You can find it on google!
