### ISSUE TITLE
Not able to install on phone from Mac 

### ISSUE THREAD

**Issue by chased35** [rileytestut/AltStore#697]
![697286A8-5654-4BC7-8DCD-CE3A43CF9628](https://user-images.githubusercontent.com/79872691/109552431-c0ebce00-7a9f-11eb-8ac8-d6084d0f7083.jpeg)

**Comment by jackwilest** [comment]
This is happening to me as well

**Comment by chased35** [comment]
> This is happening to me as well

https://twitter.com/chasedressel/status/1366504873185976321?s=21

I found the issue. Go to Twitter and look at my reply. There are 3 separate tweets but it fixed it for me.
