### ISSUE TITLE
[Bug] Altstore doesn't recognize paid developer account

### ISSUE THREAD

**Issue by hmoghani** [rileytestut/AltStore#698]
I  upgraded my apple dev account to a paid developer account. 
I install the altstore using Windows and I use the paid developer account credentials.
After installing, and when I launch the app, it asks me to Trust the certificate (usually for paid developer signed applications it doesn't ask that). I verified the certificate and I launched Altstore. When I login to my apple account, it says Free developer account however my account is paid. It also shows the wrong Team ID.

Summary:
1- Installed altstore using windows and paid developer account 
2- logged in to altstore app using the same apple developer account credentials
3- altstore shows "free developer account" in account type
4- altstore shows the wrong Team ID

Phone: iPhone 12
iOS 14.3

**Comment by delfer** [comment]
https://github.com/rileytestut/AltStore/issues/199
