### ISSUE TITLE
[Bug] Apps with Frameworks folder not being signed correctly

### ISSUE THREAD

**Issue by eni9889** [rileytestut/AltStore#7]
These are the logs when attempting to install IG ++ 

![image](https://user-images.githubusercontent.com/360222/65655863-b47e5e80-dfeb-11e9-9941-ce7f75ac90d4.png)

**Comment by eni9889** [comment]
I believe this PR should take care of the frameworks issue @rileytestut

**Comment by lonkle** [comment]
Has conflicts, and signing frameworks works fine, at least now. 😅

**Comment by michael1900** [comment]
When this bug will be fixed?

**Comment by michael1900** [comment]
> Has conflicts, and signing frameworks works fine, at least now. 😅

What you mean?
