### ISSUE TITLE
AltDaemon doesn’t work in a non-jailbroken state

### ISSUE THREAD

**Issue by bestadamdagoat** [rileytestut/AltStore#700]
Stats:

iPhone 10,6
AltDaemon: Installed
Has been jailbroken
Problem happens when in a non-jailbroken state
Jailbreak: unc0ver
iOS 14.3

**Comment by chased35** [comment]
I believe that you have to be in a jailbroken state for altdaemon to work since it works through the jailbreak. At least it would make sense to me if it wouldn’t work if you weren’t jailbroken. I could be wrong.

**Comment by GabrielL92I** [comment]
You need to refresh apps when you are on jailbroken state so you can use them when you are not jailbroken!
The altstore 1.4.4b is working just fine!

**Comment by bestadamdagoat** [comment]
Turns out this wasn’t an issue, someone told me that AltDaemon worked in a non-jailbroken state.
