### ISSUE TITLE
The biggest problem with altstore is that it doesn't fit the iPad screen

### ISSUE THREAD

**Issue by Zaq14rfv** [rileytestut/AltStore#702]
I am using altstore 1.4a4

iOS:13.5
iPad Air 2
Jailbreak with odyssey
![IMG_0611](https://user-images.githubusercontent.com/78459878/110092288-679fd980-7dd4-11eb-800c-165874e8e820.png)

**Comment by jbmagination** [comment]
AltStore Alpha is *really* outdated.. Use normal AltStore if you're not a Patreon member, otherwise use AltStore Beta
