### ISSUE TITLE
AltServer showing No Connected Devices

### ISSUE THREAD

**Issue by l0u1sg** [rileytestut/AltStore#703]
Describe the bug
AltServer shows No Connected Devices when I want to install it on my iPad

To Reproduce
Open AltServer -> Install AltStore

Expected behavior
That the installation of AltStore is error-free.

Desktop (please complete the following information if applicable):

    OS: Windows 10
    Version: 20H2

iPhone (please complete the following information):

    Device: iPad 10,2 8th generation
    iOS: 14.2 Beta 4

Additional context and logs
AltServer 1.4.3.0

**Comment by Jann3107** [comment]
same problem here, could you fix it?

**Comment by shanegillio** [comment]
hi there! sorry for the lack of response - are you still experiencing this issue?

**Comment by l0u1sg** [comment]
No, thanks !
