### ISSUE TITLE
Unc0ver crashing since updating to 1.4.5

### ISSUE THREAD

**Issue by JustinLoecher** [rileytestut/AltStore#720]
I updated today to 1.4.5 and now every time I run Unc0ver to rejailbreak my phone it crashes about step 23 (verifying resources"verified "bin/gunzip""), and my phone restarts.  Any ideas, or is there any way to install an older version on my device?  I have older installers of AltServer, but no matter what I use AltStore 1.4.5 installs on the phone.

**Comment by TheRealFayz** [comment]
Resolved the issue by rolling back to 5.3.1 Unc0ver.
