### ISSUE TITLE
Installation failed: provided url is invalid 

### ISSUE THREAD

**Issue by Z701-1** [rileytestut/AltStore#728]
![Screenshot_1](https://user-images.githubusercontent.com/81687030/113135317-a9347080-922a-11eb-9330-fe538843e36b.png)

**Comment by Z701-1** [comment]
recently uncover stopped woking for me after working for almost a year using reprovision and for some reason it now starting crashing and i deleted it and im trying to download it again i hope it fixes the problem, i tried using 3utools and it crashed so im now trying altserver but for some reason it's not installing, i tried installing the altserver but my version is not supported. hope someone can help me with this problem ;)

**Comment by dzgg001** [comment]
I also had a lot of problems with altstore, but finally I solved the problem quickly with Sideloadly, you can try it.

**Comment by SuCicada** [comment]
hello, look like your altstore.ipa url has mistake.
You can try to install  the newlest AltServer.
If you use the AltServer Patcher
You can click follow. It can make AltServer use default and right url.
![image](https://user-images.githubusercontent.com/33519267/168413537-9e73e0fa-6de6-4fa4-ae81-27b28bd91829.png)
