### ISSUE TITLE
AltServer crashes when installing AltStore

### ISSUE THREAD

**Issue by jdmry** [rileytestut/AltStore#73]
Hi, impossible for me to install, tried a few times, reboot, retry etc.

What happens:
 - install + setup mail plugin
 - plug phone via usb
 - launch AltServer
 - click on my phone on list in "Install AltStore"
 - put my apple credential
 - accept warning regarding developer certificate
 - crash but doesn't give me any error...
It does that every single time

Versions:
macOS: 10.15.1 or 10.14.5
iOS: 13.2.3

thanks

**Comment by ahoier** [comment]
Im getting this problem too.....I managed to get it to work once on my Windows 10, iPhone SE latest iOS.  and now after 7 days wont let me resign.

**Comment by dos9191** [comment]
Did you get this fixed @jdmry ?

**Comment by jdmry** [comment]
@dos9191 sorry I was sure that I put the solution here before, I did fix it by using an non developper apple account.. I think that was a bug in earlier version because then later I managed to do it with that same account with a next version.
