### ISSUE TITLE
How Do You Compile The Develop Branch?

### ISSUE THREAD

**Issue by ghost** [rileytestut/AltStore#731]
The develop branch is basically the main branch at this point, so I'd rather work off it than the main, especially since it has the January 28th (I think that was the date) fix. However, I followed your normal instructions to contribute, but the compile failed saying that certain things were missing or required and stuff like that. I tried changing where I got the dependencies from and things like that, but in the end, it still never compiled. So how am I supposed to compile the develop branch?

**Comment by Megarushing** [comment]
I dont think its meant to as it points to some commits that are not pushed in the dependencies, I have gone my way into compiling the latest branch version
