### ISSUE TITLE
Can't connect to Apple ID

### ISSUE THREAD

**Issue by rootcanary** [rileytestut/AltStore#732]
I'm unable to connect with my Apple ID. When I enter credentials, nothing happened

![IMG_1033](https://user-images.githubusercontent.com/81270358/113722951-2c553b00-96f1-11eb-9d20-87621e65b011.jpeg)

**Comment by researchimotion** [comment]
It's OK. I was find the problem: firewall on my macOS system couldn't connect with my iPhone
Sorry for the issue and thanks for your work!
