### ISSUE TITLE
invalid anisette data but both itunes and icloud are downloaded from the website

### ISSUE THREAD

**Issue by jakeyflakezz** [rileytestut/AltStore#734]
![Capture](https://user-images.githubusercontent.com/82049157/113744066-5b0fe900-96d2-11eb-8ed6-f5ff3f939f62.PNG)

**Comment by killmeorgetout** [comment]
@shanegillio 
How to solve it?

**Comment by killmeorgetout** [comment]
thx ,i deleted this folder :C:\ProgramData\Apple Computer\iTunes\adi The problem is solved.

**Comment by killmeorgetout** [comment]
> this should be resolved. I would recommend removing the ADI folder if the issue persists. deleting all files in: C:\ProgramData\Apple Computer\iTunes\adi should fix the issue! (They will be recreated next time you use AltServer)
> 
> Otherwise, just remove all the apple folders and reinstall from Apple directly

thx ,i deleted this folder :C:\ProgramData\Apple Computer\iTunes\adi The problem is solved.
