### ISSUE TITLE
Can't install Mail Plugin

### ISSUE THREAD

**Issue by Yzord** [rileytestut/AltStore#735]
I have two imacs. I downloaded Altserver to the macs, opened it and i click on "install Mail Plug-In", so i get 

_AltServer requires a Mail plug-in in order to retrieve necessary information about your Apple ID. Would you like to install it now?_

So i click "Install plug-In" and then i immediately get

_Could not connect to the server._ 

It is not even trying to find a server, the message appears instantly on both imacs. What can i do?

I run macOS Catalina 10.15.7 on both imac pro's. It worked before though.

**Comment by tim-hilt** [comment]
Open your mails preferences. You should see a button "manage plugins" or something like that. Click on it and grant access to the AltStore-plugin. It will notify you, that Mail has to be restarted. Confirm the notification and proceed with using AltStore.

**Comment by Yzord** [comment]
<img width="568" alt="Screenshot 2021-04-10 at 22 15 32" src="https://user-images.githubusercontent.com/5834848/114283480-458c1d80-9a4a-11eb-8eb4-8cbdb663b72c.png">

It isn't there...also not on my other mac. Really weird.

**Comment by Yzord** [comment]
It is working again...on both macs...i guess the server where the package is was offline or something

**Comment by cadenzah** [comment]
It seems this problem occurs time to time, and the reason is for the server? I'm facing the same problem now. At least it would be great to notice that the specific reason of the error.
