### ISSUE TITLE
Cannot Install Correctly Because Weird Domain Error

### ISSUE THREAD

**Issue by TheLegendaryBroccoli** [rileytestut/AltStore#736]
So I did look up the issue and maybe found it but not the exact issue forum. Anyways, this was working fine on my M1 Macbook Pro on Big Sur at first, then recently maybe a month ago it is no longer wants to sign, yet on my windows machine, it works fine. Honestly doesn't make any sense to me, but the issue says 

"Installation couldn't be completed. (kCFErrorDomainCFNetwork error -1003.)"

**Comment by kdhkr** [comment]
For some reason, this problems occurs if your network is outside of US.
The storage provider for the IPA files, `backblazeb2.com`, doesn't allow clients to connect `https://f000.backblazeb2.com` if they're outside of US.

If this issue persists with anyone, just head over and connect to any VPN server **located in US** (e.g. ProtonVPN) and it'll do the job.
