### ISSUE TITLE
Keep altserver running when macbook lid closed

### ISSUE THREAD

**Issue by HSAK5G** [rileytestut/AltStore#737]
My MacBook is on mac os version 10.15.2. For some reason when I close the lid on my MacBook alt server cant install refresh apps but when the lid is open everything is fine. Is there a way to keep all server running when you close the laptop lid. Any help is appreciated :).

**Comment by Pixelplayz2215YT** [comment]
My guess is because when you close the MacBook it goes into sleep mode. So I suggest if you want to refresh apps keep your MacBook open, but turn the brightness down.

**Comment by HSAK5G** [comment]
Ok thx
