### ISSUE TITLE
This is not an issue, but more like a helpful tip for people.

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [rileytestut/AltStore#738]
Basically, if you have AltStore running on your PC and your phone is connected to the safe Wi-Fi as your PC, but it says AltServer cannot find computer (or smth like that, I can't remember the whole error) while refreshing apps, go to your task bar, and click on the arrow, then go to AltServer and click close on it. Then on your task bar again, click the search bar and type AltServer, and let it load back up. Then you should be good! (To sum it all up, close and reopen AltServer on your PC)

**Comment by veritas06** [comment]
This is what I've been doing to refresh AltStore on my iPhone & iPad. I'm also hoping I can get a simple iOS Shortcut working that would close & reopen AltServer, then attempt to refresh.

**Comment by HSAK5G** [comment]
> Basically, if you have AltStore running on your PC and your phone is connected to the safe Wi-Fi as your PC, but it says AltServer cannot find computer (or smth like that, I can't remember the whole error) while refreshing apps, go to your task bar, and click on the arrow, then go to AltServer and click close on it. Then on your task bar again, click the search bar and type AltServer, and let it load back up. Then you should be good! (To sum it all up, close and reopen AltServer on your PC)

Thx this helped a lot. Had to sideload apps on usb but now works on wifi ;)
