### ISSUE TITLE
Have 2 instances of altserver on the same laptop

### ISSUE THREAD

**Issue by HSAK5G** [rileytestut/AltStore#739]
I have a windows laptop and want to have 2 instances of altserver with different apple ids. One for my ipad and one for my phone. How do i do this?

**Comment by veritas06** [comment]
I have a similar setup with my iPad & iPhone on macOS & the only issue I've run into is that I need to restart AltServer for the devices, i.e.: Refresh AltStore on my iPhone, then restart AltServer & I can refresh on my iPad. Would be great if there was a cleaner way of doing it, or leverage iOS Shortcuts to restart AltServer before attempting a refresh (I have actually been trying to get that working).

**Comment by HSAK5G** [comment]
I just used 2 laptops and installed altservet on bost of them with sifferent apple ids but its not that good. Woule be good if u can use one apple id and one laptop to do this

**Comment by veritas06** [comment]
Yeah, I definitely agree. You might want to see if you can schedule AltServer to close & reopen every hour or so on a single laptop. That might let you use just one server to refresh multiple devices.

**Comment by HSAK5G** [comment]
Ok thx!
