### ISSUE TITLE
AltStore crashes on Apple ID Sign in

### ISSUE THREAD

**Issue by yntel** [rileytestut/AltStore#74]
I've installed AltStore using the steps, ensured that the mail plugin is running. When I attempt to log into AltStore with my Apple ID (not 2FA, I made a new one just for this) the app crashes. This crash only happens when my Apple ID and password are correct - if I enter them correctly, it tells me.

When I open the app again I'm prompted to log in again.

OS X Mojave: 10.14.6
Apple Mail: 12.4
iOS: 13.2.3
Alt-Server: 1.1.1

**Comment by noah978** [comment]
This should be fixed on the latest versions of AltStore/Altserver. Closing this issue.
