### ISSUE TITLE
How can I get more then 3 apps?

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [rileytestut/AltStore#744]
So I have 2 apps installed on AltStore. AltStore, iNDS, and Delta, but I want more then those 3 how can I install more? Do I need to pay?

**Comment by Pixelplayz2215YT** [comment]
![image](https://user-images.githubusercontent.com/79018578/115303759-0472c800-a132-11eb-8a4a-cce3761ffd21.png)

**Comment by Pixelplayz2215YT** [comment]
I always get this message
![image](https://user-images.githubusercontent.com/79018578/115304252-bd390700-a132-11eb-80b8-823a63cef9ef.png)

**Comment by HSAK5G** [comment]
You can back up your apps by holding and them and then click deactivate. This will back up your app so u can doenload another app.

**Comment by Pixelplayz2215YT** [comment]
> You can back up your apps by holding and them and then click deactivate. This will back up your app so u can doenload another app.

Oh, so then when I want to download another app or re-download I have to deactivate the re-activate the other one? That's annoying :(
