### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by mcandre** [rileytestut/AltStore#745]
When I try to install AltStore onto my iPad, I get an error.

> Installation Failed
>
> The selected team does not have a program membership that is eligible for this feature. If you need assistance, please contact Apple Developer Program Support. https://developer.apple.com/support (4100)

![installation-failed](https://user-images.githubusercontent.com/5316/115480535-4bcf8600-a210-11eb-9df3-782722232139.png)

I tried running as administrator, no luck.

I have trusted my Windows host, no luck.

I ensured iTunes is configured to sync the iPad over WiFi, no luck.

I ensured iCloud and iTunes were running, no luck.

I ensured AltStore server is up to date, no luck.

I ensured iCloud and iTunes are up to date, no luck.

I unplugged and replugged my USB-C cable, no luck.

I tried again, no luck. It just keeps failing.

Windows 10, iPad Air.

**Comment by mcandre** [comment]
By the way, running the AltStore installation process on my iPad appears to trigger several emails from Apple complaining about an old developer certificate I used ten years ago. Assuming that is influencing the AltStore process, how do we go about resolving this issue?

**Comment by L-Whetstone** [comment]
Same issue here.

iPad Pro & Windows Laptop

**Comment by tabiznet** [comment]
Having the same issue with Iphone 12 Mini and Windows laptop. I'm also getting the same emails as OP

**Comment by L-Whetstone** [comment]
Interestingly I've bought a new iMac and the process works fine on there. Therefore might be a bug linked to the Windows version.

**Comment by magikarp171** [comment]
Did you find any way to make this work? I'm having your same issue. I had a developer account which is now expired but I'm not able to use my Apple ID to install AltStore on my computer.
