### ISSUE TITLE
Some IPoGo (Pokémon go spoofer) features don’t work when I install with AltStore

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [rileytestut/AltStore#747]
So I contacted people that made iPoGo (Pokemon Go Spoofer) and they said that it is out of their control weather they can make it work with AltStore or not and that it's AltStores code that doesn't decode the games basegame correctly, can you please fix that I have things in AltStore I don't want deleted and I can't use another ipa signer or else AltStore gets deleted. Thanks!

**Comment by gcha9118** [comment]
Did you find a fix for iPoGo?

**Comment by Pixelplayz2215YT** [comment]
No, it has to do with AltStore not supporting the base game of Pokémon go, I would up use if sideloadly instead

**Comment by BartmanEH** [comment]
This should be re-opened if we're to expect AtStore to be improved for wider compatibility
