### ISSUE TITLE
Error installing Mail Plug-In on macOS 11.4 Beta

### ISSUE THREAD

**Issue by thebitstick** [rileytestut/AltStore#748]
![image](https://user-images.githubusercontent.com/13919134/115973977-db31ad80-a51e-11eb-91db-14059902eb0d.png)

Mail Plug-In was working in previous 11.3 RC.

**Comment by rlatn1234** [comment]
Check #443

**Comment by gregmichael** [comment]
I am seeing this error persist in Big Sur 11.4 Beta 2

**Comment by MrPowerMac** [comment]
Error also exists on 11.4 release.

**Comment by ndthanh298** [comment]
Guide to fix for 11.4:

Quit Mail
Open /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/
Drag Info.plist to Desktop or something
Open Info.plist from where you dragged it
Duplicate Supported11.3PluginCompatibilityUUIDs and rename the last one to Supported11.4PluginCompatibilityUUIDs
Save file
Drag it back into Contents. Authorize.
Run sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle in Terminal

**Comment by ppamorim** [comment]
It's not working for me too.

**Comment by ppamorim** [comment]
@23Aaron Try to go to alt server and manually update it. It installed the latest version that contains the fix for the issue.
