### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by imTHAI** [rileytestut/AltStore#753]
Hello,
I've tried to install it this morning. On the Mac it says nothing, but the icon never shows up on the iPhone
If I try again on the Mac, after it asked me for my credentials, it says:
![Capture d’écran 2021-04-27 à 17 38 59](https://user-images.githubusercontent.com/36070606/116271456-46c68580-a780-11eb-807a-d2b9d0d6789d.png)
I accept anyway, but the AlStore never appears on my iPhone.

macOS Big Sur 11.2.3 (Apple Silicon) and iPhone 12 iOS 14.5

**Comment by imTHAI** [comment]
I'm now with Big Sure 11.3 but I still can't install

**Comment by southpaw5271** [comment]
I am having the same error. M1 MacBook Air macOS 11.4. iPhone 12 Pro iOS 14.5. I see the same popup in the image attached and when I click continue, nothing ever happens.

**Comment by imTHAI** [comment]
It finally worked for me. 
@southpaw5271 did you try rebooting your device ? I got the icon after reboot, I don't know why. Now everything is working perfectly on my iPad, and it renews certificates automatically with the Mac.
For the iPhone I've switched to another  - but not free - solution.
