### ISSUE TITLE
Solution for "Incompatible plugin"

### ISSUE THREAD

**Issue by iMatux** [rileytestut/AltStore#769]
Sorry for writing this here, but this was the first place I looked in for this problem.
First of all, disable System Integrity Protection (SIP) with "csrutil disable" on terminal after boot in Recovery Mode.
Reboot to macOS, uninstall with AltServer the mil bundle, search "/Users/<username>/Library/Application Support/Mail/Plug-ins/Bundles/", and delete AltServer file. 
Install AltServer mailbundle and activate it from Mail, now it will work. And don't forget to enable SIP again.

**Comment by vnunez85** [comment]
Hmm.. trying this. I think I understand the steps :) Hopefully it does the trick!

**Comment by nicojan** [comment]
Unfortunately, this did not work for me.

**Comment by iMatux** [comment]
> Unfortunately, this did not work for me.

Try to delete this folder /Users/<username>/Library/Containers/com.apple.mail/ , but every mail data will be deleted and downloaded again.
Be sure to have nothin here /Users/<username>/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles ,
Delete every mail reference on Caches folder on /Users/<username>/Library/Caches and /Users/<username>/Library/Saved Application State

**Comment by vnunez85** [comment]
Not dead. Download the beta AltStore. It works

**Comment by screenslaver4443** [comment]
Hi, this doesn't seem to work in Mac OS Monterey.

**Comment by lonkle** [comment]
Please use this command, and tell me your Terminal's output:

```sh
OSVersion=$(sw_vers -productVersion)PluginCompatibilityUUIDs && [[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(/usr/libexec/PlistBuddy -c 'print Supported'$OSVersion /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo "Installed Mail Plugin UUID Matches" || echo "Installed Mail Plugin Mismatched UUID" && [[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(unzip -p /Applications/AltServer.app/Contents/Resources/AltPlugin.zip AltPlugin.mailbundle/Contents/Info.plist > /tmp/AltPlugin.plist && /usr/libexec/PlistBuddy -c 'print Supported'$OSVersion /tmp/AltPlugin.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo “AltServer UUID Matches" || echo “AltServer Mismatched UUID"
```

**Comment by lonkle** [comment]
Also, project is nowhere near dead. We only commit to the "develop" branch most of the time.

**Comment by screenslaver4443** [comment]
> Hey guys. Please use this command, and tell me your Terminal's output:
> 
> ```shell
> OSVersion=$(sw_vers -productVersion)PluginCompatibilityUUIDs && [[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(/usr/libexec/PlistBuddy -c 'print Supported'$OSVersion /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo "Installed Mail Plugin UUID Matches" || echo "Installed Mail Plugin Mismatched UUID" && [[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(unzip -p /Applications/AltServer.app/Contents/Resources/AltPlugin.zip AltPlugin.mailbundle/Contents/Info.plist > /tmp/AltPlugin.plist && /usr/libexec/PlistBuddy -c 'print Supported'$OSVersion /tmp/AltPlugin.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo “AltServer UUID Matches" || echo “AltServer Mismatched UUID"
> ```

I got this: 
Print: Entry, "Supported12.0PluginCompatibilityUUIDs", Does Not Exist
Installed Mail Plugin Mismatched UUID
Print: Entry, "Supported12.0PluginCompatibilityUUIDs", Does Not Exist

**Comment by lonkle** [comment]
@screenslaver4443 You have to update your AltServer to version 1.4.6.

**Comment by screenslaver4443** [comment]
> @screenslaver4443 You have to update your AltServer to version 1.4.6.

Thanks that worked

**Comment by suwardhana** [comment]
@lonkle hi!
this is what I get from your command

Installed Mail Plugin Mismatched UUID

but I've checked the info.plist file, there's no changes
and I still can't enable the plugin.

I'm on 1.47(59)
