### ISSUE TITLE
Server Returned Invalid Response

### ISSUE THREAD

**Issue by NutrientA** [rileytestut/AltStore#77]
I installed iTunes and iCloud from Apple's website, and have my phone plugged in with AltStore running in the background. When I type my Apple ID in and my App-Specific Password, it says Server Returned Invalid Response. I allowed Firewall to run it through public and private networks. Please help?

**Comment by MrCTS** [comment]
I have the same issue.

I have a Meraki Firewall MX64 and running a pi-hole as well.  I ensured that the pihole was not blocking by disabling it's protection.  I also whitelisted the computer that is running AltStore inside my Meraki control panel as well.

**Comment by ButterCCM** [comment]
I've been having this same issue too. Are the servers down or disabled? I tried it on a windows device.

**Comment by noah978** [comment]
From now on, you must use the actual password with AltStore. App-specific passwords will no longer work. Closing this issue.

**Comment by loscar-cmd** [comment]
same here

**Comment by auslie** [comment]
still not working, running ios 12.4.8 in iphone 6 - windows 11 laptop
![image](https://user-images.githubusercontent.com/67105391/184291988-c85fe543-283c-4c27-8922-95b3a0cb999c.png)

**Comment by fightingserpent** [comment]
Delete iTunes, iCloud and altstore and reinstall everything from altstore website links.
Make sure windows media features is turned on in optional features.exe .

It worked for me in iPhone 7

**Comment by adevme** [comment]
Still an issue any fix??
