### ISSUE TITLE
iOS 15 “This codesigning version is no longer supported”

### ISSUE THREAD

**Issue by cheesycod** [rileytestut/AltStore#774]
Seems like ios and iPadOS 15 broke AltStore

**Comment by Void48** [comment]
Same issue. Hope there's a fix soon :/

**Comment by iMonZ** [comment]
+1
Maybe the backend needs a new signing system and that’s it.
Apps that were installed with Xcode 12 doesn’t work either

**Comment by VanillaChan6571** [comment]
Can confirm, iOS 15 seems to break. Here your error.

![iOS15 Broke](https://user-images.githubusercontent.com/39040261/121090805-53d68b80-c7a6-11eb-930e-9d866725d8e3.PNG)

**Comment by mcplayerteam** [comment]
Apart from the signing itself breaking, it seems that signatures made before iOS 15 will also break after updating to iOS 15. For apps (including AltStore) signed in iOS 14 then upgraded to iOS 15, I'm getting the error '"App" needs to be updated; The developer of this app needs to update it to work with this version of iOS'. I think the signing process has to be updated to include an iOS 15 tag of some sort.

**Comment by iMonZ** [comment]
> Apart from the signing itself breaking, it seems that signatures made before iOS 15 will also break after updating to iOS 15. For apps (including AltStore) signed on iOS 14 then upgraded to iOS 15, I'm getting the error '"App" needs to be updated; The developer of this app needs to update it to work with this version of iOS'. I think the signing process has to be updated to include an iOS 15 tag of some sort.

Apple already did this before.
They just require Xcode 13 or target sdk 15 for non notarized apps

**Comment by xoniq** [comment]
Does it work if we compile this with the new Xcode beta? (Currently I don't want to update Xcode for hours if it doesn't work)

**Comment by dabm-git** [comment]
> Does it work if we compile this with the new Xcode beta? (Currently I don't want to update Xcode for hours if it doesn't work)

Theoretically it should update the code signature with the new sdk 15. So it should work, but I haven't tested it.

**Comment by xoniq** [comment]
Almost there, but cannot compile any further (MBA M1, Xcode 13, Big Sur)

![Schermafbeelding 2021-06-08 om 14 34 09](https://user-images.githubusercontent.com/5212771/121185757-b0997b00-c866-11eb-86a1-6916272f69ae.png)

**Comment by 711634** [comment]
this is happening for me on ios 14.6

**Comment by dabm-git** [comment]
> Almost there, but cannot compile any further (MBA M1, Xcode 13, Big Sur)

Could you try signing a third party application .ipa, with Xcode 13 installed ?

**Comment by xoniq** [comment]
> > Almost there, but cannot compile any further (MBA M1, Xcode 13, Big Sur)
> 
> Could you try signing a third party application .ipa, with Xcode 13 installed ?

Hmm, have never done that with an existing IPA. Gonna look into that.

**Comment by jorschach-g** [comment]
Same issue, and the xcode method is not working either.

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?

**Comment by Void48** [comment]
> hello, sorry for the lack of response - is the issue still occurring on the latest version?

Pretty sure this has been fixed
