### ISSUE TITLE
The provisioning profile is invalid

### ISSUE THREAD

**Issue by hjy1129671284** [rileytestut/AltStore#775]
![image](https://user-images.githubusercontent.com/54837965/121140771-d1fd6580-c86c-11eb-8fe6-21866ec06b5f.png)

I updated my iPhone to IOS15 and find altstore broken.
After that, i restore to IOS14.6. So that found this problem.

windows 10
iphone 8P

someone could tell me how to fix?
thank you

**Comment by VanillaChan6571** [comment]
This is already known by #774 why would you spam us and open a new issue that relates to this?

**Comment by hjy1129671284** [comment]
> This is already known by #774 why would you spam us and open a new issue that relates to this?

Because this is not the same error message, and I rolled back to ios14.6 and still can't install it back.
Please accept my apology if it causes trouble

**Comment by hjy1129671284** [comment]
I just found i could use "SIdeloadly"(https://pangu8.com/sideloadly/) to install 3rd party softwares but the latest altstore version(1.4.6.0) can't, that's the same problem as the topic(The provisioning profile is invalid)
