### ISSUE TITLE
Mail plugin is not supported for Mail 15.0 (macOS 12 Beta)

### ISSUE THREAD

**Issue by StupidRepo** [rileytestut/AltStore#777]
# Info
So I am using the macOS 12 Beta update which has Mail 15.0 (or something) but the Mail Plugin requires Mail 14.0 which I don't have. How do I install AltStore on my phone now?

# Screenshot
<img width="372" alt="Error: Could not load Photo" src="https://user-images.githubusercontent.com/69256931/121534318-056cfb00-c9f9-11eb-9ab7-fa9114b84e6d.png">

**Comment by mikperk** [comment]
FYI: With macOS 12, a new extension framework called MailKit is introduced. Regular extensions for Apple Mail will then no longer run.

**Comment by bachrc** [comment]
Same here, but with Mail 14.0

<img width="306" alt="image" src="https://user-images.githubusercontent.com/5795145/122676563-ea5f6f80-d1de-11eb-8879-22ef38a8e50f.png">

**Comment by iMonZ** [comment]
Here too!

**Comment by davidrittri** [comment]
Same for me on big sur 11.4 
error with mail 14.0

**Comment by homurahomu1** [comment]
is there any way to get altstore to run on macOS 12?

**Comment by iMonZ** [comment]
> is there any way to get altstore to run on macOS 12?

Currently not!

**Comment by lonkle** [comment]
AltServer v1.4.6 should fix compatibility issues with macOS 12. Let me know if it doesn't!

**Comment by iMonZ** [comment]
> AltServer v1.4.6 should fix compatibility issues with macOS 12. Let me know if it doesn't!

Still doesn’t work

**Comment by lonkle** [comment]
You have to uninstall the Mail plugin, and then restart macOS, then install
the Mail plugin. Let me know if that works.

**Comment by lonkle** [comment]
People on macOS 11.4, run this Terminal command and tell me what it says:
```sh
[[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(unzip -p /Applications/AltServer.app/Contents/Resources/AltPlugin.zip AltPlugin.mailbundle/Contents/Info.plist > /tmp/AltPlugin.plist && /usr/libexec/PlistBuddy -c 'print ":Supported11.4PluginCompatibilityUUIDs"' AltPlugin.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo "UUID Matches" || echo "Mismatched UUID"
```

Anyone on macOS 12.0 Beta, please use this command and tell me what the output is:
```sh
[[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(unzip -p /Applications/AltServer.app/Contents/Resources/AltPlugin.zip AltPlugin.mailbundle/Contents/Info.plist > /tmp/AltPlugin.plist && /usr/libexec/PlistBuddy -c 'print ":Supported12.0PluginCompatibilityUUIDs"' AltPlugin.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo "UUID Matches" || echo "Mismatched UUID"
```

**Comment by iMonZ** [comment]
> You have to uninstall the Mail plugin, and then restart macOS, then install the Mail plugin. Let me know if that works.
> […](#)

All right now it works!
Issue can be closed

**Comment by iAnomaly** [comment]
Still not working for me even after uninstall Mail plugin, restarting macOS and installing Mail plugin and finally enabling Mail plugin in the Mail app.

Interestingly my incompatibility dialog says Mail 14.0 while the screenshot at the top of this issue says 15.0.

@lonkle I ran your command and here is the output below:
```
Installed Mail Plugin UUID Matches
“AltServer UUID Matches || echo “AltServer Mismatched UUID
```

**Comment by iMonZ** [comment]
> Still not working for me even after uninstall Mail plugin, restarting macOS and installing Mail plugin and finally enabling Mail plugin in the Mail app.
> 
> Interestingly my incompatibility dialog says Mail 14.0 while the screenshot at the top of this issue says 15.0.
> 
> @lonkle I ran your command and here is the output below:
> 
> ```
> Installed Mail Plugin UUID Matches
> “AltServer UUID Matches || echo “AltServer Mismatched UUID
> ```

This means that You still have an old version of the AltPlugin.
Try to update the version first

**Comment by lonkle** [comment]
@iAnomaly https://reddit.com/r/AltStore/comments/om3z64/solution_to_incompatible_mail_plugin_for_macos/ - does my solution posted here work for you?

**Comment by iAnomaly** [comment]
@iMonZ, I'm on the latest AltServer `1.4.6 (55)` and have uninstalled and reinstalled the Mail AltPlugin multiple times and it doesn't work.

@lonkle Yes! Solution #2 on your linked posted worked! This is the firs time AltServer has been working again in over a year! Thank you!

**Comment by lonkle** [comment]
@iAnomaly That's awesome to hear. I worked for a long time coming up with those solutions because I couldn't reproduce it myself, glad to finally have one or the other work for literally every single person so far!

**Comment by iamvinny** [comment]
Not working on macOS 12.0 Beta (21A5506j)

**Comment by obito26m** [comment]
> Funktioniert nicht unter macOS 12.0 Beta (21A5506j)

I can only confirm

**Comment by Firologame** [comment]
> Not working on macOS 12.0 Beta (21A5506j)

I confirm too, any solution ?

**Comment by MilGreat2010** [comment]
> Can you guys run this command in your Terminal app and tell me what it says - this should help us pinpoint where the problem is with the Mail plugin:
> 
> ```shell
> OSVersion=$(sw_vers -productVersion)PluginCompatibilityUUIDs && [[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(/usr/libexec/PlistBuddy -c 'print Supported'$OSVersion /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo "Installed Mail Plugin UUID Matches" || echo "Installed Mail Plugin Mismatched UUID" && [[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(unzip -p /Applications/AltServer.app/Contents/Resources/AltPlugin.zip AltPlugin.mailbundle/Contents/Info.plist > /tmp/AltPlugin.plist && /usr/libexec/PlistBuddy -c 'print Supported'$OSVersion /tmp/AltPlugin.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo “AltServer UUID Matches" || echo “AltServer Mismatched UUID"
> ```

I got: "Installed Mail Plugin Mismatched UUID

**Comment by MilGreat2010** [comment]
> > Can you guys run this command in your Terminal app and tell me what it says - this should help us pinpoint where the problem is with the Mail plugin:
> > ```shell
> > OSVersion=$(sw_vers -productVersion)PluginCompatibilityUUIDs && [[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(/usr/libexec/PlistBuddy -c 'print Supported'$OSVersion /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo "Installed Mail Plugin UUID Matches" || echo "Installed Mail Plugin Mismatched UUID" && [[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(unzip -p /Applications/AltServer.app/Contents/Resources/AltPlugin.zip AltPlugin.mailbundle/Contents/Info.plist > /tmp/AltPlugin.plist && /usr/libexec/PlistBuddy -c 'print Supported'$OSVersion /tmp/AltPlugin.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo “AltServer UUID Matches" || echo “AltServer Mismatched UUID"
> > ```
> 
> I got: "Installed Mail Plugin Mismatched UUID

oh yeah, I have the 12.0 beta (21A5534d)

**Comment by securisec** [comment]
Stopped working again on latest osx update. Mail version Version 15.0 (3693.40.0.1.81) Mac 12.1. Any suggestions? The solutions posted here no longer seems to work

**Comment by flallnatural** [comment]
> 

Yup, stopped working for me. Noticed AltStore was no longer signed on my device, tried AltServer install and was hit with this issue.

**Comment by SebastianRasch** [comment]
Latest version works fine.

**Comment by kaem-e** [comment]
latest beta version or stable, im getting the same issue (macos 12.2 mail 15)
![image](https://user-images.githubusercontent.com/46230985/152661112-cc0c6197-f8b2-4e8c-a337-9001f53a8037.png)

**Comment by lonkelle** [comment]
Anyone having issues with Mail can use this to fix them: https://github.com/Nythepegasus/AltPlugin-Fixes - the author of that repo said he'll update make sure he updates it every macOS release until we bake our own solution to this issue into AltServer directly.

**Comment by kaem-e** [comment]
Thanks yeah this worked.

**Comment by yunjia9664** [comment]
> Anyone having issues with Mail can use this to fix them: https://github.com/Nythepegasus/AltPlugin-Fixes - the author of that repo said he'll update make sure he updates it every macOS release until we bake our own solution to this issue into AltServer directly.

This worked for me. Thank you!

**Comment by franklinleandro** [comment]
Perfect!
This worked for me. Thank you!

**Comment by Anywhereyouare** [comment]
> AltServer v1.4.6 should fix compatibility issues with macOS 12. Let me know if it doesn't!

mine is not working for mail 16. what do I do??
