### ISSUE TITLE
Altstore crashes on ipa install

### ISSUE THREAD

**Issue by paulmorabito** [rileytestut/AltStore#778]
Hi,

I've built my own Blink app from the GitHub source and I can sideload it from XCode. 

I've found the .app, compressed it to a zip and then changed the extension to .ipa. When I attempt to install on my IPad running IPadOS 14.6, Altstore crashes.

Any ideas what this could be? Are there any particular build settings in XCode I need to be aware of or set?

Thanks,

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?
