### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by mvmalyi** [rileytestut/AltStore#78]
I receive the next error while trying to install the AltStore from my MacBook:
_"Could not connect to Mail plug-in. Please make sure the plug-in is installed and Mail is running, then try again."_

macOS 10.15.1
iOS 13.1.3

**Comment by mac-user669** [comment]
I get this too. It's probably something on Apple's end

**Comment by IMSomsom** [comment]
Go into “preferences” in the mail app. Under “general”

**Comment by johntdyer** [comment]
I am getting the same exact problem, I have installing from within the prefferences of the mail app and I still get the error

**Comment by ChetanRajagiri** [comment]
Go into “preferences” in the mail app. Under “general” goto "manage plugins" and enable "altplugin.mainbundle"

**Comment by eskimo** [comment]
> Go into “preferences” in the mail app. Under “general”

Doesn't exist? [pic](https://i.arxius.io/46812297.png)

**Comment by eskimo** [comment]
Smart, close a valid issue that has had no fix posted in the thread.

**Comment by CRH258** [comment]
Have no “manage plugins”...

**Comment by lee3181** [comment]
> Have no “manage plugins”...
Open the mail app, and Then you can see it on the Upper left corner

**Comment by timur4** [comment]
> Have no “manage plugins”...

https://support.mailbutler.io/knowledge-base/manage-plug-ins-gone/

**Comment by BabiuchHall** [comment]
### FIXED!
**Solution: Delete the DataVaults Folder**

Follow steps:
C. Ask Mail to Reset the DataVaults
and
D. Delete the DataVaults Folder
from these instructions: [https://c-command.com/spamsieve/help/if-the-apple-mail-plug](https://c-command.com/spamsieve/help/if-the-apple-mail-plug)

Note: removing the DataVaults folder requires disabling SIP (System Integrity Protection). Be sure to re-enable it afterwards by following the instructions at the above link.
