### ISSUE TITLE
The source "UTM Repository" is not supported by this version of AltStore

### ISSUE THREAD

**Issue by ghost** [rileytestut/AltStore#781]
![image](https://raw.githubusercontent.com/zuorong-zhang-contributer/images/main/1619fe5c0d18a6659b22d272a1420c3.jpg)

I once reported this question to UTM, and they answered:
> This is an AltStore issue.

**Comment by noah978** [comment]
AltStore Sources are still in Beta as they have many different changes to the API required before official release.
