### ISSUE TITLE
Error Your session has expired please login. (1100)

### ISSUE THREAD

**Issue by PROishacking-glitch** [rileytestut/AltStore#782]
i have ios 15 beta and iphone 7

**Comment by PROishacking-glitch** [comment]
ok i restarted altstore and now it work

**Comment by sambarker07** [comment]
I have the same issue on 14.3 and iPhone 11 Pro Max

**Comment by PROishacking-glitch** [comment]
> I have the same issue on 14.3 and iPhone 11 Pro Max
> _EDIT_ Reinstalling did not fix Altstore on Win 10. Updating iTunes and verifying authorization did not fix.

idk then
