### ISSUE TITLE
AltStore not showing my phone as connected.

### ISSUE THREAD

**Issue by cjlfilms** [rileytestut/AltStore#784]
My iPhone 12 is plugged into my computer and charging. I installed I cloud and I tunes, I can see my phone's files on I cloud, but when I try to install thealtstore on my phone, it doesn't show up as connect for some reason.
![image](https://user-images.githubusercontent.com/45830088/122214717-6a50a700-ce78-11eb-92a7-14a8d3909230.png)

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?

**Comment by cjlfilms** [comment]
I haven’t used it in a few months now, consider my problem resolved Sent from Mail for Windows From: shanegillioSent: Wednesday, January 11, 2023 5:27 PMTo: rileytestut/AltStoreCc: cjlfilms; AuthorSubject: Re: [rileytestut/AltStore] AltStore not showing my phone as connected. (#784) hello, sorry for the lack of response - is the issue still occurring on the latest version?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
