### ISSUE TITLE
Installation Failed on IOS 15

### ISSUE THREAD

**Issue by PeraDev7** [rileytestut/AltStore#789]
Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.T3UGRI/extracted/AltStore.app : 0xe8008029 (The code signature version is no longer supported.)

**Comment by Tamaki-sakuya** [comment]
Yes, I have the same issue, too

**Comment by Tamaki-sakuya** [comment]
go to patreon and pay 3 dollars to get the beta version. This version fixed this problem

**Comment by PeraDev7** [comment]
ALTERNATIVE WORKING METHOD FOR NOW : 
Download and install Sideloadly.
