### ISSUE TITLE
Altstore crash when Apple ID is entered correctly.

### ISSUE THREAD

**Issue by superasian99** [rileytestut/AltStore#79]
When I attempt to install the beta, delta or even enter my credentials into the settings it will crash when correctly entered, if entered incorrectly it alerts me. I'm using an iPhone 11 Pro on ios 13.2.3

**Comment by x-magic** [comment]
Similar issue. iPhone X on iOS 13.3
AltStore (not beta) can be installed on the phone from a Mac with no problem. But when login on AltStore on the phone, it crashes. 

Here's the console log: 
```
default	09:54:22.029539+1100	AltStore	Task <40CF36B7-0078-4A27-B713-EAE97128F428>.<3> finished successfully
default	09:54:22.030098+1100	AltStore	Got token for com.apple.gs.xcode.auth!
Expires: Tue Dec 15 09:54:21 2020
Value: ***hidden***
default	09:54:22.033672+1100	AltStore	*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[17]'
*** First throw call stack:
(***hidden***)
```
Hope it helps.

**Comment by alemolamg** [comment]
> When I attempt to install the beta, delta or even enter my credentials into the settings it will crash when correctly entered, if entered incorrectly it alerts me. I'm using an iPhone 11 Pro on ios 13.2.3

I have the same issue, I can install the .ipa in my iPhone but I can't login my ID. My account don't have verification in two steps.
I used an iPhone 6S on ios 13.3

**Comment by noah978** [comment]
This should be fixed on the latest versions of AltStore/Altserver. Closing this issue.
