### ISSUE TITLE
AltPlugin incompatible with Mail 15.0

### ISSUE THREAD

**Issue by debugged-hosting** [rileytestut/AltStore#795]
Can we add the UUID for Mail.app v15?

**Comment by debugged-hosting** [comment]
If someone tells me how to pull UUID I can post it here.

**Comment by lonkle** [comment]
I'm not on macOS 12 (beta) yet so I haven't personally tested this but our latest AltServer v1.4.6 should work with the newest Mail version. What AltServer version are you using?

**Comment by debugged-hosting** [comment]
I have tried and Mail tells me it’s not compatible. It seems like we just need to enter the new Mail versions UUID.

**Comment by lonkle** [comment]
Here's how to get the UUID: 

![Screen Shot 2021-07-13 at 8 52 43 AM](https://user-images.githubusercontent.com/5572600/125454993-eea0bf2d-387c-4cb3-ab6d-e4c4406cc6d5.jpg)

And you can check the current mail plugins whitelist here: https://github.com/rileytestut/AltStore/blob/develop/AltPlugin/Info.plist

Let me know what you find out! Because it should be supported but maybe your UUID is different for some odd reason because some users it works for and other's it doesn't. I'm trying to figure out why rn. What Mac Hardware model do you have?

**Comment by lonkle** [comment]
Here's a single Terminal command that'll tell you if your AltServer has the proper matching UUID, let me know what the output is @debugged-hosting. 

```sh
[[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(unzip -p /Applications/AltServer.app/Contents/Resources/AltPlugin.zip AltPlugin.mailbundle/Contents/Info.plist > /tmp/AltPlugin.plist && /usr/libexec/PlistBuddy -c 'print ":Supported12.0PluginCompatibilityUUIDs"' AltPlugin.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo "UUID Matches" || echo "Mismatched UUID"
```

**Comment by lorenviol** [comment]
> Here's a single Terminal command that'll tell you if your AltServer has the proper matching UUID, let me know what the output is @debugged-hosting.
> 
> ```shell
> OSVersion=$(sw_vers -productVersion)PluginCompatibilityUUIDs && [[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(/usr/libexec/PlistBuddy -c 'print Supported'$OSVersion /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo "Installed Mail Plugin UUID Matches" || echo "Installed Mail Plugin Mismatched UUID" && [[ $(defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID) == $(unzip -p /Applications/AltServer.app/Contents/Resources/AltPlugin.zip AltPlugin.mailbundle/Contents/Info.plist > /tmp/AltPlugin.plist && /usr/libexec/PlistBuddy -c 'print Supported'$OSVersion /tmp/AltPlugin.plist | sed -e 1d -e '$d' | sed 's/^[[:space:]]*//g') ]] && echo “AltServer UUID Matches" || echo “AltServer Mismatched UUID"
> ```

Still won't work for me, I'm on macOS 11.4 with AltServer 1.4.6, and that terminal command returns this: 

Installed Mail Plugin UUID Matches
“AltServer UUID Matches || echo “AltServer Mismatched UUID

**Comment by lonkle** [comment]
That’s not a command to fix it. It’s a command to tell me what I should suggest to fix it. Try this: `sudo mv ~/Library/Application\ Support/Mail/Plug-ins/Bundles/ /tmp`

**Comment by lorenviol** [comment]
Wow it worked, thanks a lot!

Couldn't do it via terminal as it was returning "Operation not permitted", so I did 
`open ~/Library/Application\ Support/Mail/Plug-ins/Bundles/` and moved everything into /tmp

The UUID in that Properties.plst was different, probably that was it.

**Comment by lonkle** [comment]
For anyone new coming here / seeing this:

**Solution #1**
• Go to AltServer and “Check for Updates” to make sure you’re on the latest version - currently there's a bug on the beta that will update you to the latest Public version, just make sure you’re either on version 1.4.6 or 1.5b6.
• Open Mail and go to Mail Preferences
• Click Manage Plugins and enable AltPlugin
• Click “Apply and Restart”

**Solution #2**
• Quit Mail
• Right click on the Finder icon in the Dock and click “Go to Folder...”
• Copy and paste this path: ~/Library/Application Support/Mail/Plug-ins
• Rename “Bundles” in the opened folder to “Bundles-Disabled”
• Open Mail and go to Mail Preferences
• Click Manage Plugins and enable AltPlugin
• Click “Apply and Restart”

One of those two solutions works 2/3rds of the time, every time.

**Comment by rdmn7** [comment]
This works! 

https://github.com/rileytestut/AltStore/issues/905#issuecomment-985985323
