### ISSUE TITLE
Could not find AltServer

### ISSUE THREAD

**Issue by g2bb** [rileytestut/AltStore#8]
I just installed the server on my pc and the app on my iPad Pro, and whenever I go to install an app it says "Could not find AltServer" even though it is up and running on my desktop, my iPad is on Wifi and my desktop is connected via ethernet to the same router.

Also, Clip and Delta (non-lite) just say "3 days" in the bubble where you would click to install and clicking on it does nothing, so the only  thing I can install right now is Delta Lite

**Comment by jamescastells** [comment]
Be sure to be using the [64-bit iTunes version](https://www.apple.com/itunes/), and not the Windows Store version.

**Comment by g2bb** [comment]
That was the issue. I had the Windows Store version. Just fixed it as you were typing that, and it worked great. Still having the issue where I can't get Delta or Clip because the buttons don't do anything

**Comment by g2bb** [comment]
Also, it appears the Altstore will not sync with a server connected to ethernet even if it's connected to the same router

**Comment by jamescastells** [comment]
Interesting. I found that Altstore always syncs if the phone is connected via lightning cable.

**Comment by g2bb** [comment]
Yea, that worked for me, but Wifi syncing won't. Not the end of the world, but something to note

**Comment by jamescastells** [comment]
Something similar happened to me. I noticed that with that option checked in iTunes, after I disconnected the phone, it wouldn't appear anymore on iTunes (it should, if wifi syncing is enabled). I force restarted my iPhone, and after connecting/disconnecting it again, it kept appearing on iTunes. AltStore worked perfectly after this.

**Comment by jamescastells** [comment]
> Clip and Delta (non-lite) just say "3 days" in the bubble where you would click to install and clicking on it does nothing

By the way, this is intentional, it means that both apps will be released on Saturday, you can't install them yet.

**Comment by g2bb** [comment]
Ah, that makes sense. Restarting my iPad worked perfect, thanks!
