### ISSUE TITLE
Unable to sideload large ipa files

### ISSUE THREAD

**Issue by Stevie-T** [rileytestut/AltStore#800]
I am trying to sideload retroarch on my iPhone. I only able to sideload the older builds found here -https://buildbot.libretro.com/stable/1.9.2/apple/

The older builds are around 300 Mb. The newer ones are around 400 Mb. When I try to sideload the newer builds, after around 2-3 mins during installation, Altstore errors out saying that it "Failed to write app data to device"  or "lost connection to AltServer". The connection is intact as Altserver has not shut down. I am not sure if there is a limitation on the size of the IPA file that we install.

**Comment by HSAK5G** [comment]
Maybe try plugging in your device to your computer with altserver on it

**Comment by Stevie-T** [comment]
I tried this by plugging the device into the computer. It does not work. Also, this issue has been highlighted in online tutorials as well. (Look in this post below step 7 section)

[https://jilaxzone.com/2021/05/16/retroarch-step-by-step-guide-to-install-play-retro-games-emulator-on-iphone-without-jailbreak/](https://jilaxzone.com/2021/05/16/retroarch-step-by-step-guide-to-install-play-retro-games-emulator-on-iphone-without-jailbreak/)

I think someone from the dev team should look into this and investigate or provide answers if there is some kind of limitation being set by apple

**Comment by kambala-decapitator** [comment]
also stumbled on this trying to install Kodi on iPhone 6s and iPad Air 2 running iOS 15, but ipa is just 130 MB.

crash reports:
[AltStore-2021-10-30-153410.ips.txt](https://github.com/rileytestut/AltStore/files/7446653/AltStore-2021-10-30-153410.ips.txt)
[AltStore-2021-10-30-160244.ips.txt](https://github.com/rileytestut/AltStore/files/7446654/AltStore-2021-10-30-160244.ips.txt)

**Comment by Stevie-T** [comment]
Update: Was able to install retroarch 1.9.12, a 400 mb ipa, with alstore 1.4.8. So I don't see this issue is persistent anymore. Other commentators on this thread, I suggest that you try the same.

**Comment by kambala-decapitator** [comment]
@Stevie-T fyi I’m on the latest version as well
