### ISSUE TITLE
AltStore app crash during IPA install

### ISSUE THREAD

**Issue by sy6sy2** [rileytestut/AltStore#803]
Steps to reproduce:

* Install AltStore on the device with AltServer
* Convert officiel Kodi des file to IPA file
* Copy IPA file on the device
* Open AltStore, go to `My Apps` tab, tap `+` button, select Kodi IPA file.
* You will see the green progress bar and around 75% AltStore crash.

I have no problem if I install Delta.

Details:

* iPhone SE 2020 with iOS 14.6
* AltServer: Version 1.4.6 (55)
* AltStore: 1.4.6

Full crash log: https://paste.kodi.tv/vugelavowi.kodi

I can upload the IPA file if needed.

Thank you.

**Comment by shanegillio** [comment]
have seen multiple reports about Kodi, so going to close this as a duplicate. know that we are working on this, and sorry for the delay
