### ISSUE TITLE
AltStore and sideloaded apps stop opening before expiration

### ISSUE THREAD

**Issue by jiznon** [rileytestut/AltStore#806]
iPhone 11 (not jailbroken)
iOS 14.6 and 14.7
AltStore 1.4.6
AltServer Windows 1.4.6.0

Been experiencing this issue for weeks now across multiple AtStore/Server/iOS version (but same phone) -- both AltStore and the 1 other app I have sideloaded will open fine when first installed/signed. However some time before the 7 days are up, they will stop opening in a similar manner is if they're expired (splash screen then crash to homescreen with no error). 

I then reinstall AltStore and AltStore opens fine, but the 1 other sideloaded app now shows splash screen, but crashes with the error "YouTube Is No Longer Available".

I then open AltStore and can see the 1 other app has 3, 4, 5 days left before expiration. I have to refresh it again from here in order for it to open. Rinse and repeat.

Been difficult trying to search for this particular issue. Is anyone else experiencing this? Any suggestions on a solution? Thanks!

**Comment by Nottoknow2** [comment]
I also have the same problem

**Comment by jiznon** [comment]
I believe I've figured it out.

I had a different jailbroken device using AltDaemon with the same Apple ID. I deleted AltStore and the dev profiles from both devices, and reinstalled using different Apple IDs. Made sure to sign in to AltStore with the same credentials that I installed it with per device, and so far have gone 6 days without seeing the issue.

**Comment by Nottoknow2** [comment]
I deactivated and reactivated and the problem has come back after 6 days

**Comment by jiznon** [comment]
What does "deactivated and reactivated" mean? 

Is your Apple ID being used to sign on another device, as in my case? 

Have you tried using a brand new Apple ID?
