### ISSUE TITLE
cannot activate more than 3 apps but apps offloading disabled

### ISSUE THREAD

**Issue by xycainoff** [rileytestut/AltStore#809]
cannot install more than 3 apps - getting error "Cannot activate more than 3 apps and app extensions. Make sure Offload Unused Apps is disabled in Settings...". But offload unused apps is disabled. 
AltStore 1.4.6b
iOS 14.7.1
iPhone 12

**Comment by Swifticul** [comment]
Disabling Offloading is mentioned to free up space for three apps. You cannot have more than three sideloaded apps up at a time, and if you offload an app, it counts to that limit. You’ll have to deactivate one of your other apps if you want to sideload a new one

**Comment by ryuu27** [comment]
Thank you I deactivated one of the apps and it worked !
