### ISSUE TITLE
Altstore app crashes 

### ISSUE THREAD

**Issue by Rosquash** [rileytestut/AltStore#81]
I tried installing Altstore on my iPhone X from my computer and it says that Altstore is already installed on another device. I haven't installed it on any other device, so I clicked continue, but when it gets installed and I try to open it, it immediately closes.

**Comment by Hazza42** [comment]
Are you on the iOS beta? Sideloading seems to be broken on the latest iOS 13.3.1 beta. All my AltStore apps refuse to open and crash immediately

**Comment by Rosquash** [comment]
I am. I guess is the issue. Maybe in a future update it may work again but if not I guess getting out of the beta could fix the issue

**Comment by noah978** [comment]
The issue was with iOS 13.3.1 and was promptly fixed on later iOS versions. Regardless, the problem should be fixed for iOS 13.3.1 on the latest versions of AltStore/Altserver. Closing this issue.
