### ISSUE TITLE
"⚠️ You do not need to delete AltStore first to manually update it." is wrong

### ISSUE THREAD

**Issue by HexCodeFFF** [rileytestut/AltStore#812]
this quote is on the altstore beta page but its wrong on windows

![image](https://user-images.githubusercontent.com/35177464/130143670-f4a38f4b-c567-423a-825d-337ae6b4c455.png)

same error for the msi and the exe

**Comment by HexCodeFFF** [comment]
actually might have to do with the beta version being 1.4.3 but the version i have installed is 1.4.6... somehow?

**Comment by lonkle** [comment]
Did you get this fixed?

**Comment by HexCodeFFF** [comment]
I mean I was able to just uninstall the old version and I was fine but it's strange that the text says that 

Like I said it might have to do with me mistakenly trying to install a beta older than the version I had installed

**Comment by BoogieHasFun** [comment]
If your on windows if you have 2 accounts uninstall altstore on the other account(s).
