### ISSUE TITLE
altserver not install....

### ISSUE THREAD

**Issue by drst3in** [rileytestut/AltStore#818]
Error occurred when installing altserver on device...

The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1001.)

What's the problem?

os : big sur 11.5.2

**Comment by sdk0213** [comment]
hello i found solution but i dont know why.. It's probably a VPN related issue. 

anyway follow my solution 

open appstore(on Mac) - download "Betternet VPN" - open Betternet VPN - VPN connect - altserver working perfectly
(This is not an advertisement. "Betternet VPN" is freeware.)

**Comment by drst3in** [comment]
> > Error occurred when installing altserver on device...
> > The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1001.)
> > What's the problem?
> > os : big sur 11.5.2
> 
> 한국분이셨군요 한국말로 다시 솔루션 적겠습니다. Betternet VPN 설치하시고 VPN 연결하시면 정상적으로 되실겁니다. 저는 기존 사용하는 VPN 프로그램 있는데 그건 또 안되고 Betternet VPN 설치하니까 되더군요. 아무튼 맥 OS 랑 관련되어있는것같습니다. 윈도우에서는 altserver가 잘작동하거든요. 해결하셨기를 바랍니다.

오~~잘됩니다!!! 감사합니다~~

**Comment by kdhkr** [comment]
For some reason, this problems occurs if your network is outside of US.
The storage provider for the IPA files, `backblazeb2.com`, doesn't allow clients to connect `https://f000.backblazeb2.com` if they're outside of US.

If this issue persists with anyone, just head over and connect to any VPN server **located at US** (e.g. ProtonVPN) and it'll do the job.

**Comment by gamalabar** [comment]
absolutely same problem for me here. 

I've tried VPN (i'm using windscribe) on my mac and phone, changing the apple id, reinstalling altserver on my mac and the mail plugin, but still the same error.

The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1200.)  

without an VPN in the US the error is -1001 (I'm in France)
