### ISSUE TITLE
Sideload other .ipa

### ISSUE THREAD

**Issue by anonymous1184** [rileytestut/AltStore#82]
Is there a way to side load an .ipa, like Chimera's .ipa?

**Comment by devinprater** [comment]
There will be in a future release.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhangchenkai** [comment]
https://www.reddit.com/r/jailbreak/comments/ejbi1w/release_install_ipa_files_using_windows/
https://www.reddit.com/r/jailbreak/comments/ejtw9x/release_install_jailbreak_via_patched_altserver/

Some related work have been done.
Hope AltStore will support this function officially.

**Comment by noah978** [comment]
The ability to sideload any IPA was released publicly awhile ago. Closing this issue.
