### ISSUE TITLE
Mail plugin incompatible since Monterey Beta 6 (21A5506j)

### ISSUE THREAD

**Issue by mikigal** [rileytestut/AltStore#821]
Mail plugin is again incompatible since Monterey Beta 6 (21A5506j). It worked on previous beta versions.
I'm using latest AltServer version.
![Zrzut ekranu 2021-08-31 o 23 38 18](https://user-images.githubusercontent.com/10632503/131579201-c11cf327-fdf9-4702-a348-eeed7df74f35.png)

**Comment by xoniq** [comment]
Same.

**Comment by blacksky2301** [comment]
Me too on beta 6

**Comment by blacksky2301** [comment]
Rename the  folder "Bundles" to "Bundles-Disabled" is not working on beta 6

**Comment by jokerknight** [comment]
Same.
and i found that the mail plist file structure was changed.
the previous way seems not working.

**Comment by KingOfDireWolves** [comment]
I downloaded this file https://github.com/rileytestut/AltStore/blob/develop/AltServer/AltPlugin.zip
and replaced the current plugin with this and now it seems to work.

**Comment by xoniq** [comment]
> I downloaded this file https://github.com/rileytestut/AltStore/blob/develop/AltServer/AltPlugin.zip
> 
> and replaced the current plugin with this and now it seems to work.

Ah thanks for notifying. Now I see the dev already had a commit for beta 6 support, which indeed the plist change:

https://github.com/rileytestut/AltStore/commit/44c431e9e06be56a15687336667a1d0e3af17a5b

**Comment by ninjaguppy** [comment]
Just tried the workaround above and when I try and install AltStore on my phone AltServer says that it needs to update the mail plug-in and replaces AltPlugin.mailbundle with the version incompatible with Monterey Beta 12

**Comment by whitesh4d0w** [comment]
Yeah, exactly the same as ninjaguppy, after this workaround altserver says that it needs to update the mail plug-in. So this doesn't work for Beta 6.

**Comment by xoniq** [comment]
The problem is that you cannot ignore installing the plugin. It's either install, or cancel everything.

I had the same, but what works; replace the plugin as mentioned before, start mail.

When Altstore want to replace the extension, don't restart mail, it replaced the files, but Mail is still having it loaded. So as long as you don't stop mail, it keeps working until we can ditch that forced plugin installer.

**Comment by whitesh4d0w** [comment]
Well that has worked, but its so weird that you have to do it this way.
So after copying the file, you start mail, enable the plugin, restart mail as it tells you, then try to install altstore on your phone - update pops up, you click on update but then DO NOT RESTART mail just let it install.. Works even on MacOS 12 beta 6.

**Comment by PythonicNinja** [comment]
> The problem is that you cannot ignore installing the plugin. It's either install, or cancel everything.
> 
> I had the same, but what works; replace the plugin as mentioned before, start mail.
> 
> When Altstore want to replace the extension, don't restart mail, it replaced the files, but Mail is still having it loaded. So as long as you don't stop mail, it keeps working until we can ditch that forced plugin installer.

I confirm that it's working on 21A5506j (MacOS 12 beta 6) 🎉

**Comment by xoniq** [comment]
> Beta 9, not work again

This workaround still works:

https://github.com/rileytestut/AltStore/issues/821#issuecomment-912469106

**Comment by mieqq** [comment]
> Its not working for Beta9 The UUID 25288CEF-7D9B-49A8-BE6B-E41DA6277CF3 has to be entered in the info.plist and the application has to be signed... You could do it your self but you have to disable Gatekeeper....
> 
> So add the UUID in Info.plist Supported12.0PluginCompatibilityUUIDs D985F0E4-3BBC-4B95-BBA1-12056AC4A531 25288CEF-7D9B-49A8-BE6B-E41DA6277CF3 sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle disable gatekeeper sudo spctl --master-disable

it works! thanks.

**Comment by Absolucy** [comment]
ah, thanks for the clarification

**Comment by rackless37** [comment]
😇

**Comment by codedprodotcom** [comment]
Anybody got this working on Monterey 12.1 ?

**Comment by kharder69** [comment]
Not yet

Ken
________________________________

**Comment by mieqq** [comment]
> Anybody got this working on Monterey 12.1 ?

https://github.com/rileytestut/AltStore/issues/905#issuecomment-985985323

**Comment by KingOfDireWolves** [comment]
Yep, the steps I listed there work for 12.1

**Comment by codedprodotcom** [comment]
> Yep, the steps I listed there work for 12.1

I just tested on 12.1 , after downloading the new plugin and replacing the old one with that one / closing mail / reopening / then enabling / doing the restart .. i still get "Mail has disabled the following plug-ins:

AltPlugin.mailbundle

Contact the makers of these plug-ins for versions that are compatible with Mail 15.0."

Am i missing a step somewhere?

**Comment by codedprodotcom** [comment]
tried stoping the mail, then pasting the new plugin , then restarting the mail app .. unfortunately same result.

**Comment by KingOfDireWolves** [comment]
> > Yep, the steps I listed there work for 12.1
> 
> I just tested on 12.1 , after downloading the new plugin and replacing the old one with that one / closing mail / reopening / then enabling / doing the restart .. i still get "Mail has disabled the following plug-ins:
> 
> AltPlugin.mailbundle
> 
> Contact the makers of these plug-ins for versions that are compatible with Mail 15.0."
> 
> Am i missing a step somewhere?

I meant the steps I listed in #905

**Comment by forcedmeme** [comment]
Just wanted to say, tried all of the above and can't get it working. Also using 12.1.

**Comment by smcue** [comment]
Same issue occurring on build 12.1, even with @xoniq workaround unfortunately.

**Comment by iVosey** [comment]
https://github.com/rileytestut/AltStore/issues/938#issue-1118037864

**Comment by drjkpalli** [comment]
doesnt work with mail version 16.0

**Comment by dan-burt** [comment]
agree that the commands to run above also are not working on Mail.app version 16.0.

is there a change to the commands? or something else that may have broken?

**Comment by dan-burt** [comment]
it does work, but the macOS menu structure has changed name and the Settings "app" has replaced "Preferences Panes". Terrible step backwards currently with UX. Think it was Mail > Settings > Manage Plug-Ins. That is weirdly a button. At the bottom. 🤷🏼‍♂️
