### ISSUE TITLE
The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1005.)

### ISSUE THREAD

**Issue by eliekh05** [rileytestut/AltStore#828]
The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1005.) when installing altstore on A1784

**Comment by kdhkr** [comment]
For some reason, this problems occurs if your network is outside of US.
The storage provider for the IPA files, `backblazeb2.com`, doesn't allow clients to connect `https://f000.backblazeb2.com` if they're outside of US.

If this issue persists with anyone, just head over and connect to any VPN server **located in US** (e.g. ProtonVPN) and it'll do the job.
