### ISSUE TITLE
installation failed: could not connect to AltServer

### ISSUE THREAD

**Issue by Mr-Styx** [rileytestut/AltStore#83]
attempting to install altstore on primary phone.
- states that altstore was downloaded to other devices and will be unable to be used on other devices. > clicked continue.
- occasionally after this step it will error out its random but this is the error :The operation couldn’t be completed. (NSURLErrorDomain error -1011.)

installation failed
- could not connect to AltServer
- mail addon is downloaded and enabled in mail preferences

config
- MBP 10.15.2
- iPhone 11 Pro max 13.3

* downloaded altstore to another iPhone using a different Apple ID.
* Apple ID freshly created and has not been used to download before.
* altserver app showed as not responding in activity monitor.

- - - - - - - - - - -- 

working instal
- iPhone XR  : iOS 13.3
- used different Apple ID 
- able to re-download altstore with old Apple ID that was originally used.

**Comment by Zm0n** [comment]
Having the same problem here all of a sudden. Even tried removing the apps from my phone and I'm still getting both of the messages you were getting. Did you ever find a solution?

11 Pro Max on 13.3.1
MacOS 10.15.3
Using my alternate Apple ID to do this.

**Comment by alexgurr** [comment]
Same.

**Comment by pricca** [comment]
Hi guys, was having the same problem, and this solution on reddit worked for me

> 3 months ago
> SOLVED: New MacOS does not interact with the iPhone through Music/iTunes any longer. So I went to Finder, clicked on the phone, and hit trust from there. Confirm it on the phone, and viola, it's ready to roll. Leaving this up for others in the future, but feel free to remove if desired.

via https://www.reddit.com/r/AltStore/comments/el6lw8/installation_failed_could_not_connect_to_altserver/

**Comment by noah978** [comment]
The solution listed above should work. Please leave a comment if the issue persists for you on the latest version of AltServer. Closing this issue.
