### ISSUE TITLE
AltDaemon not showing in Alt Store 1.4.6

### ISSUE THREAD

**Issue by KohlerVG** [rileytestut/AltStore#834]
I just installed Alt Store 1.4.6 on a non Jailbroken device, but I do not see the option to download Alt Daemon, I do not want to Jailbreak my device, I just want to be able to refresh the certificates on each app without the need of a Mac and cable to refresh the certificates.

Any help appreciated!

Thanks,
Kohler

**Comment by dareal68** [comment]
AltDaemon needs a jailbreak.

**Comment by KohlerVG** [comment]
Ok, I'm also trying to see if I can use JIT within AltServer, but I don't see it, am I doing anything wrong?

<img width="210" alt="Screen Shot 2021-09-30 at 12 47 43 PM" src="https://user-images.githubusercontent.com/65257001/135505409-0bc03d07-baa7-4007-9ca1-bbf7101eb6dc.png">

**Comment by SteveZMTstudios** [comment]
I meet an problem that I found that package on Chariz but I cannot download it because our country’s network policy.so I may need an deb packs.does anyone have it?
