### ISSUE TITLE
Windows 10 and 11 :-( (Tests 4 Betas and the Official Version)

### ISSUE THREAD

**Issue by 0xUserland** [rileytestut/AltStore#835]
Could not install AltStore to me. The provisioning profile is invalid. Please Help me! :-)
![Screenshot 2021-09-22 011514](https://user-images.githubusercontent.com/5464626/134260351-0ace9a9d-6d43-4546-acf1-e943960ae3b3.png)

**Comment by pelmahx** [comment]
### **_What of iOS version you have? If it iOS 15.1 beta, wait for AltStore update._**

**Comment by 0xUserland** [comment]
14,7.1 iPhone 11 pro Max

**Comment by 0xUserland** [comment]
New install of Windows, without any other tools, only iCloud, iTunes and AltStore comes the same error mentioned above.
