### ISSUE TITLE
"The procedure entry point idevice_get_device_list_extended"

### ISSUE THREAD

**Issue by RitualCartoon4** [rileytestut/AltStore#839]
Not sure what i've done, i uninstalled using the proper uninstaller, decided "hey i want this again" so i redownloaded it using the same installer. Now i get this message, itunes and icloud are both open, i've tried using the "fix" button, dont know what to do here. 
![image](https://user-images.githubusercontent.com/91267512/134515104-7ee18d41-c2fb-4267-9d5a-d7b0d03299b4.png)

**Comment by pelmahx** [comment]
### **_Try to update your drivers\software._**

**Comment by mailinglists35** [comment]
I solved this by removing altserver, reinstall itunes and icloud, reinstall altserver. oddly 3utools was working just fine without itunes/icloud, only with drivers, bonjour and apple application support msi's installed.
