### ISSUE TITLE
installation failed: always crash on Windows

### ISSUE THREAD

**Issue by thecyyoung** [rileytestut/AltStore#84]
Every time after I enter Apple-ID/PW and press Install, it crashes...
The gray icon on the tray disappears....

I just download AltStore today, the version should be the newest...

Thank you very much~

![cut 2020-01-08 180510](https://user-images.githubusercontent.com/59646523/71970117-010c4380-3243-11ea-933c-769f75ef1157.png)

**Comment by matt1tk** [comment]
Same issue.

**Comment by AtTimesChris** [comment]
same issue here too

**Comment by noah978** [comment]
This should be fixed on the latest versions of AltStore/Altserver. Closing this issue.
