### ISSUE TITLE
altstore is not working on iOS15

### ISSUE THREAD

**Issue by Metal-joker** [rileytestut/AltStore#846]
as title

**Comment by Metal-joker** [comment]
fixed by reinstall altstore. closing this

**Comment by wongxingke** [comment]
Can you fixed by reinstall？really？

**Comment by Metal-joker** [comment]
> Can you fixed by reinstall？really？

Sure. download latest installer from their website. and install on ur pc, then use ur pc install it to your phone, then it's done.

**Comment by wongxingke** [comment]
iOS 15.1 beta？

**Comment by Metal-joker** [comment]
> iOS 15.1 beta？

nope. ios 15 release.
