### ISSUE TITLE
JIT compilation could not be enabled for AltStore.

### ISSUE THREAD

**Issue by septfoil** [rileytestut/AltStore#847]
JIT compilation could not be enabled for AltStore.
Debug Server error -256.
macOS 11.3.1 (20E241)
iOS 15.0

**Comment by ibapps39** [comment]
I too have been experiencing this. I have reinstalled, signed in and out my AppleId, restarted my computer, and used several versions (beta and official). 

While atm I can't offer a suggestion for a fix, I can try!

**Comment by mkueller** [comment]
It's happening on my Windows PC as well. I have the newest public build.

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?

**Comment by ibapps39** [comment]
Not sure, but appreciate it!
