### ISSUE TITLE
Application is missing the application- identifier entitlement.

### ISSUE THREAD

**Issue by HSAK5G** [rileytestut/AltStore#848]
I get this error whenever I try to side load Spotify++. It works fine with some other sideloaded apps. I am running the latest version of altserver. My ios version is 15.0 and is an iPhone xr.

![image](https://user-images.githubusercontent.com/44635763/135252404-ea70952e-7e37-489c-97f5-20576c11f2d7.jpeg)

**Comment by asm19** [comment]
Same problem, iOS 15.0.1 and iPhone 12 Pro

**Comment by Owen993** [comment]
Having the same issue. iPhone XR IOS 15.0.1

**Comment by Dj3ng1s** [comment]
I have the same problem

**Comment by HSAK5G** [comment]
Works with the latest version of AltStore. Closing the issue

**Comment by Dj3ng1s** [comment]
Okay. I have AltStore 1.5b3 on my iPhone 13 pro Max. But i cant get Spotify++ work

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: HSAK5G ***@***.***>
Sendt: Sunday, November 7, 2021 10:39:05 AM
Til: rileytestut/AltStore ***@***.***>
Cc: Dj3ng1s ***@***.***>; Comment ***@***.***>
Emne: Re: [rileytestut/AltStore] Application is missing the application- identifier entitlement. (#848)


Works with the latest version of AltStore. Closing the issue

**Comment by Player110** [comment]
Same issue here, and also if yo look in your remaining ids spotify shows as using one. so now you have to wait 7 days for it to expire and give you the free space it takes.

**Comment by lonkelle** [comment]
Is it the same error as OP guys?
