### ISSUE TITLE
Can't refresh apps "Could not find Altserver"

### ISSUE THREAD

**Issue by Kazerole** [rileytestut/AltStore#85]
Hello,
I had this error message during my first use of the Altstore but then was able to download Delta after a few tries (reinstalling, rebboting etc...). But now I can't refreshthe apps and am shown this same message : "Could not find Altserver"
My phone is linked by cable, with iTunes running (internet windows version) ; on the same hotspot (tried my box and using my phone as a hotspot) ; firewalls down ; various combination of restarting phone, altserver, comupter etc... reinstalled altserver on the computer. Nothing seems to work
Ideas ? Thanks in advance

**Comment by PartyJoey** [comment]
Having the same issue

**Comment by dontbanmeplz** [comment]
#123

**Comment by noah978** [comment]
Make sure that Apple Mobile Device Service is running and you have iCloud downloaded as well. Consider installing the recently released [beta AltServer.](https://altstore.io/altserver/beta/)

Regardless, this should be fixed on the latest versions of AltStore/Altserver. Closing this issue.
