### ISSUE TITLE
No support for Mail 15.0

### ISSUE THREAD

**Issue by DJZSwag** [rileytestut/AltStore#852]
I'm currently on a m1 iMac running macOS Monterey 12.0 Public Beta (specifically build 21A5534d) and tried to install the mail plug in, but instead it said "Mail Has disabled the following plugins: AltPlugin.mailbundle, contact the makers of these plug-ins for versions that are compatible with Mail 15.0." Can you please fix this, so I can jailbreak my iPod Touch?

**Comment by iamibson** [comment]
I’m having the same issue over here

**Comment by Mcrich23** [comment]
Same

**Comment by Jiyuuneko** [comment]
Same

**Comment by sickerin** [comment]
Almost everything didn't work for me. But this did.
- Quit Mail app, then either using the finder or terminal go to ~/Library/Application Support/Mail/Plug-ins
- Delete everything under there. 
- Then go to Altserver, try un-install and reinstall.
