### ISSUE TITLE
iPhone13 Support

### ISSUE THREAD

**Issue by nakano0505** [rileytestut/AltStore#856]
I can't find my iPhone 13mini on my computer, I'm using Altstore 1.4.6, iTunes 12.12.1, iCloud 7.21.0.23, Windows 10 20H2, the same cable and USB port as my iPhone 12mini (iOS 14.2.1) and iPhoneSE2 (iOS15.0) then no problem

**Comment by TigerBeanst** [comment]
try the cable of iPhone 13mini?

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?

**Comment by nakano0505** [comment]
thanks,there is not problem with the last release with my iPhone13 now.
