### ISSUE TITLE
Won't fit iPad Screen

### ISSUE THREAD

**Issue by MyCatCondo** [rileytestut/AltStore#86]
AltStore on iPad looks really small, and I wish it could actually fit the screen AKA a iPhone/iPad app. Could you please fix this?

**Comment by suyashbansal** [comment]
Having the same issue. 😅

**Comment by JbAmade** [comment]
There should be a double arrow at the bottom right to toggle from small to large view. It doesn’t fit iPad screen by default. The default view is for iPhone and it just makes it larger for iPad.

**Comment by Samuel12321** [comment]
Suggest close superseded by #150

**Comment by noah978** [comment]
This is a duplicate of #39. Closing this issue.
