### ISSUE TITLE
Altstore error on my iPad

### ISSUE THREAD

**Issue by kleqing** [rileytestut/AltStore#861]
I installed altstore on my iPad Air 2 (iPadOS 15.0.2) but when i install UTM, the progress bar stuck at 60% (or 70%). I wait for 1 hours but it still loading. I've tried on my iPhone my the same has happened. Please help me (sorry about bad english)

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?

**Comment by kleqing** [comment]
@shanegillio That's okay. Anyway, I've been trying alstore to install another apps since the utm can't be installed and it working, except the utm. I don't know why but on my iPhone it working but on my iPad it doesn't.

**Comment by shanegillio** [comment]
ok, let me know if I can do anything else
