### ISSUE TITLE
Issue with mac os 12 and mail plugin

### ISSUE THREAD

**Issue by DevPrestigious** [rileytestut/AltStore#864]
When trying to load altstore on OS 12, it says incompatible plugin. This happened as soon as I updated from OS 11.

Any ideas?

**Comment by CodeNameDimitri** [comment]
I’m on the latest version of AltStore and macOS but the mail plug-in STILL doesn’t work. Even trying the solution in the stickied post on r/AltStore but it did not solve the issue. This issue has persisted on 3 different MacBooks. Any ideas?

![Screen Shot 2021-11-02 at 11 10 03 PM](https://user-images.githubusercontent.com/78448103/140101833-6cc3c3ad-e352-42e8-a716-573477b151b6.jpeg)

**Comment by d4x1** [comment]
@CodeNameDimitri  I think you should re-install the mail plugin. If possible, totally reinstall AltStore.

**Comment by CodeNameDimitri** [comment]
> @CodeNameDimitri  I think you should re-install the mail plugin. If possible, totally reinstall AltStore.

I tried that. I've even downgraded to an older version to then update OTA and still no dice.

**Comment by RllyX** [comment]
@CodeNameDimitri Hey, did you ever get that fixed? I'm having the same issue. I thought it might've been because I was on the macOS beta, but even after opting out, it's still an issue.

**Comment by CodeNameDimitri** [comment]
> @CodeNameDimitri Hey, did you ever get that fixed? I'm having the same issue. I thought it might've been because I was on the macOS beta, but even after opting out, it's still an issue.

I have not, I just switched to Sideloady for the time being since I have access to the Developer Program

**Comment by CodeNameDimitri** [comment]
> @CodeNameDimitri Hey, did you ever get that fixed? I'm having the same issue. I thought it might've been because I was on the macOS beta, but even after opting out, it's still an issue.

Also, it's one thing to opt. Downgrading/Upgrading to the latest public version macOS is another. If you have done that, I suggest you do.

**Comment by DevPrestigious** [comment]
I also switched to Sideloadly.
