### ISSUE TITLE
Error when installing uncover

### ISSUE THREAD

**Issue by stef2098** [rileytestut/AltStore#868]
Hello, I am trying to install uncover version 7.0.1 on my iPhone but I get the following error:
![1DA9FDF2-1D75-4786-B641-93C964270CB2](https://user-images.githubusercontent.com/85192750/139392342-6169cc51-2ce9-4d83-84f5-a02bbeeba851.png) any help would be appreciated!

**Comment by Yeudhhdhdv** [comment]
This is normal because you can install a maximum of 3 applications.

Just create new apple id
