### ISSUE TITLE
Session has expired. Please login (1100)

### ISSUE THREAD

**Issue by CoreISP** [rileytestut/AltStore#87]
I keep seeing this error when attempting to use AltServer to install AltStore. This is on a Windows machine. Tried logging out on iCloud + iTunes, rebooting, logging back in, changing Apple ID password, logging in with a browser to appleid.apple.com and try again, creating an app-specific pass + revoke them all + change password again, disable Windows Firewall, rebooting the phone: nada, nothing works. I see fastlane/sigh had similiar issues and they fixed it a while ago allegedly. And using XCode on Mac tons of users are reporting it happening there as well (and fixing it by disabling DVTDeveloperAccountUseKeychainService) - but this is Windows anyway, hehe. 

I've done some Google'ing around as well. Lots of people with the same problem using AltServer, none that have found a work-around. Any clues as to why this is happening? Out of ideas. :)

**Comment by yikefengshu** [comment]
Same problem here.

**Comment by CoreISP** [comment]
It looks like they're aware of the problem: https://twitter.com/altstoreio/status/1217354522818859008

**Comment by Malikf5** [comment]
I'm still getting this error.

**Comment by CoreISP** [comment]
Problem solved in new release

**Comment by telegramcore** [comment]
Same to me on last version 1.2.0.0, I don't know how to fix

**Comment by telegramcore** [comment]
@CoreISP wich release do you have?

**Comment by CoreISP** [comment]
@telegramcore Sorry! Notifications on GH apparently don't work as I expect, lol. The latest version from the website works here. If you're still experiencing this problem, let me know!

**Comment by meero619** [comment]
I'm still getting the same error. any help?

**Comment by smaracy90** [comment]
I had something similar on windows-10

at first make sure that you installed last version of icloud and itunes

then Make sure you are signed into iTunes

*Be sure to authorize iTunes → Accounts → Authorizations → Authorize This Computer*

Enable iTunes Wi-Fi sync for your phone

Minimize iTunes when done. Make sure it is still open in the background

Run altserver as admin

**Comment by meero619** [comment]
that's exactly what I did. no idea why it's not working.
