### ISSUE TITLE
 Altstore crash launch ios 13.5

### ISSUE THREAD

**Issue by Lithyie** [rileytestut/AltStore#870]
Hello, i did the update of altstore from the "my apps" tab in the app and it crashed and i cant launch it anymore. I reinstalled it and still cant launch it. I dont have logs since i lost my jailbreak because of that....

iphone 11, iOS 13.5

**Comment by xuanhaivptthn** [comment]
You probably want to join us on #867 , don't open another issues if there is already one similar to your problem just 3 down...

**Comment by shanegillio** [comment]
closing as dup
