### ISSUE TITLE
altstore wont open (iphone 8, ios 13.5)

### ISSUE THREAD

**Issue by urdjk** [rileytestut/AltStore#871]
recently reinstalled altstore (via windows), trusted in settings when i go to open the app it immedietly closes, no error message, latest version of altstore, latest version of icloud and itunes

**Comment by theLaxerz** [comment]
Same issue in 13.3 with iPad pro 3rd.

**Comment by urdjk** [comment]
fixed by downgrading to altstore version 1.4.7 as suggested by shevy4 in issue 874
