### ISSUE TITLE
"Unable to Launch AltStore"

### ISSUE THREAD

**Issue by CobreDev** [rileytestut/AltStore#885]
I'm a developer on a company's paid developer account, and I'm using that team in Xcode. Whenever I try to build AltStore to run on my iPhone 13 mini on iOS 15.1, it gives me this error:

**Unable to Launch AltStore**
The file "Apps" couldn't be saved in the folder "Application Support".
![image](https://user-images.githubusercontent.com/36574329/140953632-9422f63d-6e0b-471c-bd66-cc973f205cea.png)

I'm using the latest build from the main branch here. Looking at the logs, it looks to be error with entitlements but I'm not sure how to fix that. Here are the logs:

https://pastebin.com/HzaAZQjd

What am I doing wrong?

**Comment by ppamorim** [comment]
I am experiencing the same issue. Totally unable to use AltStore.

**Comment by ppamorim** [comment]
@CobreDev I think the problem relies on the App Groups. I was able to install and make AltStore work after a couple of tries.

**Comment by CobreDev** [comment]
I don't know much about App Groups but I created "group.dev.cobre.AltStore" in Xcode and reached Riley's groups with it, no luck. Am I doing it wrong?

**Comment by CobreDev** [comment]
> @CobreDev I think the problem relies on the App Groups. I was able to install and make AltStore work after a couple of tries.

@ppamorim I'm trying this again, would you mind explaining how exactly you fixed this?

**Comment by ppamorim** [comment]
I did install but it was not installing other apps. I am using another software to install apps.

**Comment by CobreDev** [comment]
Update: I was able to solve this by creating and selecting an app group, and also searching for `group.com.riley...` and replacing those instances with my app group's identifier

**Comment by Mohamad-fcz** [comment]
I have the same issue, and I'm totally unfamiliar with the terms that you guys are using. Can somebody please let me know how can I resolve this error simply?
