### ISSUE TITLE
Altstore crashed when open on iOS14.8.1

### ISSUE THREAD

**Issue by VHDelusion** [rileytestut/AltStore#886]
I updated my iPhone12 to iOS14.8.1 yesterday，then found Altstore and the app i've sideloaded crashed as i open them：（

plz fix this bug

**Comment by eismont21** [comment]
+1
The same issue is on my iPad Air with iOS 14.8.1. AltStore works fine, but sideloaded apps always crash.

**Comment by eismont21** [comment]
FIX: Re-activate sideloaded apps. It helps me.

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?

**Comment by eismont21** [comment]
A year ago the fix above solved the problem. Now all my devices are on a more current iOS version, so I can't say about the relevance of the issue.
