### ISSUE TITLE
Altstore crashes at launch on iOS 13.3.1

### ISSUE THREAD

**Issue by singhyuvraj31** [rileytestut/AltStore#89]
The installation process is fine, everything goes well but the app crashes on 13.3.1 beta.

**Comment by sonoseco** [comment]
Same here on the latest iOS beta.

**Comment by dojo90** [comment]
Same on 12.4.3

**Comment by valpinkman** [comment]
same here on 13.3.1

**Comment by LoveSicKWAR** [comment]
+1

**Comment by paulhaskew** [comment]
Also having this issue. Update was forced sadly.

**Comment by webvictim** [comment]
I had to reinstall AltStore from scratch after updating but it worked fine that.

**Comment by noah978** [comment]
This was an issue with iOS 13.3.1 but the latest version of AltStore and Delta are compatible with it. Closing this issue.
