### ISSUE TITLE
Alt store does not prompt for untether

### ISSUE THREAD

**Issue by racerx8967** [rileytestut/AltStore#893]
Hi I have an issue with an iPhone 11 Max pro on 14.3 where alt store isn’t asking to install the untether. Everything is updated on the alt store and server side. I know this is also happening to quite a few other people has anyone experienced this issue or fixed it? This has been an issue since release I was just wondering if anything is in the works to fix alt store not prompting to untether.

**Comment by mooseknuckleking** [comment]
Same issue

**Comment by d066z** [comment]
> Hi I have an issue with an iPhone 11 Max pro on 14.3 where alt store isn’t asking to install the untether. Everything is updated on the alt store and server side. I know this is also happening to quite a few other people has anyone experienced this issue or fixed it? This has been an issue since release I was just wondering if anything is in the works to fix alt store not prompting to untether.
