### ISSUE TITLE
Crash when opening altstore.

### ISSUE THREAD

**Issue by kurogasatyan** [rileytestut/AltStore#898]
I'm trying to install it on my iphone 6 but it crashes.  (after I press authenticate app firmly). Please tell me what to do.
Software version 12.5.4 Device iphone 6 Altserver version 1.4.7.0 windows11

**Comment by peterg00** [comment]
same here

**Comment by WeiZhou2372** [comment]
same problem here for iOS 12.5.4 iPad Air Altserver version 1.4.7.0 windows10.

**Comment by rayvearn** [comment]
same

**Comment by h4ck1th4rd** [comment]
same problem here any solutions? THANK YOU

**Comment by davisjason325** [comment]
same....looking for a solution.  any workarounds?

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?

**Comment by kurogasatyan** [comment]
No, not at all. It's all okay. The ploblem is already solved. Thank you for update <333

**Comment by shanegillio** [comment]
:)
