### ISSUE TITLE
Windows altstore missing dependencies and dll entry point though installed

### ISSUE THREAD

**Issue by paulhaskew** [rileytestut/AltStore#90]
After installing iCloud direct from Apple, iTunes x64 direct from Apple, restarting and installing AltStore on two different machines running Windows 10 version 1909 (OS Build 18363.592), I am getting errors stating that an entry point is missing in the CFNetwork.dll file, along with a message that iCloud is not installed. See the error messages below. Not seeing anything in the eventvwr.

![MissingEntryPoint](https://user-images.githubusercontent.com/35110616/73182599-924e3780-40d6-11ea-835b-9d73a4e19ade.jpg)
![MissingDependencies](https://user-images.githubusercontent.com/35110616/73182600-924e3780-40d6-11ea-8eaa-fd11124e047f.jpg)
![InstalledApplications](https://user-images.githubusercontent.com/35110616/73182601-92e6ce00-40d6-11ea-94c9-d862b3306c26.JPG)

**Comment by timowalraven** [comment]
I'm having the exact same issue.

**Comment by noah978** [comment]
If this issue still persists, I'd recommend starting up iCloud and logging in with the same Apple ID you use for AltStore. But considering the age of this thread, I will assume it's fixed and close this issue.
