### ISSUE TITLE
Mail Plugin doesn't work with Mail 15.0

### ISSUE THREAD

**Issue by Tejaswgupta** [rileytestut/AltStore#905]
Mail has disabled the following plug-ins:

AltPlugin.mailbundle

Contact the makers of these plug-ins for versions that are compatible with Mail 15.0.

**Comment by KingOfDireWolves** [comment]
I am listing some steps which you must follow every time an update breaks the plugin

Step 1 : Go to /System/Applications/Mail.app/Contents/Info.plist
Step 2 : Search for PluginCompatibilityUUID and copy the UUID value (it will be in the next line enclosed between string tags)
Step 3 : Go to /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist
Step 4 : Add the previously copied UUID in this file (For example if you have macOS 12.1 then add it to the Supported12.1PluginCompatibilityUUIDs).

It will be pretty obvious what you need to do when you open the info.plist file

Step 5 : Open terminal and run sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle
Step 6 : Disable gatekeeper sudo spctl --master-disable
Now open Mail app and go to preferences and enable the plugin and restart the app...

**Comment by theotherJohnC** [comment]
> Step 6 : Disable gatekeeper sudo spctl --master-disable

Disabling gatekeeper globally doesn't seem like a particularly viable solution. Granted, we're talking about side loading applications to an iPhone, but still...

**Comment by KingOfDireWolves** [comment]
> Disabling gatekeeper globally doesn't seem like a particularly viable solution. Granted, we're talking about side loading applications to an iPhone, but still...

Just enable it again you are done the plugin starts working

**Comment by KingOfDireWolves** [comment]
> Disabling gatekeeper globally doesn't seem like a particularly viable solution. Granted, we're talking about side loading applications to an iPhone, but still...

Just enable it again after the plugin starts working

**Comment by theotherJohnC** [comment]
> I am listing some steps which you must follow every time an update breaks the plugin
> 
> Step 1 : Go to /System/Applications/Mail.app/Contents/Info.plist Step 2 : Search for PluginCompatibilityUUID and copy the UUID value (it will be in the next line enclosed between string tags) Step 3 : Go to /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist Step 4 : Add the previously copied UUID in this file (For example if you have macOS 12.1 then add it to the Supported12.1PluginCompatibilityUUIDs).
> 
> It will be pretty obvious what you need to do when you open the info.plist file
> 
> Step 5 : Open terminal and run sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle Step 6 : Disable gatekeeper sudo spctl --master-disable Now open Mail app and go to preferences and enable the plugin and restart the app...

Executed the instructions, plugin still disables stating AltPlugin.mailbundle is incompatible with Mail 15.0.

**Comment by japindersi** [comment]
> Executed the instructions, plugin still disables stating AltPlugin.mailbundle is incompatible with Mail 15.0.

Works for me on Mac OS Monterey 12.1 fresh upgrade & refreshes the apps successfully with iOS 15.2 fresh upgrade. Was failing for me earlier, before I followed these steps, when I upgraded both my Mac & iPad earlier today & found it had landed me in a bother.

I think with Monterey 12.1 the functionality, or rather the way or place it stores files has changed a bit.

Previously it seemed to use the file:
~/Library/Application\ Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/Properties.plist

Now it seems to use this one:
~/Library/Application\ Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist

In fact this complete folder is new, it didn't used to be there until Mac OS Monterey 12.0.1:
~/Library/Application\ Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/AltPlugin.mailbundle/

Can you check if this folder exists & the Info.plist file above exists and contains the UUID you added, under this tag:
	<key>Supported12.1PluginCompatibilityUUIDs</key>
	<array>
		<string>***UUID***Existing***Earlier***</string>
		<string>***UUID***Added***Now***</string>
	</array>

If the new UUID exists here, it should work, if its not working then one of the intermediate steps failed.

Thanks,
Jp

**Comment by MattElek** [comment]
It seems to be possible to simply allow a gatekeeper exception, using a command such as `sudo spctl --add --label "Allow AltPlugin to load" /Users/matt/Library/Application\ Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/AltPlugin.mailbundle`

**Comment by KingOfDireWolves** [comment]
Now AltPlugin has been officially updated to support macOS 12.1

**Comment by MAClife32** [comment]
> Now AltPlugin has been officially updated to support macOS 12.1

**Comment by MAClife32** [comment]
> Now AltPlugin has been officially updated to support macOS 12.1

I'm on macOS12.1 too can you explain how you got it to work for you?

**Comment by MAClife32** [comment]
> Now AltPlugin has been officially updated to support macOS 12.1

Do you have a link?

**Comment by KingOfDireWolves** [comment]
> Do you have a link?

Just update AltServer

**Comment by gregmichael** [comment]
Updating plugin and server 1.4.8 (60) did not fix.

**Comment by Xiperiz** [comment]
Updated plugin still doesn't work, None of the methods above fix the issue

**Comment by cedmos** [comment]
Actually it worked for me but for some reason I was always trying to find it in the Plugins-Tab of the Mail App where it said "no Plugins". 

But after I recognized there is a "Manage Plugin" Button on the "General Settings" Tab (first tab) I could select it and then it startet to show up in the Plugins-Tab to be enabled.

Maybe someone else did miss that there is actually two places in the Mail-Settings where it needs to be enabled.

Best
Cedric

PS Names of the Tabs / Settings are translated from Germany so maybe slightly differ in US

**Comment by Easen** [comment]
I did everything in @KingOfDireWolves  [helpful comment](https://github.com/rileytestut/AltStore/issues/905#issuecomment-985985323) expect for Step 6, instead I ran 
```
sudo spctl --add --label "Allow AltPlugin to load" /Library/Mail/Bundles/AltPlugin.mailbundle
```

so far so good!

**Comment by xoniq** [comment]
Just updated to latest macOS 12. But still not working.

- Removed AltPlugin via Finder
- Reinstalled via AltServer
- Ran all steps above
- UUID was already in the plist file
- Did the codesign

Still not working, keeps disabling the plugin on launch of mail.

**Comment by tamarteleco** [comment]
> I am listing some steps which you must follow every time an update breaks the plugin
> 
> Step 1 : Go to /System/Applications/Mail.app/Contents/Info.plist Step 2 : Search for PluginCompatibilityUUID and copy the UUID value (it will be in the next line enclosed between string tags) Step 3 : Go to /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist Step 4 : Add the previously copied UUID in this file (For example if you have macOS 12.1 then add it to the Supported12.1PluginCompatibilityUUIDs).
> 
> It will be pretty obvious what you need to do when you open the info.plist file
> 
> Step 5 : Open terminal and run sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle Step 6 : Disable gatekeeper sudo spctl --master-disable Now open Mail app and go to preferences and enable the plugin and restart the app...

works perfect, thanks!

**Comment by Violetblache** [comment]
OMG this us a life saver watch this
 https://www.youtube.com/watch?v=wmcEpCUjGl0

**Comment by 618116** [comment]
The workaround seems not working at MacOS 12.3 beta. Mail app said the plugin is broken when you edit info.plist.

**Comment by avarayr** [comment]
I've created a bash script to automate the process of updating the compatible UUIDs. Feel free to use it 
https://gist.github.com/avarayr/2490e4f83f1781ebef440c2dc5089235


Instructions:
1. Download the gist and save it as `altermail.sh`
2. Open terminal in that folder
3. `chmod +x ./altermail.sh`
4. `sudo bash ./altermail.sh`

**Comment by MrG-11** [comment]
Guys, nothing worked for me until I tried solution 2: https://www.reddit.com/r/AltStore/comments/om3z64/solution_to_incompatible_mail_plugin_for_macos/

it works perfectly!

**Comment by xoniq** [comment]
> Guys, nothing worked for me until I tried solution 2: https://www.reddit.com/r/AltStore/comments/om3z64/solution_to_incompatible_mail_plugin_for_macos/
> 
> 
> 
> it works perfectly!

Same for me. Tried everything, but only removing the bundle cache worked.

**Comment by aesophor** [comment]
> Guys, nothing worked for me until I tried solution 2: https://www.reddit.com/r/AltStore/comments/om3z64/solution_to_incompatible_mail_plugin_for_macos/
> 
> it works perfectly!

This is the only way that works for me.

**Comment by yunjia9664** [comment]
> OMG this us a life saver watch this
> https://www.youtube.com/watch?v=wmcEpCUjGl0

I am surprised by how simple and effective this is.

**Comment by Mifaxav** [comment]
> 

this worked for me!
