### ISSUE TITLE
Keyboard doesn’t have @ symbol next to the space bar on the email field

### ISSUE THREAD

**Issue by DetachHead** [rileytestut/AltStore#907]
![74828A3A-7444-4F97-9978-C75AA563A19B](https://user-images.githubusercontent.com/57028336/144704445-efa82177-52d5-42b8-a64a-7c66026fe3b5.jpeg)

usually email fields have an @ symbol next to the keyboard like so:
![8614C90E-C016-4A55-A664-373656AB8896](https://user-images.githubusercontent.com/57028336/144704464-4a2be4eb-66d0-458e-8144-40d05a8a67d4.jpeg)

**Comment by TrustedInst** [comment]
Go to the "123" , you will see the @ key

**Comment by DetachHead** [comment]
i know, but it should be next to the spacebar so it's more easily accessible like it is in other email fields
