### ISSUE TITLE
AltServer error (-22410)

### ISSUE THREAD

**Issue by TrustedInst** [rileytestut/AltStore#909]
I can't sign in to the AltServer to install on my phone. It always say ''This action could not be completed. Try again. (-22410) ''. What do i do?. I'm using iOS 15.1

**Comment by nlahmi** [comment]
Try another AppleID (not a new one but also not the one attached to your device)

**Comment by TrustedInst** [comment]
I tried it, but not successful. I restarted my computer, and it works. Maybe some issues about my keyboard because when typing the "@", it not appear
