### ISSUE TITLE
Trouble Installing Altstore

### ISSUE THREAD

**Issue by nico671** [rileytestut/AltStore#911]
Getting a The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1001.) error when trying to install. It was working fine earlier until I uninstalled and tried to reinstall. I've tried on hotspot with vpn and on many different wifis

**Comment by nico671** [comment]
additionally altstore doesnt recognize any devices over internet connection, only through manual usb connections

**Comment by comicallybad** [comment]
same issue here. Bought a VPN just because people said that worked, wasted 12$ on that for nothing.
