### ISSUE TITLE
Keeps prompting to update apps when on latest version

### ISSUE THREAD

**Issue by DetachHead** [rileytestut/AltStore#917]
Repo: https://qnblackcat.github.io/AltStore/apps.json

After updating these two apps, AltStore seems to still think the installed versions are out of date 
![02C27167-EAF5-414C-AD4D-802DC5111296](https://user-images.githubusercontent.com/57028336/146196919-c0fc017c-fbdb-4cae-ae16-d68fd0ce5c24.jpeg)

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version? we are working on releasing an update to this soon

**Comment by DetachHead** [comment]
I don't use AltStore anymore now that I'm jailbroken but I installed it on someone else's phone the other day and didn't encounter this so I'll assume it's since been fixed. Thanks
