### ISSUE TITLE
macOS Monterey 12.1 Mail 15.0 Plugin still not working with AltServer 1.4.8

### ISSUE THREAD

**Issue by MrNoHand** [rileytestut/AltStore#918]
Plugin is not showing up in Mail V. 15.0. Already tried a complete clean install of AltServer 1.4.8 with reboot. First idea is that the installation folder is wrong. I think it should be installed in:

~/Library/Application\ Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles/AltPlugin.mailbundle/

But Mail is deleting the folder after copying and restarting the Mail app.

**Comment by phucle225** [comment]
https://github.com/rileytestut/AltStore/issues/905

**Comment by obi12341** [comment]
Still not works with latest version (1.4.8) for me. Extension is simply not showing up in mail.app
<img width="783" alt="Extension is not showing up" src="https://user-images.githubusercontent.com/199624/146685466-6a9791c1-60d7-4acb-a1f6-b46d20b76cbc.png">

**Comment by IsaacXen** [comment]
> Still not works with latest version (1.4.8) for me. Extension is simply not showing up in mail.app
> <img alt="Extension is not showing up" width="783" src="https://user-images.githubusercontent.com/199624/146685466-6a9791c1-60d7-4acb-a1f6-b46d20b76cbc.png">

It's not an extension, it's a plug-in. You should be able to find it in `Mail Preferences` - `General` - `Manage Plug-ins...` (bottom left corner).

**Comment by obi12341** [comment]
oh my bad, everythings works. Sorry for that.
