### ISSUE TITLE
Installation Failed objects-13.0+.nib

### ISSUE THREAD

**Issue by PLanB2008** [rileytestut/AltStore#92]
When trying to install altstore I receive this message:

![grafik](https://user-images.githubusercontent.com/26460239/73354416-fbc87480-4295-11ea-9b79-328445bf8900.png)

I'm running macos catalina.

**Comment by noah978** [comment]
This should be fixed on the latest versions of AltStore/Altserver. If not, please leave a comment below. Closing this issue.

**Comment by PLanB2008** [comment]
Now I reaveive this error:

<img width="453" alt="grafik" src="https://user-images.githubusercontent.com/26460239/82729533-955ddb00-9cf8-11ea-9cb8-003ea003fe04.png">

Should I open another issue for this?

**Comment by noah978** [comment]
There is an ongoing discussion in #185 for this. You can join there and help us debug the issue.
