### ISSUE TITLE
IPA?

### ISSUE THREAD

**Issue by SuperS0n1k** [rileytestut/AltStore#922]
I was just thinking, so people don’t have to use a computer to install AltStore,
Could you publish an IPA file?

**Comment by TrustedInst** [comment]
You might watched some fake AltStore installation. It required a computer to run AltServer, install and renew the apps.

**Comment by noah978** [comment]
The issue with this idea is that AltStore requires certain entitlements to be included in the applications info.plist at the time of sideloading. Therefore, the only application that can actually install AltStore to your device properly at runtime, is AltServer.
