### ISSUE TITLE
"App contains extensions" prompt only appears when sideloading but not when downloading from a source

### ISSUE THREAD

**Issue by DetachHead** [rileytestut/AltStore#929]
When I first downloaded this app I recall it gave me an option to decide whether or not to use its additional app ids. At the time I clicked yes because I didn’t know what it meant but from my understanding they aren’t required for the app to function. But I can’t seem to get it to show this prompt anymore and instead it just fails to install because I guess it’s remembered my original answer

Is there a way to make it forget my decision? Tried deleting and reinstalling AltStore but it’s still remembered all my apps/settings somehow

![D8A28AC6-04FE-4A88-A93C-14870D1491E3](https://user-images.githubusercontent.com/57028336/149610121-aa63df36-ece3-44ce-8c27-0182cc4948e9.jpeg)

**Comment by TrustedInst** [comment]
Upgrade your account to Paid Developer, or wait a week to all apps to expired. Then reinstall the AltStore and your apps

**Comment by DetachHead** [comment]
I already did that. I’m not asking for more app ids or anything, only how to get AltStore to give me the option to install an app without its additional app ids, which from my understanding doesn’t have anything to do with whether or not i have a paid developer account

**Comment by ethan-xd** [comment]
![image](https://user-images.githubusercontent.com/24442053/149684001-91d961dd-8915-4e9c-b7b1-c12ea2b55858.png)

this is what is being referred to

**Comment by DetachHead** [comment]
so it seems that option only appears when sideloading apps, but not when downloading them from a source
