### ISSUE TITLE
AltStore Beta crashing on iOS 13.3.1 (non Beta Version)

### ISSUE THREAD

**Issue by 100hp4ever** [rileytestut/AltStore#93]
Altstore Beta is crashing at launch.
Reinstall of AltStore and AltStore Beta didn't fix the issue.
Device iPhone X.

**Comment by paulhaskew** [comment]
Same issue, IPhone XS Max with iOS 13.3.1 retail.

**Comment by 100hp4ever** [comment]
fixed
