### ISSUE TITLE
Update Error!

### ISSUE THREAD

**Issue by kwlreal** [rileytestut/AltStore#931]
mac os 12.1: AltServer can’t be updated if it’s running from the location it was downloaded to.

**Comment by kwlreal** [comment]
The official website is not the latest version，The version I downloaded is 1.4.7， not 1.4.8

**Comment by Xmoncoco** [comment]
to update place your Altstore app in your application file

**Comment by helixxger** [comment]
I've got the same issue

AltServer is running from application folder, but I still get the error, that it cannot be updated...
