### ISSUE TITLE
the mail plugin don't install 

### ISSUE THREAD

**Issue by Xmoncoco** [rileytestut/AltStore#932]
I'm on Mac OS 12.1 and my mail is on 15.0 I don't know what it be cause

**Comment by jody** [comment]
Here's how I am able to reproduce an unsuccessful attempt at installation
on **macOS Monterey Version 12.1**
with **Mail Version 15.0 (3693.40.0.1.81)**

In the Mail app, select `AltPlugin.mailbundle` from the "Manage Plug-Ins..." dialog of Preferences > General.

This brings up a dialog "Do you want to allow Altplugin.mailbundle to access any files on this computer that Mail can access?"
Choose "Allow Access".

Click "Apply and Restart Mail".

During startup, Mail brings up this alert ("Incompatible Plug-ins Disabled") identifying AltPlugin.mailbundle:
<img width="260" alt="Screen Shot 2022-01-25 at 1 47 25 PM" src="https://user-images.githubusercontent.com/379845/151057686-c958dd04-4f72-4bd1-b9bb-f368688779ac.png">

**Comment by apple-ihack-geek** [comment]
I'm guessing the cause is that for some reason the most recent version of alt server is not available on the alt store website, should be an easy fix

**Comment by jorgehvillarreal** [comment]
I have the same issue and tried the solution on the video but doesn't seem to work. I also have tried uninstalling and installing the plugin and also went back to the version on the website and also no. It says "No Extensions" shows up when i go to Mail > Preferences > Extensions.

I am running:
macOS Monterey V12.2.1 (21D62)
Mail V15.0 (3693.60.0.1.1)
