### ISSUE TITLE
WinHttpQueryDataAvaliable: 12002: The operation timed out

### ISSUE THREAD

**Issue by SpikeHD** [rileytestut/AltStore#934]
iPhone 11, iOS 14.6, Windows 10, Latest AltServer (also tried with an older version from July of last year)

The only weird thing I've done to my Apple ID was that I changed my region to Japan, and then back to Canada, which is my original region, though it also didn't work while using Japan which had been the set for about a month.

Tried signing out and back in on the iPhone, as well as iTunes. Also re-authed the computer in iTunes.

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?

**Comment by SpikeHD** [comment]
Not as fr as I'm aware, thanks for reminding me that I have yet to close this :P

**Comment by amadasama** [comment]
hello, i have this problem right now and i cant find the solution. Can u help me, pls?
