### ISSUE TITLE
Mail Plugin not working 

### ISSUE THREAD

**Issue by Tushkiller** [rileytestut/AltStore#939]
Incompatible Plug-ins Disabled
Mail has disabled the following plug-ins:
AltPlugin.mailbundle
Contact the makers of these plug-ins for
versions that are compatible with Mail
16.0
<img width="263" alt="Screenshot 2022-01-29 at 7 49 10 PM" src="https://user-images.githubusercontent.com/80667954/151684206-b174f370-37b5-4804-9355-67fab9ee77da.png">
.

**Comment by iVosey** [comment]
https://github.com/rileytestut/AltStore/issues/938

**Comment by iVosey** [comment]
> #938

have u read the post before this one u created
