### ISSUE TITLE
mail plugin is not working even on macOS 12.1 

### ISSUE THREAD

**Issue by taitai20** [rileytestut/AltStore#940]
it is giving me errors and won't let me use it I also tried editing the plist but it is locked and is not working I'm wondering if devs can make an update

**Comment by heyimnitho** [comment]
I can confirm, AltServer's Mail plugin is not working on macOS Monterey 12.1 at the moment and I'm sharing some screenshots about this situation. Although, I'm using a 2017 model MBA which is good as new. Waiting for a upgrade asap.



![Screen Shot 2022-02-01 at 16 20 49](https://user-images.githubusercontent.com/60431344/151976045-3d28a1a5-2f95-4d68-a92b-c6a9ecb02d68.png)
![Screen Shot 2022-02-01 at 16 20 30](https://user-images.githubusercontent.com/60431344/151976053-4352bc9e-394a-4a56-bef4-e92158d7cc2d.png)
![Screen Shot 2022-02-01 at 16 20 17](https://user-images.githubusercontent.com/60431344/151976057-513b0f93-99b9-466b-9b65-35f2d7037cad.png)
![Screen Shot 2022-02-01 at 16 19 56](https://user-images.githubusercontent.com/60431344/151976061-cbb662a8-6cfd-4fdd-ba22-2ca14ba6761b.png)

**Comment by clementHA1** [comment]
Open the Mail app

    Click “Mail” at top left of screen

    Click preferences (a new box should open up)

    Under “General” Tab, in bottom left, click “Manage Plug-ins…”

    Right click on “AltPlugin.mailbundle”

    Click “show in finder” (another new window will pop up)

    Double Click “AltPlugin.mailbundle”

    Double click “Contents”

    Double click “Info.plist” (a new window will open)

    Scroll down about 3/4ths of the way down until you see “Supported12.3PluginCompatibilityUUIDs”

    Add <string>A4B49485-0377-4FAB-8D8E-E3B8018CFC21</string> directly under the last string

    Close out of this window

    Open Terminal

    Run: sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle (it may ask you for computer password)

    Disable gatekeeper by running: sudo spctl --master-disable

    Close terminal window

    Check box for “AltPlugin.mailbundle”

    Restart Mail

    Hopefully it works for you now

(from https://www.reddit.com/r/AltStore/comments/shmp2n/updated_computer_by_mistake_mail_plug_in_doesnt/ )

**Comment by avarayr** [comment]
https://github.com/rileytestut/AltStore/issues/905#issuecomment-1025092704

**Comment by SukiTVue** [comment]
Click on your trash bin, go to downloads where Altserver is. Drag it into applications, quit altstore, now go to applications where you dragged it to. Double click altserver, now click on the icon and click check for updates. It should update.
