### ISSUE TITLE
mail plugin is not working even on macOS 12.3 Beta

### ISSUE THREAD

**Issue by missuo** [rileytestut/AltStore#941]
![d45adb6fa232df1216d3e](https://telegraph.work/file/d45adb6fa232df1216d3e.png)

**Comment by clementHA1** [comment]
1. disable Gatekeeper into the Terminal: sudo spctl --master-disable
2. Add following string to Supported12.3PluginCompatibilityUUIDs at /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist

<string>A4B49485-0377-4FAB-8D8E-E3B8018CFC21</string>

Run following shell commands

sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle

**Comment by missuo** [comment]
> 1. disable Gatekeeper into the Terminal: sudo spctl --master-disable
> 
> 2. Add following string to Supported12.3PluginCompatibilityUUIDs at /Library/Mail/Bundles/AltPlugin.mailbundle/Contents/Info.plist
> 
> 
> 
> <string>A4B49485-0377-4FAB-8D8E-E3B8018CFC21</string>
> 
> 
> 
> Run following shell commands
> 
> 
> 
> sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle

Thanks.  I'm going to try it.

**Comment by missuo** [comment]
I ran it successfully, thank you very much. @clementHA1
