### ISSUE TITLE
installed apps crash immediately

### ISSUE THREAD

**Issue by laralove143** [rileytestut/AltStore#949]
everything works fine until i try to launch a sideloaded app, then it crashes immediately.. the same ipas installed using sideloady and the same apple id work fine tho..
(iphone 12 mini ios 15.2.1 mba m1 Monterey)

**Comment by jyu041** [comment]
same issue here, old sideloaded apps work fine, i can refresh them and they would still work, but new sideloaded apps will not launch

**Comment by jun6lee** [comment]
Same

**Comment by laralove143** [comment]
this repo seems dead :/
