### ISSUE TITLE
AltServer disconnected frequently

### ISSUE THREAD

**Issue by jiangjiangflies** [rileytestut/AltStore#952]
AltServer is disconnected frequently. After I restart my PC, it works fine again, but it only lasts for a short while and then it says "no connected device".  I have to restart my PC each time when I want to use it.

**Comment by Legendhidde** [comment]
Same problem here, have had this for a year or so. Cannot find any single solution, background refresh just doesn't work and it doesn't appear like it will ever be fixed.

**Comment by Legendhidde** [comment]
Hey dude, I found a solution for this and posted it in the issues section.
