### ISSUE TITLE
Add Apple multi-accounts for more app signes

### ISSUE THREAD

**Issue by Bellisario** [rileytestut/AltStore#954]
First, I want to thank all developers for this fantastic app!

I think you could add more than one Apple acocunts saved to "try" building app not only with one account, but with more.
This is very important for me, for example, because I can freely reload more than a limited number of apps.
I just thought this because of AltStore FAQ that says I could also create another Apple ID, so, it doesn't need the same of by iPhone, so, I could also use one for an app, and another for another one.

Thanks for your reading time! Please like below :+1:  if you like my idea!!!

**Comment by lonkelle** [comment]
This is on our roadmap IF our first idea for "unlimited" IDs doesn't work. Closing this cause it's on the roadmap. Join our Discord if you wanna check out the roadmap: https://bit.ly/altstore-delta-discord-invite
