### ISSUE TITLE
[Question] Can same Apple ID devices share build?

### ISSUE THREAD

**Issue by Bellisario** [rileytestut/AltStore#955]
Can same Apple ID devices share the same app build, or I need to compile it every time?

I'm asking this because I want to install AltStore into my iPad, too, but I'm not sure doing it because I built 8 apps and I have only 2 remaining. So, if I use AltStore on the same Apple ID, I would use the same build to prevent useless builds and to optimize build limit, it that so, or I need to use another Apple ID to prevent limit reach?

Thanks!

**Comment by Carter1190** [comment]
don't think so, but you can use two separate apple id's then u get 10 app ids per device and 3 apps per device
