### ISSUE TITLE
Every single day!

### ISSUE THREAD

**Issue by sklobi** [rileytestut/AltStore#961]
Why am I having to reinstall AltStore everyday??? 7 day certificates?? Not for me! Please help as this is quite annoying and frustrating

**Comment by fhalfkg** [comment]
Be angry with Apple
They limited that

**Comment by Staubgeborener** [comment]
There is no need to reinstall AltStore everyday. You just install it once. After that, you have to refresh your App IDs at least every 7 days. You can do this automatically in the background with the AltStore app (see settings) or a Siri shortcut.
