### ISSUE TITLE
AltPlugin vs AnisetteDataManager

### ISSUE THREAD

**Issue by dvc94ch** [rileytestut/AltStore#968]
Looks like there is some code duplication. Can someone explain the difference? I'm guessing AnisetteDataManager used to work with old macos'es and then apple changed something, now it only works from within an email plugin?

**Comment by lonkelle** [comment]
The plugin just retrieved the anisette data for AltServer. Pre-2020 anisette data wasn't needed to sign.

The Mail plugin has "Apple Permissions" so it can access AuthKit despite SIP being enabled. That data is then parsed by AltServer and sent to Apple servers to get a mobile provisioning file back.

**Comment by dvc94ch** [comment]
Ah I think there is some confusion about AltServer and AltDaemon both having an AnisetteDataManager. One interacts with AuthKit directly and the other gets the data from the Mail plugin. When I run the AuthKit code from the AltDaemon locally the machine id and one time password are empty, leading me to believe the problem was that it wasn't running as a mail plugin. But if I understood you reply correctly, some kind of error would have occurred if SIP was acting up. Currently contemplating rendering defeat to apple and just pay their overpriced yearly ios tax, and wait for the open app markets act to play out.

**Comment by lonkelle** [comment]
What are you trying to achieve rn?

**Comment by dvc94ch** [comment]
I'm working on a build tool x for easily building rust and flutter/rust projects. One of the supported platforms is ios, where it downloads the ios sdk, sets up the build and packages/signs the result. However it needs a certificate and a provisioning profile to work. The only way I know how to do it currently is building an empty ios project and have xcode generate the provisioning profile. It's quite annoying as you have to go through this process every 7 days for every project. Also I don't see why you should need a mac for ios development. This lead me to try and improve the process by wrapping altsign in a swift cli tool https://github.com/dvc94ch/noxc, but after getting stuck on https://github.com/rileytestut/AltStore/issues/909 to contemplate just using the documented appstore connect apis, which for a fee would allow you to build tools that work on linux/windows too.

**Comment by lonkelle** [comment]
Well, if you need any help with AltSign. Let us know on our Discord: https://bit.ly/altstore-delta-discord-invite
