### ISSUE TITLE
Why so heavy? Am I doing something wrong?

### ISSUE THREAD

**Issue by puyi1** [rileytestut/AltStore#969]
![AB6BF93A-D699-4E66-BB46-595C89476502](https://user-images.githubusercontent.com/101952701/159140136-043ce064-5edc-4b46-b91b-1211186b1f55.jpeg)

**Comment by awholegnuworld** [comment]
It is a bug. Delete the AltStore app and reinstall it.

**Comment by shanegillio** [comment]
hello, we are aware of an issue with AltStore holding onto memory of deleted apps. I'm going to close this as a duplicate, but be aware that we are working to resolve this soon
