### ISSUE TITLE
Install apps on device using only AltServer (without AltStore)

### ISSUE THREAD

**Issue by JJTech0130** [rileytestut/AltStore#971]
I find that it's annoying to have to use one of my precious 3 apps active for AltStore itself. It would be cool if there was a way to automatically sync apps using just the AltStore side.

**Comment by MaximilianGaedig** [comment]
Yeah this would be pretty cool, and from my understanding it should be entirely possible, would require an USB connection prolly tho. But am not sure if there aren't other apps that do the same thing already

**Comment by JJTech0130** [comment]
This is now implemented in the latest version.
(Not automatic syncing, but it can manually add IPAs. That's enough for me.)
