### ISSUE TITLE
Failed to Install Mail Plug-in

### ISSUE THREAD

**Issue by Avakining** [rileytestut/AltStore#987]
When attempting to install the Mail Plug-in, I instead receive a popup that reads, "Failed to Install Mail Plug-in / The file “Info.plist” couldn’t be opened because it isn’t in the correct format." 

macOS 12.3.1
AltServer 1.5

EDIT: Fixed by restart of AltServer app. This only happened after updating AltServer, anyway but still potentially a bug.

**Comment by JRDNXr** [comment]
Same issue occurred with me as well. Mail plug-in would not install after recent update. However, restarting AltServer remedied the situation perfectly. Thank you @Avakining.

**Comment by itfarrier** [comment]
Yes, had the same issue.

**Comment by lucastnr** [comment]
Had the same issue, but restarting AltServer seems to be the solution.
