### ISSUE TITLE
I Disabled SIP and AMFI but still getting "AltServer could not connect to Mail plug-in" popup?

### ISSUE THREAD

**Issue by SwiftMove** [rileytestut/AltStore#988]
macOS 14.4.6 Mojave
AltServer 1.5 (65)

- Rebooted into Recovery Mode and disabled Gatekeeper, SIP and AMFI...
sudo spctl --master-disable
csrutil disable
nvram boot-args="amfi_get_out_of_my_way=0x1"

- Reboot back into macOS
- AltServer > Sideload IPA > Select IPA > Enter AppleID and PW

But I'm still getting the "AltServer could not connect to Mail plug-in..." popup. What else needs to be done?

**Comment by shanegillio** [comment]
Hello, this should have been resolved in an update to AltServer so am closing
