### ISSUE TITLE
faq says to hold start when clicking altserver icon to access "sideload .ipa" option on windows when its actually shift

### ISSUE THREAD

**Issue by DetachHead** [rileytestut/AltStore#989]
according to [the faq](https://faq.altstore.io/release-notes/altserver#new), i have to hold the start button when clicking the altstore icon, but the option does not appear:

![image](https://user-images.githubusercontent.com/57028336/166580277-790f621d-5155-498a-a72b-c5b17f621f74.png)
![image](https://user-images.githubusercontent.com/57028336/166580357-511890c4-35fe-4b3e-b264-579b60d456af.png)

**Comment by ethan-xd** [comment]
Fail alert! You have to press shift when clicking the app icon. So
![image](https://user-images.githubusercontent.com/24442053/166622333-8373116a-876e-498e-9633-3164c80af618.png)

**Comment by githubashutoshsoni** [comment]
Awesome. I believe the FAQ section of alterserver needs to be updated so people don't get confused. I was pressing shift button

**Comment by shanegillio** [comment]
Hi there! The release notes do say to "hold shift" or is there somewhere else that I'm missing
