### ISSUE TITLE
Altstore taking insane storage on Ipad Generation 6

### ISSUE THREAD

**Issue by Kapitheshiba** [rileytestut/AltStore#993]
Today I opened Altstore and I saw the app taking up 20+ GB of my storage for documents. Send help and why does this happen? I only downloaded Sonolus and Uyou+
![B69E3DA4-5565-4E68-B0E6-F099C878EAB1](https://user-images.githubusercontent.com/105059574/167140473-76bce52e-3022-4a7a-810e-c7dbf2e558e0.jpeg)

**Comment by mailinglists35** [comment]
delete and reinstall. they seem to forget to delete temporary files used during install/resign 🙈 

failing the abc practice of keeping evidence of temp files in order to delete them. amateurs imho

**Comment by michael1900** [comment]
We need to pay to have some basic support. Bah...

**Comment by ap46281** [comment]
@mailinglists35 Mines at 79gb. Only just now realized because I was running out of storage on my 256..

**Comment by JJTech0130** [comment]
I'm pretty sure this is on the roadmap now. https://trello.com/c/t3mVqKFV

**Comment by mailinglists35** [comment]
> I'm pretty sure this is on the roadmap now. https://trello.com/c/t3mVqKFV

interesting. so they don't really track the github issues tracker, we all waste time writing here 🤬🥶

**Comment by mailinglists35** [comment]
omg what a horrible UI is that trello with horizontal scrolling instead of vertical

**Comment by shanegillio** [comment]
going to close this as a repeat bug report. we are aware of this issue and will be working on a fix, so stay tuned
